module

public import UnitDistance.Sqrt241.Generators.Label
public import UnitDistance.Sqrt241.Generators.Kummer
public import UnitDistance.Sqrt241.ProP.ProPOpenNormalStage
public import UnitDistance.ProTwoElementaryQuotient

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false

/-!
# The genus field is the Frattini field: `H¹(G_B) = 8`

B-world: every quadratic subextension of `Ω_B/B` (the fixed field of an open
normal subgroup of index 2 of `Gal(Ω_B/B)`) is an admissible layer of degree 2
(`ProP.proPOpenNormalStage`), hence by the Kummer classification
(`le_adjoin_roots_of_quadratic`) lies in the field generated by the eight
genus roots `chi(√α_k)` (`genusInOmegaB`).

ℚ-world: through the bridge, every index-2 open normal subgroup of `G_B`
contains `ker genusLabel`; hence `ker genusLabel` is the closed
square-commutator (Frattini) subgroup of `G_B` and `G_B` has topological
generator rank `8`.
-/

open scoped NumberField
open NumberField IsDedekindDomain

noncomputable section

namespace UnitDistance.Sqrt241.Tower

open Base CanonicalGenus IntermediateField ClassFieldTower.Sawin ClassFieldTower.ProP
open ProCGroups.Generation ProCGroups.FiniteGeneration

/-! ### B-world -/

/-- The genus roots `chi(√α_k)`, as elements of `Ω_B`. -/
def genusRootB (k : Fin 8) : OmegaB := omegaEquiv (genusRootOmega k)

theorem coe_genusRootB (k : Fin 8) : (genusRootB k : Bbar) = chi (genusRoot k) :=
  rfl

theorem genusRootB_sq (k : Fin 8) :
    (genusRootB k : Bbar) ^ 2 = algebraMap B Bbar ((alpha k : 𝓞 B) : B) := by
  rw [coe_genusRootB, ← map_pow, genusRoot_sq_alpha, AlgEquiv.commutes]

/-- The genus field inside `Ω_B`: generated over `B` by the eight genus roots. -/
def genusInOmegaB : IntermediateField B OmegaB :=
  IntermediateField.adjoin B (Set.range genusRootB)

theorem lift_genusInOmegaB :
    IntermediateField.lift genusInOmegaB =
      IntermediateField.adjoin B (Set.range fun k ↦ (genusRootB k : Bbar)) := by
  rw [genusInOmegaB, IntermediateField.lift_adjoin, ← Set.range_comp]
  rfl

/-- The local number-field instance `ProP.finiteGaloisNumberField`, restated for finite
Galois layers of `Bbar`. -/
local instance finiteGaloisLayerNumberField (E : FiniteGaloisIntermediateField B Bbar) :
    NumberField E :=
  NumberField.of_module_finite B E

/-- Every quadratic subextension of `Ω_B/B` lies in the genus field. -/
theorem indexTwo_fixedField_le_genusInOmegaB (U : OpenNormalSubgroup GBw)
    (hU : (U : Subgroup GBw).index = 2) :
    IntermediateField.fixedField (U : Subgroup GBw) ≤ genusInOmegaB := by
  let st := ProP.proPOpenNormalStage B 2 S U
  have hfield : st.val.toIntermediateField =
      IntermediateField.lift (IntermediateField.fixedField (U : Subgroup GBw)) :=
    ProP.proPOpenNormalStage_field B 2 S U
  have : IsGalois B st.val.toIntermediateField := st.val.isGalois
  let U₀ : OpenNormalSubgroup
      (ProP.maximalProPOutside B 2 S ≃ₐ[B] ProP.maximalProPOutside B 2 S) := U
  have : (U₀ : Subgroup
      (ProP.maximalProPOutside B 2 S ≃ₐ[B] ProP.maximalProPOutside B 2 S)).Normal := U.isNormal'
  have hdeg : Module.finrank B st.val.toIntermediateField = 2 := by
    rw [← IsGalois.card_aut_eq_finrank,
      ← Nat.card_congr (ProP.proPOpenNormalQuotientEquivStage B 2 S U₀).toEquiv,
      ← Subgroup.index_eq_card]
    exact hU
  have hunr : IsUnramifiedAtFinitePlacesOutside B st.val.toIntermediateField S :=
    st.property.2
  have hle := le_adjoin_roots_of_quadratic (Ω := Bbar) (fun k ↦ (genusRootB k : Bbar))
    genusRootB_sq st.val.toIntermediateField hdeg hunr
  intro x hx
  have hx' : (x : Bbar) ∈ st.val.toIntermediateField := by
    rw [hfield]
    exact (IntermediateField.mem_lift x).2 hx
  have hx'' := hle hx'
  rw [← lift_genusInOmegaB] at hx''
  exact (IntermediateField.mem_lift x).1 hx''

/-- An element of `Gal(Ω_B/B)` fixing the eight genus roots lies in every open
normal subgroup of index 2. -/
theorem mem_indexTwo_of_fixes (U : OpenNormalSubgroup GBw) (hU : (U : Subgroup GBw).index = 2)
    (g : GBw) (hg : ∀ k, g (genusRootB k) = genusRootB k) : g ∈ (U : Subgroup GBw) := by
  have hfix : g ∈ genusInOmegaB.fixingSubgroup := by
    apply mem_fixingSubgroup_adjoin
    rintro _ ⟨k, rfl⟩
    exact hg k
  have hle := IntermediateField.fixingSubgroup_antitone (indexTwo_fixedField_le_genusInOmegaB U hU)
  have hclosed := InfiniteGalois.fixingSubgroup_fixedField
    (⟨(U : Subgroup GBw), U.isClosed⟩ : ClosedSubgroup GBw)
  have := hle hfix
  rwa [hclosed] at this

/-! ### ℚ-world: the Frattini subgroup of `G_B` -/

theorem bridge_symm_genusRootB (h : GB) (k : Fin 8) (hk : (genusLabel h).toAdd k = 0) :
    bridge.symm h (genusRootB k) = genusRootB k := by
  rw [bridge_symm_apply, genusRootB, RingEquiv.symm_apply_apply]
  rw [genusLabel_apply, genusChar_eq_zero_iff] at hk
  rw [hk]

/-- Every open normal subgroup of index 2 of `G_B` contains `ker genusLabel`. -/
theorem genusLabel_ker_le (U : OpenNormalSubgroup GB) (hU : (U : Subgroup GB).index = 2) :
    genusLabel.toMonoidHom.ker ≤ (U : Subgroup GB) := by
  let f : GBw →* GB := bridge.toMulEquiv.toMonoidHom
  have hf : Function.Surjective f := bridge.surjective
  let U' : OpenNormalSubgroup GBw :=
    { toSubgroup := (U : Subgroup GB).comap f
      isOpen' := U.isOpen.preimage bridge.continuous
      isNormal' := Subgroup.Normal.comap U.isNormal' f }
  have hU' : (U' : Subgroup GBw).index = 2 := by
    change ((U : Subgroup GB).comap f).index = 2
    rw [Subgroup.index_comap_of_surjective _ hf, hU]
  intro h hh
  rw [MonoidHom.mem_ker] at hh
  have hg : ∀ k, bridge.symm h (genusRootB k) = genusRootB k := by
    intro k
    apply bridge_symm_genusRootB
    have := congrArg (fun v : Multiplicative (Fin 8 → ZMod 2) ↦ v.toAdd k) hh
    exact this
  have hmem := mem_indexTwo_of_fixes U' hU' (bridge.symm h) hg
  change f (bridge.symm h) ∈ (U : Subgroup GB) at hmem
  have : f (bridge.symm h) = h := bridge.apply_symm_apply h
  rwa [this] at hmem

theorem label_sq_eq_one (a : Multiplicative (Fin 8 → ZMod 2)) : a ^ 2 = 1 := by
  apply Multiplicative.toAdd.injective
  change (2 : ℕ) • a.toAdd = 0
  funext i
  simp [show (2 : ZMod 2) = 0 by decide]

/-- The kernel of the genus label is the Frattini subgroup of `G_B`. -/
theorem genusLabel_ker : genusLabel.toMonoidHom.ker = closedPowerCommutator 2 GB :=
  (ProTwoElementaryQuotient.closedPowerCommutator_eq_ker GB_hasPGroupOpenNormalBasis
    genusLabel label_sq_eq_one genusLabel_ker_le).symm

theorem card_labelGroup : Nat.card (Multiplicative (Fin 8 → ZMod 2)) = 2 ^ 8 := by
  rw [Nat.card_congr (Multiplicative.toAdd : Multiplicative (Fin 8 → ZMod 2) ≃ _)]
  simp

/-- `G_B` has topological generator rank `8` (`dim H¹ = 8`). -/
theorem GB_generatorRank :
    TopologicallyGeneratedByAtMost 8 GB ∧ topologicalGeneratorRank GB = 8 :=
  ProTwoElementaryQuotient.generatorRank_of_quadratic_quotient GB_hasPGroupOpenNormalBasis
    genusLabel genusLabel_surjective label_sq_eq_one genusLabel_ker_le 8 card_labelGroup

/-! ### B-world forms -/

/-- The genus label on `Gal(Ω_B/B)`, through the bridge. -/
def genusLabelB : GBw →ₜ* Multiplicative (Fin 8 → ZMod 2) :=
  genusLabel.comp (bridge : GBw →ₜ* GB)

theorem genusLabelB_apply (g : GBw) : genusLabelB g = genusLabel (bridge g) :=
  rfl

theorem bridge_fixes_iff (g : GBw) (k : Fin 8) :
    ((bridge g : GB) : Ghat) (genusRootOmega k) = genusRootOmega k ↔
      g (genusRootB k) = genusRootB k := by
  rw [bridge_apply]
  constructor
  · intro h
    have := congrArg omegaEquiv h
    rwa [RingEquiv.apply_symm_apply] at this
  · intro h
    change omegaEquiv.symm (g (genusRootB k)) = genusRootOmega k
    rw [h, genusRootB, RingEquiv.symm_apply_apply]

theorem mem_ker_genusLabelB_iff (g : GBw) :
    g ∈ genusLabelB.toMonoidHom.ker ↔ ∀ k, g (genusRootB k) = genusRootB k := by
  rw [MonoidHom.mem_ker]
  constructor
  · intro hg k
    have hk := congrArg (fun v : Multiplicative (Fin 8 → ZMod 2) ↦ v.toAdd k) hg
    exact (bridge_fixes_iff g k).1 ((genusChar_eq_zero_iff _ k).1 hk)
  · intro hg
    apply Multiplicative.toAdd.injective
    funext k
    exact (genusChar_eq_zero_iff _ k).2 ((bridge_fixes_iff g k).2 (hg k))

theorem ker_genusLabelB : genusLabelB.toMonoidHom.ker = genusInOmegaB.fixingSubgroup := by
  ext g
  rw [mem_ker_genusLabelB_iff]
  constructor
  · intro hg
    apply mem_fixingSubgroup_adjoin
    rintro _ ⟨k, rfl⟩
    exact hg k
  · intro hg k
    exact (IntermediateField.mem_fixingSubgroup_iff _ _).1 hg _
      (IntermediateField.subset_adjoin B _ ⟨k, rfl⟩)

theorem genusLabelB_surjective : Function.Surjective genusLabelB :=
  genusLabel_surjective.comp bridge.surjective

theorem genusLabelB_ker_le (U : OpenNormalSubgroup GBw) (hU : (U : Subgroup GBw).index = 2) :
    genusLabelB.toMonoidHom.ker ≤ (U : Subgroup GBw) := by
  intro g hg
  exact mem_indexTwo_of_fixes U hU g ((mem_ker_genusLabelB_iff g).1 hg)

/-- The genus field is the Frattini field of `Ω_B/B`. -/
theorem frattini_eq : closedPowerCommutator 2 GBw = genusInOmegaB.fixingSubgroup :=
  (ProTwoElementaryQuotient.closedPowerCommutator_eq_ker OmegaB_hasPGroupOpenNormalBasis
    genusLabelB label_sq_eq_one genusLabelB_ker_le).trans ker_genusLabelB

/-- `Gal(Ω_B/B)` has topological generator rank `8`. -/
theorem OmegaB_generatorRank :
    TopologicallyGeneratedByAtMost 8 GBw ∧ topologicalGeneratorRank GBw = 8 :=
  ProTwoElementaryQuotient.generatorRank_of_quadratic_quotient OmegaB_hasPGroupOpenNormalBasis
    genusLabelB genusLabelB_surjective label_sq_eq_one genusLabelB_ker_le 8 card_labelGroup

end UnitDistance.Sqrt241.Tower
