module

public import UnitDistance.Sqrt241.Tower.Bridge
public import UnitDistance.Sqrt241.Base.SUnits
public import UnitDistance.QuadraticRamification

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false

/-!
# The canonical genus field lies in `Ω`

For each Kummer radicand `α_k` of `B` (`Base.alpha k`, `k : Fin 8`) the field
`B(√α_k)` (`quadField k`, generated by `CanonicalGenus.genusRoot k`) is a
quadratic Galois extension of `B` unramified at every finite place outside `S`
(the radicand is a unit or a prime above `2, 3, 5`; `QuadraticRamification`).
By `le_OmegaBcl_of_admissible` it lies in `Ω`, hence so does the canonical
genus field `E = CanonicalGenus.field` (`canonicalGenus_le_Omega`).
-/

open scoped NumberField
open NumberField IsDedekindDomain

noncomputable section

namespace UnitDistance.Sqrt241.Tower

open Base CanonicalGenus IntermediateField ClassFieldTower.Sawin Polynomial

theorem coe_alpha_eq_algebraMap (k : Fin 8) :
    (((alpha k : 𝓞 B) : B) : Closure) = algebraMap B Closure ((alpha k : 𝓞 B) : B) :=
  rfl

theorem genusRoot_sq_alpha (k : Fin 8) :
    genusRoot k ^ 2 = algebraMap B Closure ((alpha k : 𝓞 B) : B) := by
  rw [genusRoot_sq, ← coe_alpha_eq_algebraMap, coe_alpha]

theorem isIntegral_genusRoot (k : Fin 8) : IsIntegral B (genusRoot k) :=
  Algebra.IsIntegral.isIntegral _

/-- No radicand is a square in `B`. -/
theorem alpha_nonsquare (k : Fin 8) : ∀ s : B, s ^ 2 ≠ ((alpha k : 𝓞 B) : B) := by
  intro s hs
  have he : ∀ i, (Pi.single k 1 : Fin 8 → ℕ) i < 2 := by
    intro i
    by_cases h : i = k
    · subst h
      simp
    · simp [h]
  have h := alphaProd_independent he (γ := s) (by rw [alphaProd_single, hs])
  have := congrFun h k
  simp at this

/-- The quadratic field `B(√α_k)` inside the closure. -/
def quadField (k : Fin 8) : IntermediateField B Closure :=
  IntermediateField.adjoin B {genusRoot k}

theorem genusRoot_mem_quadField (k : Fin 8) : genusRoot k ∈ quadField k :=
  IntermediateField.mem_adjoin_simple_self B (genusRoot k)

instance quadField_finiteDimensional (k : Fin 8) : FiniteDimensional B (quadField k) :=
  IntermediateField.adjoin.finiteDimensional (isIntegral_genusRoot k)

theorem minpoly_genusRoot (k : Fin 8) :
    minpoly B (genusRoot k) = X ^ 2 - C ((alpha k : 𝓞 B) : B) := by
  symm
  apply minpoly.eq_of_irreducible_of_monic
  · exact X_pow_sub_C_irreducible_of_prime Nat.prime_two (alpha_nonsquare k)
  · simp [genusRoot_sq_alpha]
  · exact monic_X_pow_sub_C _ (by norm_num)

theorem finrank_quadField (k : Fin 8) : Module.finrank B (quadField k) = 2 := by
  rw [quadField, IntermediateField.adjoin.finrank (isIntegral_genusRoot k), minpoly_genusRoot,
    natDegree_X_pow_sub_C]

instance quadField_normal (k : Fin 8) : Normal B (quadField k) := by
  rw [normal_iff_forall_map_le']
  intro σ
  rw [quadField, IntermediateField.adjoin_map, Set.image_singleton, adjoin_simple_le_iff]
  have hsq : ((σ : Closure →ₐ[B] Closure) (genusRoot k)) ^ 2 = genusRoot k ^ 2 := by
    rw [← map_pow, genusRoot_sq_alpha, AlgHom.commutes]
  rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h | h <;> rw [h]
  · exact genusRoot_mem_quadField k
  · exact neg_mem (genusRoot_mem_quadField k)

instance quadField_isGalois (k : Fin 8) : IsGalois B (quadField k) where

theorem quadField_isPGroup (k : Fin 8) : IsPGroup 2 (quadField k ≃ₐ[B] quadField k) := by
  apply IsPGroup.of_card (n := 1)
  rw [IsGalois.card_aut_eq_finrank, finrank_quadField, pow_one]

/-- Finite subextensions of `Closure/B` are number fields. -/
local instance numberFieldOfFiniteB' (K : IntermediateField B Closure) [FiniteDimensional B K] :
    NumberField K :=
  NumberField.of_module_finite B K

/-- The radicands are units (`k = 0, 1`) or divide `30` (`k ≥ 2`): a prime of
`B` containing `α_k` contains `30`. -/
theorem thirty_mem_of_alpha_mem (k : Fin 8) {P : Ideal (𝓞 B)} [P.IsPrime] (h : alpha k ∈ P) :
    (30 : 𝓞 B) ∈ P := by
  by_cases hk : 2 ≤ k.val
  · obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.1 (thirty_mem_span_alpha k hk)
    rw [← hc]
    exact P.mul_mem_left c h
  · exfalso
    apply (inferInstance : P.IsPrime).ne_top
    apply Ideal.eq_top_of_isUnit_mem P h
    have hk' : k = 0 ∨ k = 1 := by omega
    rcases hk' with rfl | rfl
    · exact isUnit_one.neg
    · exact epsUnit.isUnit

/-- `B(√α_k)/B` is unramified at every finite place outside `S`. -/
theorem quadField_unramified (k : Fin 8) : IsUnramifiedAtFinitePlacesOutside B (quadField k) S := by
  intro P hP
  let r : quadField k := AdjoinSimple.gen B (genusRoot k)
  have hr2 : r ^ 2 = algebraMap B (quadField k) ((alpha k : 𝓞 B) : B) := by
    apply Subtype.ext
    change genusRoot k ^ 2 = _
    rw [genusRoot_sq_alpha]
    rfl
  have hrint : IsIntegral ℤ r := by
    apply IsIntegral.of_pow (n := 2) (by norm_num)
    rw [hr2]
    exact ((alpha k).2).map (IsScalarTower.toAlgHom ℤ B (quadField k))
  let x : 𝓞 (quadField k) := ⟨r, hrint⟩
  have hx : x ^ 2 = algebraMap (𝓞 B) (𝓞 (quadField k)) (alpha k) := by
    apply RingOfIntegers.ext
    change r ^ 2 = _
    rw [hr2]
    rfl
  have hgen : Algebra.adjoin B {(x : quadField k)} = ⊤ :=
    (IntermediateField.adjoin.powerBasis (isIntegral_genusRoot k)).adjoin_gen_eq_top
  have h30 : (30 : 𝓞 B) ∉ P.asIdeal.under (𝓞 B) := hP
  apply QuadraticRamification.isUnramifiedAt_of_not_mem B (quadField k) (alpha k)
    (alpha_nonsquare k) x hx hgen P.asIdeal
  · intro h2
    apply h30
    rw [Ideal.mem_under, map_ofNat]
    have h15 : (30 : 𝓞 (quadField k)) = 15 * 2 := by norm_num
    rw [h15]
    exact P.asIdeal.mul_mem_left 15 h2
  · intro ha
    exact h30 (thirty_mem_of_alpha_mem k (by rw [Ideal.mem_under]; exact ha))

theorem quadField_le_OmegaBcl (k : Fin 8) : quadField k ≤ OmegaBcl :=
  le_OmegaBcl_of_admissible (quadField k) (quadField_isPGroup k) (quadField_unramified k)

theorem genusRoot_mem_Omega (k : Fin 8) : genusRoot k ∈ Omega :=
  quadField_le_OmegaBcl k (genusRoot_mem_quadField k)

/-- The canonical genus field `E` lies in `Ω`. -/
theorem canonicalGenus_le_Omega : CanonicalGenus.field ≤ Omega := by
  rw [CanonicalGenus.field, IntermediateField.adjoin_le_iff]
  rintro x (rfl | ⟨k, rfl⟩)
  · exact baseRoot_mem_Omega
  · exact genusRoot_mem_Omega k

end UnitDistance.Sqrt241.Tower
