module

public import UnitDistance.Sqrt241.Tower.OmegaB
public import UnitDistance.Sqrt241.Base.SUnits
public import Mathlib.NumberTheory.RamificationInertia.Valuation
public import Mathlib.RingTheory.RamificationInertia.Ramification
public import Mathlib.RingTheory.Trace.Basic

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false

/-!
# Kummer classification of quadratic extensions of `B` unramified outside `S`

* `isSquare_valuation_of_isUnramifiedAt`: if `β² = a` with `a` in the base and
  `w | v` is unramified, then the `v`-adic valuation of `a` is a square (the
  valuation on the top restricts to `v` with exponent `e(w|v) = 1`).
* `isSquare_valuation_of_unramifiedOutside`: the same at every place outside
  the ramification support.
* `mem_adjoin_roots_of_quadratic`: a quadratic extension `L/B` unramified at
  every finite place outside `S` lies in the field generated over `B` by
  square roots `ρ_k` of the eight radicands `α_k`, in any field `Ω ⊇ B`
  (`h(B) = 1` and the `S`-unit square classes of `B`,
  `Base.sUnit_squareclass`).
-/

open scoped NumberField
open NumberField IsDedekindDomain

noncomputable section

namespace UnitDistance.Sqrt241.Tower

open Base CanonicalGenus IntermediateField ClassFieldTower.Sawin

section Valuation

variable {K L : Type*} [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L]

/-- If `β² = a` in `L` with `a ∈ K`, and `L/K` is unramified at a prime `w`
above `v`, then `v(a)` is even. -/
theorem isSquare_valuation_of_isUnramifiedAt (v : HeightOneSpectrum (𝓞 K))
    (w : HeightOneSpectrum (𝓞 L)) [w.asIdeal.LiesOver v.asIdeal]
    [Algebra.IsUnramifiedAt (𝓞 K) w.asIdeal] (a : K) (β : L)
    (hβ : β ^ 2 = algebraMap K L a) : IsSquare (v.valuation K a) := by
  have hfin : Module.Finite (𝓞 K) (𝓞 L) := Module.IsNoetherian.finite (𝓞 K) (𝓞 L)
  have he1 : w.asIdeal.ramificationIdx (𝓞 K) = 1 := Ideal.ramificationIdx_eq_one w.asIdeal (𝓞 K)
  have he : v.asIdeal.ramificationIdx' w.asIdeal = 1 := by
    rw [Ideal.ramificationIdx'_eq_ramificationIdx v.asIdeal w.asIdeal v.ne_bot, he1]
  have h := HeightOneSpectrum.valuation_liesOver L v w a
  rw [he, pow_one, ← hβ, map_pow] at h
  exact ⟨w.valuation L β, by rw [h, sq]⟩

omit [NumberField K] [NumberField L] in
/-- A prime of `L` above a given prime of `K`. -/
theorem exists_heightOneSpectrum_liesOver (v : HeightOneSpectrum (𝓞 K)) :
    ∃ w : HeightOneSpectrum (𝓞 L), w.asIdeal.LiesOver v.asIdeal := by
  obtain ⟨⟨P, hPrime, hOver⟩⟩ := v.asIdeal.nonempty_primesOver (S := 𝓞 L)
  exact ⟨⟨P, hPrime, Ideal.ne_bot_of_liesOver_of_ne_bot v.ne_bot P⟩, hOver⟩

/-- If `L/K` is unramified at all finite places outside `T` and `β² = a`,
then `v(a)` is even at every finite place `v ∉ T` of `K`. -/
theorem isSquare_valuation_of_unramifiedOutside {T : Set (HeightOneSpectrum (𝓞 K))}
    (hL : IsUnramifiedAtFinitePlacesOutside K L T) (a : K) (β : L)
    (hβ : β ^ 2 = algebraMap K L a) (v : HeightOneSpectrum (𝓞 K)) (hv : v ∉ T) :
    IsSquare (v.valuation K a) := by
  obtain ⟨w, hw⟩ := exists_heightOneSpectrum_liesOver (L := L) v
  have hbelow : finitePlaceBelow (K := K) w = v := by
    apply HeightOneSpectrum.ext
    exact (w.asIdeal.over_def v.asIdeal).symm
  have : Algebra.IsUnramifiedAt (𝓞 K) w.asIdeal := hL w (by rw [hbelow]; exact hv)
  exact isSquare_valuation_of_isUnramifiedAt v w a β hβ

end Valuation

section Classification

variable {Ω : Type*} [Field Ω] [Algebra B Ω]

/-- A square root in `Ω` of an element `alphaProd e * γ²` of `B` is, up to sign,
`γ · ∏ ρ_k ^ e_k`, hence lies in the field generated by the `ρ_k`. -/
theorem mem_adjoin_roots_of_sq_eq (ρ : Fin 8 → Ω)
    (hρ : ∀ k, ρ k ^ 2 = algebraMap B Ω ((alpha k : 𝓞 B) : B)) (e : Fin 8 → ℕ) (γ : B)
    (z : Ω) (hz : z ^ 2 = algebraMap B Ω (alphaProd e * γ ^ 2)) :
    z ∈ IntermediateField.adjoin B (Set.range ρ) := by
  set y : Ω := algebraMap B Ω γ * ∏ k, ρ k ^ e k with hy
  have hy2 : y ^ 2 = z ^ 2 := by
    rw [hz, hy, mul_pow, ← Finset.prod_pow, map_mul, map_pow, alphaProd, map_prod]
    rw [mul_comm]
    congr 1
    apply Finset.prod_congr rfl
    intro k _
    rw [← pow_mul, mul_comm (e k) 2, pow_mul, hρ, map_pow]
  have hymem : y ∈ IntermediateField.adjoin B (Set.range ρ) := by
    apply mul_mem (IntermediateField.algebraMap_mem _ γ)
    apply prod_mem
    intro k _
    exact pow_mem (IntermediateField.subset_adjoin B (Set.range ρ) (Set.mem_range_self k)) _
  rcases sq_eq_sq_iff_eq_or_eq_neg.mp hy2 with h | h
  · rw [← h]
    exact hymem
  · rw [show z = -y by rw [h, neg_neg]]
    exact neg_mem hymem

/-- Kummer classification over `B`: a quadratic extension `L/B` inside `Ω`,
unramified at all finite places outside `S`, lies in `B(ρ_0, …, ρ_7)` for any
square roots `ρ_k ∈ Ω` of the radicands. -/
theorem le_adjoin_roots_of_quadratic (ρ : Fin 8 → Ω)
    (hρ : ∀ k, ρ k ^ 2 = algebraMap B Ω ((alpha k : 𝓞 B) : B))
    (L : IntermediateField B Ω) [FiniteDimensional B L] [NumberField L]
    (h2 : Module.finrank B L = 2) (hL : IsUnramifiedAtFinitePlacesOutside B L S) :
    L ≤ IntermediateField.adjoin B (Set.range ρ) := by
  have hfree : Module.Free B L := Module.Free.of_divisionRing B L
  have : Algebra.IsQuadraticExtension B L := { toFree := hfree, finrank_eq_two' := h2 }
  have : CharZero Ω := charZero_of_injective_algebraMap (algebraMap B Ω).injective
  intro x hx
  let y : L := ⟨x, hx⟩
  set t : B := Algebra.trace B L y
  set n : B := Algebra.norm B y
  set β : L := 2 * y - algebraMap B L t with hβdef
  set a : B := t ^ 2 - 4 * n with hadef
  have hsq := Algebra.IsQuadraticExtension.sq_eq_trace_smul_sub_norm B y
  have hβ : β ^ 2 = algebraMap B L a := by
    rw [hβdef, hadef, map_sub, map_mul, map_pow, map_ofNat]
    rw [Algebra.smul_def] at hsq
    linear_combination 4 * hsq
  have hxβ : (x : Ω) = (1 / 2 : Ω) * ((β : Ω) + algebraMap B Ω t) := by
    have hc : ((β : L) : Ω) = 2 * x - algebraMap B Ω t := by
      change L.val β = _
      rw [hβdef, map_sub, map_mul, map_ofNat, AlgHom.commutes]
      rfl
    rw [hc]
    ring
  have hβmem : (β : Ω) ∈ IntermediateField.adjoin B (Set.range ρ) := by
    by_cases ha : a = 0
    · have : β = 0 := by
        have h0 : β ^ 2 = 0 := by rw [hβ, ha, map_zero]
        exact pow_eq_zero_iff (by norm_num) |>.mp h0
      rw [this, ZeroMemClass.coe_zero]
      exact zero_mem _
    · obtain ⟨e, -, γ, -, hγ⟩ := sUnit_squareclass a ha (fun v hv ↦
        isSquare_valuation_of_unramifiedOutside hL a β hβ v hv)
      apply mem_adjoin_roots_of_sq_eq ρ hρ e γ
      rw [← hγ]
      have := congrArg (fun z : L ↦ (z : Ω)) hβ
      simpa using this
  rw [hxβ]
  apply mul_mem
  · apply div_mem (one_mem _) (ofNat_mem _ 2)
  · exact add_mem hβmem (IntermediateField.algebraMap_mem _ t)

end Classification

end UnitDistance.Sqrt241.Tower
