#!/usr/bin/env python3
"""The fifteen D4 fields of the census (d4fields15.json): checks and generated inputs.

Each entry gives two rows r1, r2 in F_2^8 (bit i <-> Kummer basis element alpha_i of tw:alpha, as in
lie241.py), the rotation class rho in F_2^2 and eight rational coordinates of beta in the basis
{1, s, sa, s sa, sb, s sb, sa sb, s sa sb} of F0 = B(sqrt a, sqrt b), where s = sqrt 241,
a = prod alpha_i^{r1_i}, b = prod alpha_i^{r2_i}, sa^2 = a, sb^2 = b.

Checks (asserted):
  1. the functional psi of (phi_1, rho) on the degree-2 layer, psi(v^[2]) = [phi_1 v = rho],
     psi([v, w]) = det(phi_1 v, phi_1 w), vanishes on the 22 quadratic initials R_2 (tw:initials-list);
  2. the 15 functionals have rank 15, so they span the dual of gr_2 G_B (dimension 15);
  3. denominators divide 120 and numerators are below 2^62 (as census_d3.c assumes).
Writes d4fields15.h (for census_d3.c) and vd4_data.gp (for vd4.gp).
"""
import contextlib
import io
import json
import sys
from fractions import Fraction
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent / "0.04273/certificates"))
with contextlib.redirect_stdout(io.StringIO()):
    from lie241 import rels, f2rank  # noqa: E402

N = 8
FIELDS = json.loads((HERE / "d4fields15.json").read_text())


def vec(s):
    return np.array([int(c) for c in s], dtype=np.uint8)


def psi(rows, rho):
    A = np.array([vec(r) for r in rows])
    rho = np.array(rho, dtype=np.uint8)
    E = np.eye(N, dtype=np.uint8)
    q = [int(np.array_equal(A.dot(E[i]) % 2, rho)) for i in range(N)]
    im = [A.dot(E[i]) % 2 for i in range(N)]
    det = [int((im[i][0] * im[j][1] + im[i][1] * im[j][0]) % 2) for i in range(N) for j in range(i + 1, N)]
    return np.array(q + det, dtype=np.uint8)


def coords36(M):
    """symmetric 8x8 matrix of lie241 (S(v) = v v^T, B(v,w) = v w^T + w v^T) -> (diagonal, i<j)"""
    return np.array([M[i, i] for i in range(N)] + [M[i, j] for i in range(N) for j in range(i + 1, N)],
                    dtype=np.uint8) % 2


def main():
    R = [coords36(m) for m in rels]
    P = []
    for f in FIELDS:
        p = psi(f["rows"], f["rho"])
        assert all(int(p.dot(r)) % 2 == 0 for r in R), f
        P.append(p)
    assert f2rank(np.array(R)) == 21
    rank = f2rank(np.array(P))
    assert rank == 15, rank
    out = ["/* generated by d4fields.py from d4fields15.json */", "static const int NF = %d;" % len(FIELDS)]
    r1 = [sum(int(c) << k for k, c in enumerate(f["rows"][0])) for f in FIELDS]
    r2 = [sum(int(c) << k for k, c in enumerate(f["rows"][1])) for f in FIELDS]
    num, den = [], []
    for f in FIELDS:
        cs = [Fraction(c) for c in f["coords"]]
        assert all(120 % c.denominator == 0 and abs(c.numerator) < 2**62 for c in cs)
        num.append([c.numerator for c in cs])
        den.append([c.denominator for c in cs])
    out.append("static const int R1[%d] = {%s};" % (len(FIELDS), ", ".join(map(str, r1))))
    out.append("static const int R2[%d] = {%s};" % (len(FIELDS), ", ".join(map(str, r2))))
    out.append("static const int64_t NUM[%d][8] = {%s};" % (len(FIELDS), ", ".join(
        "{" + ", ".join("%dLL" % v for v in row) + "}" for row in num)))
    out.append("static const int64_t DEN[%d][8] = {%s};" % (len(FIELDS), ", ".join(
        "{" + ", ".join(map(str, row)) + "}" for row in den)))
    (HERE / "d4fields15.h").write_text("\n".join(out) + "\n")
    gp = ["{FIELDS = ["]
    gp.append(",\n".join("  [%s, %s, %s, [%s]]" % ([int(c) for c in f["rows"][0]], [int(c) for c in f["rows"][1]],
                                                    f["rho"], ", ".join(f["coords"])) for f in FIELDS))
    gp.append("];}")
    (HERE / "vd4_data.gp").write_text("\n".join(gp) + "\n")
    print("d4fields: 15 functionals kill R_2 and have rank 15; wrote d4fields15.h and vd4_data.gp")


if __name__ == "__main__":
    main()
