module

public import UnitDistance.Sqrt241.Base.Units
public import UnitDistance.Sqrt241.Base.Signs
public import Mathlib.RingTheory.DedekindDomain.AdicValuation
public import Mathlib.Algebra.Squarefree.Basic

@[expose] public section
set_option backward.privateInPublic true

/-!
# `S`-units of `B = ℚ(√241)` modulo squares, `S` = primes above `2, 3, 5`

`V = {β ∈ B^× : v(β) even for every prime v ∤ 30} / B^{×2}` has the basis
`-1, ε, π₂, π₂', π₃, π₃', π₅, π₅'` (the radicands `alpha i`):

* `sUnit_squareclass`: every such `β` is `∏ alpha i ^ e i · γ²` with `e i ∈ {0, 1}`;
* `alphaProd_independent`: `∏ alpha i ^ e i` with `e i ∈ {0, 1}` is a square only for `e = 0`.

Parity of valuations is expressed as `IsSquare (v.valuation B β)` in `ℤᵐ⁰`
(`isSquare_exp_iff`: `IsSquare (exp n) ↔ Even n`); "prime not above `2, 3, 5`"
as `(30 : 𝓞 B) ∉ v.asIdeal`. The proofs use `h(B) = 1`, the unit theorem of
`Units.lean`, the valuations of the radicands at the six primes, and their signs
at the real places.
-/

noncomputable section

namespace UnitDistance.Sqrt241.Base

open NumberField IsDedekindDomain Ideal WithZero

/-! ## Parity in `ℤᵐ⁰` -/

theorem isSquare_exp_iff (n : ℤ) : IsSquare (exp n : ℤᵐ⁰) ↔ Even n := by
  constructor
  · rintro ⟨w, hw⟩
    have hw0 : w ≠ 0 := by
      rintro rfl
      simp at hw
    rw [← exp_log hw0, ← exp_add, exp_inj] at hw
    exact ⟨_, hw⟩
  · rintro ⟨m, rfl⟩
    exact ⟨exp m, exp_add m m⟩

/-! ## Height-one primes of `𝓞 B` -/

/-- The height-one prime `(q)` of a prime element. -/
def heightOneOf (q : 𝓞 B) (hq : Prime q) : HeightOneSpectrum (𝓞 B) where
  asIdeal := span {q}
  isPrime := (span_singleton_prime hq.ne_zero).mpr hq
  ne_bot := by rw [Ne, span_singleton_eq_bot]; exact hq.ne_zero

@[simp] theorem heightOneOf_asIdeal (q : 𝓞 B) (hq : Prime q) :
    (heightOneOf q hq).asIdeal = span {q} := rfl

theorem exists_prime_generator (v : HeightOneSpectrum (𝓞 B)) :
    ∃ q : 𝓞 B, Prime q ∧ v.asIdeal = span {q} := by
  obtain ⟨q, hq⟩ := (IsPrincipalIdealRing.principal v.asIdeal).principal
  have hq' : v.asIdeal = span {q} := hq
  have hne : q ≠ 0 := by
    rintro rfl
    exact v.ne_bot (by rw [hq', span_singleton_eq_bot])
  exact ⟨q, (span_singleton_prime hne).mp (hq' ▸ v.isPrime), hq'⟩

/-! ## The radicands at the six primes of `S` -/

theorem prime_alpha (i : Fin 8) (hi : 2 ≤ i.val) : Prime (alpha i) := by
  fin_cases i
  · exact absurd hi (by decide)
  · exact absurd hi (by decide)
  · exact prime_pi2
  · exact prime_pi2'
  · exact prime_pi3
  · exact prime_pi3'
  · exact prime_pi5
  · exact prime_pi5'

/-- The primes containing `30` are those generated by `alpha 2, …, alpha 7`. -/
theorem exists_alpha_of_thirty_mem {P : Ideal (𝓞 B)} [hP : P.IsPrime] (h : (30 : 𝓞 B) ∈ P) :
    ∃ i : Fin 8, 2 ≤ i.val ∧ P = span {alpha i} := by
  have h30 : (30 : 𝓞 B) = 2 * 3 * 5 := by norm_num
  rw [h30] at h
  rcases hP.mem_or_mem h with h | h5
  · rcases hP.mem_or_mem h with h2 | h3
    · rcases eq_P2_or_P2' h2 with rfl | rfl
      · exact ⟨2, by decide, rfl⟩
      · exact ⟨3, by decide, rfl⟩
    · rcases eq_P3_or_P3' h3 with rfl | rfl
      · exact ⟨4, by decide, rfl⟩
      · exact ⟨5, by decide, rfl⟩
  · rcases eq_P5_or_P5' h5 with rfl | rfl
    · exact ⟨6, by decide, rfl⟩
    · exact ⟨7, by decide, rfl⟩

theorem thirty_mem_span_alpha (i : Fin 8) (hi : 2 ≤ i.val) : (30 : 𝓞 B) ∈ span {alpha i} := by
  have h30 : (30 : 𝓞 B) = 2 * 3 * 5 := by norm_num
  rw [h30]
  fin_cases i
  · exact absurd hi (by decide)
  · exact absurd hi (by decide)
  · exact mul_mem_right _ _ (mul_mem_right _ _ natCast_mem_P2)
  · exact mul_mem_right _ _ (mul_mem_right _ _ natCast_mem_P2')
  · exact mul_mem_right _ _ (mul_mem_left _ _ natCast_mem_P3)
  · exact mul_mem_right _ _ (mul_mem_left _ _ natCast_mem_P3')
  · exact mul_mem_left _ _ natCast_mem_P5
  · exact mul_mem_left _ _ natCast_mem_P5'

/-- Coordinates of the radicands in the basis `1, ω`. -/
def alphaCoords : Fin 8 → ℤ × ℤ :=
  ![(-1, 0), (-75585293, 9148450), (-2854, -393), (3247, -393), (33, -4), (29, 4),
    (347, -42), (305, 42)]

theorem alpha_eq_mk (i : Fin 8) : alpha i = mk (alphaCoords i).1 (alphaCoords i).2 := by
  fin_cases i
  · change (-1 : 𝓞 B) = mk (-1) 0
    simp [mk]
  all_goals rfl

theorem evalHom_alpha {R : Type*} [CommRing R] (r : R) (hr : r * r = r + 60) (i : Fin 8) :
    evalHom r hr (alpha i) = ((alphaCoords i).1 : R) + ((alphaCoords i).2 : R) * r := by
  rw [alpha_eq_mk, evalHom_mk]

theorem alpha_mem_span_alpha_iff (i j : Fin 8) (hi : 2 ≤ i.val) :
    alpha j ∈ span {alpha i} ↔ j = i := by
  fin_cases i
  · exact absurd hi (by decide)
  · exact absurd hi (by decide)
  · change alpha j ∈ P2 ↔ j = 2
    rw [mem_P2, res2, evalHom_alpha]
    revert j; decide
  · change alpha j ∈ P2' ↔ j = 3
    rw [mem_P2', res2', evalHom_alpha]
    revert j; decide
  · change alpha j ∈ P3 ↔ j = 4
    rw [mem_P3, res3, evalHom_alpha]
    revert j; decide
  · change alpha j ∈ P3' ↔ j = 5
    rw [mem_P3', res3', evalHom_alpha]
    revert j; decide
  · change alpha j ∈ P5 ↔ j = 6
    rw [mem_P5, res5, evalHom_alpha]
    revert j; decide
  · change alpha j ∈ P5' ↔ j = 7
    rw [mem_P5', res5', evalHom_alpha]
    revert j; decide

/-- The height-one prime generated by the radicand `alpha i`, `i ≥ 2`. -/
def primeS (i : Fin 8) (hi : 2 ≤ i.val) : HeightOneSpectrum (𝓞 B) :=
  heightOneOf (alpha i) (prime_alpha i hi)

theorem intValuation_alpha (i j : Fin 8) (hi : 2 ≤ i.val) :
    (primeS i hi).intValuation (alpha j) = if j = i then exp (-1) else 1 := by
  split_ifs with h
  · subst h
    exact (primeS j hi).intValuation_singleton (alpha_ne_zero j) rfl
  · rw [HeightOneSpectrum.intValuation_eq_one_iff]
    exact fun hmem ↦ h ((alpha_mem_span_alpha_iff i j hi).mp hmem)

/-! ## Products of radicands -/

/-- `∏ alpha i ^ e i` in `B`. -/
def alphaProd (e : Fin 8 → ℕ) : B := ∏ i, ((alpha i : 𝓞 B) : B) ^ e i

theorem alphaProd_add (e e' : Fin 8 → ℕ) : alphaProd (e + e') = alphaProd e * alphaProd e' := by
  simp only [alphaProd, Pi.add_apply, pow_add, Finset.prod_mul_distrib]

theorem alphaProd_zero : alphaProd 0 = 1 := by
  simp [alphaProd]

theorem alphaProd_single (i : Fin 8) : alphaProd (Pi.single i 1) = ((alpha i : 𝓞 B) : B) := by
  rw [alphaProd, Finset.prod_eq_single i]
  · simp
  · intro j _ hj
    simp [hj]
  · simp

theorem alphaProd_ne_zero (e : Fin 8 → ℕ) : alphaProd e ≠ 0 := by
  rw [alphaProd, Finset.prod_ne_zero_iff]
  intro i _
  apply pow_ne_zero
  rw [Ne, RingOfIntegers.coe_eq_zero_iff]
  exact alpha_ne_zero i

theorem alphaProd_mod_two (e : Fin 8 → ℕ) :
    alphaProd e = alphaProd (fun i ↦ e i % 2) * (alphaProd (fun i ↦ e i / 2)) ^ 2 := by
  simp only [alphaProd, ← Finset.prod_pow, ← Finset.prod_mul_distrib, ← pow_mul, ← pow_add]
  refine Finset.prod_congr rfl fun i _ ↦ ?_
  congr 1
  omega

/-- `x` is a product of radicands times a nonzero square. -/
def Expressible (x : B) : Prop := ∃ e : Fin 8 → ℕ, ∃ γ : B, γ ≠ 0 ∧ x = alphaProd e * γ ^ 2

theorem Expressible.mul {x y : B} (hx : Expressible x) (hy : Expressible y) :
    Expressible (x * y) := by
  obtain ⟨e, γ, hγ, rfl⟩ := hx
  obtain ⟨e', γ', hγ', rfl⟩ := hy
  exact ⟨e + e', γ * γ', mul_ne_zero hγ hγ', by rw [alphaProd_add]; ring⟩

theorem Expressible.pow {x : B} (hx : Expressible x) (n : ℕ) : Expressible (x ^ n) := by
  induction n with
  | zero => exact ⟨0, 1, one_ne_zero, by simp [alphaProd_zero]⟩
  | succ n ih => rw [pow_succ]; exact ih.mul hx

theorem expressible_alpha (i : Fin 8) : Expressible ((alpha i : 𝓞 B) : B) :=
  ⟨Pi.single i 1, 1, one_ne_zero, by rw [alphaProd_single]; ring⟩

theorem expressible_sq {γ : B} (hγ : γ ≠ 0) : Expressible (γ ^ 2) :=
  ⟨0, γ, hγ, by rw [alphaProd_zero, one_mul]⟩

theorem expressible_unit (u : (𝓞 B)ˣ) : Expressible (((u : 𝓞 B) : B)) := by
  obtain ⟨a, b, _, _, w, rfl⟩ := unit_eq_mul_sq u
  have hw : ((w : 𝓞 B) : B) ≠ 0 := by
    rw [Ne, RingOfIntegers.coe_eq_zero_iff]; exact w.ne_zero
  have h1 : (((((-1 : (𝓞 B)ˣ) ^ a * epsUnit ^ b * w ^ 2 : (𝓞 B)ˣ) : 𝓞 B) : B)) =
      ((alpha 0 : 𝓞 B) : B) ^ a * ((alpha 1 : 𝓞 B) : B) ^ b * ((w : 𝓞 B) : B) ^ 2 := by
    simp [alpha]
  rw [h1]
  exact (((expressible_alpha 0).pow a).mul ((expressible_alpha 1).pow b)).mul (expressible_sq hw)

/-- An element of `𝓞 B` not divisible by any prime outside `S` is expressible. -/
theorem expressible_of_supported {x : 𝓞 B} (hx : x ≠ 0)
    (hS : ∀ v : HeightOneSpectrum (𝓞 B), (30 : 𝓞 B) ∉ v.asIdeal → x ∉ v.asIdeal) :
    Expressible (x : B) := by
  induction x using WfDvdMonoid.induction_on_irreducible with
  | zero => exact absurd rfl hx
  | unit u hu => exact expressible_unit hu.unit
  | mul z p hz hp ih =>
    have hS' : ∀ v : HeightOneSpectrum (𝓞 B), (30 : 𝓞 B) ∉ v.asIdeal → z ∉ v.asIdeal :=
      fun v hv hzv ↦ hS v hv (v.asIdeal.mul_mem_left p hzv)
    have hpp : Prime p := hp.prime
    have h30 : (30 : 𝓞 B) ∈ span {p} := by
      by_contra h
      exact hS (heightOneOf p hpp) h (mem_span_singleton.mpr (dvd_mul_right p z))
    have : (span {p}).IsPrime := (span_singleton_prime hpp.ne_zero).mpr hpp
    obtain ⟨i, _, hi⟩ := exists_alpha_of_thirty_mem h30
    obtain ⟨w, hw⟩ := (span_singleton_eq_span_singleton.mp hi).symm
    have hpw : ((p : 𝓞 B) : B) = ((alpha i : 𝓞 B) : B) * (((w : 𝓞 B)) : B) := by
      rw [← hw]; exact coe_mul _ _
    rw [coe_mul, hpw]
    exact ((expressible_alpha i).mul (expressible_unit w)).mul (ih hz hS')

/-! ## The main theorems -/

/-- **`S`-units modulo squares.** If `β ≠ 0` has even valuation at every prime of `B` not
above `2, 3, 5`, then `β = ∏ alpha i ^ e i · γ²` with `e i ∈ {0, 1}`. -/
theorem sUnit_squareclass (β : B) (hβ : β ≠ 0)
    (heven : ∀ v : HeightOneSpectrum (𝓞 B), (30 : 𝓞 B) ∉ v.asIdeal →
      IsSquare (v.valuation B β)) :
    ∃ e : Fin 8 → ℕ, (∀ i, e i < 2) ∧ ∃ γ : B, γ ≠ 0 ∧ β = alphaProd e * γ ^ 2 := by
  -- clear denominators: `β = (x y) · (1/y)²`
  obtain ⟨x, y, hy, hxy⟩ := IsFractionRing.div_surjective (A := 𝓞 B) β
  have hy0 : y ≠ 0 := nonZeroDivisors.ne_zero hy
  have hyB : ((y : 𝓞 B) : B) ≠ 0 := by rw [Ne, RingOfIntegers.coe_eq_zero_iff]; exact hy0
  have hx0 : x ≠ 0 := by
    rintro rfl
    apply hβ
    rw [← hxy, map_zero, zero_div]
  set z := x * y with hz
  have hz0 : z ≠ 0 := mul_ne_zero hx0 hy0
  have hβz : β = (z : B) * ((y : B)⁻¹) ^ 2 := by
    rw [← hxy, hz, coe_mul]
    change (x : B) / (y : B) = (x : B) * (y : B) * ((y : B)⁻¹) ^ 2
    field_simp
  -- squarefree part
  obtain ⟨c, d, hcd, hd⟩ := exists_sq_mul_squarefree z
  have hc0 : c ≠ 0 := by
    rintro rfl
    apply hz0
    rw [← hcd]; simp
  -- `d` is not divisible by primes outside `S`
  have hdS : ∀ v : HeightOneSpectrum (𝓞 B), (30 : 𝓞 B) ∉ v.asIdeal → d ∉ v.asIdeal := by
    intro v hv
    have hsqz : IsSquare (v.intValuation z) := by
      have h2 : v.valuation B ((z : 𝓞 B) : B) =
          v.valuation B β * (v.valuation B ((y : 𝓞 B) : B)) ^ 2 := by
        rw [hβz, map_mul, map_pow, map_inv₀, mul_assoc, ← mul_pow,
          inv_mul_cancel₀ ((Valuation.ne_zero_iff _).mpr hyB), one_pow, mul_one]
      have h3 : v.intValuation z = v.valuation B β * (v.valuation B ((y : 𝓞 B) : B)) ^ 2 := by
        rw [← h2]
        exact (HeightOneSpectrum.valuation_of_algebraMap v z).symm
      rw [h3]
      exact (heven v hv).mul (IsSquare.sq _)
    have hsqd : IsSquare (v.intValuation d) := by
      have hc : v.intValuation c ≠ 0 := v.intValuation_ne_zero c hc0
      have h3 : v.intValuation d = v.intValuation z * ((v.intValuation c) ^ 2)⁻¹ := by
        rw [← hcd, map_mul, map_pow, mul_comm (v.intValuation c ^ 2), mul_assoc,
          mul_inv_cancel₀ (pow_ne_zero 2 hc), mul_one]
      rw [h3]
      exact hsqz.mul (IsSquare.sq _).inv
    -- `d` is squarefree, so its valuation is `exp 0` or `exp (-1)`
    obtain ⟨n, hn⟩ : ∃ n : ℕ, v.intValuation d = exp (-(n : ℤ)) :=
      ⟨_, v.intValuation_if_neg hd.ne_zero⟩
    have hnot2 : ¬ v.intValuation d ≤ exp (-((2 : ℕ) : ℤ)) := by
      rw [HeightOneSpectrum.intValuation_le_pow_iff_mem]
      obtain ⟨q, hq, hvq⟩ := exists_prime_generator v
      rw [hvq, span_singleton_pow, mem_span_singleton]
      intro hdvd
      exact hq.not_isUnit (hd q (by rwa [← sq]))
    rw [hn, exp_le_exp] at hnot2
    rw [hn, isSquare_exp_iff] at hsqd
    have hn0 : n = 0 := by
      obtain ⟨m, hm⟩ := hsqd
      omega
    rw [← HeightOneSpectrum.intValuation_eq_one_iff, hn, hn0]
    simp
  have hdE := expressible_of_supported hd.ne_zero hdS
  -- assemble
  have hβE : Expressible β := by
    have hcB : ((c : 𝓞 B) : B) ≠ 0 := by rw [Ne, RingOfIntegers.coe_eq_zero_iff]; exact hc0
    have hyi : ((y : 𝓞 B) : B)⁻¹ ≠ 0 := inv_ne_zero hyB
    have : β = ((d : 𝓞 B) : B) * (((c : 𝓞 B) : B) * ((y : 𝓞 B) : B)⁻¹) ^ 2 := by
      rw [hβz, ← hcd, coe_mul, coe_pow]
      ring
    rw [this]
    exact hdE.mul (expressible_sq (mul_ne_zero hcB hyi))
  obtain ⟨e, γ, hγ, hβe⟩ := hβE
  refine ⟨fun i ↦ e i % 2, fun i ↦ Nat.mod_lt _ (by norm_num),
    alphaProd (fun i ↦ e i / 2) * γ, mul_ne_zero (alphaProd_ne_zero _) hγ, ?_⟩
  rw [hβe, alphaProd_mod_two e]
  ring

/-- The valuation of a product of radicands at the prime of `alpha i`. -/
theorem valuation_alphaProd (i : Fin 8) (hi : 2 ≤ i.val) (e : Fin 8 → ℕ) :
    (primeS i hi).valuation B (alphaProd e) = exp (-(e i : ℤ)) := by
  rw [alphaProd, map_prod]
  simp only [map_pow]
  have h : ∀ j, (primeS i hi).valuation B ((alpha j : 𝓞 B) : B) = if j = i then exp (-1) else 1 := by
    intro j
    rw [← intValuation_alpha i j hi]
    exact HeightOneSpectrum.valuation_of_algebraMap _ _
  simp only [h]
  rw [Finset.prod_eq_single i]
  · rw [ite_eq_left rfl, ← exp_nsmul]
    congr 1
    simp
  · intro j _ hj
    simp [hj]
  · simp

/-- **Independence.** A product of distinct radicands is a square only if it is empty. -/
theorem alphaProd_independent {e : Fin 8 → ℕ} (he : ∀ i, e i < 2) {γ : B}
    (h : alphaProd e = γ ^ 2) : e = 0 := by
  have hval : ∀ i : Fin 8, 2 ≤ i.val → e i = 0 := by
    intro i hi
    have h2 : IsSquare ((primeS i hi).valuation B (alphaProd e)) := by
      rw [h, map_pow]; exact IsSquare.sq _
    rw [valuation_alphaProd, isSquare_exp_iff] at h2
    have := he i
    obtain ⟨m, hm⟩ := h2
    omega
  have hprod : alphaProd e = (-1 : B) ^ e 0 * ((eps : 𝓞 B) : B) ^ e 1 := by
    rw [alphaProd, Fin.prod_univ_eight]
    rw [hval 2 (by decide), hval 3 (by decide), hval 4 (by decide), hval 5 (by decide),
      hval 6 (by decide), hval 7 (by decide)]
    simp [alpha]
  rw [hprod] at h
  have h0 := he 0
  have h1 := he 1
  have hsq : ∀ (f : B →ₐ[ℚ] ℝ), 0 ≤ f ((-1 : B) ^ e 0 * ((eps : 𝓞 B) : B) ^ e 1) := by
    intro f
    rw [h, map_pow]
    exact sq_nonneg _
  have hplus := hsq embPlus
  have hminus := hsq embMinus
  simp only [map_mul, map_pow, map_neg, map_one] at hplus hminus
  have hεp := embPlus_eps_pos
  have hεm := embMinus_eps_neg
  have he0 : e 0 = 0 := by
    by_contra hne
    have h01 : e 0 = 1 := by omega
    rw [h01, pow_one] at hplus
    have := pow_pos hεp (e 1)
    linarith
  have he1 : e 1 = 0 := by
    by_contra hne
    have h11 : e 1 = 1 := by omega
    rw [he0, h11, pow_zero, pow_one, one_mul] at hminus
    linarith
  funext i
  fin_cases i
  · exact he0
  · exact he1
  all_goals exact hval _ (by decide)

/-- A product of radicands with exponents in `{0, 1}` is a square iff all exponents vanish. -/
theorem isSquare_alphaProd_iff {e : Fin 8 → ℕ} (he : ∀ i, e i < 2) :
    IsSquare (alphaProd e) ↔ e = 0 := by
  constructor
  · rintro ⟨γ, hγ⟩
    exact alphaProd_independent he (by rw [hγ, sq])
  · rintro rfl
    exact ⟨1, by rw [alphaProd_zero, mul_one]⟩

/-- `-1` and `ε` are independent modulo squares of `B^×` (hence of units). -/
theorem neg_one_pow_mul_eps_pow_isSquare_iff {a b : ℕ} (ha : a < 2) (hb : b < 2) :
    IsSquare ((-1 : B) ^ a * ((eps : 𝓞 B) : B) ^ b) ↔ a = 0 ∧ b = 0 := by
  have h : (-1 : B) ^ a * ((eps : 𝓞 B) : B) ^ b = alphaProd ![a, b, 0, 0, 0, 0, 0, 0] := by
    simp [alphaProd, Fin.prod_univ_eight, alpha]
  rw [h, isSquare_alphaProd_iff]
  · constructor
    · intro he
      exact ⟨congrFun he 0, congrFun he 1⟩
    · rintro ⟨rfl, rfl⟩
      funext i
      fin_cases i <;> rfl
  · intro i
    fin_cases i <;> simp [ha, hb]

theorem not_isSquare_neg_one : ¬ IsSquare (-1 : B) := by
  have := (neg_one_pow_mul_eps_pow_isSquare_iff (a := 1) (b := 0) (by norm_num) (by norm_num))
  simpa using this

theorem not_isSquare_eps : ¬ IsSquare ((eps : 𝓞 B) : B) := by
  have := (neg_one_pow_mul_eps_pow_isSquare_iff (a := 0) (b := 1) (by norm_num) (by norm_num))
  simpa using this

theorem not_isSquare_neg_eps : ¬ IsSquare (-((eps : 𝓞 B) : B)) := by
  have := (neg_one_pow_mul_eps_pow_isSquare_iff (a := 1) (b := 1) (by norm_num) (by norm_num))
  simpa using this

end UnitDistance.Sqrt241.Base
