"""GS over B' = B(sqrt W), W subset of the Kummer group of the tower over B=Q(sqrt 241).
Model of the natural presentation over B' (no S'-class group term; c'>=0 only helps)."""
import itertools, math, sys
import numpy as np
from dgroup import gen, jennings_dims, X, Y, Z, W as WW, mul, ELEMS, E

def v(s): return np.array([int(c) for c in s], dtype=np.int64)
VEC = {
 'i1': v('10111010'), 'i2': v('11000101'),
 'x1': v('00100000'), 'y1': v('11110010'), 'z1': v('10000100'),
 'x2': v('00010000'), 'y2': v('10000001'), 'z2': v('11111000'),
 'tq1': v('00001000'), 'fq1': v('10100111'),
 'tq2': v('00000100'), 'fq2': v('11101011'),
 'tr1': v('00000010'), 'fr1': v('01100101'),
 'tr2': v('00000001'), 'fr2': v('01011010'),
 'F29a': v('00100111'), 'F29b': v('00011011'), 'F7': v('01110000'),
}

def rank2(M):
    M = [row.copy() % 2 for row in M]
    r = 0
    if not M: return 0
    ncol = len(M[0])
    for c in range(ncol):
        piv = None
        for i in range(r, len(M)):
            if M[i][c]: piv = i; break
        if piv is None: continue
        M[r], M[piv] = M[piv], M[r]
        for i in range(len(M)):
            if i != r and M[i][c]: M[i] = (M[i] + M[r]) % 2
        r += 1
    return r

def nullspace2(rows, n=8):
    """basis of {a in F2^n : rows . a = 0}"""
    sols = []
    for a in itertools.product(range(2), repeat=n):
        a = np.array(a)
        if all((r @ a) % 2 == 0 for r in rows): sols.append(a)
    # extract basis
    basis = []
    for s in sols:
        if s.any() and rank2(basis + [s]) > len(basis): basis.append(s)
    return basis

D = gen([X, Y, Z])

def dyadic_kernel(xv, yv, zv, Wb):
    """subgroup of D killed by restriction to W (Wb: list of basis vectors of W in F2^8)."""
    imgs = [np.array([(g @ w) % 2 for w in Wb]) for g in (xv, yv, zv)]
    K = frozenset(g for g in D if not ((g[0]*imgs[0] + g[1]*imgs[1] + (g[2] % 2)*imgs[2]) % 2).any())
    r = rank2(imgs)
    # inertia of D is <x,y,w>; image of inertia
    ri = rank2([imgs[0], imgs[1]])
    return K, r, ri

def hil(dims, t):
    h = 1.0
    for i, d in enumerate(dims): h *= (1 + t**(i+1))**d
    return h

JD = {}
def jd(K):
    if K not in JD: JD[K] = jennings_dims(K) if len(K) > 1 else []
    return JD[K]

def PBprime(t, Wb, design):
    """design: dict place-> type. Returns (P, details)."""
    k = len(Wb)
    total = 1.0
    sav = 0.0
    det = []
    def img(vec): return np.array([(vec @ w) % 2 for w in Wb])
    # real places
    for p in ('i1', 'i2'):
        r = rank2([img(VEC[p])])
        n = 2**(k - r)
        if r == 0:
            b = (t*t/(1+t)) - t   # real place, C2, one generator
            sav = max(sav, t*t/(1+t))
        else:
            b = -t                # complex place
        total += n * b; det.append((p, r, n, round(b, 4)))
    # dyadic
    for j in ('1', '2'):
        K, r, ri = dyadic_kernel(VEC['x'+j], VEC['y'+j], VEC['z'+j], Wb)
        n = 2**(k - r)
        kw = 2**r + 2
        dims = jd(K)
        psi = kw*t - 1 + 1/hil(dims, t)
        b = psi - t
        if r == 0:
            hD = hil(dims, t); sav = max(sav, t*t*(1 - t**7/hD))
        total += n * b; det.append(('p'+j, r, n, round(b, 4), dims))
    # tame
    for q in ('q1', 'q2', 'r1', 'r2'):
        ty = design.get(q, '22')
        tv, fv = img(VEC['t'+q]), img(VEC['f'+q])
        if ty == '22':
            # Gamma = <tau,phi> = C2xC2 ; image in W^dual
            r = rank2([tv, fv]); n = 2**(k - r)
            if r == 0: b = 2*t - 1 + 1/(1+t)**2 - t
            elif r == 1:
                # kernel C2 (either inertia-only (unram in B' ... ) or Frobenius-only)
                b = 2*t - 1 + 1/(1+t) - t   # local group C2 inside, 2 local generators
            else:
                b = 2*t - 1 + 1 - t         # trivial: both generators killed
        elif ty == '21':
            # Gamma = <tau>, phi killed (phi' = phi or phi*tau chosen in design)
            r = rank2([tv]); n = 2**(k - r)
            if r == 0: b = 2*t - 1 + 1/(1+t) - t
            else: b = 2*t - 1 + 1 - t
        total += n * b; det.append((q, ty, r, n, round(b, 4)))
    # caps (Frobenius order 4): C4 generated by Frob; restriction
    for c in design.get('caps', ['F29a', 'F29b', 'F7']):
        fvec = img(VEC[c]); r = rank2([fvec]); n = 2**(k - r)
        # 7 is inert in B: its place has local degree 2 but same accounting
        if r == 0: psi = t - 1 + 1/((1+t)*(1+t*t))
        else: psi = t - 1 + 1/(1+t)   # remaining C2
        total += n * psi; det.append((c, r, n, round(psi, 4)))
    total -= sav
    return total, det

def killed(design):
    ks = []
    for q in ('q1', 'q2', 'r1', 'r2'):
        if design.get(q) == '21':
            ks.append((VEC['f'+q] + (VEC['t'+q] if design.get(q+'tw') else 0)) % 2)
    return ks

def subspaces(basis, k):
    """all k-dim subspaces of span(basis), as reduced lists of vectors."""
    n = len(basis)
    seen = set()
    vecs = []
    for coeffs in itertools.product(range(2), repeat=n):
        if any(coeffs):
            vv = sum(c*b for c, b in zip(coeffs, basis)) % 2
            vecs.append(vv)
    for combo in itertools.combinations(range(len(vecs)), k):
        M = [vecs[i] for i in combo]
        if rank2(M) < k: continue
        span = set()
        for coeffs in itertools.product(range(2), repeat=k):
            span.add(tuple(sum(c*m for c, m in zip(coeffs, M)) % 2))
        key = frozenset(span)
        if key in seen: continue
        seen.add(key)
        yield M

def best_t(Wb, design):
    best = (1e9, None)
    for t in np.arange(0.15, 0.45, 0.005):
        P, det = PBprime(t, Wb, design)
        if P < best[0]: best = (P, t, det)
    return best

if __name__ == "__main__":
    designs = {
      'orig': {},
      '3:21': {'q1': '21', 'q2': '21'},
      '3,5:21': {'q1': '21', 'q2': '21', 'r1': '21', 'r2': '21'},
      'q1:21': {'q1': '21'},
    }
    for name, des in designs.items():
        ks = killed(des)
        VM = nullspace2(ks) if ks else [np.eye(8, dtype=np.int64)[i] for i in range(8)]
        P0 = best_t([], des)
        print("design", name, "dim V_M", len(VM), "P_B min", round(P0[0], 4), "t", round(P0[1], 3), flush=True)
        for k in (1, 2, 3):
            res = []
            for Wb in subspaces(VM, k):
                P = best_t(Wb, des)
                res.append((P[0], P[1], [''.join(map(str, w)) for w in Wb], P[2]))
            res.sort(key=lambda r: r[0])
            print("  k", k, "count", len(res))
            for r in res[:3]:
                print("   P", round(r[0], 4), "t", round(r[1], 3), r[2])
                print("     ", r[3])
            sys.stdout.flush()
