module

public import UnitDistance.Sqrt241.V2.Freedom
public import UnitDistance.AbsolutePrimeImages
public import UnitDistance.Sqrt241.Local.CapRanges
public import UnitDistance.Sqrt241.Genus.Frobenius

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false

/-!
# Version 2: the primes of `K_j` above the capped prime `41₁`

In the Galois closure `K̃_j` the chosen prime `P₀` above `41` (`restrictedAbsolutePrime`) has
stabilizer generated by the restriction of the absolute Frobenius `F₄₁`
(`decompositionRestriction_range`; `41` is unramified in `Ω`). The normalized cap element
is `Frob(41₁) = fr F₄₁ fr⁻¹` (`fr ∈ {1, σ̂}`), so the prime `Pcap = fr · P₀` has stabilizer
`⟨Frob(41₁)⟩` (`stabilizer_Pcap`).

`(√241 − 6)(√241 + 6) = 205 ∈ 41ℤ`, so `Pcap` contains `√241 − r` for `r = 6` or `r = −6`
(`capRoot`). A prime `Q` of `K̃_j` above `41` containing `√241 − r` is `s · Pcap` with
`s ∈ G_B` (`eq_smul_Pcap`): otherwise `Q = s σ̂ · Pcap` would contain `−√241 − r`, and `Pcap`
would contain `2r = ±12`. Its stabilizer is `⟨s Frob(41₁) s⁻¹⟩`, whose fourth powers fix `K_j`
(`Frob(41₁)⁴ ∈ kernelHat41 ≤ Gal(Ω/K_j)`, normal in `G_B`). With the residue Frobenius
(`Ideal.Quotient.stabilizerHom_surjective`), `z^{41⁴} ≡ z` modulo every prime `P` of `K_j`
above `41` containing `√241 − r` (`pow_sub_mem_of_capped`), so `N P ≤ 41⁴`; since the
residue degree of `M` at `41` is at least `4` (version 1's census), `N P = 41⁴`
(`absNorm_capped`), and `e(P | 41) = 1`.

The identification of `Pcap ∩ B` with `P41[1] = (41, √241 − 6)` (that is, `r = 6`) is not
needed and not proved.
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.V2

open Tower Retained UnitDistance.NumberFieldAnalysis IsDedekindDomain NumberField
open UnitDistance.PrimeCompletion _root_.UnitDistance.Sqrt241.Local
open scoped Pointwise

attribute [local instance] PrimeCompletion.primeFact PrimeCompletion.baseRationalAlgebra

/-! ### Integers of subfields of `Ω` -/

/-- The image in `Ω` of an integer of a subfield `F ≤ Ω`. -/
def toOmega (F : IntermediateField ℚ Omega) : 𝓞 F →+* Omega :=
  (F.val : F →+* Omega).comp (algebraMap (𝓞 F) F)

theorem toOmega_injective (F : IntermediateField ℚ Omega) : Function.Injective (toOmega F) :=
  fun _ _ h => RingOfIntegers.ext (Subtype.ext h)

theorem toOmega_res_smul (L : IntermediateField ℚ Omega) [FiniteDimensional ℚ L]
    [IsGalois ℚ L] (t : Ghat) (x : 𝓞 L) :
    toOmega L (Input.res L t • x) = t (toOmega L x) :=
  GaloisEmbedding.restriction_commutes L.val t (x : L)

/-- `√241` in `𝓞 F` for `B ≤ F ≤ Ω`. -/
theorem isIntegral_rootOmega : IsIntegral ℤ rootOmega := by
  apply IsIntegral.of_pow two_pos
  rw [rootOmega_sq]
  simpa using (isIntegral_algebraMap (R := ℤ) (A := Omega) (x := 241))

/-- `√241` in `𝓞 F` for `B ≤ F ≤ Ω`. -/
def sqrtInt (F : IntermediateField ℚ Omega) (hF : BinOmega ≤ F) : 𝓞 F :=
  ⟨⟨rootOmega, hF rootOmega_mem_BinOmega⟩, (mem_integralClosure_iff ℤ F).mpr
    ((isIntegral_algHom_iff ((F.val : F →+* Omega).toIntAlgHom) F.val.injective).mp
      isIntegral_rootOmega)⟩

@[simp] theorem toOmega_sqrtInt (F : IntermediateField ℚ Omega) (hF : BinOmega ≤ F) :
    toOmega F (sqrtInt F hF) = rootOmega := rfl

/-! ### The capped prime of the Galois closure -/

section Closure

variable (j : ℕ)

/-- The absolute Frobenius at the chosen place above `41`, in `Ĝ`. -/
abbrev F41 : Ghat := decompositionMap prime41 frob41Abs

/-- The chosen prime of `K̃_j` above `41`. -/
def P0 : Ideal (𝓞 (levelClosure j)) :=
  (restrictedAbsolutePrime (levelClosure j) prime41 (jK (levelClosure j))).asIdeal

instance P0_isPrime : (P0 j).IsPrime :=
  (restrictedAbsolutePrime (levelClosure j) prime41 (jK (levelClosure j))).isPrime

instance P0_liesOver : (P0 j).LiesOver (rationalPrimeIdeal 41) :=
  restrictedAbsolutePrime_liesOver (levelClosure j) prime41 (jK (levelClosure j))

theorem stabilizer_P0 : MulAction.stabilizer Gal(levelClosure j/ℚ) (P0 j) =
    Subgroup.zpowers (Input.res (levelClosure j) F41) := by
  rw [P0, ← decompositionRestriction_range, decompositionRestriction_eq_comp]
  exact decomposition_range_unramified prime41 (by decide) (Input.res (levelClosure j))

theorem coe_frob41_zero : ((frob41 0 : GB) : Ghat) = frame place41 0 * F41 * (frame place41 0)⁻¹ :=
  coe_localMapB _ _ _ _ _

theorem stabilizer_smul_eq (t : Ghat) (Q : Ideal (𝓞 (levelClosure j))) (g : Ghat)
    (hQ : MulAction.stabilizer Gal(levelClosure j/ℚ) Q =
      Subgroup.zpowers (Input.res (levelClosure j) g)) :
    MulAction.stabilizer Gal(levelClosure j/ℚ) (Input.res (levelClosure j) t • Q) =
      Subgroup.zpowers (Input.res (levelClosure j) (t * g * t⁻¹)) := by
  rw [MulAction.stabilizer_smul_eq_stabilizer_map_conj, hQ, MonoidHom.map_zpowers]
  congr 1
  rw [map_mul, map_mul, map_inv]
  rfl

theorem liesOver_smul (σ : Gal(levelClosure j/ℚ)) (Q : Ideal (𝓞 (levelClosure j))) (p : ℕ)
    [Q.LiesOver (rationalPrimeIdeal p)] : (σ • Q).LiesOver (rationalPrimeIdeal p) := by
  constructor
  rw [Ideal.over_def Q (rationalPrimeIdeal p)]
  ext n
  change algebraMap ℤ _ n ∈ Q ↔ algebraMap ℤ _ n ∈ σ • Q
  rw [Ideal.mem_pointwise_smul_iff_inv_smul_mem, smul_algebraMap]

/-- **The capped prime** `Pcap = fr · P₀` of `K̃_j`. -/
def Pcap : Ideal (𝓞 (levelClosure j)) := Input.res (levelClosure j) (frame place41 0) • P0 j

instance Pcap_isPrime : (Pcap j).IsPrime := Ideal.IsPrime.smul _

instance Pcap_liesOver : (Pcap j).LiesOver (rationalPrimeIdeal 41) := liesOver_smul j _ _ 41

theorem stabilizer_Pcap : MulAction.stabilizer Gal(levelClosure j/ℚ) (Pcap j) =
    Subgroup.zpowers (Input.res (levelClosure j) ((frob41 0 : GB) : Ghat)) := by
  rw [Pcap, stabilizer_smul_eq j _ _ F41 (stabilizer_P0 j), coe_frob41_zero]

/-! ### The window element -/

/-- `√241` in `𝓞 K̃_j`. -/
abbrev sqrtClosure : 𝓞 (levelClosure j) :=
  sqrtInt (levelClosure j) ((BinOmega_le_level j).trans (level_le_levelClosure j))

open Classical in
/-- **The root `r = ±6`** with `√241 − r ∈ Pcap`. -/
def capRoot : ℤ := if sqrtClosure j - 6 ∈ Pcap j then 6 else -6

theorem capRoot_cases : capRoot j = 6 ∨ capRoot j = -6 := by
  unfold capRoot
  split_ifs
  · exact Or.inl rfl
  · exact Or.inr rfl

theorem capRoot_mem : sqrtClosure j - (capRoot j : 𝓞 (levelClosure j)) ∈ Pcap j := by
  have h205 : (sqrtClosure j - 6) * (sqrtClosure j + 6) = ((205 : ℤ) : 𝓞 (levelClosure j)) := by
    apply toOmega_injective
    rw [map_mul, map_sub, map_add, map_intCast, map_ofNat, toOmega_sqrtInt]
    have h := rootOmega_sq
    push_cast
    linear_combination h
  have hmem : (sqrtClosure j - 6) * (sqrtClosure j + 6) ∈ Pcap j := by
    rw [h205, Genus.intCast_mem_iff (p := 41)]
    norm_num
  unfold capRoot
  split_ifs with h
  · push_cast
    exact h
  · rcases Ideal.IsPrime.mem_or_mem inferInstance hmem with h' | h'
    · exact absurd h' h
    · push_cast
      rwa [sub_neg_eq_add]

/-- **Primes above `41` containing `√241 − r` are the `G_B`-translates of `Pcap`.** -/
theorem eq_smul_Pcap (Q : Ideal (𝓞 (levelClosure j))) [Q.IsPrime]
    [Q.LiesOver (rationalPrimeIdeal 41)]
    (hQ : sqrtClosure j - (capRoot j : 𝓞 (levelClosure j)) ∈ Q) :
    ∃ s ∈ GB, Q = Input.res (levelClosure j) s • Pcap j := by
  obtain ⟨τ, hτ⟩ := Ideal.exists_smul_eq_of_isGaloisGroup (rationalPrimeIdeal 41) (Pcap j) Q
    Gal(levelClosure j/ℚ)
  obtain ⟨t, rfl⟩ := GaloisEmbedding.restriction_surjective (levelClosure j).val τ
  by_cases ht : t ∈ GB
  · exact ⟨t, ht, hτ.symm⟩
  · exfalso
    have ht' : t⁻¹ ∉ GB := fun h => ht (by simpa using GB.inv_mem h)
    have hroot : t⁻¹ rootOmega = -rootOmega := (not_mem_GB_iff _).mp ht'
    rw [← hτ, Ideal.mem_pointwise_smul_iff_inv_smul_mem] at hQ
    have hsum := (Pcap j).add_mem hQ (capRoot_mem j)
    have he : (Input.res (levelClosure j) t)⁻¹ •
        (sqrtClosure j - (capRoot j : 𝓞 (levelClosure j))) +
        (sqrtClosure j - (capRoot j : 𝓞 (levelClosure j))) =
          ((-2 * capRoot j : ℤ) : 𝓞 (levelClosure j)) := by
      apply toOmega_injective
      rw [← map_inv, map_add, toOmega_res_smul]
      simp only [map_sub, map_intCast, toOmega_sqrtInt, hroot]
      push_cast
      ring
    rw [he, Genus.intCast_mem_iff (p := 41)] at hsum
    rcases capRoot_cases j with h | h <;> rw [h] at hsum <;> norm_num at hsum

attribute [local instance] Ideal.Quotient.field in
/-- Frobenius lifting: if the `n`-th powers of the stabilizer of `Q` fix `x`, then
`x^{41^n} ≡ x (mod Q)`. -/
theorem pow_sub_mem_of_stab (Q : Ideal (𝓞 (levelClosure j))) [Q.IsPrime]
    [Q.LiesOver (rationalPrimeIdeal 41)] (n : ℕ) (x : 𝓞 (levelClosure j))
    (hx : ∀ σ ∈ MulAction.stabilizer Gal(levelClosure j/ℚ) Q, (σ ^ n) • x = x) :
    x ^ (41 ^ n) - x ∈ Q := by
  have := Genus.isMaximal_of_liesOver Q (p := 41)
  let _ : Fintype (ℤ ⧸ rationalPrimeIdeal 41) := Fintype.ofFinite _
  obtain ⟨σ, hσ⟩ := Ideal.Quotient.stabilizerHom_surjective Gal(levelClosure j/ℚ)
    (rationalPrimeIdeal 41) Q
    (FiniteField.frobeniusAlgEquivOfAlgebraic (ℤ ⧸ rationalPrimeIdeal 41) (𝓞 (levelClosure j) ⧸ Q))
  have h1 : Ideal.Quotient.stabilizerHom Q (rationalPrimeIdeal 41) Gal(levelClosure j/ℚ) (σ ^ n)
      (Ideal.Quotient.mk Q x) = Ideal.Quotient.mk Q x := by
    rw [Ideal.Quotient.stabilizerHom_apply]
    congr 1
    exact hx σ.1 σ.2
  rw [map_pow, hσ, AlgEquiv.coe_pow, FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate,
    Fintype.card_eq_nat_card, Int.card_ideal_quot] at h1
  rw [← Ideal.Quotient.eq, map_pow]
  exact h1

end Closure

/-! ### Primes of the level above the capped prime -/

section Level

variable (j : ℕ)

/-- `√241` in `𝓞 K_j`. -/
abbrev sqrtLevel : 𝓞 (level j) := sqrtInt (level j) (BinOmega_le_level j)

/-- **The window element** `√241 − r` at `41`. -/
def window41 : 𝓞 (level j) := sqrtLevel j - (capRoot j : 𝓞 (level j))

theorem toOmega_window41 : toOmega (level j) (window41 j) = rootOmega - (capRoot j : Omega) := by
  rw [window41, map_sub, map_intCast]
  rfl

/-- Every prime of `K_j` above `41` containing `√241 − r`: `z^{41⁴} ≡ z` for every `z`. -/
theorem pow_sub_mem_of_capped (P : Ideal (𝓞 (level j))) [P.IsPrime]
    [P.LiesOver (rationalPrimeIdeal 41)] (hP : window41 j ∈ P) (z : 𝓞 (level j)) :
    z ^ (41 ^ 4) - z ∈ P := by
  let := algebraOfLe (level_le_levelClosure j)
  have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot
    (rationalPrimeIdeal_ne_bot_of_prime (p := 41) (by norm_num)) P
  have : P.IsMaximal := Ideal.IsPrime.isMaximal inferInstance hP0
  obtain ⟨Q, hQ, hQP⟩ := exists_maximal_liesOver (L := levelClosure j) P
  have : Q.LiesOver (rationalPrimeIdeal 41) := Ideal.LiesOver.trans Q P _
  have hmap : ∀ y : 𝓞 (level j), toOmega (levelClosure j) (algebraMap _ _ y) =
      toOmega (level j) y := fun _ => rfl
  have hunder : ∀ y : 𝓞 (level j), y ∈ P ↔ algebraMap (𝓞 (level j)) _ y ∈ Q := by
    intro y
    rw [Ideal.over_def Q P]
    rfl
  have hwQ : sqrtClosure j - (capRoot j : 𝓞 (levelClosure j)) ∈ Q := by
    have h := (hunder _).mp hP
    have he : algebraMap (𝓞 (level j)) (𝓞 (levelClosure j)) (window41 j) =
        sqrtClosure j - (capRoot j : 𝓞 (levelClosure j)) := by
      apply toOmega_injective
      rw [hmap, toOmega_window41, map_sub, map_intCast, toOmega_sqrtInt]
    rwa [he] at h
  obtain ⟨s, hs, rfl⟩ := eq_smul_Pcap j Q hwQ
  have hstab := stabilizer_smul_eq j s (Pcap j) _ (stabilizer_Pcap j)
  have hg4 : (s * ((frob41 0 : GB) : Ghat) * s⁻¹) ^ 4 ∈ levelGroup j := by
    rw [conj_pow]
    exact levelGroup_conj_mem j hs (frob41_pow_four_mem_levelGroup j)
  have key := pow_sub_mem_of_stab j _ 4 (algebraMap (𝓞 (level j)) _ z) (by
    intro σ hσ
    rw [hstab] at hσ
    obtain ⟨m, rfl⟩ := Subgroup.mem_zpowers_iff.mp hσ
    have he : ((Input.res (levelClosure j) (s * ((frob41 0 : GB) : Ghat) * s⁻¹)) ^ m) ^ 4 =
        Input.res (levelClosure j) (((s * ((frob41 0 : GB) : Ghat) * s⁻¹) ^ 4) ^ m) := by
      rw [map_zpow, map_pow, ← zpow_natCast, ← zpow_mul, ← zpow_natCast, ← zpow_mul, mul_comm]
    rw [he]
    apply toOmega_injective
    rw [toOmega_res_smul, hmap]
    have hmem : ((s * ((frob41 0 : GB) : Ghat) * s⁻¹) ^ 4) ^ m ∈ (level j).fixingSubgroup := by
      rw [level_fixingSubgroup]
      exact Subgroup.zpow_mem _ hg4 m
    exact hmem ⟨_, (z : level j).2⟩)
  rw [hunder, map_sub, map_pow]
  exact key

theorem M_inertiaDegIn_41 : 4 ≤ (rationalPrimeIdeal 41).inertiaDegIn (𝓞 input.M) :=
  M_census 41 (by decide)

/-- **Primes of `K_j` above `41` containing `√241 − r` have norm `41⁴` and residue degree
`4`.** -/
theorem absNorm_capped (P : Ideal (𝓞 (level j))) [P.IsPrime]
    [P.LiesOver (rationalPrimeIdeal 41)] (hP : window41 j ∈ P) :
    Ideal.absNorm P = 41 ^ 4 ∧ P.inertiaDeg ℤ = 4 := by
  let := algebraOfLe (M_le_level j)
  have hp : (41 : ℕ).Prime := by norm_num
  have hP0 : P ≠ ⊥ := Ideal.ne_bot_of_liesOver_of_ne_bot
    (rationalPrimeIdeal_ne_bot_of_prime hp) P
  have : P.IsMaximal := Ideal.IsPrime.isMaximal inferInstance hP0
  have hle := absNorm_le_of_forall_pow_sub_mem (p := 41) P (41 ^ 4) (by norm_num)
    (pow_sub_mem_of_capped j P hP)
  have hnorm : Ideal.absNorm P = 41 ^ P.inertiaDeg ℤ := by
    rw [Ideal.absNorm_eq_pow_inertiaDeg' P hp, Ideal.inertiaDeg'_eq_inertiaDeg]
  let V := P.under (𝓞 input.M)
  have : P.LiesOver V := ⟨rfl⟩
  have : V.LiesOver (rationalPrimeIdeal 41) := Ideal.LiesOver.tower_bot P V _
  have hV : V.inertiaDeg ℤ = (rationalPrimeIdeal 41).inertiaDegIn (𝓞 input.M) :=
    inertiaDeg_eq_inertiaDegIn 41 V
  have hf4 : 4 ≤ P.inertiaDeg ℤ := by
    have h1 := inertiaDeg_le_of_liesOver V P
    rw [hV] at h1
    exact M_inertiaDegIn_41.trans h1
  have hf : P.inertiaDeg ℤ ≤ 4 := by
    rw [hnorm] at hle
    exact (Nat.pow_le_pow_iff_right (by norm_num)).mp hle
  have hf' : P.inertiaDeg ℤ = 4 := le_antisymm hf hf4
  exact ⟨by rw [hnorm, hf'], hf'⟩

/-- Every prime of `K_j` above `41` is unramified over `41`. -/
theorem ramificationIdx_41 (P : Ideal (𝓞 (level j))) [P.IsPrime]
    [P.LiesOver (rationalPrimeIdeal 41)] : P.ramificationIdx ℤ = 1 := by
  let := algebraOfLe (M_le_level j)
  let := algebraOfLe (level_le_levelClosure j)
  have hp : (41 : ℕ).Prime := by norm_num
  have := rationalPrimeIdeal_isMaximal_of_prime hp
  have hmem : prime41.val ∉ ({2, 3, 5, 241} : Finset ℕ) := by decide
  apply ramificationIdx_eq_of_sandwich (M := input.M) (L := levelClosure j) _
    (rationalPrimeIdeal_ne_bot_of_prime hp)
  · intro V _ _
    rw [ramificationIdx_eq_ramificationIdxIn 41 V]
    exact ramificationIdxIn_eq_one_away input.M prime41 hmem
  · intro W _ _
    rw [ramificationIdx_eq_ramificationIdxIn 41 W]
    exact ramificationIdxIn_eq_one_away (levelClosure j) prime41 hmem

end Level

end UnitDistance.Sqrt241.V2
