"""Amortized model over a real quadratic base B=Q(sqrt D) with 2 split.

Per-Q-unit normalisation: P_B = 2*(base + sum options) - (1 - s_D)  < 0.
Split primes: same options as over Q.  Inert primes (one prime of norm q^2):
  ramified (e=2): 1/2 generator per Q-unit, block over B halved;
  caps: local group generated by Frob_B, block halved.
"""
import sys
import numpy as np
from design import c1, dyadic, block, uncapped, pt, arch, C_SLACK, LOG2, PD
from optimize import PR
from util import L


def sD(t):
    return t * t * (1 - t**7 / PD(t))


def opts_split(delta, t, q):
    o = [(0.0, 0.0, "-")]
    rdc = -(0.5 - delta) * 0.5 * np.log(q)
    if q <= 61:
        o.append((-t + uncapped(t), rdc, "R:U"))
        for f in (2, 4, 8):
            o.append((-t + block(t, 2, f), rdc + pt(delta, q, 2, f), f"R:{f}"))
    for f in (2, 4, 8):
        o.append((block(t, 1, f), pt(delta, q, 1, f), f"u:{f}"))
    return o


def opts_inert(delta, t, q):
    o = [(0.0, 0.0, "-")]
    rdc = -(0.5 - delta) * 0.5 * np.log(q)
    if q <= 61:
        # ramified: local image C2 x Z2 (uncapped), C2 x C2 (abs f=4), C2 x C4 (abs f=8)
        o.append(((-t + uncapped(t)) / 2, rdc, "iR:U"))
        o.append(((-t + block(t, 2, 2)) / 2, rdc + pt(delta, q, 2, 4), "iR:4"))
        o.append(((-t + block(t, 2, 4)) / 2, rdc + pt(delta, q, 2, 8), "iR:8"))
        # absolute f=2: Frob_B killed (degree one): extra t
        o.append(((-t + t + c1(t)) / 2, rdc + pt(delta, q, 2, 2), "iR:2"))
    # unramified caps: Frob_B order 2 (abs f=4), order 4 (abs f=8), killed (abs f=2)
    o.append((block(t, 1, 2) / 2, pt(delta, q, 1, 4), "iu:4"))
    o.append((block(t, 1, 4) / 2, pt(delta, q, 1, 8), "iu:8"))
    o.append((t / 2, pt(delta, q, 1, 2), "iu:2"))
    return o


def solve(delta, t, D, res=2e-4, primes=PR):
    base = 1 - 2 * t + dyadic(t) + c1(t) - (1 - sD(t)) / 2
    Mbase = pt(delta, 2, 8, 4) - (0.5 - delta) * (2.25 * LOG2 + 0.5 * np.log(D)) - C_SLACK + arch(delta, 0.0)
    items = []
    for q in primes:
        if D % q == 0:
            continue
        items.append((q, opts_split(delta, t, q) if L(D, q) == 1 else opts_inert(delta, t, q)))
    lo = sum(min(o[0] for o in op) for _, op in items)
    hi = sum(max(o[0] for o in op) for _, op in items)
    off = int(np.floor(lo / res)) - 2
    n = int(np.ceil(hi / res)) - off + 3
    best = np.full(n, -np.inf)
    best[-off] = 0.0
    choice = []
    for q, op in items:
        new = np.full(n, -np.inf)
        arg = np.zeros(n, dtype=np.int16)
        for j, (dP, dM, lab) in enumerate(op):
            s = int(np.ceil(dP / res - 1e-12))
            sh = np.full(n, -np.inf)
            if s >= 0:
                sh[s:] = best[:n - s]
            else:
                sh[:n + s] = best[-s:]
            cand = sh + dM
            m = cand > new
            new[m] = cand[m]
            arg[m] = j
        choice.append(arg)
        best = new
    idx = np.arange(n)
    feas = (idx + off) * res < -base
    b = int(np.argmax(np.where(feas, best, -np.inf)))
    M = best[b]
    ch = []
    for (q, op), arg in zip(reversed(items), reversed(choice)):
        j = arg[b]
        dP, dM, lab = op[j]
        if lab != "-":
            ch.append((q, lab))
        b -= int(np.ceil(dP / res - 1e-12))
    return Mbase + M, ch[::-1]


def best_delta(D, ts=np.arange(0.15, 0.40, 0.0025), lo=0.036, hi=0.05):
    info = None
    for _ in range(16):
        mid = (lo + hi) / 2
        bM, bi = -np.inf, None
        for t in ts:
            M, ch = solve(mid, t, D)
            if M > bM:
                bM, bi = M, (t, ch)
        if bM > 0:
            lo, info = mid, bi
        else:
            hi = mid
    return lo, info


if __name__ == "__main__":
    for D in [int(x) for x in sys.argv[1:]]:
        d, info = best_delta(D)
        print("D", D, "delta", round(d, 6), "t", round(info[0], 4), info[1], flush=True)
