module

public import UnitDistance.Sqrt241.Levels.PrimeFreedom
public import UnitDistance.Sqrt241.Local.FrobeniusLocal
public import UnitDistance.Sqrt241.Genus.LocalTypes

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false

/-!
# The census: residue degree `4` at `41, 47, 53, 59, 61, 67, 79, 83, 97`

At a census prime `p` (split in `B`, unramified in `Ω`), the decomposition image in
`Gal(K/ℚ)` is cyclic on the restriction of the absolute Frobenius `F`
(`Local.decomposition_range_unramified`). `F ∈ G_B`, and its genus label `v` is the vector of
Legendre symbols of the radicands at the prime of `B` below the chosen place
(`Local.exists_absolute_frobenius_split`, `Local.frobenius_label_of_split`), from explicit
square-class tables at both `p`-adic roots of `241` (`CensusData`; the chosen place is
not known). For both roots `S(v) ≠ 0` in `Q_B`, so `ρ_B(F)² ≠ 1`, while `F⁴ ∈ core` for
every `F ∈ G_B` (`Q_B` has exponent `4`). Hence `F` has order `4` in `Gal(K/ℚ)` for every
admissible `K`: `e = 1` and `f = 4` (`census_inertiaDeg`).

The tables are checked by `decide +kernel` (`censusData_valid`); they are generated by
`scripts/sqrt241/generate_census_tables.py` (square classes `2 c'` with
`c' ≡ nA + nB·(±(2a−1)) mod p`, `a` a root of `X² − X − 60`).
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.Retained

open Tower Presentation Cut GroupData ProCGroups UnitDistance.PrimeCompletion
open _root_.UnitDistance.Sqrt241.Local NumberFieldAnalysis CanonicalGenus NumberField
open Base (B)

attribute [local instance] PrimeCompletion.primeFact PrimeCompletion.baseRationalAlgebra

/-! ### Radicands with integral numerators -/

/-- `2 × radicandA`. -/
def nA : Fin 8 → ℤ := ![-2, -142022136, -6101, 6101, 62, 62, 652, 652]
/-- `2 × radicandB`. -/
def nB : Fin 8 → ℤ := ![0, 9148450, -393, -393, -4, 4, -42, 42]

theorem radicandA_eq (k : Fin 8) : radicandA k = (nA k : ℚ) / 2 := by
  fin_cases k <;> norm_num [radicandA, nA]

theorem radicandB_eq (k : Fin 8) : radicandB k = (nB k : ℚ) / 2 := by
  fin_cases k <;> norm_num [radicandB, nB]

section Generic

variable (p : Nat.Primes) (hsq : IsSquare (241 : ℚ_[p.val]))

theorem placeEmb_alphaB_eq (k : Fin 8) :
    placeEmb p hsq (Base.alphaB k) =
      ((nA k : ℚ_[p.val]) + (nB k : ℚ_[p.val]) * placeRoot p hsq) / 2 := by
  rw [Base.algHom_alphaB, placeEmb_sqrt241, radicandA_eq, radicandB_eq]
  simp only [eq_ratCast]
  push_cast
  ring

theorem placeRoot_eq_or (t : ℚ_[p.val]) (ht : t ^ 2 = 241) :
    placeRoot p hsq = t ∨ placeRoot p hsq = -t :=
  sq_eq_sq_iff_eq_or_eq_neg.mp ((placeRoot_sq p hsq).trans ht.symm)

/-- **Square classes from residues.** -/
theorem squareclass_of_residue (t : ℤ_[p.val]) (ε : ℤ)
    (hs : placeRoot p hsq = ((ε : ℤ_[p.val]) * t : ℤ_[p.val])) (T : ℤ)
    (hT : PadicInt.toZMod t = (T : ZMod p.val)) (k : Fin 8) (c' : ℤ)
    (hc : ((nA k + nB k * ε * T : ℤ) : ZMod p.val) = (c' : ZMod p.val))
    (hne : (2 * c' : ZMod p.val) ≠ 0) :
    ∃ z : ℚ_[p.val], z ≠ 0 ∧ placeEmb p hsq (Base.alphaB k) = ((2 * c' : ℤ) : ℚ_[p.val]) * z ^ 2 := by
  set u : ℤ_[p.val] := (nA k : ℤ_[p.val]) + (nB k : ℤ_[p.val]) * (ε : ℤ_[p.val]) * t with hu
  have hres : PadicInt.toZMod u = (c' : ZMod p.val) * 1 ^ 2 := by
    rw [hu, map_add, map_mul, map_mul, map_intCast, map_intCast, map_intCast, hT, ← hc]
    push_cast
    ring
  obtain ⟨z, hz0, hz⟩ := Base.padicInt_eq_mul_sq_of_toZMod ⟨1, by simpa using hne, hres⟩
  refine ⟨(z : ℚ_[p.val]) / 2, ?_, ?_⟩
  · have : (z : ℚ_[p.val]) ≠ 0 := fun h => hz0 (Subtype.ext h)
    exact div_ne_zero this two_ne_zero
  · rw [placeEmb_alphaB_eq, hs]
    have hz' := congrArg (fun y : ℤ_[p.val] => (y : ℚ_[p.val])) hz
    simp only [hu, PadicInt.coe_add, PadicInt.coe_mul, PadicInt.coe_intCast, PadicInt.coe_pow]
      at hz'
    push_cast at hz' ⊢
    rw [show ((nA k : ℚ_[p.val]) + (nB k : ℚ_[p.val]) * ((ε : ℚ_[p.val]) * (t : ℚ_[p.val]))) =
      (nA k : ℚ_[p.val]) + (nB k : ℚ_[p.val]) * (ε : ℚ_[p.val]) * (t : ℚ_[p.val]) by ring, hz']
    ring

end Generic

/-! ### Census data -/

/-- Census data at `p`: a root `a` of `X² − X − 60` mod `p`, and for both signs of the
chosen `√241 ≡ ±(2a − 1)` the reduced square classes `c'` (the class of `α_k` is `2c'`)
and the Frobenius vectors. -/
structure CensusData where
  p : ℕ
  a : ℤ
  cp : Fin 8 → ℤ
  cm : Fin 8 → ℤ
  svp : Fin 8 → ZMod 2
  svm : Fin 8 → ZMod 2

namespace CensusData

variable (D : CensusData)

/-- The finite conditions, checked by `decide +kernel`. -/
abbrev Valid : Prop :=
  D.p.Prime ∧ D.p ∉ ({2, 3, 5, 241} : Finset ℕ) ∧ ¬ (D.p : ℤ) ∣ 2 * D.a - 1 ∧
    (D.p : ℤ) ∣ D.a ^ 2 - D.a - 60 ∧
    (∀ k, ((nA k + nB k * 1 * (2 * D.a - 1) : ℤ) : ZMod D.p) = (D.cp k : ZMod D.p) ∧
      (2 * D.cp k : ZMod D.p) ≠ 0 ∧ ¬ (D.p : ℤ) ∣ 2 * D.cp k ∧
      ((2 * D.cp k : ℤ) : ZMod D.p) ^ ((D.p - 1) / 2) =
        Multiquadratic.binarySignInteger (D.svp k)) ∧
    (∀ k, ((nA k + nB k * (-1) * (2 * D.a - 1) : ℤ) : ZMod D.p) = (D.cm k : ZMod D.p) ∧
      (2 * D.cm k : ZMod D.p) ≠ 0 ∧ ¬ (D.p : ℤ) ∣ 2 * D.cm k ∧
      ((2 * D.cm k : ℤ) : ZMod D.p) ^ ((D.p - 1) / 2) =
        Multiquadratic.binarySignInteger (D.svm k)) ∧
    D.svp ≠ 0 ∧ D.svm ≠ 0 ∧ Retained.squareForm D.svp ≠ 0 ∧ Retained.squareForm D.svm ≠ 0 ∧
    ¬ (D.p : ℤ) ∣ 964 ∧ (∀ i, ¬ (D.p : ℤ) ∣ 4 * Genus.normValue i)

end CensusData

/-! ### The Frobenius label from census data -/

theorem census_frobenius_label (D : CensusData) (hD : D.Valid) :
    ∃ (hp : D.p.Prime), haveI : Fact D.p.Prime := ⟨hp⟩
      ∃ (_ : IsSquare (241 : ℚ_[D.p])),
        HasLabel (absFrob ⟨D.p, hp⟩).val D.svp ∨ HasLabel (absFrob ⟨D.p, hp⟩).val D.svm := by
  obtain ⟨hp, hnot, hunit, hroot, hcp, hcm, hsvp, hsvm, -, -, h964, hN⟩ := hD
  have : Fact D.p.Prime := ⟨hp⟩
  let P : Nat.Primes := ⟨D.p, hp⟩
  obtain ⟨r, hr, hra⟩ := Base.exists_omegaRoot (p := D.p) D.a hunit hroot
  set t : ℤ_[D.p] := 2 * r - 1 with htdef
  have ht : t * t = 241 := by
    rw [htdef]
    linear_combination (4 : ℤ_[D.p]) * hr
  have hT : PadicInt.toZMod t = ((2 * D.a - 1 : ℤ) : ZMod D.p) := by
    rw [htdef, map_sub, map_mul, map_ofNat, map_one, hra]
    push_cast
    ring
  have ht' : (t : ℚ_[D.p]) ^ 2 = 241 := by
    have h := congrArg (fun y : ℤ_[D.p] => (y : ℚ_[D.p])) ht
    simp only [PadicInt.coe_mul] at h
    rw [sq, h]
    norm_cast
  have hsq : IsSquare (241 : ℚ_[D.p]) := ⟨(t : ℚ_[D.p]), by rw [← sq, ht']⟩
  have he : (rationalPrimeIdeal D.p).ramificationIdxIn (𝓞 CanonicalGenus.Carrier) = 1 :=
    Genus.ramificationIdxIn_eq_one D.p h964 hN
  have hp2 : P.val ≠ 2 := by
    intro h
    apply hnot
    rw [show D.p = 2 from h]
    decide
  refine ⟨hp, hsq, ?_⟩
  rcases placeRoot_eq_or P hsq (t : ℚ_[D.p]) ht' with hs | hs
  · left
    have hc : ∀ k, ∃ z : ℚ_[P.val], z ≠ 0 ∧
        placeEmb P hsq (Base.alphaB k) = ((2 * D.cp k : ℤ) : ℚ_[P.val]) * z ^ 2 :=
      fun k => squareclass_of_residue P hsq t 1 (by rw [hs]; simp) (2 * D.a - 1) hT k (D.cp k)
        (by simpa using (hcp k).1) (hcp k).2.1
    obtain ⟨d, hd⟩ := exists_absolute_frobenius_split P hsq hp2 (fun k => 2 * D.cp k) hc
      (fun k => (hcp k).2.2.1) D.svp (fun k => (hcp k).2.2.2) CanonicalGenus.Carrier
      CanonicalGenus.field.val (fun k => ⟨Genus.gE k, rfl⟩)
    exact frobenius_label_of_split P hsq he hsvp d hd
  · right
    have hc : ∀ k, ∃ z : ℚ_[P.val], z ≠ 0 ∧
        placeEmb P hsq (Base.alphaB k) = ((2 * D.cm k : ℤ) : ℚ_[P.val]) * z ^ 2 :=
      fun k => squareclass_of_residue P hsq t (-1) (by rw [hs]; simp) (2 * D.a - 1) hT k (D.cm k)
        (by simpa using (hcm k).1) (hcm k).2.1
    obtain ⟨d, hd⟩ := exists_absolute_frobenius_split P hsq hp2 (fun k => 2 * D.cm k) hc
      (fun k => (hcm k).2.2.1) D.svm (fun k => (hcm k).2.2.2) CanonicalGenus.Carrier
      CanonicalGenus.field.val (fun k => ⟨Genus.gE k, rfl⟩)
    exact frobenius_label_of_split P hsq he hsvm d hd

/-! ### Fourth powers lie in the core -/

theorem Input.pow_four_mem_retainedKer (I : Input) {g : Ghat} (hg : g ∈ GB) :
    g ^ 4 ∈ I.retainedKer := by
  refine (I.mem_retainedKer_iff _).mpr ⟨GB.pow_mem hg 4, ?_⟩
  have he : (⟨g ^ 4, GB.pow_mem hg 4⟩ : GB) = (⟨g, hg⟩ : GB) ^ 4 := rfl
  rw [he, map_pow]
  exact LocalModels.pow_four_eq_one Retained.cocycle _

theorem Input.pow_four_mem_core (I : Input) {g : Ghat} (hg : g ∈ GB) : g ^ 4 ∈ I.core := by
  rw [Input.mem_core_iff]
  refine ⟨I.pow_four_mem_retainedKer hg, ?_⟩
  have hg' : sigmaHat⁻¹ * g * sigmaHat ∈ GB := by
    simpa using GB_normal.conj_mem g hg sigmaHat⁻¹
  have he : sigmaHat⁻¹ * g ^ 4 * sigmaHat = (sigmaHat⁻¹ * g * sigmaHat) ^ 4 := by
    have h := map_pow (MulAut.conj sigmaHat⁻¹) g 4
    simp only [MulAut.conj_apply, inv_inv] at h
    exact h
  rw [he]
  exact I.pow_four_mem_retainedKer hg'

/-! ### Residue degree `4` in `M` -/

/-- **Census**: at a prime with valid census data, `e = 1` and `f = 4` in `M`. -/
theorem census_M (D : CensusData) (hD : D.Valid) :
    (rationalPrimeIdeal D.p).ramificationIdxIn (𝓞 input.M) = 1 ∧
      (rationalPrimeIdeal D.p).inertiaDegIn (𝓞 input.M) = 4 := by
  obtain ⟨hp, hsq, hlab⟩ := census_frobenius_label D hD
  have hnot := hD.2.1
  have hS : Retained.squareForm D.svp ≠ 0 ∧ Retained.squareForm D.svm ≠ 0 :=
    ⟨hD.2.2.2.2.2.2.2.2.1, hD.2.2.2.2.2.2.2.2.2.1⟩
  let P : Nat.Primes := ⟨D.p, hp⟩
  set F : Ghat := decompositionMap P (absFrob P) with hFdef
  have hFB : F ∈ GB := decompositionMap_mem_GB P hsq _
  -- the label and the retained square
  have hsqne : input.retainedMap (⟨F, hFB⟩ ^ 2) ≠ 1 := by
    obtain ⟨sv, hsv, hSv⟩ : ∃ sv : Fin 8 → ZMod 2, HasLabel (absFrob P).val sv ∧
        Retained.squareForm sv ≠ 0 := by
      rcases hlab with h | h
      · exact ⟨D.svp, h, hS.1⟩
      · exact ⟨D.svm, h, hS.2⟩
    have hl : genusLabel (⟨F, hFB⟩ : GB) = Multiplicative.ofAdd sv :=
      genusLabel_of_hasLabelHat _ _ ⟨(absFrob P).val, rfl, hsv⟩
    rw [map_pow, Retained.sq_coordinates, input.retainedMap_base, hl]
    intro h
    exact hSv (congrArg ClassTwo.GroupModel.central h)
  have hK : input.M.fixingSubgroup ≤ input.core := by rw [input.M_fixingSubgroup]
  have h2 : Input.res input.M F ^ 2 ≠ 1 := by
    have := input.resB_ne_one_of_retainedMap hK hsqne
    rw [map_pow, resB_apply] at this
    exact this
  have h4 : Input.res input.M F ^ 4 = 1 := by
    rw [← map_pow]
    apply (res_eq_one_iff input.M _).mpr
    rw [input.M_fixingSubgroup]
    exact input.pow_four_mem_core hFB
  have hord : orderOf (Input.res input.M F) = 4 := by
    have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
    exact orderOf_eq_prime_pow (p := 2) (n := 1) (by simpa using h2) (by simpa using h4)
  have hpn : P.val ∉ ({2, 3, 5, 241} : Finset ℕ) := hnot
  have hdec : Nat.card (decompositionRestriction P input.M (jK input.M)).range = 1 * 4 := by
    have hr := decomposition_range_unramified P hpn (Input.res input.M)
    rw [decompositionRestriction_eq_comp]
    change Nat.card ((Input.res input.M).comp (decompositionMap P)).toMonoidHom.range = 1 * 4
    rw [hr, Nat.card_zpowers, one_mul, ← hord]
  have hin : Nat.card (inertiaRestriction P input.M (jK input.M)).range = 1 := by
    have hb : (inertiaRestriction P input.M (jK input.M)).range = ⊥ := by
      apply le_antisymm _ bot_le
      rintro _ ⟨σ, rfl⟩
      rw [Subgroup.mem_bot, inertiaRestriction_eq, inertia_killed P hpn σ, map_one]
    rw [hb, Subgroup.card_bot]
  exact ramification_residue_of_absolute_image_cards P input.M (jK input.M) 1 4 one_pos hin hdec

/-! ### The nine census primes -/

-- BEGIN Generated by scripts/sqrt241/generate_census_tables.py — do not edit by hand.
/-- The census data (generated by `scripts/sqrt241/generate_census_tables.py`). -/
def censusData : Fin 9 → CensusData := ![
  ⟨41, 18, ![39, 37, 29, 13, 4, 38, 2, 31], ![39, 1, 28, 12, 38, 4, 31, 2], ![0, 0, 1, 1, 0, 1, 0, 0], ![0, 0, 1, 1, 1, 0, 0, 0]⟩,
  ⟨47, 19, ![45, 33, 38, 20, 8, 22, 38, 44], ![45, 7, 27, 9, 22, 8, 44, 38], ![1, 1, 1, 1, 0, 1, 1, 1], ![1, 0, 0, 0, 1, 0, 1, 1]⟩,
  ⟨53, 17, ![51, 41, 10, 22, 36, 35, 8, 24], ![51, 18, 31, 43, 35, 36, 24, 8], ![0, 0, 1, 0, 1, 0, 0, 1], ![0, 0, 0, 1, 0, 1, 1, 0]⟩,
  ⟨59, 26, ![57, 21, 52, 41, 35, 30, 44, 21], ![57, 56, 18, 7, 30, 35, 21, 44], ![1, 1, 0, 1, 1, 0, 0, 1], ![1, 0, 0, 1, 0, 1, 1, 0]⟩,
  ⟨61, 14, ![59, 12, 2, 4, 15, 48, 6, 17], ![59, 20, 57, 59, 48, 15, 17, 6], ![0, 1, 0, 1, 1, 1, 0, 0], ![0, 1, 1, 0, 1, 1, 0, 0]⟩,
  ⟨67, 22, ![65, 61, 48, 56, 24, 33, 52, 46], ![65, 23, 11, 19, 33, 24, 46, 52], ![1, 0, 0, 1, 1, 1, 0, 0], ![1, 1, 0, 1, 1, 1, 0, 0]⟩,
  ⟨79, 39, ![77, 9, 57, 14, 70, 54, 25, 15], ![77, 61, 65, 22, 54, 70, 15, 25], ![1, 0, 1, 1, 1, 1, 0, 1], ![1, 1, 0, 0, 1, 1, 1, 0]⟩,
  ⟨83, 33, ![81, 60, 60, 61, 51, 73, 80, 62], ![81, 11, 22, 23, 73, 51, 62, 80], ![1, 0, 0, 1, 1, 0, 0, 0], ![1, 1, 0, 1, 0, 1, 0, 0]⟩,
  ⟨97, 43, ![95, 25, 70, 50, 13, 14, 89, 51], ![95, 27, 47, 27, 14, 13, 51, 89], ![0, 0, 0, 0, 1, 1, 0, 1], ![0, 0, 0, 0, 1, 1, 1, 0]⟩]
-- END Generated by scripts/sqrt241/generate_census_tables.py.

set_option maxRecDepth 100000 in
set_option maxHeartbeats 16000000 in
theorem censusData_valid (i : Fin 9) : (censusData i).Valid := by
  fin_cases i <;> decide +kernel

theorem censusData_p : ∀ i : Fin 9, (censusData i).p = ![41, 47, 53, 59, 61, 67, 79, 83, 97] i := by
  decide

/-- **The census in `M`**: residue degree `≥ 4` at `41, 47, 53, 59, 61, 67, 79, 83, 97`. -/
theorem M_census : ∀ p ∈ ({41, 47, 53, 59, 61, 67, 79, 83, 97} : Finset ℕ),
    4 ≤ (rationalPrimeIdeal p).inertiaDegIn (𝓞 input.M) := by
  intro p hp
  have key : ∀ i : Fin 9, 4 ≤ (rationalPrimeIdeal (censusData i).p).inertiaDegIn (𝓞 input.M) :=
    fun i => (census_M (censusData i) (censusData_valid i)).2.ge
  simp only [Finset.mem_insert, Finset.mem_singleton] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact key 0
  · exact key 1
  · exact key 2
  · exact key 3
  · exact key 4
  · exact key 5
  · exact key 6
  · exact key 7
  · exact key 8

end UnitDistance.Sqrt241.Retained
