#!/usr/bin/env python3
"""Finite facts about the dyadic group D and its group algebra F_2[D].

Section 2 (Lemmas tw:local-two and tw:local-fox) uses the group

    D = < x, y, z | x^2, y^2, z^4, [y,z]^2, [x,y], [x,z], [[y,z],z] >,

with [g,h] = g^-1 h^-1 g h.  Its elements are the normal forms
x^a1 y^a2 z^a3 w^a4 (a1, a2, a4 in {0,1}, a3 in Z/4, w = [y,z]) with

    (a1,a2,a3,a4)(b1,b2,b3,b4) = (a1+b1, a2+b2, a3+b3, a4+b4+a3*b2).

The program checks, by exhaustive computation:
  1. this law defines a group of order 32 generated by x, y, z, in which the
     seven relations hold and w = [y,z] (that the presented group has at most
     32 elements, since every element is one of these normal forms, is shown
     in the proof of Lemma tw:local-two);
  2. the Frattini subgroup <z^2, w> is central of exponent 2;
  3. the powers I^m of the augmentation ideal of F_2[D] have dimensions
     32, 31, 28, 23, 16, 9, 4, 1, 0 (m = 0..8), and I^7 = F_2 * Omega, where
     Omega is the sum of all group elements;
  4. for m < 7 the map I^m/I^(m+1) -> (I^(m+1)/I^(m+2))^3,
     b -> (b X1, b X2, b X3) with X1, X2, X3 = x-1, y-1, z-1, is injective,
     and so is b -> (b(X2+X3), b(X2+X1), b X1); for m = 7 both maps are zero;
  5. for the word r = y^2 [x,y] [x,z], which maps to 1 in D and has quadratic
     class y^[2] + [x,y] + [x,z], the Fox row d'r in F_2[D]^3 satisfies the
     fundamental formula, is congruent to (X2+X3, X2+X1, X1) modulo I^2, and
     the module F_2[D] d'r, filtered by F^n = (I^(n-1))^3, has Hilbert series
     t^2 (P_D(t) - t^7) with P_D(t) = (1+t)^3 (1+t^2)^2.
Every check is asserted; the program prints one line per check.
"""

import itertools

# ---------------------------------------------------------------- the group D
ELEMS = [(a1, a2, a3, a4) for a1 in range(2) for a2 in range(2)
         for a3 in range(4) for a4 in range(2)]
INDEX = {g: i for i, g in enumerate(ELEMS)}
E = (0, 0, 0, 0)
X, Y, Z, W = (1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)


def mul(g, h):
    return ((g[0] + h[0]) % 2, (g[1] + h[1]) % 2, (g[2] + h[2]) % 4,
            (g[3] + h[3] + g[2] * h[1]) % 2)


def inv(g):
    for h in ELEMS:
        if mul(g, h) == E:
            return h
    raise AssertionError("no inverse")


def power(g, k):
    out = E
    for _ in range(k):
        out = mul(out, g)
    return out


def comm(g, h):
    return mul(mul(inv(g), inv(h)), mul(g, h))


def generated(gens):
    group = {E}
    while True:
        bigger = group | {mul(a, b) for a in group for b in gens}
        if bigger == group:
            return group
        group = bigger


def check(label, condition):
    assert condition, label
    print("PASS", label)


def check_group():
    check("associativity of the normal-form law",
          all(mul(mul(a, b), c) == mul(a, mul(b, c))
              for a in ELEMS for b in ELEMS for c in ELEMS))
    check("identity and inverses", all(mul(E, g) == g == mul(g, E) and mul(g, inv(g)) == E
                                      for g in ELEMS))
    relations = [power(X, 2), power(Y, 2), power(Z, 4), power(comm(Y, Z), 2),
                 comm(X, Y), comm(X, Z), comm(comm(Y, Z), Z)]
    check("the seven relations of D hold", all(r == E for r in relations))
    check("[y,z] = w", comm(Y, Z) == W)
    check("x, y, z generate a group of order 32", len(generated([X, Y, Z])) == 32)
    frattini = generated([power(Z, 2), W])
    check("Frattini subgroup <z^2, w> has order 4, is central and has exponent 2",
          len(frattini) == 4
          and all(mul(f, g) == mul(g, f) for f in frattini for g in ELEMS)
          and all(power(f, 2) == E for f in frattini))
    check("every square lies in <z^2, w>, so D has exponent 4",
          all(power(g, 2) in frattini for g in ELEMS))


# ---------------------------------------------------- the group algebra F_2[D]
# An element of F_2[D] is a 32-bit integer; bit i is the coefficient of ELEMS[i].
OMEGA = (1 << 32) - 1


def right_mult(v, g):
    """v * g for v in F_2[D] and g in D."""
    out = 0
    for i in range(32):
        if v >> i & 1:
            out ^= 1 << INDEX[mul(ELEMS[i], g)]
    return out


def right_mult_alg(v, u):
    """v * u for v, u in F_2[D]."""
    out = 0
    for j in range(32):
        if u >> j & 1:
            out ^= right_mult(v, ELEMS[j])
    return out


def left_mult_alg(u, v):
    return right_mult_alg(u, v)


def reduce(v, basis):
    for p in sorted(basis, reverse=True):
        if v >> p & 1:
            v ^= basis[p]
    return v


def span(vectors):
    basis = {}
    for v in vectors:
        v = reduce(v, basis)
        if v:
            basis[v.bit_length() - 1] = v
    return basis


ONE = 1 << INDEX[E]
XS = [ONE ^ (1 << INDEX[g]) for g in (X, Y, Z)]            # x-1, y-1, z-1


def powers_of_augmentation():
    ideals = [span(1 << i for i in range(32))]
    for _ in range(9):
        ideals.append(span(right_mult_alg(v, t) for v in ideals[-1].values() for t in XS))
    return ideals


def graded_kernel_dimensions(ideals, triple):
    """dim of the kernel of I^m/I^(m+1) -> (I^(m+1)/I^(m+2))^3, b -> (b t_1, b t_2, b t_3)."""
    dims = []
    for m in range(8):
        complement = span(reduce(v, ideals[m + 1]) for v in ideals[m].values())
        target = ideals[m + 2]
        images = []
        for v in complement.values():
            image = 0
            for k, t in enumerate(triple):
                image |= reduce(right_mult_alg(v, t), target) << (32 * k)
            images.append(image)
        dims.append(len(complement) - len(span(images)))
    return dims


def check_algebra():
    ideals = powers_of_augmentation()
    dims = [len(ideals[m]) for m in range(9)]
    check("dim I^m = 32,31,28,23,16,9,4,1,0 for m = 0..8",
          dims == [32, 31, 28, 23, 16, 9, 4, 1, 0])
    check("I^7 is spanned by Omega = sum of all group elements",
          list(ideals[7].values()) == [OMEGA])
    x1, x2, x3 = XS
    check("b -> (b X1, b X2, b X3) is injective on I^m/I^(m+1) for m < 7, zero for m = 7",
          graded_kernel_dimensions(ideals, (x1, x2, x3)) == [0, 0, 0, 0, 0, 0, 0, 1])
    check("b -> (b(X2+X3), b(X2+X1), b X1) is injective on I^m/I^(m+1) for m < 7, zero for m = 7",
          graded_kernel_dimensions(ideals, (x2 ^ x3, x2 ^ x1, x1)) == [0, 0, 0, 0, 0, 0, 0, 1])
    return ideals


# ------------------------------------------------------------ one Fox row
def fox_row(word):
    """Fox row of a word in x, y, z (letters 0,1,2; negative = inverse) in F_2[D]^3."""
    gens = (X, Y, Z)
    row = [0, 0, 0]
    prefix = E
    for letter in word:
        k = abs(letter) - 1
        if letter > 0:
            # d(u g) = d(u) + u e_g
            row[k] ^= 1 << INDEX[prefix]
            prefix = mul(prefix, gens[k])
        else:
            # d(u g^-1) = d(u) - u g^-1 e_g
            prefix = mul(prefix, inv(gens[k]))
            row[k] ^= 1 << INDEX[prefix]
    return row, prefix


def filtered_hilbert_series(row, ideals):
    """Coefficients of the Hilbert series of F_2[D] row, filtered by F^n = (I^(n-1))^3."""
    module = span(sum(left_mult_alg(1 << INDEX[g], row[k]) << (32 * k) for k in range(3))
                  for g in ELEMS)
    def level(n):                      # F^n of the ambient module, as a span
        if n <= 1:
            return span(1 << i for i in range(96))
        return span(v << (32 * k) for k in range(3) for v in ideals[n - 1].values())
    dims = []
    for n in range(11):
        ambient = level(n)
        both = span(list(ambient.values()) + list(module.values()))
        dims.append(len(ambient) + len(module) - len(both))   # dim(module meet F^n)
    return [dims[n] - dims[n + 1] for n in range(10)]


def check_fox_row(ideals):
    # r = y^2 [x,y] [x,z] with [g,h] = g^-1 h^-1 g h; letters 1,2,3 = x,y,z
    word = [2, 2, -1, -2, 1, 2, -1, -3, 1, 3]
    row, value = fox_row(word)
    check("the word r = y^2 [x,y] [x,z] maps to 1 in D", value == E)
    x1, x2, x3 = XS
    fundamental = right_mult_alg(row[0], x1) ^ right_mult_alg(row[1], x2) ^ right_mult_alg(row[2], x3)
    check("its Fox row satisfies d1 r (x-1) + d2 r (y-1) + d3 r (z-1) = r - 1 = 0",
          fundamental == 0)
    expected = (x2 ^ x3, x2 ^ x1, x1)
    check("its Fox row is congruent to (X2+X3, X2+X1, X1) modulo I^2",
          all(reduce(row[k] ^ expected[k], ideals[2]) == 0 for k in range(3)))
    series = filtered_hilbert_series(row, ideals)
    # t^2 (P_D - t^7): coefficients of P_D are 1,3,5,7,7,5,3,1
    check("F_2[D] d'r has Hilbert series t^2 (P_D(t) - t^7)",
          series == [0, 0, 1, 3, 5, 7, 7, 5, 3, 0])


if __name__ == "__main__":
    check_group()
    ideals = check_algebra()
    check_fox_row(ideals)
    print("dyadic241: all checks passed")
