-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.GaussianWindows
public import UnitDistance.Sqrt241.Geometry.GaussianProfiles
public import UnitDistance.ProfileOverlap
public import UnitDistance.Sqrt241.Target
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.GaussianWindows` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! # Compact windows of the actual angular Gaussian profile -/

namespace UnitDistance.Sqrt241


namespace Witness

/-- The actual compact-coordinate logarithmic profile energy is quadratic. -/
theorem compactProfile_energy (z : ℂ) :
    -Real.log (compactProfile z) = (2*increment)*‖z‖^2 := by
  rw [compactProfile_gaussian, complexGaussian, Real.log_exp]
  ring

theorem compactProfile_energy_nonneg (z : ℂ) : 0 ≤ -Real.log (compactProfile z) := by
  rw [compactProfile_energy]
  exact mul_nonneg (mul_nonneg (by norm_num) increment_pos.le) (sq_nonneg _)

theorem isCompact_compactProfile_energyWindow (T : ℝ) :
    IsCompact (energyWindow (fun z : ℂ => -Real.log (compactProfile z)) T) := by
  have he : (fun z : ℂ => -Real.log (compactProfile z)) =
      (fun z : ℂ => (2*increment)*‖z‖^2) := funext compactProfile_energy
  rw [he]
  exact isCompact_quadratic_energyWindow (mul_pos (by norm_num) increment_pos) T

end Witness
end UnitDistance.Sqrt241
