-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.HeckeSignedArithmetic
public import UnitDistance.HeckeSignedWeights
public import UnitDistance.HeckeNormCharacter
public import UnitDistance.Sqrt241.Geometry.QuadraticRootNormCongruence

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.HeckeSignedArithmetic` with the radicand `7` replaced by an
admissible `d` (`QuadraticRoot.Admissible`, used with `d = 3`): only its
radicand-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! An actual square root of `d` discharges the signed unit covariance hypothesis
and identifies the finite character with the signed archimedean norm. -/
noncomputable section
open NumberField NumberField.InfinitePlace DedekindResidue MeasureTheory
open NumberField.mixedEmbedding NumberField.Units NumberField.Units.dirichletUnitTheorem
open scoped BigOperators Real Classical
namespace UnitDistance.Sqrt241.NumberFieldAnalysis
variable {d : ℕ} [Fact (UnitDistance.Sqrt241.QuadraticRoot.Admissible d)]
variable (K : Type*) [Field K] [NumberField K]

theorem unit_rational_norm_eq_one_of_root (r : K) (hr : r^2=(d : K))
    (epsilon : (𝓞 K)ˣ) :
    Algebra.norm ℚ (algebraMap (𝓞 K) K (epsilon : 𝓞 K)) = 1 := by
  have h := Sqrt241.QuadraticRoot.integer_norm_eq_one_of_isUnit_of_root
    r hr (epsilon : 𝓞 K) epsilon.isUnit
  rw [← Algebra.coe_norm_int, h]
  norm_num

theorem heckeSignedTerm_unit_mul_of_root (r : K) (hr : r^2=(d : K))
    (t : ℝ) (u : logSpace K) (epsilon : (𝓞 K)ˣ) (y : K) :
    NumberFieldAnalysis.heckeSignedTerm K t u (embeddingCoords K (algebraMap (𝓞 K) K (epsilon : 𝓞 K)*y)) =
      NumberFieldAnalysis.heckeSignedTerm K t (u+logEmbedding K (Additive.ofMul epsilon)) (embeddingCoords K y) :=
  NumberFieldAnalysis.heckeSignedTerm_unit_mul_of_norm_one K t u epsilon
    (unit_rational_norm_eq_one_of_root K r hr epsilon) y

theorem idealChiFour_principal_eq_signedArchCharacter (r : K) (hr : r^2=(d : K))
    (x : 𝓞 K) (hx : x ≠ 0) (hodd : Odd (Algebra.norm ℤ x)) :
    NumberFieldAnalysis.idealChiFour K (Ideal.span {x}) = NumberFieldAnalysis.signedArchCharacter K (x : K) := by
  rw [NumberFieldAnalysis.idealChiFour, NumberFieldAnalysis.chiFourReal, Ideal.absNorm_span_singleton,
    Sqrt241.QuadraticRoot.integer_norm_chi4_eq_sign_of_root r hr x hodd,
    NumberFieldAnalysis.signedArchCharacter_eq_sign_norm K (by exact_mod_cast hx), ← Algebra.coe_norm_int,
    sign_intCast]
  simp only [Int.sign_eq_sign, SignType.intCast_cast]

end UnitDistance.Sqrt241.NumberFieldAnalysis
