-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.HeckeSignedThetaIdentities
public import UnitDistance.Sqrt241.Geometry.HeckeSignedBochner
public import UnitDistance.HeckeDyadicInclusionExclusion
public import UnitDistance.HeckeFiniteMellin
public import UnitDistance.Sqrt241.Geometry.HeckeSignedOddSupport

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.HeckeSignedThetaIdentities` with the radicand `7` replaced by an
admissible `d` (`QuadraticRoot.Admissible`, used with `d = 3`): only its
radicand-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! Actual unit periodicity, independence of the fundamental box, and the
integrated finite dyadic inclusion–exclusion identity. -/
noncomputable section
open NumberField NumberField.InfinitePlace DedekindResidue MeasureTheory
open NumberField.mixedEmbedding NumberField.Units NumberField.Units.dirichletUnitTheorem
open scoped Real Classical nonZeroDivisors ENNReal NNReal Topology
set_option backward.isDefEq.respectTransparency false
namespace UnitDistance.Sqrt241.NumberFieldAnalysis
variable {d : ℕ} [Fact (UnitDistance.Sqrt241.QuadraticRoot.Admissible d)]
open UnitDistance.OddNormDyadic
variable (K : Type*) [Field K] [NumberField K]


/-- Actual unit multiplication permutes the filtered signed lattice sum. -/
theorem heckeOddSignedTheta_periodic_unit (r : K) (hr : r^2=(d : K))
    (J : (Ideal (𝓞 K))⁰) (t : ℝ) (u : logSpace K) (epsilon : (𝓞 K)ˣ) :
    NumberFieldAnalysis.heckeOddSignedTheta K J t (u+logEmbedding K (Additive.ofMul epsilon)) =
      NumberFieldAnalysis.heckeOddSignedTheta K J t u := by
  unfold NumberFieldAnalysis.heckeOddSignedTheta
  conv_rhs => rw [← Equiv.tsum_eq (unitMulLatticeEquiv K (FractionalIdeal.mk0 K J) epsilon)]
  apply tsum_congr
  intro v
  obtain ⟨a, ha, hva⟩ := (mem_idealZLattice K (FractionalIdeal.mk0 K J) _).mp v.property
  have hcoe : ((unitMulLatticeEquiv K (FractionalIdeal.mk0 K J) epsilon v :
      idealZLattice K (FractionalIdeal.mk0 K J)) : EuclideanSpace ℝ (index K)) =
      embeddingCoords K (algebraMap (𝓞 K) K (epsilon : 𝓞 K)*a) := by
    change mulCoords K _ (v : EuclideanSpace ℝ (index K)) = _
    rw [← hva, mulCoords_embeddingCoords]
  rw [hcoe, ← hva, heckeOddSignedTerm_unit_mul K r hr]

theorem heckeOddSignedTheta_periodic (r : K) (hr : r^2=(d : K))
    (J : (Ideal (𝓞 K))⁰) (t : ℝ) :
    ∀ l ∈ unitLattice K, ∀ u, NumberFieldAnalysis.heckeOddSignedTheta K J t (l+u) = NumberFieldAnalysis.heckeOddSignedTheta K J t u := by
  intro l hl u
  obtain ⟨b, hb, heq⟩ := Submodule.mem_map.mp hl
  rw [add_comm, ← heq]
  exact heckeOddSignedTheta_periodic_unit K r hr J t u (Additive.toMul b)


/-- The actual signed averaged theta is a finite combination of the actual parity
averages whose entire Mellin transforms have already been constructed. -/
theorem heckeOddSignedG_eq_finiteParityUnitAverage
    (r : K) (hr : r^2=(d : K)) (J : (Ideal (𝓞 K))⁰)
    (hJ : Odd (Ideal.absNorm (J : Ideal (𝓞 K)))) {t : ℝ} (ht : 0 < t) :
    (NumberFieldAnalysis.heckeOddSignedG K J t : ℂ) = NumberFieldAnalysis.finiteHeckeParityUnitAverage K (NumberFieldAnalysis.heckeRealParity K)
      (Finset.univ : Finset (DyadicPrime K)).powerset
      (fun S => idealZLattice K (FractionalIdeal.mk0 K (dyadicSubideal K J S)))
      (fun S => ((torsionOrder K : ℝ)⁻¹ : ℂ)*(-1:ℂ)^S.card) (fun _ => 1) t := by
  have hbox := NumberFieldAnalysis.setIntegral_unitBox_swap_complex K (fun u => (NumberFieldAnalysis.heckeOddSignedTheta K J t u : ℂ))
    (fun l hl u => congrArg Complex.ofReal (heckeOddSignedTheta_periodic K r hr J t l hl u))
  have hpoint (u : logSpace K) : (NumberFieldAnalysis.heckeOddSignedTheta K J t u : ℂ) =
      ∑ S ∈ (Finset.univ : Finset (DyadicPrime K)).powerset,
        (-1:ℂ)^S.card * NumberFieldAnalysis.heckeParityTheta (NumberFieldAnalysis.heckeRealParity K)
          (idealZLattice K (FractionalIdeal.mk0 K (dyadicSubideal K J S)))
          (placeWeights K (heckeWeights K t u)) := by
    rw [NumberFieldAnalysis.heckeOddSignedTheta, Complex.ofReal_tsum]
    exact NumberFieldAnalysis.heckeOddSignedTerm_tsum_inclusionExclusion K J hJ ht u
  unfold NumberFieldAnalysis.heckeOddSignedG
  rw [Complex.ofReal_mul, ← integral_complex_ofReal, ← hbox]
  simp_rw [hpoint]
  rw [integral_finsetSum _ (fun S _ =>
    (NumberFieldAnalysis.integrableOn_heckeParityTheta_heckeWeights K (NumberFieldAnalysis.heckeRealParity K)
      (idealZLattice K (FractionalIdeal.mk0 K (dyadicSubideal K J S))) ht).const_mul ((-1:ℂ)^S.card))]
  simp_rw [integral_const_mul]
  simp only [NumberFieldAnalysis.finiteHeckeParityUnitAverage, NumberFieldAnalysis.heckeParityUnitAverage, one_mul, Finset.mul_sum, mul_assoc, Complex.ofReal_inv]

end UnitDistance.Sqrt241.NumberFieldAnalysis
