-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.HeckeSignedOddSupport
public import UnitDistance.Sqrt241.Geometry.HeckeSignedArithmetic
public import UnitDistance.HeckeSignedScaling
public import UnitDistance.Sqrt241.Geometry.QuadraticRootNormCongruence

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.HeckeSignedOddSupport` with the radicand `7` replaced by an
admissible `d` (`QuadraticRoot.Admissible`, used with `d = 3`): only its
radicand-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! The literal odd integral-norm support and its actual unit covariance.
This support is the finite-place restriction used by the signed theta series. -/
noncomputable section
open NumberField NumberField.InfinitePlace DedekindResidue MeasureTheory
open NumberField.mixedEmbedding NumberField.mixedEmbedding.fundamentalCone
open NumberField.Units NumberField.Units.dirichletUnitTheorem
open scoped BigOperators Real Classical nonZeroDivisors NNReal ENNReal
set_option backward.isDefEq.respectTransparency false
namespace UnitDistance.Sqrt241.NumberFieldAnalysis
variable {d : ℕ} [Fact (UnitDistance.Sqrt241.QuadraticRoot.Admissible d)]
variable (K : Type*) [Field K] [NumberField K]


theorem oddNormPoint_unit_mul (r : K) (hr : r^2=(d : K))
    (epsilon : (𝓞 K)ˣ) (y : K) :
    NumberFieldAnalysis.oddNormPoint K (embeddingCoords K (algebraMap (𝓞 K) K (epsilon : 𝓞 K)*y)) ↔
      NumberFieldAnalysis.oddNormPoint K (embeddingCoords K y) := by
  have hnorm (eps : (𝓞 K)ˣ) : Algebra.norm ℤ (eps : 𝓞 K) = 1 :=
    Sqrt241.QuadraticRoot.integer_norm_eq_one_of_isUnit_of_root r hr _ eps.isUnit
  constructor
  · rintro ⟨a,ha,hodd⟩
    refine ⟨(↑epsilon⁻¹ : 𝓞 K)*a, ?_, ?_⟩
    · have he := NumberFieldAnalysis.embeddingCoords_injective K ha
      congr 1
      push_cast
      change algebraMap (𝓞 K) K (↑epsilon⁻¹ : 𝓞 K) * algebraMap (𝓞 K) K a = y
      change algebraMap (𝓞 K) K a = _ at he
      rw [he, ← mul_assoc, ← map_mul]
      simp
    · simpa only [map_mul, hnorm, one_mul] using hodd
  · rintro ⟨a,ha,hodd⟩
    refine ⟨(epsilon : 𝓞 K)*a, ?_, ?_⟩
    · have he := NumberFieldAnalysis.embeddingCoords_injective K ha
      congr 1
      push_cast
      change algebraMap (𝓞 K) K (epsilon : 𝓞 K) * algebraMap (𝓞 K) K a = _
      change algebraMap (𝓞 K) K a = y at he
      rw [he]
    · simpa only [map_mul, hnorm, one_mul] using hodd

theorem signedArchCharacter_conePreimage_eq_chiFour (r : K) (hr : r^2=(d : K))
    (J : (Ideal (𝓞 K))⁰) (a : idealSet K J)
    (ha : Odd (intNorm (idealSetMap K J a))) :
    NumberFieldAnalysis.signedArchCharacter K (conePreimage K J a) = NumberFieldAnalysis.chiFourReal (intNorm (idealSetMap K J a)) := by
  let x : (𝓞 K)⁰ := preimageOfMemIntegerSet (idealSetMap K J a)
  have hx : (x : 𝓞 K) ≠ 0 := nonZeroDivisors.coe_ne_zero x
  have hn : Odd (Algebra.norm ℤ (x : 𝓞 K)) := Int.natAbs_odd.mp ha
  have h := idealChiFour_principal_eq_signedArchCharacter K r hr (x : 𝓞 K) hx hn
  simpa only [NumberFieldAnalysis.idealChiFour, Ideal.absNorm_span_singleton, intNorm, conePreimage] using h.symm


theorem heckeOddSignedTerm_unit_mul (r : K) (hr : r^2=(d : K))
    (t : ℝ) (u : logSpace K) (epsilon : (𝓞 K)ˣ) (y : K) :
    NumberFieldAnalysis.heckeOddSignedTerm K t u (embeddingCoords K (algebraMap (𝓞 K) K (epsilon : 𝓞 K)*y)) =
      NumberFieldAnalysis.heckeOddSignedTerm K t (u+logEmbedding K (Additive.ofMul epsilon)) (embeddingCoords K y) := by
  unfold NumberFieldAnalysis.heckeOddSignedTerm
  rw [oddNormPoint_unit_mul K r hr, heckeSignedTerm_unit_mul_of_root K r hr]

/-- Each actual cone generator contributes the ordinary character of its norm.
Even norms vanish before taking any integral. -/
theorem heckeOddSignedTerm_cone_norm_scaled (r : K) (hr : r^2=(d : K))
    (J : (Ideal (𝓞 K))⁰) (a : idealSet K J) {t : ℝ} (ht : 0 < t) (u : logSpace K) :
    NumberFieldAnalysis.heckeOddSignedTerm K t u (embeddingCoords K (conePreimage K J a)) =
      NumberFieldAnalysis.chiFourReal (intNorm (idealSetMap K J a)) *
        NumberFieldAnalysis.heckeSignedTerm K ((intNorm (idealSetMap K J a) : ℝ)^2*t)
          (u+xShift K (conePreimage K J a)) (embeddingCoords K 1) := by
  unfold NumberFieldAnalysis.heckeOddSignedTerm
  rw [NumberFieldAnalysis.oddNormPoint_conePreimage]
  split_ifs with ha
  · rw [NumberFieldAnalysis.heckeSignedTerm_norm_scaled K (conePreimage_ne_zero K J a) ht.le,
      signedArchCharacter_conePreimage_eq_chiFour K r hr J a ha, abs_norm_conePreimage]
  · rw [NumberFieldAnalysis.chiFourReal_zero_of_even (Nat.not_odd_iff_even.mp ha), zero_mul]

end UnitDistance.Sqrt241.NumberFieldAnalysis
