-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.HeckeSignedMellinFinite
public import UnitDistance.Sqrt241.Geometry.HeckeSignedMellinLattice
public import UnitDistance.HeckeSignedClassRegroup

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.HeckeSignedMellinFinite` with the radicand `7` replaced by an
admissible `d` (`QuadraticRoot.Admissible`, used with `d = 3`): only its
radicand-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! Finiteness and measurability of the actual signed Mellin masses. -/
noncomputable section
open NumberField NumberField.InfinitePlace DedekindResidue MeasureTheory
open NumberField.mixedEmbedding NumberField.mixedEmbedding.fundamentalCone
open NumberField.Units NumberField.Units.dirichletUnitTheorem
open scoped BigOperators Real Classical nonZeroDivisors NNReal ENNReal
namespace UnitDistance.Sqrt241.NumberFieldAnalysis
variable {d : ℕ} [Fact (UnitDistance.Sqrt241.QuadraticRoot.Admissible d)]
variable (K : Type*) [Field K] [NumberField K]


/-- All signed parts of the actual lattice Mellin mass are finite on 2σ>1. -/
theorem lintegral_mellin_heckeOddSignedLatticeMass_ne_top (r : K) (hr : r^2=(d : K))
    (J : (Ideal (𝓞 K))⁰) (delta : ℝ) {σ : ℝ} (hσ : 1 < 2*σ) :
    (∫⁻ t in Set.Ioi (0:ℝ), ENNReal.ofReal (t^(σ-1)) *
      NumberFieldAnalysis.heckeOddSignedLatticeMass K J delta t) ≠ ⊤ := by
  rw [lintegral_mellin_heckeOddSignedLatticeMass K r hr J delta (by linarith)]
  exact ENNReal.mul_ne_top
    (ENNReal.mul_ne_top (NumberFieldAnalysis.heckeSignedGammaMass_ne_top K σ) (ENNReal.natCast_ne_top _))
    (NumberFieldAnalysis.tsum_subtype_positive_chiFourIdealWeight_ne_top K _ delta hσ)

end UnitDistance.Sqrt241.NumberFieldAnalysis
