-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.LocalOneDimensionalProfiles
public import UnitDistance.Sqrt241.Geometry.TensorFiniteProfiles
public import UnitDistance.Sqrt241.Witness
public import UnitDistance.Sqrt241.Geometry.WitnessLocalFunctional

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.LocalOneDimensionalProfiles` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Individual finite-place shell factors

One-dimensional shell factors allow the two primes in an actual conjugate
pair to retain their own completion types. Their product has the same exact
mass as the two-coordinate witness, without any identification of completions.
-/

noncomputable section
open Set MeasureTheory
open scoped Classical BigOperators

namespace UnitDistance.Sqrt241.Local.BallSystem
variable {G : Type*} [AddCommGroup G] [MeasurableSpace G]
  {μ : Measure G} {Q : ℝ} (B : Local.BallSystem G μ Q)


variable [TopologicalSpace G]


end UnitDistance.Sqrt241.Local.BallSystem

namespace UnitDistance.Sqrt241.Witness
variable {G : Type*} [AddCommGroup G] [MeasurableSpace G]
  {μ : Measure G} (v : Fin 5) (B : Local.BallSystem G μ (residueCard v))

def localShellFactor (k : ℤ) : G → ℝ := B.shellFactor k (Finset.range 6) (shellWeightNat v)


/-- The two-coordinate witness is literally the product of its two one-dimensional factors. -/
theorem localShellProfile_eq_factors (x : G × G) :
    localShellProfile v B x = localShellFactor v B 0 x.1 *
      localShellFactor v B (periodPower v) x.2 := by
  unfold localShellProfile Local.BallSystem.shellProfile localShellFactor Local.BallSystem.shellFactor
  rw [Finset.sum_product, Finset.sum_mul]
  apply Finset.sum_congr rfl
  intro i hi
  rw [Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro j hj
  simp only [Local.BallSystem.shellCell, Set.indicator, Set.mem_prod]
  split_ifs <;> simp_all

end UnitDistance.Sqrt241.Witness
