-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.RelativeFieldEnergy
public import UnitDistance.Sqrt241.Geometry.RelativeFieldProfile
public import UnitDistance.Sqrt241.Geometry.TensorEnergy
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.RelativeFieldEnergy` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Actual field energy and relative deformation windows

The energy uses the actual singleton/pair grouping of the quadratic field.
Its exponential is exactly the previously bounded field profile. The true
common window and all its relative deformations are compact.
-/

noncomputable section
open NumberField NumberField.InfinitePlace MeasureTheory
open scoped Classical
namespace UnitDistance.Sqrt241.RelativeUnits
variable {F K : Type} [Field F] [Field K] [NumberField F] [NumberField K]
  [Algebra F K] [Algebra.IsQuadraticExtension F K] [IsTotallyComplex K]

def relativeEnergy (ι : K ≃ₐ[F] K) (hι : ι ≠ 1) (x : EuclideanIdeal.Space K) : ℝ :=
  Witness.tensorPositionEnergy
    (EuclideanIdeal.tensorCoordinates K (RelativeUnits.relativePlaceGrouping ι hι) x)

theorem relativeEnergy_weight_p (ι : K ≃ₐ[F] K) (hι : ι ≠ 1)
    (x : EuclideanIdeal.Space K) :
    Real.exp (-Witness.p*relativeEnergy ι hι x) = relativeProfile ι hι x :=
  Witness.tensorPositionEnergy_weight_p _

theorem continuous_relativeEnergy (ι : K ≃ₐ[F] K) (hι : ι ≠ 1) :
    Continuous (relativeEnergy ι hι) :=
  Witness.continuous_tensorPositionEnergy.comp
    (EuclideanIdeal.tensorCoordinates K (RelativeUnits.relativePlaceGrouping ι hι)).continuous


theorem isCompact_relativeEnergy_window (ι : K ≃ₐ[F] K) (hι : ι ≠ 1) (T : ℝ) :
    IsCompact (energyWindow (relativeEnergy ι hι) T) :=
  (EuclideanIdeal.tensorCoordinates K (RelativeUnits.relativePlaceGrouping ι hι)).toHomeomorph.isCompact_preimage.mpr
    (Witness.isCompact_tensorPositionEnergy_window T)


end UnitDistance.Sqrt241.RelativeUnits
