-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.RelativeArithmeticAmplitude
public import UnitDistance.RelativeUnitsMass
public import UnitDistance.RelativeArchimedeanCoordinates
public import UnitDistance.Sqrt241.Geometry.TensorFunctional
public import UnitDistance.FiniteFunctionalCertificate
public import UnitDistance.Sqrt241.Target
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.RelativeArithmeticAmplitude` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Exact arithmetic normalization of the geometric amplitude

The quantities in this file are actual number-field invariants and the actual
Gaussian/Student integrals. The finite-place factor is kept separate so that
its later identification with an S-adic integral cannot be confused with the
scalar normalization proved here. No tower or graph existence is asserted.
-/

noncomputable section
open NumberField NumberField.InfinitePlace
open scoped Classical

namespace UnitDistance.Sqrt241.RelativeUnits
open UnitDistance.NumberFieldAnalysis

variable {F K : Type} [Field F] [Field K] [NumberField F] [NumberField K]
  [Algebra F K] [Algebra.IsQuadraticExtension F K] [IsTotallyComplex K]


/-- Actual mass, covolume and archimedean factors, multiplied by a separately
specified finite-place normalized functional. The factor `2^(2+δ)` is the
one in the proved unordered finite geometric transfer. -/
def arithmeticAmplitude (ι : K ≃ₐ[F] K) (finiteFactor ε : ℝ) : ℝ :=
  RelativeUnits.relativeUnitMass ι * (RelativeUnits.arithmeticCovolume K)^increment / (2:ℝ)^(2+increment) *
    Witness.tensorFunctional (RelativeUnits.RealPlaceIndex F) (RelativeUnits.PairPlaceIndex F) * finiteFactor *
      Real.exp (-4*(ε*(Module.finrank ℚ F : ℝ)))

theorem arithmeticAmplitude_pos (ι : K ≃ₐ[F] K) (hι : ι ≠ 1)
    {finiteFactor ε : ℝ} (hfinite : 0 < finiteFactor) :
    0 < arithmeticAmplitude ι finiteFactor ε := by
  unfold arithmeticAmplitude
  positivity [RelativeUnits.relativeUnitMass_pos ι hι, RelativeUnits.arithmeticCovolume_pos (K := K),
    Witness.tensorFunctional_pos (RelativeUnits.RealPlaceIndex F) (RelativeUnits.PairPlaceIndex F)]

/-- The exact exponential rate from actual arithmetic invariants. -/
def arithmeticRate (F K : Type) [Field F] [Field K] [NumberField F] [NumberField K]
    (finiteRate ε : ℝ) : ℝ :=
  finiteRate - (1/2-increment)*Real.log (rootDiscriminant F) -
    Real.log (relativeResidue K F)/(Module.finrank ℚ F : ℝ) +
    (1-increment)*Real.log 2 + (1-RelativeUnits.signatureRatio F)*Real.log Real.pi +
    (1-2*RelativeUnits.signatureRatio F)*Witness.JCompact + RelativeUnits.signatureRatio F*Witness.JPair - 4*ε

theorem log_arithmeticAmplitude (hunr : FiniteUnramified F K)
    (ι : K ≃ₐ[F] K) (hι : ι ≠ 1) (hb : 0 < nrRealPlaces F)
    {finiteFactor : ℝ} (hfinite : 0 < finiteFactor) (ε : ℝ) :
    Real.log (arithmeticAmplitude ι finiteFactor ε) =
      (Module.finrank ℚ F : ℝ)*
        arithmeticRate F K (Real.log finiteFactor/(Module.finrank ℚ F : ℝ)) ε -
          (3+increment)*Real.log 2 := by
  have hm := RelativeUnits.relativeUnitMass_pos ι hι
  have hD := RelativeUnits.arithmeticCovolume_pos (K := K)
  have ht := Witness.tensorFunctional_pos (RelativeUnits.RealPlaceIndex F) (RelativeUnits.PairPlaceIndex F)
  rw [arithmeticAmplitude, Real.log_mul (by positivity) (by positivity),
    Real.log_mul (by positivity) hfinite.ne', Real.log_mul (by positivity) ht.ne',
    Real.log_div (by positivity) (by positivity), Real.log_mul hm.ne' (by positivity),
    Real.log_rpow hD, Real.log_rpow (by norm_num : (0:ℝ)<2), Real.log_exp,
    RelativeUnits.log_relativeUnitMass hunr ι hι hb, RelativeUnits.log_arithmeticCovolume hunr,
    Witness.log_tensorFunctional]
  have hs : (nrRealPlaces F : ℝ)+2*nrComplexPlaces F = Module.finrank ℚ F := by
    exact_mod_cast card_add_two_mul_card_eq_rank F
  change _ + ((nrRealPlaces F : ℝ)*Witness.JCompact +
    (nrComplexPlaces F : ℝ)*Witness.JPair) + _ + _ = _
  unfold arithmeticRate RelativeUnits.signatureRatio
  field_simp [(RelativeUnits.degree_pos_real (F := F)).ne']
  rw [show (nrRealPlaces F : ℝ) = (Module.finrank ℚ F : ℝ)-2*nrComplexPlaces F by linarith]
  ring

/-- Exact normalization, including the remaining constant factor of two
from the arithmetic mass and every unordered-edge factor. -/
theorem arithmeticAmplitude_eq_exp (hunr : FiniteUnramified F K)
    (ι : K ≃ₐ[F] K) (hι : ι ≠ 1) (hb : 0 < nrRealPlaces F)
    {finiteFactor : ℝ} (hfinite : 0 < finiteFactor) (ε : ℝ) :
    arithmeticAmplitude ι finiteFactor ε =
      Real.exp ((Module.finrank ℚ F : ℝ)*
        arithmeticRate F K (Real.log finiteFactor/(Module.finrank ℚ F : ℝ)) ε) /
          (2:ℝ)^(3+increment) := by
  rw [← Real.exp_log (arithmeticAmplitude_pos ι hι hfinite),
    log_arithmeticAmplitude hunr ι hι hb hfinite ε, Real.exp_sub,
    Real.rpow_def_of_pos (by norm_num : (0:ℝ)<2)]
  congr 2
  ring


section Family
open Filter

variable (Fs Ks : ℕ → Type)
  [∀ j, Field (Fs j)] [∀ j, Field (Ks j)]
  [∀ j, NumberField (Fs j)] [∀ j, NumberField (Ks j)]
  [∀ j, Algebra (Fs j) (Ks j)]
  [∀ j, Algebra.IsQuadraticExtension (Fs j) (Ks j)]
  [∀ j, IsTotallyComplex (Ks j)]


end Family

end UnitDistance.Sqrt241.RelativeUnits
