-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.SIntegerWitnessVertices
public import UnitDistance.Sqrt241.Geometry.SIntegerWitnessWindow
public import UnitDistance.SIntegerPlaneProjection
public import UnitDistance.GeometryFinite
public import UnitDistance.Sqrt241.Geometry.RelativeFieldProfile
public import UnitDistance.Sqrt241.Geometry.SIntegerWitnessProfile
public import UnitDistance.Sqrt241.Geometry.TensorFiniteProfiles
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.SIntegerWitnessVertices` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! # Genuine finite S-integer vertex sets for every witness transformation -/

noncomputable section
open Set MeasureTheory NumberField NumberField.InfinitePlace IsDedekindDomain
open scoped Classical BigOperators nonZeroDivisors

namespace UnitDistance.Sqrt241.SIntegerCRT
open UnitDistance.RelativeIdealCosets UnitDistance.RelativeUnits

variable {F K : Type} [Field F] [Field K] [NumberField F] [NumberField K]
  [Algebra F K] [Algebra.IsQuadraticExtension F K] [IsTotallyComplex K]
  {S : Type*} [Fintype S] {ι : K ≃ₐ[F] K}

local instance verticesLocalMeasurableSpace (P : S × Bool → HeightOneSpectrum (𝓞 K)) (t : S × Bool) :
    MeasurableSpace ((P t).adicCompletion K) := borel ((P t).adicCompletion K)
local instance verticesLocalBorelSpace (P : S × Bool → HeightOneSpectrum (𝓞 K)) (t : S × Bool) :
    BorelSpace ((P t).adicCompletion K) := ⟨rfl⟩


def witnessDeformedWindow (hι : ι ≠ 1) (D : PrimePairFamily ι S) (v : S → Fin 5)
    (n₀ : S → ℤ) (T : ℝ) (h : PairPlaceIndex F → ℝ) :
    Set (EuclideanIdeal.Space K × SIntegerCRT.LocalProduct D.prime) :=
  SIntegerCRT.witnessDeformation hι D h ⁻¹' witnessSAdicWindow hι D v n₀ T

theorem witnessDeformedWindow_compact (hι : ι ≠ 1) (D : PrimePairFamily ι S)
    (v : S → Fin 5) (n₀ : S → ℤ) (T : ℝ) (h : PairPlaceIndex F → ℝ) :
    IsCompact (witnessDeformedWindow hι D v n₀ T h) :=
  (SIntegerCRT.witnessDeformation hι D h).isCompact_preimage.mpr (witnessSAdicWindow_compact hι D v n₀ T)

theorem witnessDeformedWindow_volume (hι : ι ≠ 1) (D : PrimePairFamily ι S)
    (v : S → Fin 5) (n₀ : S → ℤ) (T : ℝ) (h : PairPlaceIndex F → ℝ) :
    SIntegerCRT.semiLocalHaar D.prime (witnessDeformedWindow hι D v n₀ T h) =
      SIntegerCRT.semiLocalHaar D.prime (witnessSAdicWindow hι D v n₀ T) :=
  (SIntegerCRT.witnessDeformation_measurePreserving hι D h).measure_preimage
    (measurableSet_supportedWindow (witnessSAdicSupport_measurable D v n₀)
      (witnessSAdicEnergy_continuous hι D v n₀).measurable T).nullMeasurableSet


/-- Actual diagonal S-integer points in the transformed common witness window. -/
def witnessDiagonalVertices (hι : ι ≠ 1) (D : PrimePairFamily ι S) (v : S → Fin 5)
    (n₀ : S → ℤ) (T : ℝ) (h : PairPlaceIndex F → ℝ)
    (r : EuclideanIdeal.Space K × SIntegerCRT.LocalProduct D.prime) : Finset (SIntegerCRT.diagonalSIntegers D.prime) := by
  letI := SIntegerCRT.diagonalSIntegers_discreteTopology D.prime (SIntegerCRT.primePair_injective D)
  exact compactLatticeWindow (SIntegerCRT.diagonalSIntegers D.prime) (SIntegerCRT.diagonalSIntegers_closed D)
    (witnessDeformedWindow hι D v n₀ T h) (witnessDeformedWindow_compact hι D v n₀ T h) r

@[simp] theorem mem_witnessDiagonalVertices (hι : ι ≠ 1) (D : PrimePairFamily ι S)
    (v : S → Fin 5) (n₀ : S → ℤ) (T : ℝ) (h : PairPlaceIndex F → ℝ)
    (r : EuclideanIdeal.Space K × SIntegerCRT.LocalProduct D.prime) (x : SIntegerCRT.diagonalSIntegers D.prime) :
    x ∈ witnessDiagonalVertices hι D v n₀ T h r ↔
      x.val+r ∈ witnessDeformedWindow hι D v n₀ T h := by
  letI := SIntegerCRT.diagonalSIntegers_discreteTopology D.prime (SIntegerCRT.primePair_injective D)
  exact mem_compactLatticeWindow _ _ _ _ _ _

/-- The same finite vertex set, as actual field S-integers. -/
def witnessSIntegerVertices (hι : ι ≠ 1) (D : PrimePairFamily ι S) (v : S → Fin 5)
    (n₀ : S → ℤ) (T : ℝ) (h : PairPlaceIndex F → ℝ)
    (r : EuclideanIdeal.Space K × SIntegerCRT.LocalProduct D.prime) : Finset ((Set.range D.prime).integer K) :=
  (witnessDiagonalVertices hι D v n₀ T h r).map (SIntegerCRT.diagonalEmbeddingEquiv D.prime).symm.toEmbedding


/-- The original Poisson bound applies directly to the exponential energy
sum over the entire actual diagonal lattice intersection. -/
theorem witnessDiagonalVertices_weight_sum_le (hι : ι ≠ 1) (D : PrimePairFamily ι S)
    (v : S → Fin 5)
    (hQ : ∀ s, (Ideal.absNorm (D.prime (s, false)).asIdeal : ℝ) = Witness.residueCard (v s))
    (n₀ : S → ℤ)
    (hgap : Real.log 2+2*Real.log 5+2 ≤
      EuclideanIdeal.dualScale K (SIntegerCRT.periodIdeal D.prime (witnessPeriodExponent v n₀)))
    (T : ℝ) (h : PairPlaceIndex F → ℝ) (r : EuclideanIdeal.Space K × SIntegerCRT.LocalProduct D.prime) :
    (∑ l ∈ witnessDiagonalVertices hι D v n₀ T h r,
      Real.exp (-Witness.p*witnessSAdicEnergy hι D v n₀ (SIntegerCRT.witnessDeformation hι D h (l.val+r)))) ≤
      2*(Witness.compactMass^nrRealPlaces F*Witness.pairMass^nrComplexPlaces F)*
        Witness.tensorFiniteMass v / ((2⁻¹ : ℝ)^nrComplexPlaces K*Real.sqrt |(discr K : ℝ)|) := by
  have hw := witnessSAdic_weight_sum_le hι D v hQ n₀ hgap h r.1 r.2
    (witnessSIntegerVertices hι D v n₀ T h r)
  rw [witnessSIntegerVertices, Finset.sum_map] at hw
  refine le_trans (le_of_eq ?_) hw
  apply Finset.sum_congr rfl
  intro l hl
  have hx := (mem_witnessDiagonalVertices hι D v n₀ T h r l).mp hl
  rw [witnessSAdicEnergy_weight hι D v n₀ hx.1]
  have he := congrArg Subtype.val ((SIntegerCRT.diagonalEmbeddingEquiv D.prime).apply_symm_apply l)
  change SIntegerCRT.diagonalEmbedding D.prime ((SIntegerCRT.diagonalEmbeddingEquiv D.prime).symm l) = l.val at he
  rw [← he]
  change Sqrt241.RelativeUnits.relativeProfile ι hι
      (EuclideanIdeal.deformation K (reciprocalLogScale ι hι h)
        (EuclideanIdeal.embedding K ((SIntegerCRT.diagonalEmbeddingEquiv D.prime).symm l).val+r.1)) * _ = _
  rw [add_comm (EuclideanIdeal.embedding K ((SIntegerCRT.diagonalEmbeddingEquiv D.prime).symm l).val) r.1]
  rfl

end UnitDistance.Sqrt241.SIntegerCRT
