-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.SIntegerReferenceFiniteSteps
public import UnitDistance.SIntegerReferenceSteps
public import UnitDistance.Sqrt241.Geometry.SIntegerReferenceRescaling
public import UnitDistance.Sqrt241.Geometry.SIntegerPairedCoordinates
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.SIntegerReferenceFiniteSteps` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! # Actual finite valuation labels after the signed-reference normalization -/

noncomputable section
open NumberField IsDedekindDomain
open scoped Classical nonZeroDivisors

namespace UnitDistance.Sqrt241.SIntegerCRT
open UnitDistance.RelativeIdealCosets UnitDistance.RelativeCompletion UnitDistance.Local.ValuedHaar

variable {F K : Type} [Field F] [Field K] [NumberField F] [NumberField K]
  [Algebra F K] [Algebra.IsQuadraticExtension F K]
  {S : Type*} [Fintype S] {ι : K ≃ₐ[F] K}

local instance finiteStepMeasurableSpace (v : HeightOneSpectrum (𝓞 K)) :
    MeasurableSpace (v.adicCompletion K) := borel (v.adicCompletion K)
local instance finiteStepBorelSpace (v : HeightOneSpectrum (𝓞 K)) :
    BorelSpace (v.adicCompletion K) := ⟨rfl⟩

/-- An actual norm-one field element with relative exponent `n-n₀` becomes
the literal canonical reciprocal step at exponent `n`, with an actual unit
in each selected completion. -/
theorem referenceFiniteStep_of_normOne (hι : ι ≠ 1) (D : PrimePairFamily ι S)
    (v : S → Fin 5)
    (hQ : ∀ s, (Ideal.absNorm (D.prime (s, false)).asIdeal : ℝ) = Witness.residueCard (v s))
    (n₀ n : S → ℤ) (β : K) (hβ : Algebra.norm F β = 1)
    (hv : ∀ s, (D.prime (s, false)).valuation K β = WithZero.exp (-(n s-n₀ s))) :
    ∃ u : (s : S) → ValuationOneUnits ((D.prime (s, false)).adicCompletion K),
      SIntegerCRT.pairedCoordinates D (SIntegerCRT.referenceRescaling D n₀ (SIntegerCRT.localEmbedding D.prime β)) =
        fun s => (witnessPairSteps D v hQ s).step (n s) (u s) := by
  have hs (s : S) := normOne_eq_reciprocalStep_of_valuation ι hι
    (D.prime (s, false)) (D.prime (s, true)) (D.partner s) β hβ (n s-n₀ s) (hv s)
  choose u hu using hs
  refine ⟨u, ?_⟩
  rw [SIntegerCRT.pairedCoordinates_referenceRescaling]
  funext s
  change reciprocalRescaling ((D.prime (s, false)).adicCompletion K) (n₀ s)
    (pairCoordinates ι (D.prime (s, false)) (D.prime (s, true)) (D.partner s)
      (algebraMap K ((D.prime (s, false)).adicCompletion K) β,
       algebraMap K ((D.prime (s, true)).adicCompletion K) β)) = _
  rw [hu s, reciprocalRescaling_step]
  change (reciprocalSteps ((D.prime (s, false)).adicCompletion K)).step
    (n s-n₀ s+n₀ s) (u s) =
    (reciprocalSteps ((D.prime (s, false)).adicCompletion K)).step (n s) (u s)
  rw [sub_add_cancel]

variable [IsTotallyComplex K]


end UnitDistance.Sqrt241.SIntegerCRT
