-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentComplexDecay
public import UnitDistance.Sqrt241.Geometry.StudentComplexCoordinates
public import UnitDistance.Sqrt241.Geometry.StudentComplexExtension
public import UnitDistance.Sqrt241.Geometry.StudentComplexMajorant
public import UnitDistance.Sqrt241.Geometry.StudentComplexPolynomial
public import UnitDistance.Sqrt241.Geometry.StudentComplexTubeCertificate
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentComplexDecay` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! Actual Student decay in each real coordinate of the geometric tube. -/

namespace UnitDistance.Sqrt241.Witness

private theorem real_coordinate_student_le (x : Witness.StudentRealPlane) (i : Fin 2) :
    (1+‖x‖^2)^(-s*p) ≤ (1+(x i)^2)^(-s*p) := by
  have hnorm := PiLp.norm_apply_le x i
  rw [Real.norm_eq_abs] at hnorm
  have hsq : (x i)^2 ≤ ‖x‖^2 := by nlinarith [sq_abs (x i), abs_nonneg (x i), norm_nonneg x]
  apply Real.rpow_le_rpow_of_nonpos (by positivity) (by linarith)
  have hs := witness_basic.1
  have hp := witness_basic.2.2.1
  nlinarith

private theorem normalized_student_le_one (x : Witness.StudentRealPlane) :
    (1+‖x‖^2)^(-s*p) ≤ 1 := by
  have hs := witness_basic.1
  have hp := witness_basic.2.2.1
  simpa only [Real.one_rpow] using Real.rpow_le_rpow_of_nonpos zero_lt_one
    (by nlinarith [sq_nonneg ‖x‖] : 1 ≤ 1+‖x‖^2) (by nlinarith : -s*p ≤ 0)

/-- One uniform constant works for every scalar real coordinate of the first
complex plane, at every allowed imaginary displacement. -/
theorem complexPairWeight_fst_coordinate_norm_le
    (x y : Witness.StudentRealPlane × Witness.StudentRealPlane) (i : Fin 2)
    (hy1 : ‖y.1‖ ≤ 1/1000) (hy2 : ‖y.2‖ ≤ 1/1000) :
    ‖complexPairWeight (Witness.pairComplexShift x y)‖ ≤
      (fourierTubeConstant*14^p)*(1+(x.1 i)^2)^(-s*p) := by
  have h := complexPairWeight_normalized_norm_le x y hy1 hy2
  have hq : (0:ℝ) ≤ (fourierTubeLoss:ℝ) := by exact_mod_cast fourierTubeLoss_nonneg
  have hK : 0 ≤ fourierTubeConstant := by unfold fourierTubeConstant; positivity
  have hp0 : 0 ≤ (1+‖x.1‖^2)^(-s*p) := by positivity
  have hprod : (1+‖x.1‖^2)^(-s*p)*(1+‖x.2‖^2)^(-s*p) ≤
      (1+(x.1 i)^2)^(-s*p) := by
    calc
      _ ≤ (1+‖x.1‖^2)^(-s*p)*1 :=
        mul_le_mul_of_nonneg_left (normalized_student_le_one x.2) hp0
      _ ≤ _ := by simpa only [mul_one] using real_coordinate_student_le x.1 i
  calc
    _ ≤ _ := h
    _ ≤ fourierTubeConstant*((1+(x.1 i)^2)^(-s*p)*14^p) :=
      mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_right hprod (by positivity)) hK
    _ = _ := by ring

/-- The same uniform scalar decay bound for the second complex plane. -/
theorem complexPairWeight_snd_coordinate_norm_le
    (x y : Witness.StudentRealPlane × Witness.StudentRealPlane) (i : Fin 2)
    (hy1 : ‖y.1‖ ≤ 1/1000) (hy2 : ‖y.2‖ ≤ 1/1000) :
    ‖complexPairWeight (Witness.pairComplexShift x y)‖ ≤
      (fourierTubeConstant*14^p)*(1+(x.2 i)^2)^(-s*p) := by
  have h := complexPairWeight_normalized_norm_le x y hy1 hy2
  have hq : (0:ℝ) ≤ (fourierTubeLoss:ℝ) := by exact_mod_cast fourierTubeLoss_nonneg
  have hK : 0 ≤ fourierTubeConstant := by unfold fourierTubeConstant; positivity
  have hp0 : 0 ≤ (1+‖x.2‖^2)^(-s*p) := by positivity
  have hprod : (1+‖x.1‖^2)^(-s*p)*(1+‖x.2‖^2)^(-s*p) ≤
      (1+(x.2 i)^2)^(-s*p) := by
    calc
      _ ≤ 1*(1+‖x.2‖^2)^(-s*p) :=
        mul_le_mul_of_nonneg_right (normalized_student_le_one x.1) hp0
      _ ≤ _ := by simpa only [one_mul] using real_coordinate_student_le x.2 i
  calc
    _ ≤ _ := h
    _ ≤ fourierTubeConstant*((1+(x.2 i)^2)^(-s*p)*14^p) :=
      mul_le_mul_of_nonneg_left (mul_le_mul_of_nonneg_right hprod (by positivity)) hK
    _ = _ := by ring

end UnitDistance.Sqrt241.Witness
