-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentComplexIntegral
public import UnitDistance.Sqrt241.Geometry.StudentComplexMajorant
public import UnitDistance.Sqrt241.Geometry.StudentComplexExtension
public import UnitDistance.Sqrt241.Geometry.StudentComplexRealRestriction
public import UnitDistance.Sqrt241.Geometry.StudentProfiles
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentComplexIntegral` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! Integrability and exact mass control of the actual holomorphic tube slices. -/

open MeasureTheory

namespace UnitDistance.Sqrt241.Witness

theorem continuous_normalizedStudentPair_shift (y : Witness.StudentRealPlane × Witness.StudentRealPlane) :
    Continuous (fun z : ℂ × ℂ => Witness.pairComplexShift (normalizedStudentPair z) y) := by
  unfold Witness.pairComplexShift normalizedStudentPair Witness.complexToStudentRealPlane BernsteinTube.complexShift
  fun_prop

theorem continuous_complexPairWeight_shift (y : Witness.StudentRealPlane × Witness.StudentRealPlane)
    (hy1 : ‖y.1‖ ≤ 1/1000) (hy2 : ‖y.2‖ ≤ 1/1000) :
    Continuous (fun z : ℂ × ℂ => complexPairWeight (Witness.pairComplexShift (normalizedStudentPair z) y)) := by
  apply continuous_iff_continuousAt.mpr
  intro z
  exact ContinuousAt.comp (f := fun w : ℂ × ℂ => Witness.pairComplexShift (normalizedStudentPair w) y)
    (complexPairWeight_differentiableAt (normalizedStudentPair z) y hy1 hy2).continuousAt
    (continuous_normalizedStudentPair_shift y).continuousAt

/-- Every permitted shifted slice is genuinely Lebesgue integrable. -/
theorem integrable_complexPairWeight_shift (y : Witness.StudentRealPlane × Witness.StudentRealPlane)
    (hy1 : ‖y.1‖ ≤ 1/1000) (hy2 : ‖y.2‖ ≤ 1/1000) :
    Integrable (fun z : ℂ × ℂ => complexPairWeight (Witness.pairComplexShift (normalizedStudentPair z) y)) :=
  (integrable_pairMass.const_mul fourierTubeConstant).mono'
    (continuous_complexPairWeight_shift y hy1 hy2).aestronglyMeasurable
    (Filter.Eventually.of_forall (fun z => complexPairWeight_norm_le z y hy1 hy2))

/-- The full shifted absolute integral is bounded by the manuscript's exact
constant times the independently defined original mass `pairMass`. -/
theorem integral_norm_complexPairWeight_shift_le (y : Witness.StudentRealPlane × Witness.StudentRealPlane)
    (hy1 : ‖y.1‖ ≤ 1/1000) (hy2 : ‖y.2‖ ≤ 1/1000) :
    (∫ z : ℂ × ℂ, ‖complexPairWeight (Witness.pairComplexShift (normalizedStudentPair z) y)‖) ≤
      fourierTubeConstant * pairMass := by
  have h := integral_mono (integrable_complexPairWeight_shift y hy1 hy2).norm
    (integrable_pairMass.const_mul fourierTubeConstant)
    (fun z => complexPairWeight_norm_le z y hy1 hy2)
  simpa only [integral_const_mul, pairMass] using h

end UnitDistance.Sqrt241.Witness
