-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentSchwartzGrowth
public import UnitDistance.Sqrt241.Geometry.StudentProfiles
public import Mathlib.Analysis.Distribution.TemperateGrowth
public import Mathlib.Analysis.Calculus.IteratedDeriv.Defs
public import Mathlib.Analysis.SpecialFunctions.Pow.Deriv
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentSchwartzGrowth` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Temperate growth of the actual polynomial Student weight

All derivatives of the exact published weight have polynomial growth. Real
powers are handled on their actual positive range, including the Bernstein
polynomial whose lower bound is one. No smoothness or derivative-growth
hypothesis is imposed on the witness.
-/

open scoped BigOperators ContDiff

namespace UnitDistance.Sqrt241


namespace Witness

/-- The two-coordinate Bernstein correction as an ordinary real function. -/
noncomputable def studentPolynomial (z : ℂ × ℂ) : ℝ :=
  polynomial (1+a*‖z.1‖^2)⁻¹ (1+a*‖z.2‖^2)⁻¹

theorem studentPolynomial_one_le (z : ℂ × ℂ) : 1 ≤ studentPolynomial z :=
  (polynomial_bounds (student_coordinate_bounds z.1).1.le (student_coordinate_bounds z.1).2
    (student_coordinate_bounds z.2).1.le (student_coordinate_bounds z.2).2).1

theorem temperateGrowth_studentPolynomial : studentPolynomial.HasTemperateGrowth := by
  have hcoord : (fun z : ℂ => (1+a*‖z‖^2)⁻¹).HasTemperateGrowth := by
    have h := temperateGrowth_studentWeight witness_basic.2.1 1
    change (fun z : ℂ => (1+a*‖z‖^2)^(-(1 : ℝ))).HasTemperateGrowth at h
    simpa only [Real.rpow_neg_one] using h
  have hf : (fun z : ℂ × ℂ => z.1).HasTemperateGrowth :=
    (ContinuousLinearMap.fst ℝ ℂ ℂ).hasTemperateGrowth
  have hs : (fun z : ℂ × ℂ => z.2).HasTemperateGrowth :=
    (ContinuousLinearMap.snd ℝ ℂ ℂ).hasTemperateGrowth
  have ht := hcoord.comp hf
  have hu := hcoord.comp hs
  change (fun z : ℂ × ℂ => polynomial _ _).HasTemperateGrowth
  unfold polynomial bernstein3
  fun_prop

/-- The exact published profile raised to any real power is a temperate
multiplier. Positivity and the polynomial lower bound are proved from its
actual rational coefficients. -/
theorem temperateGrowth_pairProfile_rpow (q : ℝ) :
    (fun z : ℂ × ℂ => pairProfile z ^ q).HasTemperateGrowth := by
  have hpoly := temperateGrowth_rpow_of_one_le temperateGrowth_studentPolynomial
    studentPolynomial_one_le q
  have hw := temperateGrowth_studentWeight witness_basic.2.1 (s*q)
  have hf := (ContinuousLinearMap.fst ℝ ℂ ℂ).hasTemperateGrowth
  have hs := (ContinuousLinearMap.snd ℝ ℂ ℂ).hasTemperateGrowth
  have hprod := ((hw.comp hf).mul (hw.comp hs)).mul hpoly
  convert! hprod using 1
  funext z
  have hbase (x : ℂ) : 0 < 1+a*‖x‖^2 := by have := witness_basic.2.1; positivity
  have hpolypos : 0 < studentPolynomial z := lt_of_lt_of_le zero_lt_one (studentPolynomial_one_le z)
  rw [pairProfile_student_identity]
  change (studentWeight a s z.1 * studentWeight a s z.2 * studentPolynomial z)^q = _
  unfold studentWeight
  rw [Real.mul_rpow (mul_nonneg (Real.rpow_nonneg (hbase _).le _) (Real.rpow_nonneg (hbase _).le _)) hpolypos.le,
    Real.mul_rpow (Real.rpow_nonneg (hbase _).le _) (Real.rpow_nonneg (hbase _).le _)]
  simp only [Function.comp_apply, Pi.mul_apply,
    ← Real.rpow_mul (hbase _).le, neg_mul, studentPolynomial]
  rfl

end Witness
end UnitDistance.Sqrt241
