-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentComplexRealRestriction
public import UnitDistance.Sqrt241.Geometry.StudentComplexExtension
public import UnitDistance.Sqrt241.Geometry.StudentComplexPolynomial
public import UnitDistance.Sqrt241.Geometry.StudentProfiles
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentComplexRealRestriction` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! The complex extension restricts to the exact published real p-th power. -/

open scoped BigOperators

namespace UnitDistance.Sqrt241.Witness


/-- Exactly the manuscript's normalization in each of the two complex
coordinates, retaining the ordinary complex Euclidean norm. -/
noncomputable def normalizedStudentPair (z : ℂ × ℂ) : Witness.StudentRealPlane × Witness.StudentRealPlane :=
  (Real.sqrt a • Witness.complexToStudentRealPlane z.1,
   Real.sqrt a • Witness.complexToStudentRealPlane z.2)

theorem normalizedStudentPair_fst_norm_sq (z : ℂ × ℂ) :
    ‖(normalizedStudentPair z).1‖^2 = a*‖z.1‖^2 := by
  simp only [normalizedStudentPair, norm_smul, Real.norm_eq_abs,
    abs_of_nonneg (Real.sqrt_nonneg _), mul_pow,
    Witness.complexToStudentRealPlane_norm_sq, Real.sq_sqrt witness_basic.2.1.le]

theorem normalizedStudentPair_snd_norm_sq (z : ℂ × ℂ) :
    ‖(normalizedStudentPair z).2‖^2 = a*‖z.2‖^2 := by
  simp only [normalizedStudentPair, norm_smul, Real.norm_eq_abs,
    abs_of_nonneg (Real.sqrt_nonneg _), mul_pow,
    Witness.complexToStudentRealPlane_norm_sq, Real.sq_sqrt witness_basic.2.1.le]


/-- The literal p-th power of the original profile factors into two Student
weights and the p-th power of the same original polynomial. -/
theorem pairProfile_rpow_identity (z : ℂ × ℂ) :
    pairProfile z ^ p =
      (1+a*‖z.1‖^2)^(-s*p) * (1+a*‖z.2‖^2)^(-s*p) *
      (polynomial (1+a*‖z.1‖^2)⁻¹ (1+a*‖z.2‖^2)⁻¹)^p := by
  have hb (w : ℂ) : 0 ≤ 1+a*‖w‖^2 := by have := witness_basic.2.1; positivity
  obtain ⟨ht0, ht1⟩ := student_coordinate_bounds z.1
  obtain ⟨hu0, hu1⟩ := student_coordinate_bounds z.2
  have hP := (polynomial_bounds ht0.le ht1 hu0.le hu1).1
  rw [pairProfile_student_identity]
  unfold studentWeight
  rw [Real.mul_rpow (mul_nonneg (Real.rpow_nonneg (hb _) _) (Real.rpow_nonneg (hb _) _))
      (by linarith : 0 ≤ polynomial _ _),
    Real.mul_rpow (Real.rpow_nonneg (hb _) _) (Real.rpow_nonneg (hb _) _)]
  simp only [← Real.rpow_mul (hb _)]

/-- The independently defined principal-power extension has exactly the
published p-th-power weight as its real restriction. -/
theorem complexPairWeight_real (z : ℂ × ℂ) :
    complexPairWeight (Witness.pairComplexShift (normalizedStudentPair z) 0) =
      ((pairProfile z ^ p : ℝ):ℂ) := by
  have hb (w : ℂ) : 0 ≤ 1+a*‖w‖^2 := by have := witness_basic.2.1; positivity
  obtain ⟨ht0, ht1⟩ := student_coordinate_bounds z.1
  obtain ⟨hu0, hu1⟩ := student_coordinate_bounds z.2
  have hP := (polynomial_bounds ht0.le ht1 hu0.le hu1).1
  simp only [complexPairWeight, Witness.pairComplexShift, Prod.fst_zero, Prod.snd_zero,
    Witness.studentDenominator_real, normalizedStudentPair_fst_norm_sq,
    normalizedStudentPair_snd_norm_sq, ← Complex.ofReal_inv,
    complexPolynomial_ofReal, ← Complex.ofReal_cpow (hb _),
    ← Complex.ofReal_cpow (by linarith : 0 ≤ polynomial _ _),
    ← Complex.ofReal_mul, pairProfile_rpow_identity]

end UnitDistance.Sqrt241.Witness
