-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentComplexTubeSegments
public import UnitDistance.Sqrt241.Geometry.StudentComplexSlices

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentComplexTubeSegments` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! Endpoint membership suffices for the actual coordinate contour tube. -/

open MeasureTheory Set

namespace UnitDistance.Sqrt241.Witness


/-- The actual first-plane Fourier contour needs only endpoint membership in
the specified Euclidean tube; all intermediate membership is proved. -/
theorem complexPairWeightFstSlice_fourier_shift_of_endpoints
    (z : Witness.StudentComplexPlane × Witness.StudentComplexPlane) (i : Fin 2) (a₀ b₀ ξ : ℝ)
    (ha : ‖Witness.studentRealPlaneUpdate (Witness.studentComplexPlaneImag z.1) i a₀‖ ≤ 1/1000)
    (hb : ‖Witness.studentRealPlaneUpdate (Witness.studentComplexPlaneImag z.1) i b₀‖ ≤ 1/1000)
    (hz2 : ‖Witness.studentComplexPlaneImag z.2‖ ≤ 1/1000) :
    (Real.exp (2*Real.pi*ξ*a₀):ℂ) *
      (∫ x : ℝ, complexPairWeightFstSlice z i ((x:ℂ)+(a₀:ℂ)*Complex.I)*
        FourierContour.fourierKernel ξ (x:ℂ)) =
    (Real.exp (2*Real.pi*ξ*b₀):ℂ) *
      (∫ x : ℝ, complexPairWeightFstSlice z i ((x:ℂ)+(b₀:ℂ)*Complex.I)*
        FourierContour.fourierKernel ξ (x:ℂ)) :=
  complexPairWeightFstSlice_fourier_shift z i a₀ b₀ ξ
    (fun _ ht => Witness.studentRealPlaneUpdate_norm_le_of_mem_uIcc _ i ha hb ht) hz2

theorem complexPairWeightSndSlice_fourier_shift_of_endpoints
    (z : Witness.StudentComplexPlane × Witness.StudentComplexPlane) (i : Fin 2) (a₀ b₀ ξ : ℝ)
    (hz1 : ‖Witness.studentComplexPlaneImag z.1‖ ≤ 1/1000)
    (ha : ‖Witness.studentRealPlaneUpdate (Witness.studentComplexPlaneImag z.2) i a₀‖ ≤ 1/1000)
    (hb : ‖Witness.studentRealPlaneUpdate (Witness.studentComplexPlaneImag z.2) i b₀‖ ≤ 1/1000) :
    (Real.exp (2*Real.pi*ξ*a₀):ℂ) *
      (∫ x : ℝ, complexPairWeightSndSlice z i ((x:ℂ)+(a₀:ℂ)*Complex.I)*
        FourierContour.fourierKernel ξ (x:ℂ)) =
    (Real.exp (2*Real.pi*ξ*b₀):ℂ) *
      (∫ x : ℝ, complexPairWeightSndSlice z i ((x:ℂ)+(b₀:ℂ)*Complex.I)*
        FourierContour.fourierKernel ξ (x:ℂ)) :=
  complexPairWeightSndSlice_fourier_shift z i a₀ b₀ ξ hz1
    (fun _ ht => Witness.studentRealPlaneUpdate_norm_le_of_mem_uIcc _ i ha hb ht)

end UnitDistance.Sqrt241.Witness
