-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentComplexMajorant
public import UnitDistance.Sqrt241.Geometry.StudentComplexRealRestriction
public import UnitDistance.Sqrt241.Geometry.StudentComplexExtension
public import UnitDistance.Sqrt241.Geometry.StudentComplexPolynomial
public import UnitDistance.Sqrt241.Geometry.StudentComplexTubeCertificate
public import UnitDistance.Sqrt241.Geometry.StudentProfiles
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentComplexMajorant` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! The explicit pointwise contour majorant for the actual p-th power. -/

namespace UnitDistance.Sqrt241.Witness

/-- The explicit factor in the published two-coordinate Fourier envelope. -/
noncomputable def fourierTubeConstant : ℝ :=
  (1-(1/1000:ℝ)^2)^(-2*s*p) * (1+(fourierTubeLoss:ℝ))^p

private theorem denominator_cpow_norm_le (x y : Witness.StudentRealPlane) (hy : ‖y‖ ≤ 1/1000) :
    ‖(BernsteinTube.studentDenominator (BernsteinTube.complexShift x y))^((-s*p:ℝ):ℂ)‖ ≤
      (1-(1/1000:ℝ)^2)^(-s*p)*(1+‖x‖^2)^(-s*p) := by
  rw [Complex.norm_cpow_real]
  have hlow := BernsteinTube.studentDenominator_norm_lower x y (by norm_num : (0:ℝ)≤1/1000) hy
  have hs := witness_basic.1
  have hp := witness_basic.2.2.1
  have h := Real.rpow_le_rpow_of_nonpos (by positivity : 0 < (1-(1/1000:ℝ)^2)*(1+‖x‖^2))
    hlow (by nlinarith : -s*p ≤ 0)
  rwa [Real.mul_rpow (by norm_num : (0:ℝ)≤1-(1/1000:ℝ)^2) (by positivity)] at h

private theorem polynomial_cpow_norm_le (x y : Witness.StudentRealPlane × Witness.StudentRealPlane)
    (hy1 : ‖y.1‖ ≤ 1/1000) (hy2 : ‖y.2‖ ≤ 1/1000) :
    ‖(complexPolynomial
      (BernsteinTube.studentDenominator (Witness.pairComplexShift x y).1)⁻¹
      (BernsteinTube.studentDenominator (Witness.pairComplexShift x y).2)⁻¹)^(p:ℂ)‖ ≤
      (1+(fourierTubeLoss:ℝ))^p *
        (polynomial (1+‖x.1‖^2)⁻¹ (1+‖x.2‖^2)⁻¹)^p := by
  have hb (w : Witness.StudentRealPlane) : 0 < 1+‖w‖^2 := by positivity
  have hcoord (w : Witness.StudentRealPlane) :
      0 ≤ (1+‖w‖^2)⁻¹ ∧ (1+‖w‖^2)⁻¹ ≤ 1 :=
    ⟨(inv_pos.mpr (hb w)).le, (inv_le_one₀ (hb w)).mpr (by nlinarith [sq_nonneg ‖w‖])⟩
  have hi (w v : Witness.StudentRealPlane) (hv : ‖v‖ ≤ 1/1000) :
      ‖(BernsteinTube.studentDenominator (BernsteinTube.complexShift w v))⁻¹ -
        (((1+‖w‖^2)⁻¹:ℝ):ℂ)‖ ≤ (Witness.fourierTubeOmega:ℝ) := by
    have h := BernsteinTube.studentDenominator_inv_sub_real_norm_le w v
      (by norm_num : (0:ℝ)≤1/1000) (by norm_num : (1/1000:ℝ)<1) hv
    norm_num [Witness.fourierTubeOmega_eq] at h ⊢
    exact h
  have hpoly := complexPolynomial_norm_le (hcoord x.1).1 (hcoord x.1).2
    (hcoord x.2).1 (hcoord x.2).2 _ _ (hi x.1 y.1 hy1) (hi x.2 y.2 hy2)
  simp only [add_sub_cancel] at hpoly
  have hP := (polynomial_bounds (hcoord x.1).1 (hcoord x.1).2
    (hcoord x.2).1 (hcoord x.2).2).1
  have hq : (0:ℝ) ≤ (fourierTubeLoss:ℝ) := by exact_mod_cast fourierTubeLoss_nonneg
  rw [Complex.norm_cpow_real]
  have h := Real.rpow_le_rpow (norm_nonneg _) hpoly witness_basic.2.2.1.le
  rwa [Real.mul_rpow (by linarith : 0 ≤ 1+(fourierTubeLoss:ℝ))
    (by linarith : 0 ≤ polynomial _ _)] at h

/-- The pointwise shifted majorant is the exact real p-th-power profile
multiplied by the published explicit constant. This supplies the integrable
majorant needed by the remaining contour shift. -/
theorem complexPairWeight_norm_le (z : ℂ × ℂ) (y : Witness.StudentRealPlane × Witness.StudentRealPlane)
    (hy1 : ‖y.1‖ ≤ 1/1000) (hy2 : ‖y.2‖ ≤ 1/1000) :
    ‖complexPairWeight (Witness.pairComplexShift (normalizedStudentPair z) y)‖ ≤
      fourierTubeConstant * pairProfile z ^ p := by
  have h1 := denominator_cpow_norm_le (normalizedStudentPair z).1 y.1 hy1
  have h2 := denominator_cpow_norm_le (normalizedStudentPair z).2 y.2 hy2
  have hP := polynomial_cpow_norm_le (normalizedStudentPair z) y hy1 hy2
  have hprod := mul_le_mul h1 h2 (norm_nonneg _) (by positivity)
  have hall := mul_le_mul hprod hP (norm_nonneg _) (by positivity)
  simp only [← norm_mul] at hall
  change ‖complexPairWeight (Witness.pairComplexShift (normalizedStudentPair z) y)‖ ≤ _ at hall
  rw [normalizedStudentPair_fst_norm_sq, normalizedStudentPair_snd_norm_sq] at hall
  calc
    _ ≤ _ := hall
    _ = _ := by
      rw [fourierTubeConstant, pairProfile_rpow_identity]
      have hpow : (1-(1/1000:ℝ)^2)^(-s*p) * (1-(1/1000:ℝ)^2)^(-s*p) =
          (1-(1/1000:ℝ)^2)^(-2*s*p) := by
        rw [← Real.rpow_add (by norm_num : (0:ℝ)<1-(1/1000:ℝ)^2)]
        congr 1
        ring
      calc
        _ = ((1-(1/1000:ℝ)^2)^(-s*p)*(1-(1/1000:ℝ)^2)^(-s*p)) *
            (1+(fourierTubeLoss:ℝ))^p *
            ((1+a*‖z.1‖^2)^(-s*p)*(1+a*‖z.2‖^2)^(-s*p)*
              (polynomial (1+a*‖z.1‖^2)⁻¹ (1+a*‖z.2‖^2)⁻¹)^p) := by ring
        _ = _ := by rw [hpow]

end UnitDistance.Sqrt241.Witness
