-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentMoments
public import UnitDistance.Sqrt241.Geometry.StudentOverlap
public import UnitDistance.Sqrt241.Geometry.GaussianMoments
public import UnitDistance.GeometryEndpointExchange
public import UnitDistance.Sqrt241.Geometry.StudentProfiles
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentMoments` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Finite second moments of the actual Student pair energy

A fractional power of the positive profile absorbs its squared logarithm.
The exact witness leaves room for a smaller Student exponent still above the
complex integrability threshold, so the proved reciprocal convolution bound
also controls the endpoint energy moments.
-/

open MeasureTheory Filter
open scoped ENNReal Topology

namespace UnitDistance.Sqrt241


namespace Witness

/-- A rational exponent strictly between the Student threshold and one. -/
noncomputable def momentPower : ℝ := (s+1)/(2*s)

theorem momentPower_bounds : 0 ≤ momentPower ∧ momentPower < 1 ∧ 1 < s*momentPower := by
  norm_num [momentPower, s]

noncomputable def pairMomentConstant : ℝ :=
  14*(2744+2/(1-momentPower)^2)*(14^momentPower)^2

/-- A pointwise estimate for the actual logarithmic energy, retaining the
actual reciprocal displacement and replacing only the decay exponent. -/
theorem pair_first_energy_sq_bound (w : ℝ × (ℂ × ℂ)) :
    (pairEnergy w.2)^2 * pairOverlapIntegrand w ≤
      pairMomentConstant * studentPairOverlap a (s*momentPower) w := by
  let x := pairProfile w.2
  let y := pairProfile (w.2+Witness.reciprocalPairStep w.1)
  let q := momentPower
  let C := 2744+2/(1-q)^2
  have hx : 0 < x := pairProfile_pos _
  have hy : 0 < y := pairProfile_pos _
  have hq0 : 0 ≤ q := momentPower_bounds.1
  have hq1 : q < 1 := momentPower_bounds.2.1
  have hlog := log_square_mul_le_fractional hx (pairProfile_le_fourteen _) hq0 hq1
  have hyfrac := bounded_profile_le_fractional hy (pairProfile_le_fourteen _) hq0 hq1.le
  have hC : 0 ≤ C := by dsimp [C]; positivity
  have hxy := mul_le_mul hlog hyfrac hy.le (mul_nonneg hC (Real.rpow_nonneg hx.le q))
  have hxg := pairProfile_rpow_le w.2 hq0
  have hyg := pairProfile_rpow_le (w.2+Witness.reciprocalPairStep w.1) hq0
  have hg (z : ℂ) : 0 ≤ studentWeight a (s*q) z := studentWeight_nonneg witness_basic.2.1.le _ _
  have hprod := mul_le_mul hxg hyg (Real.rpow_nonneg hy.le q)
    (mul_nonneg (mul_nonneg (hg _) (hg _)) (by positivity : 0 ≤ (14:ℝ)^q))
  have hcoeff : 0 ≤ 14*C := mul_nonneg (by norm_num) hC
  calc
    (pairEnergy w.2)^2 * pairOverlapIntegrand w = (-Real.log x)^2*x*y := by
      simp only [pairEnergy, pairOverlapIntegrand, x, y]
      ring
    _ ≤ (C*x^q)*(14*y^q) := hxy
    _ = (14*C)*(x^q*y^q) := by ring
    _ ≤ (14*C)*(((studentWeight a (s*q) w.2.1 * studentWeight a (s*q) w.2.2)*14^q)*
        ((studentWeight a (s*q) (w.2+Witness.reciprocalPairStep w.1).1 *
          studentWeight a (s*q) (w.2+Witness.reciprocalPairStep w.1).2)*14^q)) :=
      mul_le_mul_of_nonneg_left hprod hcoeff
    _ = pairMomentConstant * studentPairOverlap a (s*momentPower) w := by
      dsimp [pairMomentConstant, studentPairOverlap, Witness.reciprocalPairStep, q, C]
      ring

/-- The first endpoint has finite unnormalized second energy moment over
both logarithmic displacement and the two complex coordinates. -/
theorem integrable_pair_first_energy_sq_weight : Integrable (fun w : ℝ × (ℂ × ℂ) =>
    (pairEnergy w.2)^2 * pairOverlapIntegrand w) := by
  have hm : Measurable (fun w : ℝ × (ℂ × ℂ) =>
      (pairEnergy w.2)^2 * pairOverlapIntegrand w) :=
    ((measurable_pairEnergy.comp measurable_snd).pow_const 2).mul measurable_pairOverlapIntegrand
  apply ((integrable_studentPairOverlap witness_basic.2.1 momentPower_bounds.2.2).const_mul
    pairMomentConstant).mono' hm.aestronglyMeasurable
  filter_upwards with w
  rw [Real.norm_eq_abs, abs_of_nonneg
    (mul_nonneg (sq_nonneg _) (pairOverlapIntegrand_pos w).le)]
  exact pair_first_energy_sq_bound w

/-- The normalized actual pair overlap probability law. -/
noncomputable def pairOverlapLaw : Measure (ℝ × (ℂ × ℂ)) :=
  overlapLaw volume (fun w => pairEnergy w.2)
    (fun w => pairEnergy (w.2+Witness.reciprocalPairStep w.1)) pairOverlap

theorem pair_first_endpoint_memLp :
    MemLp (fun w : ℝ × (ℂ × ℂ) => pairEnergy w.2) 2 pairOverlapLaw := by
  have hm : Measurable (fun w : ℝ × (ℂ × ℂ) => pairEnergy w.2) :=
    measurable_pairEnergy.comp measurable_snd
  apply (memLp_two_iff_integrable_sq hm.aestronglyMeasurable).mpr
  have hlaw : pairOverlapLaw = (volume : Measure (ℝ × (ℂ × ℂ))).withDensity
      (fun w => ENNReal.ofReal (pairOverlapIntegrand w/pairOverlap)) := by
    unfold pairOverlapLaw overlapLaw
    simp only [pairEnergy_overlap_weight]
  rw [hlaw, integrable_withDensity_iff_integrable_smul'
    (show Measurable (fun w => ENNReal.ofReal (pairOverlapIntegrand w/pairOverlap)) from
      (measurable_pairOverlapIntegrand.div_const pairOverlap).ennreal_ofReal)
    (Filter.Eventually.of_forall (fun _ => ENNReal.ofReal_lt_top))]
  simp only [smul_eq_mul]
  apply (integrable_pair_first_energy_sq_weight.div_const pairOverlap).congr
  filter_upwards with w
  rw [ENNReal.toReal_ofReal (div_nonneg (pairOverlapIntegrand_pos w).le pairOverlap_pos.le)]
  ring

/-- The normalization uses the independently defined actual overlap integral. -/
theorem pairOverlapLaw_probability : IsProbabilityMeasure pairOverlapLaw :=
  overlapLaw_probability volume _ _ pairOverlap_pos
    integrable_pairEnergy_overlap pairEnergy_overlap_mass

/-- Both actual endpoint energies have finite second moments, and their
means and variances agree by the explicit Haar-preserving reflection. -/
theorem pair_endpoint_moments :
    MemLp (fun w : ℝ × (ℂ × ℂ) => pairEnergy w.2) 2 pairOverlapLaw ∧
    MemLp (fun w : ℝ × (ℂ × ℂ) => pairEnergy (w.2+Witness.reciprocalPairStep w.1)) 2 pairOverlapLaw ∧
    (∫ w, pairEnergy (w.2+Witness.reciprocalPairStep w.1) ∂pairOverlapLaw) =
      (∫ w, pairEnergy w.2 ∂pairOverlapLaw) ∧
    ProbabilityTheory.variance (fun w => pairEnergy (w.2+Witness.reciprocalPairStep w.1)) pairOverlapLaw =
      ProbabilityTheory.variance (fun w => pairEnergy w.2) pairOverlapLaw := by
  have hstep : Measurable Witness.reciprocalPairStep := by unfold Witness.reciprocalPairStep; fun_prop
  have hm : supportedOverlapMeasure (volume : Measure ℝ) (volume : Measure (ℂ × ℂ))
      Witness.reciprocalPairStep Set.univ = volume := by
    simp [supportedOverlapMeasure, ← Measure.volume_eq_prod]
  letI : (volume : Measure (ℂ × ℂ)).IsAddLeftInvariant := by
    rw [Measure.volume_eq_prod]
    infer_instance
  letI : (volume : Measure (ℂ × ℂ)).IsNegInvariant := by
    constructor
    exact ((Measure.measurePreserving_neg (volume : Measure ℂ)).prod
      (Measure.measurePreserving_neg (volume : Measure ℂ))).map_eq
  have h := even_supported_endpoint_moments (volume : Measure ℝ)
    (volume : Measure (ℂ × ℂ)) Witness.reciprocalPairStep hstep Set.univ MeasurableSet.univ
    (by simp) pairEnergy pairEnergy_neg pairOverlap
  simp only [hm, firstEnergy, secondEnergy] at h
  exact ⟨pair_first_endpoint_memLp, h pair_first_endpoint_memLp⟩

end Witness
end UnitDistance.Sqrt241
