-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentFourierDirection
public import UnitDistance.Sqrt241.Geometry.StudentFourierIntegrand
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentFourierDirection` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! The extremal direction in the product of the two actual Euclidean tube balls. -/

namespace UnitDistance.Sqrt241.Witness


/-- The exact positive Fourier exponent supplied by the certified radius and
the original normalization `sqrt(a)`. -/
noncomputable def studentFourierSigma : ℝ := 2*Real.pi*(1/1000)/Real.sqrt a


theorem studentFourDirection_phase (ξ : ℂ × ℂ) :
    (2*Real.pi/Real.sqrt a)*
      (∑ i, Witness.studentFourFrequency ξ i*Witness.studentFourDirection ξ i) =
        -studentFourierSigma*(‖ξ.1‖+‖ξ.2‖) := by
  rw [Witness.studentFourDirection_dot]
  unfold studentFourierSigma
  ring

end UnitDistance.Sqrt241.Witness
