-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentFourierEnvelope
public import UnitDistance.Sqrt241.Geometry.StudentFourierShift
public import UnitDistance.Sqrt241.Geometry.StudentFourierDirection
public import Mathlib.Analysis.Fourier.FourierTransform
public import UnitDistance.Sqrt241.Geometry.StudentComplexMajorant
public import UnitDistance.Sqrt241.Geometry.StudentComplexRealRestriction
public import UnitDistance.Sqrt241.Geometry.StudentFourierIntegrand
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentFourierEnvelope` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# The actual original Student Fourier envelope

The original noninteger `pairProfile^p` has the exact sum-of-coordinate-norms
Fourier decay, with its own independently defined mass and certified tube
constant. All contour and tube inputs are discharged in this theorem.
-/

open MeasureTheory FourierTransform

namespace UnitDistance.Sqrt241.Witness


theorem pairProfile_fourier_eq_studentFourIntegral (ξ : WithLp 2 (ℂ × ℂ)) :
    𝓕 (fun x : WithLp 2 (ℂ × ℂ) => ((pairProfile (WithLp.ofLp x)^p:ℝ):ℂ)) ξ =
      ∫ x, studentFourIntegrand 0 (Witness.studentFourFrequency (WithLp.ofLp ξ)) x := by
  rw [Real.fourier_eq']
  rw [← Witness.studentFourEuclideanCoordinates_measurePreserving.integral_comp']
  apply integral_congr_ae
  filter_upwards [] with x
  rw [studentFourIntegrand, Witness.studentFourKernel_frequency]
  have hw : studentFourWeight 0 x = ((pairProfile (Witness.studentFourCoordinates x)^p:ℝ):ℂ) := by
    simp only [studentFourWeight, Witness.studentFourPlanes_zero, complexPairWeight_real]
  rw [hw]
  simp only [Witness.studentFourEuclideanCoordinates_apply, WithLp.ofLp_toLp, smul_eq_mul, mul_comm]

/-- The original profile has the exact product-tube Fourier envelope, with
the published noninteger power, original mass, and certified tube constant. -/
theorem pairProfile_fourier_envelope (ξ : WithLp 2 (ℂ × ℂ)) :
    ‖𝓕 (fun x : WithLp 2 (ℂ × ℂ) => ((pairProfile (WithLp.ofLp x)^p:ℝ):ℂ)) ξ‖ ≤
      (fourierTubeConstant*pairMass)*
        Real.exp (-studentFourierSigma*(‖(WithLp.ofLp ξ).1‖+‖(WithLp.ofLp ξ).2‖)) := by
  let ζ := WithLp.ofLp ξ
  have hy := Witness.studentFourDirection_mem_tube ζ
  rw [pairProfile_fourier_eq_studentFourIntegral,
    studentFourIntegral_shift (Witness.studentFourDirection ζ) _ hy, studentFourDirection_phase]
  rw [norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
  calc
    _ ≤ Real.exp (-studentFourierSigma*(‖ζ.1‖+‖ζ.2‖))*
        (∫ x, ‖studentFourIntegrand (Witness.studentFourDirection ζ) (Witness.studentFourFrequency ζ) x‖) :=
      mul_le_mul_of_nonneg_left (norm_integral_le_integral_norm _)
        (Real.exp_pos _).le
    _ ≤ Real.exp (-studentFourierSigma*(‖ζ.1‖+‖ζ.2‖))*(fourierTubeConstant*pairMass) := by
      apply mul_le_mul_of_nonneg_left _ (Real.exp_pos _).le
      simpa only [norm_studentFourIntegrand] using integral_norm_studentFourWeight_le _ hy
    _ = _ := by ring

end UnitDistance.Sqrt241.Witness
