-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.StudentFourierIntegrand
public import UnitDistance.StudentFourierCoordinates
public import UnitDistance.StudentFourierScaling
public import UnitDistance.Sqrt241.Geometry.StudentComplexExtension
public import UnitDistance.Sqrt241.Geometry.StudentComplexIntegral
public import UnitDistance.Sqrt241.Geometry.StudentComplexMajorant
public import UnitDistance.Sqrt241.Geometry.StudentComplexRealRestriction
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.StudentFourierIntegrand` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! Integrable four-coordinate Fourier integrands on the actual complex tube. -/

open MeasureTheory

namespace UnitDistance.Sqrt241.Witness


noncomputable def studentFourWeight (y x : Fin 4 → ℝ) : ℂ :=
  complexPairWeight (Witness.pairComplexShift (normalizedStudentPair (Witness.studentFourCoordinates x))
    (Witness.studentFourPlanes y))

theorem continuous_studentFourWeight (y : Fin 4 → ℝ) (hy : Witness.studentFourTube y) :
    Continuous (studentFourWeight y) :=
  (continuous_complexPairWeight_shift (Witness.studentFourPlanes y) hy.1 hy.2).comp
    Witness.continuous_studentFourCoordinates

theorem integrable_studentFourWeight (y : Fin 4 → ℝ) (hy : Witness.studentFourTube y) :
    Integrable (studentFourWeight y) :=
  Witness.studentFourCoordinates_measurePreserving.integrable_comp_of_integrable
    (integrable_complexPairWeight_shift (Witness.studentFourPlanes y) hy.1 hy.2)

theorem integral_norm_studentFourWeight_le (y : Fin 4 → ℝ) (hy : Witness.studentFourTube y) :
    (∫ x, ‖studentFourWeight y x‖) ≤ fourierTubeConstant*pairMass := by
  unfold studentFourWeight
  rw [Witness.studentFourCoordinates_measurePreserving.integral_comp'
    (fun z => ‖complexPairWeight (Witness.pairComplexShift (normalizedStudentPair z) (Witness.studentFourPlanes y))‖)]
  exact integral_norm_complexPairWeight_shift_le _ hy.1 hy.2


noncomputable def studentFourIntegrand (y ξ x : Fin 4 → ℝ) : ℂ :=
  studentFourWeight y x * Witness.studentFourKernel ξ x

@[simp] theorem norm_studentFourIntegrand (y ξ x : Fin 4 → ℝ) :
    ‖studentFourIntegrand y ξ x‖ = ‖studentFourWeight y x‖ := by
  simp [studentFourIntegrand]

theorem integrable_studentFourIntegrand (y ξ : Fin 4 → ℝ) (hy : Witness.studentFourTube y) :
    Integrable (studentFourIntegrand y ξ) :=
  (integrable_studentFourWeight y hy).norm.mono'
    ((continuous_studentFourWeight y hy).mul
      (Witness.continuous_studentFourKernel ξ)).aestronglyMeasurable
    (Filter.Eventually.of_forall (fun _ => (norm_studentFourIntegrand _ _ _).le))

end UnitDistance.Sqrt241.Witness
