-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.TensorEnergy
public import UnitDistance.Sqrt241.Geometry.TensorFourier
public import UnitDistance.Sqrt241.Geometry.GaussianWindows
public import UnitDistance.Sqrt241.Geometry.StudentWindows
public import UnitDistance.GeometryProductWindows
public import UnitDistance.Sqrt241.Geometry.StudentProfiles
public import UnitDistance.Sqrt241.Target
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.TensorEnergy` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# The actual tensor energy and common energy window

The position energy is the literal sum of the published Gaussian and Student
logarithmic energies. Its p-th exponential is the original tensor weight.
The displacement is one in singleton coordinates and `(exp u, exp (-u))`
in every paired block. The actual common sublevel window is compact.
-/

noncomputable section
open MeasureTheory
open scoped BigOperators

namespace UnitDistance.Sqrt241.Witness

/-- The actual compact-place logarithmic energy. -/
def compactEnergy (z : ℂ) : ℝ := -Real.log (compactProfile z)

theorem compactEnergy_eq (z : ℂ) : compactEnergy z = (2*increment)*‖z‖^2 :=
  compactProfile_energy z

theorem compactEnergy_nonneg (z : ℂ) : 0 ≤ compactEnergy z := compactProfile_energy_nonneg z

theorem continuous_compactEnergy : Continuous compactEnergy := by
  simp only [show compactEnergy = (fun z : ℂ => (2*increment)*‖z‖^2) from funext compactEnergy_eq]
  fun_prop

@[simp] theorem compactEnergy_neg (z : ℂ) : compactEnergy (-z) = compactEnergy z := by
  simp only [compactEnergy_eq, norm_neg]

theorem compactEnergy_weight (q : ℝ) (z : ℂ) :
    Real.exp (-q*compactEnergy z) = compactProfile z^q := by
  have hz : 0 < compactProfile z := Real.exp_pos _
  rw [compactEnergy, Real.rpow_def_of_pos hz]
  congr 1
  ring

/-- The local energies depend only on the actual complex moduli. -/
theorem compactEnergy_eq_of_norm_eq {z w : ℂ} (h : ‖z‖ = ‖w‖) :
    compactEnergy z = compactEnergy w := by
  rw [compactEnergy_eq, compactEnergy_eq, h]

theorem pairEnergy_eq_of_norm_eq {z w : ℂ × ℂ}
    (h₁ : ‖z.1‖ = ‖w.1‖) (h₂ : ‖z.2‖ = ‖w.2‖) : pairEnergy z = pairEnergy w := by
  simp only [pairEnergy, pairProfile, h₁, h₂]

variable {β γ : Type*} [Fintype β] [Fintype γ]


/-- The literal total logarithmic energy on ordinary block coordinates. -/
def tensorPositionEnergy (x : Witness.TensorCoordinates β γ) : ℝ :=
  (∑ i, compactEnergy (x.1 i)) + ∑ j, pairEnergy (x.2 j)


theorem continuous_tensorPositionEnergy :
    Continuous (tensorPositionEnergy (β := β) (γ := γ)) := by
  unfold tensorPositionEnergy
  exact (continuous_finsetSum _ (fun i _ => continuous_compactEnergy.comp
    ((continuous_apply i).comp continuous_fst))).add
      (continuous_finsetSum _ (fun j _ => continuous_pairEnergy.comp
        ((continuous_apply j).comp continuous_snd)))


/-- The exponential of the actual summed energy is the literal product of
local powers, in particular the original Poisson weight at `q = p`. -/
theorem tensorPositionEnergy_weight (q : ℝ) (x : Witness.TensorCoordinates β γ) :
    Real.exp (-q*tensorPositionEnergy x) =
      (∏ i, compactProfile (x.1 i)^q) * ∏ j, pairProfile (x.2 j)^q := by
  unfold tensorPositionEnergy
  rw [mul_add, Real.exp_add]
  simp only [Finset.mul_sum, Real.exp_sum, compactEnergy_weight, pairEnergy_weight]

theorem tensorPositionEnergy_weight_p (x : Witness.TensorCoordinates β γ) :
    Real.exp (-p*tensorPositionEnergy x) = tensorWeight x := tensorPositionEnergy_weight p x

/-- Coordinate phases do not change the actual tensor energy. -/
theorem tensorPositionEnergy_eq_of_norm_eq {x y : Witness.TensorCoordinates β γ}
    (hc : ∀ i, ‖x.1 i‖ = ‖y.1 i‖)
    (hp₁ : ∀ j, ‖(x.2 j).1‖ = ‖(y.2 j).1‖)
    (hp₂ : ∀ j, ‖(x.2 j).2‖ = ‖(y.2 j).2‖) :
    tensorPositionEnergy x = tensorPositionEnergy y := by
  unfold tensorPositionEnergy
  congr 1
  · exact Finset.sum_congr rfl (fun i _ => compactEnergy_eq_of_norm_eq (hc i))
  · exact Finset.sum_congr rfl (fun j _ => pairEnergy_eq_of_norm_eq (hp₁ j) (hp₂ j))


theorem compactEnergy_sum_nonneg (x : β → ℂ) : 0 ≤ ∑ i, compactEnergy (x i) :=
  Finset.sum_nonneg (fun _ _ => compactEnergy_nonneg _)

theorem pairEnergy_sum_lower (x : γ → ℂ × ℂ) :
    -(Fintype.card γ : ℝ)*Real.log 14 ≤ ∑ j, pairEnergy (x j) := by
  simpa only [Finset.sum_const, Finset.card_univ, nsmul_eq_mul, mul_neg, neg_mul] using
    Finset.sum_le_sum (s := Finset.univ) (fun j _ => pairEnergy_lower (x j))


/-- Compactness concerns the actual common sublevel set of the summed energy.
The product windows occur only as a containing compact set. -/
theorem isCompact_tensorPositionEnergy_window (T : ℝ) :
    IsCompact (energyWindow (tensorPositionEnergy (β := β) (γ := γ)) T) := by
  have hc : IsCompact (energyWindow (fun x : β → ℂ => ∑ i, compactEnergy (x i))
      (T+(Fintype.card γ:ℝ)*Real.log 14)) :=
    isCompact_sum_energyWindow (fun _ : β => compactEnergy) (fun _ => continuous_compactEnergy)
      (fun _ => 0) (fun _ z => compactEnergy_nonneg z)
      (fun _ t => isCompact_compactProfile_energyWindow t) _
  have hp : IsCompact (energyWindow (fun x : γ → ℂ × ℂ => ∑ j, pairEnergy (x j)) T) :=
    isCompact_sum_energyWindow (fun _ : γ => pairEnergy) (fun _ => continuous_pairEnergy)
      (fun _ => -Real.log 14) (fun _ z => pairEnergy_lower z)
      (fun _ t => isCompact_pair_energyWindow t) _
  apply (hc.prod hp).of_isClosed_subset
    (isClosed_le continuous_tensorPositionEnergy continuous_const)
  intro x hx
  change tensorPositionEnergy x ≤ T at hx
  change (∑ i, compactEnergy (x.1 i)) ≤ T+(Fintype.card γ:ℝ)*Real.log 14 ∧
    (∑ j, pairEnergy (x.2 j)) ≤ T
  unfold tensorPositionEnergy at hx
  constructor <;> linarith [compactEnergy_sum_nonneg x.1, pairEnergy_sum_lower x.2]

end UnitDistance.Sqrt241.Witness
