-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.TensorPhaseInvariance
public import UnitDistance.Sqrt241.Geometry.TensorEnergy
public import UnitDistance.GeometryTiling
public import Mathlib.Analysis.Complex.Isometry
public import Mathlib.MeasureTheory.Measure.Haar.InnerProductSpace

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.TensorPhaseInvariance` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Phase invariance of the actual common-window overlap

Equal individual complex moduli give an explicit product of rotations.
This map preserves ordinary volume and the summed energy, so the overlap
volume depends only on displacement moduli, including zero coordinates.
-/

noncomputable section
open MeasureTheory
open scoped Classical
namespace UnitDistance.Sqrt241.Witness


variable {β γ : Type*} [Fintype β] [Fintype γ]


variable (x y : Witness.TensorCoordinates β γ)
  (hc : ∀ i, ‖x.1 i‖ = ‖y.1 i‖)
  (hp₁ : ∀ j, ‖(x.2 j).1‖ = ‖(y.2 j).1‖)
  (hp₂ : ∀ j, ‖(x.2 j).2‖ = ‖(y.2 j).2‖)


theorem tensorPositionEnergy_phase (z : Witness.TensorCoordinates β γ) :
    tensorPositionEnergy (Witness.tensorPhaseEquiv x y hc hp₁ hp₂ z) = tensorPositionEnergy z := by
  apply tensorPositionEnergy_eq_of_norm_eq
  · intro i
    exact (Witness.normRotation (x.1 i) (y.1 i) (hc i)).norm_map _
  · intro j
    exact (Witness.normRotation (x.2 j).1 (y.2 j).1 (hp₁ j)).norm_map _
  · intro j
    exact (Witness.normRotation (x.2 j).2 (y.2 j).2 (hp₂ j)).norm_map _


end UnitDistance.Sqrt241.Witness
