-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.TensorFieldCoordinates
public import UnitDistance.Sqrt241.Geometry.TensorFourier
public import UnitDistance.EuclideanIdealSeparation
public import UnitDistance.Sqrt241.Geometry.GaussianProfiles
public import UnitDistance.Sqrt241.Geometry.StudentProfiles
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.TensorFieldCoordinates` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Ordinary-volume singleton/pair coordinates for a totally complex field

An actual bijection of complex places specifies the singleton and pair blocks.
The induced continuous linear coordinates preserve ordinary Lebesgue measure
and the real Euclidean inner product. No mass or Fourier hypothesis occurs.
-/

noncomputable section
open MeasureTheory NumberField NumberField.mixedEmbedding NumberField.InfinitePlace
open scoped Classical BigOperators

namespace UnitDistance.Sqrt241.EuclideanIdeal

variable (K : Type*) [Field K] [NumberField K] [IsTotallyComplex K]
variable {β γ : Type*} [Fintype β] [Fintype γ]


/-- The literal archimedean p-th-power profile on the field's Euclidean space. -/
def archimedeanProfile (g : EuclideanIdeal.ComplexPlaces K ≃ β ⊕ (γ ⊕ γ)) : EuclideanIdeal.Space K → ℝ :=
  Witness.tensorProfile (EuclideanIdeal.tensorCoordinates K g)

theorem archimedeanProfile_pos (g : EuclideanIdeal.ComplexPlaces K ≃ β ⊕ (γ ⊕ γ)) (x : EuclideanIdeal.Space K) :
    0 < archimedeanProfile K g x := Witness.tensorProfile_pos _ _

theorem temperateGrowth_archimedeanProfile (g : EuclideanIdeal.ComplexPlaces K ≃ β ⊕ (γ ⊕ γ)) :
    (archimedeanProfile K g).HasTemperateGrowth := Witness.temperateGrowth_tensorProfile _

theorem integrable_archimedeanProfile (g : EuclideanIdeal.ComplexPlaces K ≃ β ⊕ (γ ⊕ γ)) :
    Integrable (archimedeanProfile K g) :=
  Witness.integrable_tensorProfile _ (EuclideanIdeal.tensorCoordinates_measurePreserving K g)

theorem integral_archimedeanProfile (g : EuclideanIdeal.ComplexPlaces K ≃ β ⊕ (γ ⊕ γ)) :
    (∫ x, archimedeanProfile K g x) =
      Witness.compactMass ^ Fintype.card β * Witness.pairMass ^ Fintype.card γ :=
  Witness.integral_tensorProfile _ (EuclideanIdeal.tensorCoordinates_measurePreserving K g)

theorem integral_archimedeanProfile_pos (g : EuclideanIdeal.ComplexPlaces K ≃ β ⊕ (γ ⊕ γ)) :
    0 < ∫ x, archimedeanProfile K g x := by
  rw [integral_archimedeanProfile]
  positivity [Witness.compactMass_pos, Witness.pairMass_pos]

open FourierTransform in
/-- The actual global profile satisfies the original Fourier bound with
`M = 2` and `σ = 1`, for all dimensions and all singleton/pair groupings. -/
theorem archimedeanProfile_fourier_envelope (g : EuclideanIdeal.ComplexPlaces K ≃ β ⊕ (γ ⊕ γ)) (ξ : EuclideanIdeal.Space K) :
    ‖𝓕 (fun x => ((archimedeanProfile K g x:ℝ):ℂ)) ξ‖ ≤
      ((∫ x, archimedeanProfile K g x) * 2^nrComplexPlaces K) *
        Real.exp (-EuclideanIdeal.coordinateNorm K ξ) := by
  have h := Witness.tensorProfile_fourier_envelope (EuclideanIdeal.tensorCoordinates K g)
    (EuclideanIdeal.tensorCoordinates_measurePreserving K g) (EuclideanIdeal.tensorCoordinates_inner K g) ξ
  rwa [EuclideanIdeal.tensorCoordinates_norm K g, EuclideanIdeal.tensorCoordinates_card K g,
    ← integral_archimedeanProfile K g] at h

end UnitDistance.Sqrt241.EuclideanIdeal
