-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.TensorOverlapCoordinates
public import UnitDistance.Sqrt241.Geometry.TensorEnergy
public import UnitDistance.Sqrt241.Geometry.StudentMoments
public import UnitDistance.TensorProfiles
public import UnitDistance.Sqrt241.Geometry.StudentProfiles

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.TensorOverlapCoordinates` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-!
# Ordinary endpoint coordinates and product overlap laws

Regroup logarithmic displacements together with their corresponding Student
positions. This is an actual ordinary-volume equivalence. The two elementary
measure lemmas transport overlap laws and factor two independent densities.
-/

noncomputable section
open MeasureTheory ProbabilityTheory
open scoped BigOperators ENNReal

namespace UnitDistance.Sqrt241


namespace Witness

variable {β γ : Type*} [Fintype β] [Fintype γ]


/-- The first endpoint energy after the actual regrouping. -/
def tensorFirstEnergy (w : Witness.TensorEndpointCoordinates β γ) : ℝ :=
  (∑ i, compactEnergy (w.1 i)) + ∑ j, pairEnergy (w.2 j).2

/-- The second endpoint uses the literal normalized displacement. -/
def tensorSecondEnergy (w : Witness.TensorEndpointCoordinates β γ) : ℝ :=
  (∑ i, compactEnergy (w.1 i+1)) +
    ∑ j, pairEnergy ((w.2 j).2+Witness.reciprocalPairStep (w.2 j).1)


theorem measurable_tensorFirstEnergy :
    Measurable (tensorFirstEnergy (β := β) (γ := γ)) := by
  have hc := continuous_compactEnergy.measurable
  have hp := measurable_pairEnergy
  unfold tensorFirstEnergy
  fun_prop

theorem measurable_tensorSecondEnergy :
    Measurable (tensorSecondEnergy (β := β) (γ := γ)) := by
  have hc := continuous_compactEnergy.measurable
  have hp := measurable_pairEnergy
  have hs := Witness.measurable_reciprocalPairStep
  unfold tensorSecondEnergy
  fun_prop

end Witness
end UnitDistance.Sqrt241
