-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.WitnessPeriodSeparation
public import UnitDistance.NumericalReduction
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.WitnessPeriodSeparation` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! The actual finite witness period satisfies the uniform Fourier separation
criterion. Only crude proved logarithm bounds are needed for its large margin. -/

noncomputable section
open scoped BigOperators
namespace UnitDistance.Sqrt241.Witness

/-- Normalized logarithmic volume of the actual published finite periods. -/
def periodLogDensity : ℝ :=
  ∑ v : Fin 5, (periodPower v : ℝ)*Real.log (primes v)/(ramification v : ℝ)

/-- Lower bound for a logarithm ratio from an integer power comparison. -/
private theorem log_mul_le_of_pow_le {x y : ℝ} (hx : 0 < x) (a b : ℕ) (h : x^a ≤ y^b) :
    (a : ℝ)*Real.log x ≤ (b : ℝ)*Real.log y := by
  rw [← Real.log_pow, ← Real.log_pow]
  exact Real.log_le_log (by positivity) h

/-- The ℚ lemma `24 ≤ periodLogDensity` fails for the five types
(`periodLogDensity ≈ 15.69`); comparisons with powers of two give the bound
in units of `log 2` that the separation below needs. -/
theorem periodLogDensity_lower : (1579/70 : ℝ)*Real.log 2 ≤ periodLogDensity := by
  have h3 := log_mul_le_of_pow_le (x := 2) (y := 3) (by norm_num) 19 12 (by norm_num)
  have h5 := log_mul_le_of_pow_le (x := 2) (y := 5) (by norm_num) 23 10 (by norm_num)
  have h29 := log_mul_le_of_pow_le (x := 2) (y := 29) (by norm_num) 34 7 (by norm_num)
  have h7 := log_mul_le_of_pow_le (x := 2) (y := 7) (by norm_num) 14 5 (by norm_num)
  push_cast at h3 h5 h29 h7
  norm_num [periodLogDensity, Fin.sum_univ_succ, periodPower, primes, ramification]
  linarith

theorem logRD_le : logRD ≤ (33/4 : ℝ)*Real.log 2 := by
  have h := log_mul_le_of_pow_le (x := 3615) (y := 2) (by norm_num) 1 12 (by norm_num)
  push_cast at h
  unfold logRD
  linarith

theorem logRD_le_seven : logRD ≤ 7 := by
  have h2 := log_two_precise.2
  norm_num only [div_one] at h2
  have h := logRD_le
  linarith

/-- The exact published finite periods satisfy the scalar condition with
the proved common Fourier constants `M = 2`, `sigma = 1`. -/
theorem period_fourier_separation :
    Real.log 2+2*Real.log 5+2 ≤ 2*Real.exp (periodLogDensity/2-logRD) := by
  have hH := periodLogDensity_lower
  have hL := logRD_le
  have h5 := log_mul_le_of_pow_le (x := 5) (y := 2) (by norm_num) 3 7 (by norm_num)
  push_cast at h5
  have hpos : 0 < Real.log 2 := Real.log_pos (by norm_num)
  have he := Real.add_one_le_exp (periodLogDensity/2-logRD)
  linarith

end UnitDistance.Sqrt241.Witness
