-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.
module

public import UnitDistance.WitnessLocalFunctional
public import UnitDistance.Sqrt241.FiniteFunctionalArithmetic
public import UnitDistance.LocalOperator
public import UnitDistance.LocalProduct
public import UnitDistance.Sqrt241.Witness

@[expose] public section
set_option backward.privateInPublic true

/-! Copy of `UnitDistance.WitnessLocalFunctional` for the witness `UnitDistance.Sqrt241.Witness`:
only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;
generic declarations are used from the original. -/
set_option autoImplicit false


/-! # The published finite expression is the actual local integral functional

The six rational weights are extended by zero to natural shell indices. The
finite-index sums are identified exactly, then the existing local integration
theorems evaluate the actual profile. The measured ball system and reciprocal
steps are ordinary local geometric inputs, not a unit-distance construction.
-/

noncomputable section
open MeasureTheory
open scoped BigOperators

namespace UnitDistance.Sqrt241.Witness

/-- The published six coefficients, with zero weight beyond shell five. -/
def shellWeightNat (v : Fin 5) (i : ℕ) : ℝ :=
  if h : i < 6 then (shellWeights v ⟨i, h⟩ : ℝ) else 0

@[simp] theorem shellWeightNat_fin (v : Fin 5) (i : Fin 6) :
    shellWeightNat v i = (shellWeights v i : ℝ) := by
  simp [shellWeightNat, i.isLt]

theorem shellWeightNat_nonneg (v : Fin 5) (i : ℕ) : 0 ≤ shellWeightNat v i := by
  unfold shellWeightNat
  split_ifs with hi
  · exact_mod_cast (shellWeights_pos v ⟨i, hi⟩).le
  · exact le_rfl

theorem shellSquareMass_witness (v : Fin 5) :
    Local.shellSquareMass (residueCard v) (Finset.range 6) (shellWeightNat v) =
      finiteSecond v := by
  unfold Local.shellSquareMass finiteSecond
  rw [Finset.sum_range]
  simp only [shellWeightNat_fin]

theorem shellInteraction_witness (v : Fin 5) :
    Local.shellInteraction (residueCard v) (Finset.range 6) (shellWeightNat v) =
      finiteTransition v := by
  unfold Local.shellInteraction finiteTransition
  simp_rw [Finset.sum_range, shellWeightNat_fin]

theorem shellLpMass_witness (v : Fin 5) :
    Local.shellLpMass (residueCard v) p (Finset.range 6) (shellWeightNat v) = finiteLp v := by
  unfold Local.shellLpMass finiteLp
  rw [Finset.sum_range]
  simp only [shellWeightNat_fin]

variable {G : Type*} [AddCommGroup G] [MeasurableSpace G]
    {μ : Measure G} (v : Fin 5) (B : Local.BallSystem G μ (residueCard v))

/-- The actual two-coordinate shell profile of the published witness. -/
def localShellProfile : G × G → ℝ :=
  B.shellProfile (periodPower v) (Finset.range 6 ×ˢ Finset.range 6)
    (fun ij => shellWeightNat v ij.1 * shellWeightNat v ij.2)

theorem localShellProfile_moment [SFinite μ] :
    (∫ x, localShellProfile v B x ^ p ∂μ.prod μ) =
      residueCard v ^ periodPower v * finiteLp v ^ 2 := by
  rw [localShellProfile, B.shellProfile_moment (lt_trans zero_lt_one (residueCard_gt_one v))
    _ _ _ (ne_of_gt witness_basic.2.2.1),
    Local.product_shell_moment _ _ _ _ _ _
      (fun i _ => shellWeightNat_nonneg v i) (fun i _ => shellWeightNat_nonneg v i),
    shellLpMass_witness]
  ring

variable {U : Type*} [MeasurableSpace U] (S : B.ReciprocalSteps U)
    (ν : Measure U) [IsProbabilityMeasure ν]

theorem localShellProfile_energy [MeasurableAdd₂ G] [SFinite μ] [μ.IsAddRightInvariant]
    (hs : ∀ n, Measurable (S.step n)) :
    (∫ x, localShellProfile v B x *
      B.displacementOperator S ν (localShellProfile v B) x ∂μ.prod μ) =
      residueCard v ^ periodPower v *
        (((periodPower v : ℝ) + 1) * finiteSecond v ^ 2 +
          2 * finiteSecond v * finiteTransition v) := by
  rw [localShellProfile, B.shellProfile_operator_eq S ν
    (lt_trans zero_lt_one (residueCard_gt_one v)) hs,
    Local.symmetric_product_shell_energy, shellSquareMass_witness, shellInteraction_witness]


end UnitDistance.Sqrt241.Witness
