module

public import UnitDistance.Sqrt241.Local.Caps
public import UnitDistance.Sqrt241.Base.Local41

@[expose] public section
set_option backward.privateInPublic true

/-!
# The cap element `Frob(41₁)` (version 2)

`frob41 P ∈ G_B` (`P = 0, 1` for the capped prime `41₁ = ker(ω ↦ 24)` and the uncapped
`41₂`) is the normalized image of the ℚ package's absolute Frobenius at `41`, exactly as
`frob29 P` in `Caps.lean`; labels `00111000` (28) and `00110100` (44)
(`frob41_hasLabel`). In every discrete quotient of `G_B` killing the image of inertia, the
normalized decomposition image at `41_P` is generated by `frob41 P`
(`decomposition41_range`).
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.Local

open NumberField CanonicalGenus Base UnitDistance.PrimeCompletion Multiquadratic Tower
open ProCGroups ProCGroups.ProC

attribute [local instance] PrimeCompletion.primeFact PrimeCompletion.baseRationalAlgebra

abbrev prime41 : Nat.Primes := ⟨41, by norm_num⟩

theorem isSquare_241_41 : IsSquare (241 : ℚ_[41]) :=
  ⟨iota41 sqrt241, by rw [← sq]; exact (iota_sqrt241_sq root41 root41_mul_self).symm⟩

theorem fortyone_not_mem : prime41.val ∉ ({2, 3, 5, 241} : Finset ℕ) := by decide

/-- The chosen place above `41`, restricted to `B`. -/
def emb41 : B →ₐ[ℚ] ℚ_[41] := placeEmb prime41 isSquare_241_41

open Classical in
/-- `0` if the chosen place above `41` lies over the capped prime `41₁`, else `1`. -/
def place41 : Fin 2 := if emb41 = iota41 then 0 else 1

theorem emb41_eq (P : Fin 2) (h : place41 = P) : emb41 = ![iota41, iota41'] P := by
  rcases algHom_eq_iota41_or emb41 with he | he
  · have h0 : place41 = 0 := by simp [place41, he]
    rw [← h, h0, he]
    rfl
  · by_cases h' : emb41 = iota41
    · have h0 : place41 = 0 := by simp [place41, h']
      rw [← h, h0, h']
      rfl
    · have h1 : place41 = 1 := by simp [place41, h']
      rw [← h, h1, he]
      rfl

def class41 : Fin 2 → Fin 8 → ℤ := ![squareclass41, squareclass41']
def frob41Mask : Fin 2 → ℕ := ![28, 44]
/-- The Frobenius labels at `41₁`, `41₂`. -/
def frob41Vec (P : Fin 2) : Fin 8 → ZMod 2 := RetainedQuadratic.binaryVector 8 (frob41Mask P)

theorem frob41_table : ∀ P : Fin 2,
    (∀ k, ¬((prime41.val : ℕ) : ℤ) ∣ class41 P k) ∧
    (∀ k, ((class41 P k : ℤ) : ZMod prime41.val) ^ ((prime41.val - 1) / 2) =
      binarySignInteger (frob41Vec P k)) := by
  decide +kernel

theorem sigmaMatrix_frob41Vec : ∀ P : Fin 2, sigmaMatrix (frob41Vec P) = frob41Vec (1 - P) := by
  decide +kernel

theorem frob41Vec_ne_zero : ∀ P : Fin 2, frob41Vec P ≠ 0 := by decide +kernel

theorem emb41_alpha (m : Fin 8) : ∃ z : ℚ_[41], z ≠ 0 ∧
    emb41 (alphaB m) = (class41 place41 m : ℚ_[41]) * z ^ 2 := by
  rw [alphaB_eq]
  rcases Fin.exists_fin_two.mp ⟨place41, rfl⟩ with h | h
  · rw [emb41_eq 0 h, h]
    exact iota41_alpha m
  · rw [emb41_eq 1 h, h]
    exact iota41'_alpha m

/-- The genus field is unramified at `41`. -/
theorem genus_ramificationIdxIn_41 :
    (NumberFieldAnalysis.rationalPrimeIdeal 41).ramificationIdxIn (𝓞 Carrier) = 1 :=
  Genus.ramificationIdxIn_eq_one 41 (by decide) (by decide)

/-- The absolute Frobenius at `41` (at the chosen place). -/
abbrev frob41Abs : AbsoluteDecomposition prime41 := absFrob prime41

theorem frob41Abs_hasLabel : HasLabel frob41Abs.val (frob41Vec place41) := by
  obtain ⟨hunit, hsv⟩ := frob41_table place41
  obtain ⟨d, hd⟩ := exists_absolute_frobenius_split prime41 isSquare_241_41 (by decide)
    (class41 place41) emb41_alpha hunit (frob41Vec place41) hsv
    CanonicalGenus.Carrier CanonicalGenus.field.val (fun k => ⟨Genus.gE k, rfl⟩)
  exact frobenius_label_of_split prime41 isSquare_241_41 genus_ramificationIdxIn_41
    (frob41Vec_ne_zero place41) d hd

/-- The normalized decomposition map at `41_P`. -/
def decomposition41 (P : Fin 2) : AbsoluteDecomposition prime41 →ₜ* GB :=
  localMapB prime41 isSquare_241_41 place41 P

/-- **`Frob(41_P)` ∈ G_B.** -/
def frob41 (P : Fin 2) : GB := decomposition41 P frob41Abs

theorem frob41_hasLabel (P : Fin 2) : HasLabelHat (frob41 P) (frob41Vec P) := by
  have h := localMapB_hasLabel prime41 isSquare_241_41 place41 P frob41Abs frob41Abs_hasLabel
  by_cases hP : P = place41
  · have e : ∀ a b : Fin 8 → ZMod 2, (if P = place41 then a else b) = a :=
      fun a b => by simp [hP]
    rw [e] at h
    rw [show frob41Vec P = frob41Vec place41 by rw [hP]]
    exact h
  · have e : ∀ a b : Fin 8 → ZMod 2, (if P = place41 then a else b) = b :=
      fun a b => by simp [hP]
    rw [e, sigmaMatrix_frob41Vec, fin2_one_sub_of_ne hP] at h
    exact h

/-- At `41_P`: if the discrete quotient kills inertia, the (normalized) decomposition image is
`⟨Frob(41_P)⟩`. -/
theorem decomposition41_range (P : Fin 2) {H : Type*} [Group H] [TopologicalSpace H]
    [DiscreteTopology H] (q : GB →ₜ* H)
    (hI : ∀ σ : AbsoluteInertia prime41, q (decomposition41 P σ.val) = 1) :
    (q.comp (decomposition41 P)).toMonoidHom.range = Subgroup.zpowers (q (frob41 P)) :=
  range_eq_zpowers_of_inertia prime41 (q.comp (decomposition41 P)) hI

end UnitDistance.Sqrt241.Local
