module

public import UnitDistance.Sqrt241.Local.Caps
public import UnitDistance.Sqrt241.Local.Unramified

@[expose] public section
set_option backward.privateInPublic true

/-!
# Decomposition images at `29` and `7` in every discrete quotient

With `inertia_killed` (`Unramified.lean`), the decomposition images at `7` and at `29_P`
are generated by `F₇` resp. `Frob(29_P)` in every discrete quotient of `Ĝ` resp. `G_B`
(`decomposition7_range'`, `decomposition29_range'`), unconditionally.
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.Local

open Tower UnitDistance.PrimeCompletion

attribute [local instance] PrimeCompletion.primeFact PrimeCompletion.baseRationalAlgebra

theorem seven_not_mem : prime7.val ∉ ({2, 3, 5, 241} : Finset ℕ) := by decide

theorem twentynine_not_mem : prime29.val ∉ ({2, 3, 5, 241} : Finset ℕ) := by decide

/-- **At 7**: in every discrete quotient of `Ĝ`, the decomposition image is `⟨F₇⟩`. -/
theorem decomposition7_range' {H : Type*} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    (q : Ghat →ₜ* H) :
    (q.comp (decompositionMap prime7)).toMonoidHom.range = Subgroup.zpowers (q frob7) :=
  decomposition7_range q (fun σ => by rw [inertia_killed prime7 seven_not_mem σ, map_one])

/-- **At `29_P`**: in every discrete quotient of `G_B`, the normalized decomposition image is
`⟨Frob(29_P)⟩`. -/
theorem decomposition29_range' (P : Fin 2) {H : Type*} [Group H] [TopologicalSpace H]
    [DiscreteTopology H] (q : GB →ₜ* H) :
    (q.comp (decomposition29 P)).toMonoidHom.range = Subgroup.zpowers (q (frob29 P)) :=
  decomposition29_range P q (fun σ => by
    rw [decomposition29, inertia_killed_B prime29 twentynine_not_mem isSquare_241_29 place29 P σ,
      map_one])

/-- **Any prime `p ∉ {2, 3, 5, 241}`**: in every discrete quotient of `Ĝ`, the image of the
chosen decomposition group is generated by the image of the absolute Frobenius. -/
theorem decomposition_range_unramified (p : Nat.Primes) (hp : p.val ∉ ({2, 3, 5, 241} : Finset ℕ))
    {H : Type*} [Group H] [TopologicalSpace H] [DiscreteTopology H] (q : Ghat →ₜ* H) :
    (q.comp (decompositionMap p)).toMonoidHom.range =
      Subgroup.zpowers (q (decompositionMap p (absFrob p))) :=
  range_eq_zpowers_of_inertia p (q.comp (decompositionMap p))
    (fun σ => by
      change q (decompositionMap p σ.val) = 1
      rw [inertia_killed p hp σ, map_one])

end UnitDistance.Sqrt241.Local
