module

public import UnitDistance.Sqrt241.Local.Frobenius
public import UnitDistance.Sqrt241.Local.FrobeniusLocal

@[expose] public section
set_option backward.privateInPublic true

/-!
# The cap elements `Frob(29₁)`, `Frob(29₂)`, `F₇`

* `frob29 P ∈ G_B` (`P = 0, 1` for `29₁ = (π₂₉)`, `29₂ = (π₂₉')`) is the normalized image
  of the ℚ package's absolute Frobenius at `29`; labels `00100111` (228) and
  `00011011` (216) (`frob29_hasLabel`).
* `frob7 ∈ Ĝ` is the image of the absolute Frobenius at `7`: `frob7 ∉ G_B`,
  `frob7 ^ 2 ∈ G_B` with label `01110000` (14) (`frob7_not_mem`, `frob7_sq_hasLabel`).
* In every discrete quotient of `Ĝ` killing the image of inertia, the decomposition
  image at `29` (normalized, either prime) resp. `7` is generated by `frob29 P`
  resp. `frob7` (`decomposition29_range`, `decomposition7_range`).
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.Local

open NumberField CanonicalGenus Base UnitDistance.PrimeCompletion Multiquadratic Tower
open ProCGroups ProCGroups.ProC

attribute [local instance] PrimeCompletion.primeFact PrimeCompletion.baseRationalAlgebra

/-! ## The prime 29 -/

abbrev prime29 : Nat.Primes := ⟨29, by norm_num⟩

/-- The chosen place above `29`, restricted to `B`. -/
def emb29 : B →ₐ[ℚ] ℚ_[29] := placeEmb prime29 isSquare_241_29

open Classical in
/-- `0` if the chosen place above `29` lies over `29₁ = (π₂₉)`, else `1`. -/
def place29 : Fin 2 := if emb29 = iota29 then 0 else 1

theorem emb29_eq (P : Fin 2) (h : place29 = P) : emb29 = ![iota29, iota29'] P := by
  rcases algHom_eq_iota29_or emb29 with he | he
  · have h0 : place29 = 0 := by simp [place29, he]
    rw [← h, h0, he]
    rfl
  · by_cases h' : emb29 = iota29
    · have h0 : place29 = 0 := by simp [place29, h']
      rw [← h, h0, h']
      rfl
    · have h1 : place29 = 1 := by simp [place29, h']
      rw [← h, h1, he]
      rfl

def class29 : Fin 2 → Fin 8 → ℤ := ![squareclass29, squareclass29']
def frob29Mask : Fin 2 → ℕ := ![228, 216]
/-- The Frobenius labels at `29₁`, `29₂`. -/
def frob29Vec (P : Fin 2) : Fin 8 → ZMod 2 := RetainedQuadratic.binaryVector 8 (frob29Mask P)

theorem frob29_table : ∀ P : Fin 2,
    (∀ k, ¬((prime29.val : ℕ) : ℤ) ∣ class29 P k) ∧
    (∀ k, ((class29 P k : ℤ) : ZMod prime29.val) ^ ((prime29.val - 1) / 2) =
      binarySignInteger (frob29Vec P k)) := by
  decide +kernel

theorem sigmaMatrix_frob29Vec : ∀ P : Fin 2, sigmaMatrix (frob29Vec P) = frob29Vec (1 - P) := by
  decide +kernel

theorem frob29Vec_ne_zero : ∀ P : Fin 2, frob29Vec P ≠ 0 := by decide +kernel

theorem emb29_alpha (m : Fin 8) : ∃ z : ℚ_[29], z ≠ 0 ∧
    emb29 (alphaB m) = (class29 place29 m : ℚ_[29]) * z ^ 2 := by
  rw [alphaB_eq]
  rcases Fin.exists_fin_two.mp ⟨place29, rfl⟩ with h | h
  · rw [emb29_eq 0 h, h]
    exact iota29_alpha m
  · rw [emb29_eq 1 h, h]
    exact iota29'_alpha m

/-- The absolute Frobenius at `29` (at the chosen place). -/
abbrev frob29Abs : AbsoluteDecomposition prime29 := absFrob prime29

theorem frob29Abs_hasLabel : HasLabel frob29Abs.val (frob29Vec place29) := by
  obtain ⟨hunit, hsv⟩ := frob29_table place29
  obtain ⟨d, hd⟩ := exists_absolute_frobenius_split prime29 isSquare_241_29 (by decide)
    (class29 place29) emb29_alpha hunit (frob29Vec place29) hsv
    CanonicalGenus.Carrier CanonicalGenus.field.val (fun k => ⟨Genus.gE k, rfl⟩)
  exact frobenius_label_of_split prime29 isSquare_241_29 Genus.ramificationIdxIn_29
    (frob29Vec_ne_zero place29) d hd

/-- The normalized decomposition map at `29_P`. -/
def decomposition29 (P : Fin 2) : AbsoluteDecomposition prime29 →ₜ* GB :=
  localMapB prime29 isSquare_241_29 place29 P

/-- **`Frob(29_P)` ∈ G_B.** -/
def frob29 (P : Fin 2) : GB := decomposition29 P frob29Abs

theorem frob29_hasLabel (P : Fin 2) : HasLabelHat (frob29 P) (frob29Vec P) := by
  have h := localMapB_hasLabel prime29 isSquare_241_29 place29 P frob29Abs frob29Abs_hasLabel
  by_cases hP : P = place29
  · have e : ∀ a b : Fin 8 → ZMod 2, (if P = place29 then a else b) = a :=
      fun a b => by simp [hP]
    rw [e] at h
    rw [show frob29Vec P = frob29Vec place29 by rw [hP]]
    exact h
  · have e : ∀ a b : Fin 8 → ZMod 2, (if P = place29 then a else b) = b :=
      fun a b => by simp [hP]
    rw [e, sigmaMatrix_frob29Vec, fin2_one_sub_of_ne hP] at h
    exact h

/-! ## The prime 7 -/

/-- The absolute Frobenius at `7`. -/
abbrev frob7Abs : AbsoluteDecomposition prime7 := absFrob prime7

theorem frob7Abs_spec : frob7Abs.val baseRoot = -baseRoot ∧ HasLabel (frob7Abs.val ^ 2) Base.frob7 := by
  obtain ⟨d, hd1, hd2⟩ := exists_absolute_frobenius_seven CanonicalGenus.Carrier
    CanonicalGenus.field.val (fun k => ⟨Genus.gE k, rfl⟩) ⟨Genus.bE, rfl⟩
  exact frobenius_label_of_inert prime7 Genus.ramificationIdxIn_7 d hd1 hd2

/-- **`F₇ ∈ Ĝ`**, the image of the absolute Frobenius at `7`. -/
def frob7 : Ghat := decompositionMap prime7 frob7Abs

theorem frob7_not_mem : frob7 ∉ GB :=
  (toGhat_not_mem_GB_iff _).mpr frob7Abs_spec.1

theorem frob7_sq_mem : frob7 ^ 2 ∈ GB := by
  rw [frob7, decompositionMap_apply, ← map_pow, toGhat_mem_GB_iff]
  change (frob7Abs.val * frob7Abs.val) baseRoot = baseRoot
  rw [AlgEquiv.mul_apply, frob7Abs_spec.1, map_neg, frob7Abs_spec.1, neg_neg]

theorem frob7Vec_eq : Base.frob7 = RetainedQuadratic.binaryVector 8 14 := by decide +kernel

theorem frob7_sq_hasLabel : HasLabelHat (frob7 ^ 2) (RetainedQuadratic.binaryVector 8 14) :=
  ⟨frob7Abs.val ^ 2, by rw [map_pow]; rfl, frob7Vec_eq ▸ frob7Abs_spec.2⟩

theorem sigmaMatrix_frob7 : sigmaMatrix (RetainedQuadratic.binaryVector 8 14) =
    RetainedQuadratic.binaryVector 8 14 := by decide +kernel

/-! ## Decomposition images in discrete quotients -/

/-- At `7`: if the discrete quotient kills inertia, the decomposition image is `⟨F₇⟩`. -/
theorem decomposition7_range {H : Type*} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    (q : Ghat →ₜ* H) (hI : ∀ σ : AbsoluteInertia prime7, q (decompositionMap prime7 σ.val) = 1) :
    (q.comp (decompositionMap prime7)).toMonoidHom.range = Subgroup.zpowers (q frob7) :=
  range_eq_zpowers_of_inertia prime7 (q.comp (decompositionMap prime7)) hI

/-- At `29_P`: if the discrete quotient kills inertia, the (normalized) decomposition image is
`⟨Frob(29_P)⟩`. -/
theorem decomposition29_range (P : Fin 2) {H : Type*} [Group H] [TopologicalSpace H]
    [DiscreteTopology H] (q : GB →ₜ* H)
    (hI : ∀ σ : AbsoluteInertia prime29, q (decomposition29 P σ.val) = 1) :
    (q.comp (decomposition29 P)).toMonoidHom.range = Subgroup.zpowers (q (frob29 P)) :=
  range_eq_zpowers_of_inertia prime29 (q.comp (decomposition29 P)) hI

end UnitDistance.Sqrt241.Local
