module

public import UnitDistance.Sqrt241.Local.TamePairs
public import UnitDistance.SigmaUnramifiedFrobenius
public import UnitDistance.AbsolutePrimeIndices
public import UnitDistance.Sqrt241.Genus.ExactTypes

@[expose] public section
set_option backward.privateInPublic true

/-!
# Frobenius elements at the unramified primes `29` (split) and `7` (inert): generation

The ℚ package's absolute Frobenius `SigmaUnramified.absoluteFrobenius p` (arithmetic
residue degree one) generates the image of the whole chosen decomposition group in
every discrete quotient that kills inertia (`image_zpowers_of_inertia`), the
generalization of `SigmaUnramified.decomposition_image_zpowers` to arbitrary targets.

Its genus labels are found by the "exponent-two trick" of the ℚ package
(`ExtraPrime.sigmaFrobenius_genus`): restriction to the canonical genus field `E`
kills inertia at `29` and `7` (`e_E = 1`, `Genus.ExactTypes`), so the restriction of
any labelled element of the decomposition group is a power of the restriction of the
Frobenius; the automorphisms of `E` fixing `√241` have order `≤ 2`
(`frobenius_label_of_split`, `frobenius_label_of_inert`).
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.Local

open NumberField CanonicalGenus Base UnitDistance.PrimeCompletion Multiquadratic Tower
open ProCGroups ProCGroups.ProC ClassFieldTower.Martinet.Shafarevich
open LocalClassFieldTheory ClassFormation ClassFieldTower.Cohomology.ProfiniteInteger

attribute [local instance] PrimeCompletion.primeFact PrimeCompletion.baseRationalAlgebra

/-! ## The unramified quotient is generated by the Frobenius -/

/-- The absolute Frobenius at `p` (the ℚ package's `SigmaUnramified.absoluteFrobenius`). -/
abbrev absFrob (p : Nat.Primes) : AbsoluteDecomposition p := SigmaUnramified.absoluteFrobenius p

section Generation

variable (p : Nat.Primes) {H : Type*} [Group H] [TopologicalSpace H] [DiscreteTopology H]
  (f : AbsoluteDecomposition p →ₜ* H) (hf : ∀ σ : AbsoluteInertia p, f σ.val = 1)

/-- `f` read on the local absolute Galois group. -/
def localOf : Gal(SeparableClosure (Base p)/Base p) →ₜ* H :=
  f.comp ⟨(decompositionEquiv p).symm.toMulEquiv.toMonoidHom, (decompositionEquiv p).symm.continuous⟩

omit [DiscreteTopology H] in
include hf in
theorem localOf_ker_le :
    (localResidueDegree (Base p)).toMonoidHom.ker ≤ (localOf p f).toMonoidHom.ker := by
  intro σ hσ
  have hi : (decompositionEquiv p).symm σ ∈ AbsoluteInertia p := by
    apply (decomposition_mem_inertia_iff p _).mp
    simpa using hσ
  exact hf ⟨_, hi⟩

include hf in
/-- The factorization of `f` through the arithmetic residue degree. -/
def residueFactorOf : ZHatMul →ₜ* H :=
  (ProCGroups.QuotientGroup.liftₜ (localResidueDegree (Base p)).toMonoidHom.ker
    (localOf p f) (localOf_ker_le p f hf)).comp
      ⟨(localUnramifiedQuotientContinuousMulEquiv (Base p)).symm.toMulEquiv.toMonoidHom,
        (localUnramifiedQuotientContinuousMulEquiv (Base p)).symm.continuous⟩

include hf in
theorem residueFactorOf_degree (σ : Gal(SeparableClosure (Base p)/Base p)) :
    residueFactorOf p f hf (localResidueDegree (Base p) σ) = localOf p f σ := by
  have h : localResidueDegree (Base p) σ =
      localUnramifiedQuotientContinuousMulEquiv (Base p)
        (QuotientGroup.mk' (localResidueDegree (Base p)).toMonoidHom.ker σ) := rfl
  rw [h]
  change ProCGroups.QuotientGroup.liftₜ (localResidueDegree (Base p)).toMonoidHom.ker
    (localOf p f) (localOf_ker_le p f hf)
    ((localUnramifiedQuotientContinuousMulEquiv (Base p)).symm
      (localUnramifiedQuotientContinuousMulEquiv (Base p) _)) = _
  rw [ContinuousMulEquiv.symm_apply_apply]
  rfl

include hf in
theorem residueFactorOf_generator :
    residueFactorOf p f hf generator = f (absFrob p) := by
  rw [← SigmaUnramified.localFrobenius_degree p, residueFactorOf_degree]
  rfl

include hf in
/-- **Generation.** In a discrete quotient killing inertia, the image of the chosen
decomposition group is generated by the image of the Frobenius. -/
theorem image_zpowers_of_inertia (d : AbsoluteDecomposition p) :
    f d ∈ Subgroup.zpowers (f (absFrob p)) := by
  have h := SigmaUnramified.profiniteInteger_image_zpowers (residueFactorOf p f hf)
    (localResidueDegree (Base p) (decompositionEquiv p d))
  rw [residueFactorOf_degree, residueFactorOf_generator] at h
  change f ((decompositionEquiv p).symm (decompositionEquiv p d)) ∈ _ at h
  simpa only [ContinuousMulEquiv.symm_apply_apply] using h

include hf in
theorem range_eq_zpowers_of_inertia :
    f.toMonoidHom.range = Subgroup.zpowers (f (absFrob p)) := by
  apply le_antisymm
  · rintro _ ⟨d, rfl⟩
    exact image_zpowers_of_inertia p f hf d
  · apply Subgroup.zpowers_le.mpr
    exact ⟨absFrob p, rfl⟩

end Generation

/-! ## Restriction to the genus field kills unramified inertia -/

/-- Restriction of the chosen decomposition group to the canonical genus field. -/
def genusRestrictionD (p : Nat.Primes) : AbsoluteDecomposition p →ₜ* Gal(CanonicalGenus.Carrier/ℚ) :=
  genusRestriction.comp ⟨(AbsoluteDecomposition p).subtype, continuous_subtype_val⟩

theorem genusRestrictionD_apply (p : Nat.Primes) (d : AbsoluteDecomposition p) (x : Carrier) :
    ((genusRestrictionD p d x : Carrier) : Closure) = d.val (x : Closure) :=
  GaloisEmbedding.restriction_commutes CanonicalGenus.field.val d.val x

theorem genusRestrictionD_inertia (p : Nat.Primes)
    (he : (NumberFieldAnalysis.rationalPrimeIdeal p.val).ramificationIdxIn (𝓞 Carrier) = 1)
    (σ : AbsoluteInertia p) : genusRestrictionD p σ.val = 1 := by
  have hcard := inertiaRestriction_card p Carrier CanonicalGenus.field.val
  rw [he] at hcard
  have hbot := Subgroup.eq_bot_of_card_eq _ hcard
  have hmem : inertiaRestriction p Carrier CanonicalGenus.field.val σ ∈
      (inertiaRestriction p Carrier CanonicalGenus.field.val).range := ⟨σ, rfl⟩
  rw [hbot, Subgroup.mem_bot] at hmem
  exact hmem

/-! ## The exponent-two trick -/

theorem hasLabel_of_genusRestrictionD_eq (p : Nat.Primes) {d e : AbsoluteDecomposition p}
    (h : genusRestrictionD p d = genusRestrictionD p e) {v : Fin 8 → ZMod 2}
    (hd : HasLabel d.val v) : HasLabel e.val v := by
  intro k
  have he := genusRestrictionD_apply p e (Genus.gE k)
  have hd' := genusRestrictionD_apply p d (Genus.gE k)
  rw [Genus.coe_gE] at he hd'
  rw [← he, ← h, hd']
  exact hd k

/-- At a split unramified prime, the Frobenius has the label of any labelled element with
nonzero label. -/
theorem frobenius_label_of_split (p : Nat.Primes) (hsq : IsSquare (241 : ℚ_[p.val]))
    (he : (NumberFieldAnalysis.rationalPrimeIdeal p.val).ramificationIdxIn (𝓞 Carrier) = 1)
    {v : Fin 8 → ZMod 2} (hv : v ≠ 0) (d : AbsoluteDecomposition p) (hd : HasLabel d.val v) :
    HasLabel (absFrob p).val v := by
  have hmem := image_zpowers_of_inertia p (genusRestrictionD p)
    (genusRestrictionD_inertia p he) d
  set g := genusRestrictionD p (absFrob p)
  have hgb : g Genus.bE = Genus.bE := by
    apply Subtype.ext
    rw [genusRestrictionD_apply]
    exact decomposition_fixes_baseRoot p hsq _
  have hg2 : g ^ 2 = 1 := by rw [sq]; exact Genus.aut_sq_eq_one g hgb
  obtain ⟨n, hn⟩ := hmem
  change g ^ n = _ at hn
  have hsplit : g ^ n = (g ^ 2) ^ (n / 2) * g ^ (n % 2) := by
    rw [← zpow_natCast g 2, ← zpow_mul, ← zpow_add, Nat.cast_ofNat, Int.mul_ediv_add_emod]
  have hcases : genusRestrictionD p d = 1 ∨ genusRestrictionD p d = g := by
    rw [← hn, hsplit, hg2, one_zpow, one_mul]
    rcases Int.emod_two_eq_zero_or_one n with h0 | h1
    · left
      rw [h0, zpow_zero]
    · right
      rw [h1, zpow_one]
  rcases hcases with h1 | hg
  · exfalso
    apply hv
    have h0 : HasLabel d.val 0 := by
      intro k
      have h2 := genusRestrictionD_apply p d (Genus.gE k)
      rw [Genus.coe_gE, h1] at h2
      rw [← h2]
      simp
    exact hd.unique h0
  · exact hasLabel_of_genusRestrictionD_eq p hg hd

/-- At an inert unramified prime, the Frobenius moves `√241`, and its square has the label
of the square of any element moving `√241`. -/
theorem frobenius_label_of_inert (p : Nat.Primes)
    (he : (NumberFieldAnalysis.rationalPrimeIdeal p.val).ramificationIdxIn (𝓞 Carrier) = 1)
    (d : AbsoluteDecomposition p) (hd1 : d.val baseRoot = -baseRoot)
    {v : Fin 8 → ZMod 2} (hd2 : HasLabel (d.val ^ 2) v) :
    (absFrob p).val baseRoot = -baseRoot ∧ HasLabel ((absFrob p).val ^ 2) v := by
  have hmem := image_zpowers_of_inertia p (genusRestrictionD p)
    (genusRestrictionD_inertia p he) d
  set g := genusRestrictionD p (absFrob p)
  have hdb : genusRestrictionD p d Genus.bE = -Genus.bE := by
    apply Subtype.ext
    rw [genusRestrictionD_apply]
    simpa using hd1
  have hg4 : (g ^ 2) ^ 2 = 1 := by rw [← pow_mul]; exact Genus.aut_pow_four g
  have hg2b : (g ^ 2) Genus.bE = Genus.bE := by rw [sq]; exact Genus.aut_sq_bE g
  have hpowfix (m : ℤ) : ((g ^ 2) ^ m) Genus.bE = Genus.bE := by
    have : g ^ 2 ∈ MulAction.stabilizer (Gal(Carrier/ℚ)) Genus.bE := hg2b
    exact (Subgroup.zpow_mem _ this m : (g ^ 2) ^ m ∈ MulAction.stabilizer _ Genus.bE)
  obtain ⟨n, hn⟩ := hmem
  change g ^ n = _ at hn
  have hsplit : g ^ n = (g ^ 2) ^ (n / 2) * g ^ (n % 2) := by
    rw [← zpow_natCast g 2, ← zpow_mul, ← zpow_add, Nat.cast_ofNat, Int.mul_ediv_add_emod]
  have hodd : n % 2 = 1 := by
    rcases Int.emod_two_eq_zero_or_one n with h0 | h1
    · exfalso
      have hfix : (g ^ n) Genus.bE = Genus.bE := by
        rw [hsplit, h0, zpow_zero, mul_one]
        exact hpowfix _
      rw [hn] at hfix
      rw [hfix] at hdb
      have h2 : (2 : Carrier) * Genus.bE = 0 := by linear_combination hdb
      exact (mul_ne_zero two_ne_zero Genus.bE_ne_zero) h2
    · exact h1
  have hgd : genusRestrictionD p d = (g ^ 2) ^ (n / 2) * g := by
    rw [← hn, hsplit, hodd, zpow_one]
  refine ⟨?_, ?_⟩
  · -- g moves √241
    have hgb : g Genus.bE = -Genus.bE := by
      rcases Genus.aut_bE g with h | h
      · exfalso
        have : genusRestrictionD p d Genus.bE = Genus.bE := by
          rw [hgd, AlgEquiv.mul_apply, h, hpowfix]
        rw [this] at hdb
        have h2 : (2 : Carrier) * Genus.bE = 0 := by linear_combination hdb
        exact (mul_ne_zero two_ne_zero Genus.bE_ne_zero) h2
      · exact h
    have h' := congrArg (fun x : Carrier => (x : Closure)) hgb
    simp only [g, genusRestrictionD_apply] at h'
    simpa using h'
  · -- the squares agree on E
    have hcomm : Commute ((g ^ 2) ^ (n / 2)) g := ((Commute.refl g).pow_left 2).zpow_left (n / 2)
    have hsq : (genusRestrictionD p d) ^ 2 = g ^ 2 := by
      rw [hgd, hcomm.mul_pow, ← zpow_natCast ((g ^ 2) ^ (n / 2)) 2, ← zpow_mul, mul_comm,
        zpow_mul, zpow_natCast, hg4, one_zpow, one_mul]
    intro k
    have hk := hd2 k
    have h1 := genusRestrictionD_apply p (absFrob p ^ 2) (Genus.gE k)
    have h2 := genusRestrictionD_apply p (d ^ 2) (Genus.gE k)
    rw [Genus.coe_gE] at h1 h2
    change (absFrob p ^ 2).val (genusRoot k) = _
    rw [← h1, map_pow, ← hsq, ← map_pow, h2]
    exact hk

end UnitDistance.Sqrt241.Local
