#!/usr/bin/env python3
"""Split exact rational certificates; generated arithmetic remains checked by Lean."""
from pathlib import Path
import re
from fractions import Fraction
ROOT=Path(__file__).resolve().parents[3]
def table(name,file,count):
    txt=(ROOT/'UnitDistance'/file).read_text().split('def '+name+' ',1)[1].split('\ndef ',1)[0]
    vals=re.findall(r'\((-?\d+) : ℚ\) / (\d+)',txt)
    assert len(vals)==count,(name,len(vals))
    return vals
b=table('pairMassBracketScalarTableQ3','PairMassDegree3DenseData.lean',256)
c=table('pairMassPowerContractionTable3','PairMassDegree3DenseData.lean',1024)
d=table('pairMassContractionCoefficient3','PairMassDegree3Data.lean',256)
def val(p): return Fraction(int(p[0]),int(p[1]))
def lit(p): return f'(({p[0]} : ℚ) / {p[1]})'
def expr(i,j,s,t):
    return ' +\n    '.join(f'pairMassBracketScalarDataQ3 {r} {i} {j} * pairMassPowerContractionData3 {r} {i} {j} {s} {t}' for r in range(4))
text='''import UnitDistance.PairMassDegree3DenseData

/-! Exact scalar certificates for the degree-three dense pair-mass table.
Generated by verification/astra-sol-20260920b/root/generate_pair_mass_scalar.py.
Each table lookup is converted definitionally to rational literals, then
`norm_num` produces a proof of the scalar equality. There is no native evaluation.
Splitting the certificate avoids a monolithic table reduction in independent
kernel replay. The numerical inputs are the existing attributed repository data.
-/
namespace UnitDistance.Witness
set_option maxHeartbeats 1000000000
set_option maxRecDepth 100000

'''
names=[]
for i in range(8):
 for j in range(8):
  for s in range(2):
   for t in range(2):
    bs=[b[(r*8+i)*8+j] for r in range(4)]
    cs=[c[(((r*8+i)*8+j)*2+s)*2+t] for r in range(4)]
    rhs=d[((i*8+j)*2+s)*2+t]
    assert sum(val(x)*val(y) for x,y in zip(bs,cs))==val(rhs),(i,j,s,t)
    name=f'pairMassScalarRun20260920b_{i}_{j}_{s}_{t}'
    names.append(name)
    text+=f'private theorem {name} :\n    {expr(i,j,s,t)} = pairMassContractionCoefficient3 {i} {j} {s} {t} := by\n'
    numeric=' +\n    '.join(f'{lit(x)} * {lit(y)}' for x,y in zip(bs,cs))
    text+='  change '+numeric+' = '+lit(rhs)+'\n  norm_num\n\n'
text+='theorem pairMassScalarCoefficients3_eq_declared (i j : Fin 8) (s t : Fin 2) :\n    '+expr('i','j','s','t')+' = pairMassContractionCoefficient3 i j s t := by\n'
text+='  fin_cases i <;> fin_cases j <;> fin_cases s <;> fin_cases t\n'
text+=''.join(f'  · exact {n}\n' for n in names)
text+='\nend UnitDistance.Witness\n'
(ROOT/'UnitDistance/PairMassDegree3ScalarCertificateRun20260920b.lean').write_text(text)
print('Generated 256 individually checked scalar candidates')
