-- Generated by scripts/sqrt241/generate_dyadic_certificate.py — do not edit by hand.
module

public import UnitDistance.Sqrt241.Discriminant.Horner
public import Mathlib.Algebra.QuadraticAlgebra.Basic
public import Mathlib.Tactic.NormNum

@[expose] public section
set_option backward.privateInPublic true


/-!
# The dyadic certificate: an explicit model of `ℚ(√241, √2, √π₂', √β₁)`

`M4 = ℚ[r, t, g, s]` with `r² = 241`, `t² = 2`, `g² = π₂'(r) = (6101 - 393 r)/2` and
`s² = β₁ = (-25 + 2r) + (-139 - 9r) g`, as nested `QuadraticAlgebra`s over `ℚ`
(coordinates with respect to `r^a t^b g^c s^d`, index `a + 2b + 4c + 8d`).

In the number field `F = ℚ(r, t, g, s)` (degree 16) the prime above
`𝔭₁ = (π₂)`, `π₂ = (-6101 - 393 r)/2`, is unique, with `e = 8`, `f = 1` and
different exponent `18` (PARI). It is principal, generated by `y = yM`
(norm `2`). The data below are kernel-checked:

* `f_yM`: `f(y) = 0` for the monic integer polynomial `f = fL` (the characteristic
  polynomial of `y`);
* `u_yM`: `π₂ · u = y⁸` for the explicit unit `u = uM`, and `h_uM`: `h(u) = 0` for the
  monic integer polynomial `h = hL` (so `u` is integral and every prime containing `π₂`
  contains `y`);
* `f_split`: `f = X⁸ G + 2 Kp` with `Kp(0) = 1` (so `2 ∈ (y)⁸ ⋅ unit` at the prime `(y)`);
* `f_deriv`: `f' = X¹⁸ Z + f W` with `Z(0)` odd (so `v(f'(y)) = 18` at `(y)`).

Generated by `scripts/sqrt241/generate_dyadic_certificate.py` from
`scripts/sqrt241/dyadic_certificate.gp`.
-/

noncomputable section

namespace UnitDistance.Sqrt241.Discriminant.Dyadic

open UnitDistance.Sqrt241.Discriminant

/-- `ℚ(√241)`, generator `r`. -/
abbrev M1 := QuadraticAlgebra ℚ 241 0
/-- `ℚ(r, √2)`, generator `t`. -/
abbrev M2 := QuadraticAlgebra M1 2 0
/-- `π₂' = (6101 - 393 r)/2` in `M2`. -/
def pi2pM : M2 := ⟨⟨6101 / 2, -393 / 2⟩, 0⟩
/-- `ℚ(r, t, √π₂')`, generator `g`. -/
abbrev M3 := QuadraticAlgebra M2 pi2pM 0
/-- `β₁ = (-25 + 2r) + (-139 - 9r) g` in `M3`. -/
def beta1M : M3 := ⟨⟨⟨-25, 2⟩, 0⟩, ⟨⟨-139, -9⟩, 0⟩⟩
/-- `ℚ(r, t, g, √β₁)`, generator `s`. -/
abbrev M4 := QuadraticAlgebra M3 beta1M 0

/-- `π₂ = (-6101 - 393 r)/2` in the model. -/
def pi2M : M4 := ⟨⟨⟨⟨-6101 / 2, -393 / 2⟩, 0⟩, 0⟩, 0⟩

/-- The generator `y` of the prime above `𝔭₁`. -/
def yM : M4 :=
  ⟨⟨⟨⟨(201/8), (13/8)⟩, ⟨20, (5/4)⟩⟩,
    ⟨⟨(-1599/8), (-103/8)⟩, ⟨(885/16), (57/16)⟩⟩⟩,
   ⟨⟨⟨(191/8), (-9/8)⟩, ⟨1, (1/4)⟩⟩,
    ⟨⟨(175/8), (11/8)⟩, ⟨(-1227/16), (-79/16)⟩⟩⟩⟩

/-- The unit `u = y⁸ / π₂`. -/
def uM : M4 :=
  ⟨⟨⟨⟨(-2823974344943/8), (-181917593295/8)⟩, ⟨-249621050349, -16078921389⟩⟩,
    ⟨⟨(339419326153899/2), (21863920776921/2)⟩, ⟨(1920044726305467/16), (123680953463187/16)⟩⟩⟩,
   ⟨⟨⟨(-3998570576755/8), (-257252444275/8)⟩, ⟨(-1411586736787/4), (-91088567155/4)⟩⟩,
    ⟨⟨(220938163017415/4), (14231880209695/4)⟩, ⟨(624908302414811/16), (40253874181715/16)⟩⟩⟩⟩

/-- Characteristic polynomial of `y` (constant term first). -/
def fL : List ℤ :=
    [2, 436, -81606, -46036936, -9030768424, -763234150068, -10105796572904, -2611575573680,
     351521220743, 345620204958, 64760568869, -391293574, 57596022, -3319130, 57601, -402, 1]

/-- `fL` without its leading coefficient `1`. -/
def fL₀ : List ℤ := fL.dropLast

/-- Characteristic polynomial of `u` (constant term first). -/
def hL : List ℤ :=
    [1, -34060174908869090, -2567238413601552775540906075323,
     -2167439270297716520801814582941941178378206018,
     -889425864886809103042578359374376264404802418287077592163610,
     -367506643833028417374339644094804060364074077117111778663021179280255721662,
     448589723494635113406113592661305418108954492089866361317577715185663014882163931,
     106337163779202046407474330172180943717755362818575778608868045866765879060578706,
     24576111551097956742446564992061179209102187769495636560007509487383234932417618,
     -3532714168129727413542573990078226749624691823002407888582030752715976526,
     181826733294862678125360242990893269994738583286745553878987059979,
     -3711573602847220475072660867292083808983487661556685456558,
     19827813414335196021284513340203452717418793338726, -43514440201537813812334545337692035986,
     620703701167190331302735925, 5647948689886, 1]

/-- `hL` without its leading coefficient `1`. -/
def hL₀ : List ℤ := hL.dropLast

/-- `f = X⁸ G + 2 Kp`. -/
def GhiL : List ℤ :=
    [351521220743, 345620204958, 64760568869, -391293574, 57596022, -3319130, 57601, -402, 1]

/-- `Kp = 1 + X Kp₁`. -/
def Kp₁L : List ℤ :=
    [218, -40803, -23018468, -4515384212, -381617075034, -5052898286452, -1305787786840]

/-- `f' = X¹⁸ Z + f W`. -/
def ZL : List ℤ :=
    [-696379322689947793049822891107339490575379989589,
     -373127813031739800309546497911022994807940947603410,
     -90178331906905268642913256963891982342990522826690926,
     -12633022048963897869229441355945175236533507059216663265,
     -870941657782186340393854922324357649500855618696812426132,
     -11079351192040321789267958165866293889739212856985162401193,
     -2859624491967441816130610857383560530028814169779459619023,
     386264439995399942311857625457522921413093598405188543111,
     378831452019623932576594435385814376458835527111993096129,
     70940353435778607285267903743952943709774476370727138784,
     -428442472405291613727100179628797745155243895662364380,
     63081888377673997364124461285515294981615469251365585,
     -3635728915185950316412762064504418598671433895662048,
     63097395354544542712702715380322415384811753749587,
     -440365816477287759574205659429302627838419224627,
     1095445928292147765366996052869463343914073485]

/-- The cofactor `W` in `f' = X¹⁸ Z + f W`. -/
def WL : List ℤ :=
    [218, -129130, -32010010, -11334220034, -2731350860412, -1134053513999026, -317843339630354964,
     -103900569142224890758, -33243154663726032241912, -10529043843838298741940580,
     -3334495822889913601402033069, -1064082235152132725698462862714,
     -337813322021670529489682593398243, -107283676267047535457085126807321787,
     -34132201034969510085961518232035148035, -10843107405335730776325555150862610109988,
     -3446696155642103326753824221636415038316343, -1095445928292147765366996052869463343914073485]

/-- `Z = Z₀ + X Z₁`. -/
def Z₀ : ℤ := -696379322689947793049822891107339490575379989589

/-- `Z = Z₀ + X Z₁`. -/
def Z₁L : List ℤ := ZL.tail

theorem fL_eq : fL = fL₀ ++ [1] := by decide

theorem hL_eq : hL = hL₀ ++ [1] := by decide

theorem ZL_eq : ZL = Z₀ :: Z₁L := by decide

theorem Z₀_odd : Odd Z₀ := by decide

set_option maxRecDepth 100000 in
/-- Kernel check: `f(y) = 0` in the model. -/
theorem f_yM : horner fL yM = 0 := by decide +kernel

/-- Exact intermediate coordinates for the bounded multiplication checks below. -/
private def y2M : M4 :=
  ⟨⟨⟨⟨(23201/8), (1493/8)⟩, ⟨(8521/4), (549/4)⟩⟩,
    ⟨⟨(-57843/2), -1863⟩, ⟨(-386847/16), (-24919/16)⟩⟩⟩,
   ⟨⟨⟨(5673/8), (381/8)⟩, ⟨(1053/2), (55/2)⟩⟩,
    ⟨⟨(-45565/4), (-2935/4)⟩, ⟨(-116147/16), (-7483/16)⟩⟩⟩⟩

private def y3M : M4 :=
  ⟨⟨⟨⟨340962, (43927/2)⟩, ⟨(1910447/8), (123059/8)⟩⟩,
    ⟨⟨(-64375353/8), (-4146781/8)⟩, ⟨(-46071729/8), (-2967741/8)⟩⟩⟩,
   ⟨⟨⟨110673, (14195/2)⟩, ⟨(629143/8), (40583/8)⟩⟩,
    ⟨⟨(-18234071/8), (-1174563/8)⟩, ⟨(-12587307/8), (-810819/8)⟩⟩⟩⟩

private def y4M : M4 :=
  ⟨⟨⟨⟨(312086077/8), (20103213/8)⟩, ⟨27575814, 1776315⟩⟩,
    ⟨⟨(-3234455665/2), (-208349605/2)⟩, ⟨(-18240982503/16), (-1175004975/16)⟩⟩⟩,
   ⟨⟨⟨(125035505/8), (8054609/8)⟩, ⟨(44252919/4), (2850267/4)⟩⟩,
    ⟨⟨(-1727200199/4), (-111258743/4)⟩, ⟨(-4903016471/16), (-315831071/16)⟩⟩⟩⟩

private def y5M : M4 :=
  ⟨⟨⟨⟨(34749154301/8), (2238389833/8)⟩, ⟨(24583595145/8), (1583568525/8)⟩⟩,
    ⟨⟨(-2265486061283/8), (-145932785839/8)⟩, ⟨(-3204178390387/16), (-206399274235/16)⟩⟩⟩,
   ⟨⟨⟨(16416386221/8), (1057469241/8)⟩, ⟨(11603687631/8), (747460335/8)⟩⟩,
    ⟨⟨(-623680690255/8), (-40174804979/8)⟩, ⟨(-882082075051/16), (-56819901339/16)⟩⟩⟩⟩

private def y6M : M4 :=
  ⟨⟨⟨⟨(1797175263775/4), (115766235379/4)⟩, ⟨(1270711434185/4), (81853719105/4)⟩⟩,
    ⟨⟨(-183623253669447/4), (-11828213561247/4)⟩, ⟨(-259696736125707/8), (-16728537343003/8)⟩⟩⟩,
   ⟨⟨⟨(1012558640857/4), (65224639057/4)⟩, ⟨(715999411401/4), (46121572537/4)⟩⟩,
    ⟨⟨(-53178429550129/4), (-3425523777589/4)⟩, ⟨(-75199767996369/8), (-4844042885969/8)⟩⟩⟩⟩

private def y7M : M4 :=
  ⟨⟨⟨⟨(316944554261249/8), (20416193483449/8)⟩, ⟨(224109152790333/8), (14436139580097/8)⟩⟩,
    ⟨⟨(-56350849594708229/8), (-3629877316974781/8)⟩, ⟨(-79691468370279803/16), (-5133378741832811/16)⟩⟩⟩,
   ⟨⟨⟨(233286771671929/8), (15027321941561/8)⟩, ⟨(164960895610769/8), (10626065419021/8)⟩⟩,
    ⟨⟨(-17287901645466417/8), (-1113611640149825/8)⟩, ⟨(-24448948313785547/16), (-1574895206485163/16)⟩⟩⟩⟩

private def y8M : M4 :=
  ⟨⟨⟨⟨(17229514246123289/8), (1109850577127697/8)⟩, ⟨1522910454847803, 98099286090723⟩⟩,
    ⟨⟨-1035398709352364118, -66695893959619332⟩, ⟨(-11714193510274242249/16), (-754577537258476209/16)⟩⟩⟩,
   ⟨⟨⟨(24380214921700165/8), (1570467699593245/8)⟩, ⟨(8619681071044501/4), (555242467884973/4)⟩⟩,
    ⟨⟨(-1347943901435045725/4), (-86828699612596645/4)⟩, ⟨(-3812565369202767353/16), (-245588924615831969/16)⟩⟩⟩⟩

set_option maxRecDepth 100000 in
private theorem yM_step2 : yM * yM = y2M := by decide +kernel

set_option maxRecDepth 100000 in
private theorem yM_step3 : y2M * yM = y3M := by decide +kernel

set_option maxRecDepth 100000 in
private theorem yM_step4 : y3M * yM = y4M := by decide +kernel

set_option maxRecDepth 100000 in
private theorem yM_step5 : y4M * yM = y5M := by decide +kernel

set_option maxRecDepth 100000 in
private theorem yM_step6 : y5M * yM = y6M := by decide +kernel

set_option maxRecDepth 100000 in
private theorem yM_step7 : y6M * yM = y7M := by decide +kernel

set_option maxRecDepth 100000 in
private theorem yM_step8 : y7M * yM = y8M := by decide +kernel

set_option maxRecDepth 100000 in
private theorem pi2M_mul_uM : pi2M * uM = y8M := by decide +kernel

set_option maxRecDepth 100000 in
/-- Kernel check: `π₂ u = y⁸` in the model. -/
theorem u_yM : pi2M * uM = yM * yM * yM * yM * yM * yM * yM * yM := by
  have h3 := (congrArg (fun z : M4 => z * yM) yM_step2).trans yM_step3
  have h4 := (congrArg (fun z : M4 => z * yM) h3).trans yM_step4
  have h5 := (congrArg (fun z : M4 => z * yM) h4).trans yM_step5
  have h6 := (congrArg (fun z : M4 => z * yM) h5).trans yM_step6
  have h7 := (congrArg (fun z : M4 => z * yM) h6).trans yM_step7
  have h8 := (congrArg (fun z : M4 => z * yM) h7).trans yM_step8
  exact pi2M_mul_uM.trans h8.symm

set_option maxRecDepth 100000 in
/-- Kernel check: `h(u) = 0` in the model. -/
theorem h_uM : horner hL uM = 0 := by decide +kernel

/-- `f = X⁸ G + 2 (1 + X Kp₁)`, in any commutative ring. -/
theorem f_split {R : Type*} [CommRing R] (z : R) :
    horner fL z = z ^ 8 * horner GhiL z + 2 * (1 + z * horner Kp₁L z) := by
  simp only [fL, GhiL, Kp₁L, horner_cons, horner_nil]
  push_cast
  ring

/-- `f' = X¹⁸ Z + f W`, in any commutative ring. -/
theorem f_deriv {R : Type*} [CommRing R] (z : R) :
    hornerD fL z = z ^ 18 * horner ZL z + horner fL z * horner WL z := by
  simp only [fL, ZL, WL, horner_cons, horner_nil, hornerD_cons, hornerD_nil]
  push_cast
  ring

end UnitDistance.Sqrt241.Discriminant.Dyadic
