/-
Ported from Naganori Yamaguchi, SawinTotallyRealTowers, commit
3a455e1aa9140dbbe7b7d68f508392a69c86d0f4, under Apache-2.0.
Modified: project-local imports relocated; Lean 4.32 compatibility changes
are recorded in third-party/yamaguchi/compatibility.patch. The Mathlib
4.35 Denumerable import relocation is recorded in
third-party/yamaguchi/lean-v4.35-migration.patch.
Original declaration namespaces and mathematical statements are retained.
-/

module

public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.IdealPowerRadicalModule
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.NegativeThreeLocalRadical
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.RationalIdealSquareRadical
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.RealCharacterInertiaCorrection
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.AbsoluteRealKernelField
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.GlobalReciprocityCharacter
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Local.FinitePlaceH2Localization
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Local.FinitePlaceUnramifiedH1
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.EmptySupportKummerCokernel
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.NegativeThreeCharacter
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.AbsoluteCharacterRadicalReciprocity
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.FinitePlaceCyclotomicMuPKummerComparison
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.FinitePlaceH1AdicRestriction
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.FiniteSupportLocalReciprocityIdeleCharacter
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.IdealPowerRadicalAbsoluteKummerLinear
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.IdealPowerRadicalExact
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.IdealPowerRadicalSelmer
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Radical.LocalValuationKummerDual
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Kummer.LocalReciprocityCharacterPairing
public import UnitDistance.Upstream.Yamaguchi.ProCGroups.ProP.ContinuousH1
public import Mathlib.Algebra.BigOperators.Group.Finset.Basic
public import Mathlib.LinearAlgebra.Dual.Defs
public import Mathlib.NumberTheory.NumberField.Basic
public import Mathlib.NumberTheory.Padics.HeightOneSpectrum
public import Mathlib.Topology.Algebra.ContinuousMonoidHom
public import Mathlib.Topology.Instances.ZMod

@[expose] public section
set_option backward.privateInPublic true


set_option autoImplicit false

/-!
# Arbitrary finite inertia data with a prescribed real value

The rational ideal-square radical is generated by the actual class of −1.
The local restriction of the character of ℚ(√−3) has nonzero reciprocity
pairing with that class. Subtracting its uniquely determined scalar multiple
at three therefore corrects any finite local family to annihilate the radical.
Global reciprocity realizes the corrected family, and the existing real-sign
correction preserves all inertia outside an allowed set containing three.
-/

open NumberField IsDedekindDomain
open scoped NumberField BigOperators Classical

noncomputable section
namespace ClassFieldTower.Sawin
open ClassFieldTower.Martinet.Shafarevich ClassFieldTower.ProP

private local instance radicalExistenceValuative
    (F : Type) [Field F] [NumberField F] (v : HeightOneSpectrum (𝓞 F)) :
    ValuativeRel (v.adicCompletion F) := finitePlaceAdicCompletionValuativeRel F v

private local instance radicalExistenceLocalField
    (F : Type) [Field F] [NumberField F] (v : HeightOneSpectrum (𝓞 F)) :
    IsNonarchimedeanLocalField (v.adicCompletion F) :=
  finitePlaceAdicCompletionIsNonarchimedeanLocalField F v

private local instance radicalExistenceH1Module
    {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] :
    Module (ZMod 2) (ContinuousH1ZMod (p := 2) (G := G)) := continuousH1ZModModule

private local instance radicalExistenceH1AddCommGroup
    {G : Type} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] :
    AddCommGroup (ContinuousH1ZMod (p := 2) (G := G)) :=
  ContinuousAddMonoidHom.instAddCommGroup (Additive G) (ZMod 2)

private local instance radicalExistencePairingDualAddCommGroup
    {K : Type} [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    AddCommGroup (Module.Dual (ZMod 2) (absolutePowerClassModP K 2)) := by
  letI : AddCommGroup (absolutePowerClassModP K 2) :=
    (absolutePowerClassModP K 2).isAddCommGroup
  letI : Module (ZMod 2) (absolutePowerClassModP K 2) :=
    (absolutePowerClassModP K 2).isModule
  letI : Semiring (ZMod 2) :=
    (inferInstance : CommRing (ZMod 2)).toCommSemiring.toSemiring
  letI : Module (ZMod 2) (ZMod 2) := Semiring.toModule
  letI : SMulCommClass (ZMod 2) (ZMod 2) (ZMod 2) :=
    ⟨fun r s x => by
      change r * (s * x) = s * (r * x)
      ac_rfl⟩
  exact @LinearMap.addCommGroup
    (ZMod 2) (ZMod 2) (absolutePowerClassModP K 2) (ZMod 2)
    _ _ _ _ (absolutePowerClassModP K 2).isModule
    Semiring.toModule (RingHom.id (ZMod 2))

private local instance radicalExistencePairingDualAddZeroClass
    {K : Type} [Field K] [ValuativeRel K] [TopologicalSpace K]
    [IsNonarchimedeanLocalField K] :
    AddZeroClass (Module.Dual (ZMod 2) (absolutePowerClassModP K 2)) :=
  (inferInstance : AddCommGroup
    (Module.Dual (ZMod 2) (absolutePowerClassModP K 2))).toAddGroup.toAddZeroClass

section LocalValues
variable (F : Type) [Field F] [NumberField F]

private def radicalNegOne : idealPowerRadicalModP F 2 :=
  Additive.ofMul (integralUnitToIdealNthPowerRadicalQuotient F (2 : ℕ+) (-1))

private theorem radicalNegOne_image :
    idealPowerRadicalToAbsolutePowerClassLinearMap F 2 (radicalNegOne F) =
      Additive.ofMul (QuotientGroup.mk' (powMonoidHom 2 : Fˣ →* Fˣ).range (-1)) := by
  rfl

private def localRadicalValue (v : HeightOneSpectrum (𝓞 F))
    (χ : ContinuousH1ZMod (p := 2) (G := finitePlaceAbsoluteDecompositionGroup F v)) :
    ZMod 2 :=
  localReciprocityH1PowerClassPairing (v.adicCompletion F) 2
    (finitePlaceDecompositionH1ToAdic F 2 v χ)
    (finitePlacePowerClassLocalization F 2 v
      (idealPowerRadicalToAbsolutePowerClassLinearMap F 2 (radicalNegOne F)))

private theorem localRadicalValue_absoluteCharacter
    (v : HeightOneSpectrum (𝓞 F))
    (χ : Field.absoluteGaloisGroup F →ₜ* Multiplicative (ZMod 2)) :
    localRadicalValue F v
      (h1OfCharacter (χ.comp (finitePlaceAbsoluteDecompositionInclusion F v))) =
      (globalReciprocityIdeleCharacter F 2 χ
        (IdeleGroup.finitePlaceIdele v (-1))).toAdd := by
  let χv := finitePlaceAbsoluteH1AdicRestriction F 2 v (Additive.ofMul χ)
  let a : (v.adicCompletion F)ˣ :=
    Units.map (algebraMap F (v.adicCompletion F)).toMonoidHom (-1)
  have hLoc := (congrArg (fun q : absolutePowerClassModP F 2 =>
    finitePlacePowerClassLocalization F 2 v q) (radicalNegOne_image F)).trans
      (finitePlacePowerClassLocalization_mk F 2 v (-1 : Fˣ))
  have hPair := congrArg (fun q : absolutePowerClassModP (v.adicCompletion F) 2 =>
    localReciprocityH1PowerClassPairing (v.adicCompletion F) 2 χv q) hLoc
  have hEval := localReciprocityH1PowerClassPairing_mk (v.adicCompletion F) 2 χv a
  have hUnit : a = (-1 : (v.adicCompletion F)ˣ) := by
    apply Units.ext
    change algebraMap F (v.adicCompletion F) (-1) = -1
    rw [map_neg, map_one]
  have hArtin := (congrArg (fun u : (v.adicCompletion F)ˣ =>
    localReciprocityUnitCharacter (v.adicCompletion F) 2 χv u) hUnit).trans
      (localReciprocityUnitCharacter_absoluteCharacter F (2 : ℕ+) χ v (-1))
  have hEval' : (localReciprocityH1PowerClassPairing (v.adicCompletion F) 2 χv)
      (finitePlacePowerClassLocalization F 2 v
        (idealPowerRadicalToAbsolutePowerClassLinearMap F 2 (radicalNegOne F))) =
      (localReciprocityUnitCharacter (v.adicCompletion F) 2 χv a).toAdd :=
    hPair.trans hEval
  have hχ : finitePlaceDecompositionH1ToAdic F 2 v
      (h1OfCharacter (χ.comp (finitePlaceAbsoluteDecompositionInclusion F v))) = χv := by
    ext σ
    rfl
  unfold localRadicalValue
  rw [hχ]
  exact hEval'.trans (congrArg Multiplicative.toAdd hArtin)

private theorem localRadicalValue_sub
    (v : HeightOneSpectrum (𝓞 F))
    (χ ψ : ContinuousH1ZMod (p := 2) (G := finitePlaceAbsoluteDecompositionGroup F v)) :
    localRadicalValue F v (χ - ψ) = localRadicalValue F v χ - localRadicalValue F v ψ := by
  unfold localRadicalValue
  rw [map_sub, map_sub]
  rfl

private theorem localRadicalValue_smul
    (v : HeightOneSpectrum (𝓞 F)) (a : ZMod 2)
    (χ : ContinuousH1ZMod (p := 2) (G := finitePlaceAbsoluteDecompositionGroup F v)) :
    localRadicalValue F v (a • χ) = a * localRadicalValue F v χ := by
  unfold localRadicalValue
  rw [map_smul, map_smul, LinearMap.smul_apply, smul_eq_mul]

private theorem localRadicalValue_zero (v : HeightOneSpectrum (𝓞 F)) :
    localRadicalValue F v 0 = 0 := by
  unfold localRadicalValue
  rw [map_zero, map_zero, LinearMap.zero_apply]

private theorem radicalFamily_negOne_eq_sum
    (S : Finset (HeightOneSpectrum (𝓞 F)))
    (χ : ∀ v : ↥S, ContinuousH1ZMod (p := 2)
      (G := finitePlaceAbsoluteDecompositionGroup F v.1)) :
    (absolutePowerClassDualRestriction F 2
      (finiteSupportLocalReciprocityPowerClassFunctional F 2 S
        (fun v => finitePlaceDecompositionH1ToAdic F 2 v.1 (χ v)))) (radicalNegOne F) =
      ∑ v : ↥S, localRadicalValue F v.1 (χ v) := by
  exact finiteSupportLocalReciprocityPowerClassFunctional_apply F 2 S
    (fun v => finitePlaceDecompositionH1ToAdic F 2 v.1 (χ v))
    (idealPowerRadicalToAbsolutePowerClassLinearMap F 2 (radicalNegOne F))

end LocalValues

private theorem localRadicalValue_negThree_ne_zero :
    localRadicalValue ℚ
      ((Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
        (⟨3, Nat.prime_three⟩ : Nat.Primes))
      (h1OfCharacter (negativeThreeCharacter.comp
        (finitePlaceAbsoluteDecompositionInclusion ℚ
          ((Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
            (⟨3, Nat.prime_three⟩ : Nat.Primes))))) ≠ 0 := by
  intro h
  have he := localRadicalValue_absoluteCharacter ℚ
    ((Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
      (⟨3, Nat.prime_three⟩ : Nat.Primes)) negativeThreeCharacter
  exact negativeThreeCharacter_three_neg_one_ne_one
    (Multiplicative.toAdd.injective (he.symm.trans h))

/-- Any finite local quadratic-character family can be corrected only at
three so that its actual reciprocity functional annihilates the rational
ideal-square radical. -/
theorem exists_localFamily_radical_annihilator_adjusted_at_three
    (S : Finset (HeightOneSpectrum (𝓞 ℚ)))
    (χ : ∀ v : ↥S, finitePlaceAbsoluteDecompositionGroup ℚ v.1 →ₜ*
      Multiplicative (ZMod 2)) :
    let v₃ := (Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
      (⟨3, Nat.prime_three⟩ : Nat.Primes)
    ∃ ψ : ∀ v : ↥(insert v₃ S), finitePlaceAbsoluteDecompositionGroup ℚ v.1 →ₜ*
      Multiplicative (ZMod 2),
      (absolutePowerClassDualRestriction ℚ 2
        (finiteSupportLocalReciprocityPowerClassFunctional ℚ 2 (insert v₃ S)
          (fun v => finitePlaceDecompositionH1ToAdic ℚ 2 v.1 (h1OfCharacter (ψ v)))) = 0) ∧
      (∀ (v : ↥S) (_hv : v.1 ≠ v₃),
        ψ ⟨v.1, Finset.mem_insert_of_mem v.property⟩ = χ v) := by
  let v₃ : HeightOneSpectrum (𝓞 ℚ) :=
    (Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
      (⟨3, Nat.prime_three⟩ : Nat.Primes)
  let U := insert v₃ S
  let bχ : ∀ v : HeightOneSpectrum (𝓞 ℚ),
      ContinuousH1ZMod (p := 2) (G := finitePlaceAbsoluteDecompositionGroup ℚ v) :=
    fun v => if hv : v ∈ S then h1OfCharacter (χ ⟨v, hv⟩) else 0
  let nχ : ∀ v : HeightOneSpectrum (𝓞 ℚ),
      ContinuousH1ZMod (p := 2) (G := finitePlaceAbsoluteDecompositionGroup ℚ v) :=
    fun v => h1OfCharacter (negativeThreeCharacter.comp
      (finitePlaceAbsoluteDecompositionInclusion ℚ v))
  let c : ZMod 2 := ∑ v ∈ U, localRadicalValue ℚ v (bχ v)
  let d : ZMod 2 := localRadicalValue ℚ v₃ (nχ v₃)
  have hd : d ≠ 0 := localRadicalValue_negThree_ne_zero
  let a : ZMod 2 := c / d
  let fχ : ∀ v : HeightOneSpectrum (𝓞 ℚ),
      ContinuousH1ZMod (p := 2) (G := finitePlaceAbsoluteDecompositionGroup ℚ v) :=
    fun v => bχ v - if v = v₃ then a • nχ v else 0
  let ψ : ∀ v : ↥U, finitePlaceAbsoluteDecompositionGroup ℚ v.1 →ₜ*
      Multiplicative (ZMod 2) := fun v => characterOfH1 (fχ v.1)
  have hValue (v : HeightOneSpectrum (𝓞 ℚ)) :
      localRadicalValue ℚ v (fχ v) = localRadicalValue ℚ v (bχ v) -
        if v = v₃ then a * localRadicalValue ℚ v (nχ v) else 0 := by
    dsimp only [fχ]
    rw [localRadicalValue_sub]
    by_cases hv : v = v₃
    · rw [if_pos hv, if_pos hv, localRadicalValue_smul]
    · rw [if_neg hv, if_neg hv, localRadicalValue_zero]
  have hCorrection : (∑ v ∈ U,
      if v = v₃ then a * localRadicalValue ℚ v (nχ v) else 0) = a * d := by
    rw [Finset.sum_eq_single v₃]
    · rw [if_pos rfl]
    · intro v hv hne
      exact if_neg hne
    · intro h
      exact (h (Finset.mem_insert_self v₃ S)).elim
  have hsumSub (s : Finset (HeightOneSpectrum (𝓞 ℚ)))
      (f g : HeightOneSpectrum (𝓞 ℚ) → ZMod 2) :
      (∑ v ∈ s, (f v - g v)) = (∑ v ∈ s, f v) - (∑ v ∈ s, g v) := by
    classical
    induction s using Finset.induction_on with
    | empty => simp
    | @insert v s hv ih =>
      simp only [Finset.sum_insert hv]
      rw [ih]
      abel
  have hSum : (∑ v ∈ U, localRadicalValue ℚ v (fχ v)) = 0 := by
    calc
      (∑ v ∈ U, localRadicalValue ℚ v (fχ v)) =
          (∑ v ∈ U, localRadicalValue ℚ v (bχ v)) -
            (∑ v ∈ U, if v = v₃ then a * localRadicalValue ℚ v (nχ v) else 0) := by
        simp_rw [hValue]
        change (∑ v ∈ U, (localRadicalValue ℚ v (bχ v) -
          (if v = v₃ then a * localRadicalValue ℚ v (nχ v) else 0 : ZMod 2))) = _
        exact hsumSub U (fun v => localRadicalValue ℚ v (bχ v))
          (fun v => if v = v₃ then a * localRadicalValue ℚ v (nχ v) else 0)
      _ = c - (c / d) * d := by
        rw [hCorrection]
      _ = 0 := by
        rw [div_mul_cancel₀ c hd, sub_self]
  have hSumSubtype : (∑ v : ↥U, localRadicalValue ℚ v.1 (fχ v.1)) = 0 :=
    (Finset.sum_coe_sort U (fun v => localRadicalValue ℚ v (fχ v))).trans hSum
  have hRoundTrip : ∀ v : ↥U, h1OfCharacter (ψ v) = fχ v.1 := by
    intro v
    ext σ
    rfl
  refine ⟨ψ, ?_, ?_⟩
  · ext x
    rcases rationalIdealSquareRadical_eq_zero_or_neg_one x with hx | hx
    · rw [hx, map_zero, LinearMap.zero_apply]
    · rw [hx]
      have h := radicalFamily_negOne_eq_sum ℚ U (fun v => h1OfCharacter (ψ v))
      simp_rw [hRoundTrip] at h
      exact h.trans hSumSubtype
  · intro v hv
    apply ContinuousMonoidHom.ext
    intro σ
    change Multiplicative.ofAdd ((fχ v.1) (Additive.ofMul σ)) = χ v σ
    dsimp only [fχ]
    rw [if_neg hv]
    have hsub : bχ v.1 - (0 : ContinuousH1ZMod
        (p := 2) (G := finitePlaceAbsoluteDecompositionGroup ℚ v.1)) = bχ v.1 :=
      sub_zero _
    rw [hsub]
    change Multiplicative.ofAdd (bχ v.1 (Additive.ofMul σ)) = χ v σ
    dsimp only [bχ]
    rw [dif_pos v.property]
    rfl

/-- Prescribe an arbitrary finite inertia family and the real value over ℚ.
The allowed prime three absorbs the radical and sign corrections, so all
specified inertia values outside T are retained. -/
theorem exists_absoluteCharacter_with_prescribed_inertia_and_real_value
    (T : Set (HeightOneSpectrum (𝓞 ℚ)))
    (hThree : (Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
      (⟨3, Nat.prime_three⟩ : Nat.Primes) ∈ T)
    (S : Finset (HeightOneSpectrum (𝓞 ℚ)))
    (χ : ∀ v : ↥S, finitePlaceAbsoluteDecompositionGroup ℚ v.1 →ₜ*
      Multiplicative (ZMod 2))
    (ε : Multiplicative (ZMod 2)) :
    ∃ γ : Field.absoluteGaloisGroup ℚ →ₜ* Multiplicative (ZMod 2),
      (∀ v : InfinitePlace ℚ,
        γ (absoluteInfinitePlaceArtinNegOne ℚ v) = ε) ∧
      (∀ (v : ↥S), v.1 ∉ T →
        ∀ σ : finitePlaceAbsoluteInertiaSubgroup ℚ v.1,
          χ v σ.1 = γ (finitePlaceAbsoluteDecompositionInclusion ℚ v.1 σ.1)) ∧
      (∀ (v : HeightOneSpectrum (𝓞 ℚ)), v ∉ S → v ∉ T →
        ∀ σ : finitePlaceAbsoluteInertiaSubgroup ℚ v,
          γ (finitePlaceAbsoluteDecompositionInclusion ℚ v σ.1) = 1) := by
  let v₃ : HeightOneSpectrum (𝓞 ℚ) :=
    (Rat.HeightOneSpectrum.primesEquiv (R := 𝓞 ℚ)).symm
      (⟨3, Nat.prime_three⟩ : Nat.Primes)
  obtain ⟨ψ, hψ, hKeep⟩ := exists_localFamily_radical_annihilator_adjusted_at_three S χ
  obtain ⟨γ, hReal, hInside, hOutside⟩ :=
    exists_absoluteCharacter_with_real_value_of_radical_annihilator
      T hThree (insert v₃ S) ψ hψ ε
  refine ⟨γ, hReal, ?_, ?_⟩
  · intro v hv σ
    have hNe : v.1 ≠ v₃ := fun he => hv (he.symm ▸ hThree)
    have h := hInside ⟨v.1, Finset.mem_insert_of_mem v.property⟩ hv σ
    rw [hKeep v hNe] at h
    exact h
  · intro v hv hT σ
    have hNe : v ≠ v₃ := fun he => hT (he.symm ▸ hThree)
    exact hOutside v (fun h => (Finset.mem_insert.mp h).elim hNe hv) hT σ

end ClassFieldTower.Sawin
