module

public import UnitDistance.ArithmeticCompletedSquareclasses
public import UnitDistance.GeneratedQuadraticTower

@[expose] public section
set_option backward.privateInPublic true


/-!
# The actual full completed quadratic field

This constructs the field generated by the seven specified catalog
squareclasses over the actual genus field. Its relative and absolute degrees
and its actual Galois property are derived from proved nonsquareness and
invariance. No arithmetic tower or ramification claim is part of this file.
-/

noncomputable section
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000
set_option synthInstance.maxHeartbeats 200000
set_option backward.isDefEq.respectTransparency false
namespace UnitDistance.ArithmeticCompleted
open ArithmeticChosenGenus Multiquadratic

/-- The actual iterated quadratic construction of the seven-radical field. -/
def completedTower : GeneratedGaloisTower ℚ completedRadicand Finset.univ :=
  Classical.choice (exists_generatedGaloisTower ℚ completedRadicand
    completedRadicand_ne_zero completed_products_not_isSquare
    completedRadicand_invariant Finset.univ)

/-- The actual full completed quadratic field. -/
abbrev CompletedField := completedTower.Carrier

instance completedField_field : Field CompletedField := completedTower.field
instance completedField_charZero : CharZero CompletedField := completedTower.charZero
instance completedField_algebraGenus : Algebra GenusField CompletedField := completedTower.algebra
instance completedField_algebraRat : Algebra ℚ CompletedField := DivisionRing.toRatAlgebra

theorem completedTower_baseAlgebra_eq : completedTower.baseAlgebra = completedField_algebraRat :=
  Subsingleton.elim _ _
instance completedField_scalarTower : IsScalarTower ℚ GenusField CompletedField := by
  rw [← completedTower_baseAlgebra_eq]
  exact completedTower.scalarTower
instance completedField_finiteGenus : Module.Finite GenusField CompletedField := completedTower.finite
instance completedField_galoisRat : IsGalois ℚ CompletedField := by
  rw [← completedTower_baseAlgebra_eq]
  exact completedTower.baseGalois

instance completedField_numberField : NumberField CompletedField where
  to_finiteDimensional := Module.Finite.trans GenusField CompletedField

/-- The relative degree follows from the seven genuinely independent
actual genus-field squareclasses. -/
theorem completedField_relative_degree : Module.finrank GenusField CompletedField = 128 := by
  simpa using completedTower.degree

/-- The actual full completed field has absolute degree 2^14. -/
theorem completedField_degree : Module.finrank ℚ CompletedField = 16384 := by
  rw [← Module.finrank_mul_finrank ℚ GenusField CompletedField,
    genusField_degree,completedField_relative_degree]

/-- The actual Galois group has the proved field degree. -/
theorem completedField_galoisGroup_card : Nat.card (Gal(CompletedField/ℚ)) = 16384 := by
  rw [IsGalois.card_aut_eq_finrank,completedField_degree]

/-- The constructed field contains an actual square root of every one of
the seven independently specified completed radicands. -/
theorem completedField_contains_radical (j : Fin 7) :
    ∃ x : CompletedField, x^2 = algebraMap GenusField CompletedField (completedRadicand j) := by
  obtain ⟨x,hx⟩ := completedTower.toActualGaloisTower.toActualTower.isSquare_radical j
    (Finset.mem_univ j) (completedRadicand_ne_zero j)
  exact ⟨x,by simpa [pow_two] using hx.symm⟩

/-- The actual field is generated over the actual genus field by the
square roots of precisely the seven completed radicands. -/
theorem completedField_generated :
    Algebra.adjoin GenusField (radicalSet (L := CompletedField) completedRadicand Finset.univ) = ⊤ :=
  completedTower.generated

end UnitDistance.ArithmeticCompleted
