module

public import UnitDistance.CanonicalRetainedField
public import UnitDistance.ArithmeticRetainedField

@[expose] public section
set_option backward.privateInPublic true


/-! The independently defined nineteen-radical field is isomorphic to the
actual retained field constructed by the arithmetic squareclass proofs. -/
noncomputable section
set_option backward.isDefEq.respectTransparency false
set_option maxHeartbeats 2000000
namespace UnitDistance.CanonicalRetained
open scoped BigOperators Classical
open Multiquadratic
abbrev G := ArithmeticChosenGenus.GenusField
abbrev M := ArithmeticRetained.RetainedField

def initialGenusEmbedding : G →ₐ[ℚ] Closure := IsAlgClosed.lift

def aligningSigns (i : Fin 7) : ZMod 2 :=
  if initialGenusEmbedding (ArithmeticChosenGenus.roots i)=genusRoot i then 0 else 1

def genusEmbedding : G →ₐ[ℚ] Closure :=
  initialGenusEmbedding.comp (ArithmeticChosenGenus.signAutomorphism aligningSigns).toAlgHom

theorem genusEmbedding_root (i : Fin 7) :
    genusEmbedding (ArithmeticChosenGenus.roots i)=genusRoot i := by
  have hs : (initialGenusEmbedding (ArithmeticChosenGenus.roots i))^2=(genusRoot i)^2 := by
    rw [←map_pow,ArithmeticChosenGenus.roots_sq,genusRoot_sq]
    exact initialGenusEmbedding.commutes _
  change initialGenusEmbedding
    (ArithmeticChosenGenus.signAutomorphism aligningSigns (ArithmeticChosenGenus.roots i))=_
  rw [ArithmeticChosenGenus.signAutomorphism_roots,map_mul]
  rcases sq_eq_sq_iff_eq_or_eq_neg.mp hs with h | h
  · simp [aligningSigns,h,binarySign,binarySignInteger]
  · by_cases hsame : initialGenusEmbedding (ArithmeticChosenGenus.roots i)=genusRoot i
    · simp [aligningSigns,hsame,binarySign,binarySignInteger]
    · simp only [aligningSigns,if_neg hsame]
      norm_num [binarySign,binarySignInteger,h]

/-- Extend the aligned actual genus embedding into an algebraic closure. -/
def embedding : M →ₐ[ℚ] Closure := by
  letI : Algebra G Closure := genusEmbedding.toRingHom.toAlgebra
  let θ : M →ₐ[G] Closure := IsAlgClosed.lift
  exact θ.toRingHom.toRatAlgHom

theorem embedding_genus (x : G) :
    embedding (algebraMap G M x)=genusEmbedding x := by
  letI : Algebra G Closure := genusEmbedding.toRingHom.toAlgebra
  exact (IsAlgClosed.lift : M →ₐ[G] Closure).commutes x

theorem genusEmbedding_maskRoot (m : ℕ) :
    genusEmbedding (ArithmeticCatalog.maskRoot m)=maskRoot m := by
  simp only [ArithmeticCatalog.maskRoot,maskRoot,map_prod]
  apply Finset.prod_congr rfl
  intro i _
  split <;> simp [genusEmbedding_root]

theorem catalog_data (i : Fin 17) :
    (NormExtensionCatalog.catalog i).x=catalogX i ∧
    (NormExtensionCatalog.catalog i).y=catalogY i ∧
    CatalogSquareclassData.masksA i=rootMasks i := by
  have h : ∀ i : Fin 17,
      (NormExtensionCatalog.catalog i).x=catalogX i ∧
      (NormExtensionCatalog.catalog i).y=catalogY i ∧
      CatalogSquareclassData.masksA i=rootMasks i := by decide +kernel
  exact h i

theorem genusEmbedding_catalog (i : Fin 17) :
    genusEmbedding (ArithmeticCatalog.catalogAlpha i)=catalogRadicand i := by
  simp only [ArithmeticCatalog.catalogAlpha,NormExtensionCatalog.alpha,map_add,map_mul,
    map_intCast,ArithmeticCatalog.rootsA,genusEmbedding_maskRoot,catalogRadicand,ArithmeticCatalog.masksA]
  rw [(catalog_data i).1,(catalog_data i).2.1,(catalog_data i).2.2]

theorem genusEmbedding_retainedRadicand (j : Fin 12) :
    genusEmbedding (ArithmeticRetained.retainedRadicand j)=retainedRadicand j := by
  have hw : CatalogSquareclassData.retainedWords j=wordMasks j := by
    have h : ∀ j : Fin 12,CatalogSquareclassData.retainedWords j=wordMasks j := by decide +kernel
    exact h j
  simp only [ArithmeticRetained.retainedRadicand,ArithmeticCatalog.wordRadicand,
    NormExtensionCatalog.radicand,map_prod,Finset.prod_filter,retainedRadicand,hw]
  apply Finset.prod_congr rfl
  intro i _
  split
  · exact genusEmbedding_catalog i
  · exact map_one _

/-- Every element of the aligned genus field lies in the independently
specified field generated by the nineteen radicals. -/
theorem genusEmbedding_mem (x : G) : genusEmbedding x∈field := by
  have hle : Algebra.adjoin ℚ
      (radicalSet (L := G) ArithmeticChosenGenus.radicands Finset.univ) ≤
      field.toSubalgebra.comap genusEmbedding := by
    apply Algebra.adjoin_le_iff.mpr
    rintro y ⟨i,_,hy⟩
    change genusEmbedding y∈field
    have hs : (genusEmbedding y)^2=(genusRoot i)^2 := by
      rw [←map_pow,hy,genusRoot_sq]
      exact genusEmbedding.commutes _
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hs with h | h
    · rw [h]; exact genusRoot_mem i
    · rw [h]; exact field.neg_mem (genusRoot_mem i)
  rw [ArithmeticChosenGenus.genusField_generated] at hle
  exact hle (show x∈(⊤ : Subalgebra ℚ G) from trivial)

theorem field_le_embedding_range : field ≤ embedding.fieldRange := by
  apply IntermediateField.adjoin_le_iff.mpr
  rintro x (⟨i,rfl⟩ | ⟨j,rfl⟩)
  · exact ⟨algebraMap G M (ArithmeticChosenGenus.roots i),
      (embedding_genus _).trans (genusEmbedding_root i)⟩
  · obtain ⟨r,hr⟩ := ArithmeticRetained.retainedField_contains_radical j
    have hs : (retainedRoot j)^2=(embedding r)^2 := by
      rw [retainedRoot_sq,←map_pow,hr,embedding_genus,genusEmbedding_retainedRadicand]
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hs with h | h
    · exact ⟨r,h.symm⟩
    · refine ⟨-r,?_⟩
      rw [map_neg]
      exact h.symm

theorem embedding_mem (x : M) : embedding x∈field := by
  let S : Subalgebra G M :=
    { carrier := {x | embedding x∈field}
      algebraMap_mem' := fun y => by
        change embedding (algebraMap G M y)∈field
        rw [embedding_genus]
        exact genusEmbedding_mem y
      zero_mem' := by simp
      one_mem' := by simp
      add_mem' := fun hx hy => by
        change embedding (_+_)∈field
        rw [map_add]
        exact field.add_mem hx hy
      mul_mem' := fun hx hy => by
        change embedding (_*_)∈field
        rw [map_mul]
        exact field.mul_mem hx hy }
  have hle : Algebra.adjoin G
      (radicalSet (L := M) ArithmeticRetained.retainedRadicand Finset.univ) ≤ S := by
    apply Algebra.adjoin_le_iff.mpr
    rintro y ⟨j,_,hy⟩
    change embedding y∈field
    have hs : (embedding y)^2=(retainedRoot j)^2 := by
      rw [←map_pow,hy,embedding_genus,genusEmbedding_retainedRadicand,retainedRoot_sq]
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hs with h | h
    · rw [h]; exact retainedRoot_mem j
    · rw [h]; exact field.neg_mem (retainedRoot_mem j)
  rw [ArithmeticRetained.retainedField_generated] at hle
  exact hle (show x∈(⊤ : Subalgebra G M) from trivial)

theorem embedding_fieldRange : embedding.fieldRange=field := by
  apply le_antisymm
  · rintro x ⟨y,rfl⟩
    exact embedding_mem y
  · exact field_le_embedding_range

/-- The independent nineteen-root definition is the actual arithmetic
retained field, up to an actual rational algebra isomorphism. -/
def equiv : Carrier ≃ₐ[ℚ] ArithmeticRetained.RetainedField :=
  (embedding.equivFieldRange.trans (IntermediateField.equivOfEq embedding_fieldRange)).symm

theorem degree : Module.finrank ℚ Carrier=524288 := by
  rw [equiv.toLinearEquiv.finrank_eq]
  exact ArithmeticRetained.retainedField_degree

end UnitDistance.CanonicalRetained
