module

public import UnitDistance.DyadicGradedMaps

@[expose] public section
set_option backward.privateInPublic true


/-! Kernel-checked identity minors for both orientations of the actual
dyadic graded multiplication map. Generated by the named Python script;
the mathematical trust base is the generic soundness proof and Lean kernel. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

namespace UnitDistance.Dyadic.Graded
open Filtration

theorem finrank_stage_zero : Module.finrank F (stage 0) = 32 := by
  rw [← AlgebraD.finrank_augmentationPower_eq]
  exact AlgebraD.finrank_augmentationPower_zero

def minorMasks0 (left : Bool) : Fin 1 → ℕ :=
  if left then ![1] else ![1]
def minorPivots0 : Fin 1 → Fin 3 × Fin 32 := ![(0, 15)]

theorem minor0_correct : ∀ left i j,
    joint left b2 pivots2 (combination b0 (minorMasks0 left i))
      (minorPivots0 j) = if i = j then 1 else 0 := by decide +kernel

theorem gradedKernel_0 : ∀ left v, v ∈ stage 0 →
    ((∀ k, sidedStep left k v ∈ stage 2) ↔ v ∈ stage 1) := by
  apply gradedKernel_of_certificate 0 b0 b2 pivots2
    stage_zero_eq stage_2_eq pivots2_correct
    (d := 1) ?_ minorMasks0 minorPivots0 minor0_correct
  rw [finrank_stage_zero, finrank_stage_1]

def minorMasks1 (left : Bool) : Fin 3 → ℕ :=
  if left then ![257, 5, 261] else ![257, 5, 261]
def minorPivots1 : Fin 3 → Fin 3 × Fin 32 := ![(0, 7), (0, 13), (1, 7)]

theorem minor1_correct : ∀ left i j,
    joint left b3 pivots3 (combination b1 (minorMasks1 left i))
      (minorPivots1 j) = if i = j then 1 else 0 := by decide +kernel

theorem gradedKernel_1 : ∀ left v, v ∈ stage 1 →
    ((∀ k, sidedStep left k v ∈ stage 3) ↔ v ∈ stage 2) := by
  apply gradedKernel_of_certificate 1 b1 b3 pivots3
    stage_1_eq stage_3_eq pivots3_correct
    (d := 3) ?_ minorMasks1 minorPivots1 minor1_correct
  rw [finrank_stage_1, finrank_stage_2]

def minorMasks2 (left : Bool) : Fin 5 → ℕ :=
  if left then ![279, 17, 3, 274, 22] else ![279, 17, 3, 274, 22]
def minorPivots2 : Fin 5 → Fin 3 × Fin 32 := ![(0, 5), (0, 11), (0, 14), (1, 5), (2, 5)]

theorem minor2_correct : ∀ left i j,
    joint left b4 pivots4 (combination b2 (minorMasks2 left i))
      (minorPivots2 j) = if i = j then 1 else 0 := by decide +kernel

theorem gradedKernel_2 : ∀ left v, v ∈ stage 2 →
    ((∀ k, sidedStep left k v ∈ stage 4) ↔ v ∈ stage 3) := by
  apply gradedKernel_of_certificate 2 b2 b4 pivots4
    stage_2_eq stage_4_eq pivots4_correct
    (d := 5) ?_ minorMasks2 minorPivots2 minor2_correct
  rw [finrank_stage_2, finrank_stage_3]

def minorMasks3 (left : Bool) : Fin 7 → ℕ :=
  if left then ![273, 387, 25, 15, 281, 399, 19] else ![273, 387, 25, 15, 281, 399, 412]
def minorPivots3 : Fin 7 → Fin 3 × Fin 32 := ![(0, 3), (0, 6), (0, 9), (0, 12), (1, 3), (1, 6), (2, 3)]

theorem minor3_correct : ∀ left i j,
    joint left b5 pivots5 (combination b3 (minorMasks3 left i))
      (minorPivots3 j) = if i = j then 1 else 0 := by decide +kernel

theorem gradedKernel_3 : ∀ left v, v ∈ stage 3 →
    ((∀ k, sidedStep left k v ∈ stage 5) ↔ v ∈ stage 4) := by
  apply gradedKernel_of_certificate 3 b3 b5 pivots5
    stage_3_eq stage_5_eq pivots5_correct
    (d := 7) ?_ minorMasks3 minorPivots3 minor3_correct
  rw [finrank_stage_3, finrank_stage_4]

def minorMasks4 (left : Bool) : Fin 7 → ℕ :=
  if left then ![138, 220, 19, 128, 211, 8, 31] else ![138, 220, 19, 128, 211, 8, 31]
def minorPivots4 : Fin 7 → Fin 3 × Fin 32 := ![(0, 1), (0, 4), (0, 10), (1, 1), (1, 4), (2, 1), (2, 4)]

theorem minor4_correct : ∀ left i j,
    joint left b6 pivots6 (combination b4 (minorMasks4 left i))
      (minorPivots4 j) = if i = j then 1 else 0 := by decide +kernel

theorem gradedKernel_4 : ∀ left v, v ∈ stage 4 →
    ((∀ k, sidedStep left k v ∈ stage 6) ↔ v ∈ stage 5) := by
  apply gradedKernel_of_certificate 4 b4 b6 pivots6
    stage_4_eq stage_6_eq pivots6_correct
    (d := 7) ?_ minorMasks4 minorPivots4 minor4_correct
  rw [finrank_stage_4, finrank_stage_5]

def minorMasks5 (left : Bool) : Fin 5 → ℕ :=
  if left then ![27, 15, 29, 8, 2] else ![27, 15, 2, 8, 29]
def minorPivots5 : Fin 5 → Fin 3 × Fin 32 := ![(0, 2), (0, 8), (1, 2), (2, 2), (2, 8)]

theorem minor5_correct : ∀ left i j,
    joint left b7 pivots7 (combination b5 (minorMasks5 left i))
      (minorPivots5 j) = if i = j then 1 else 0 := by decide +kernel

theorem gradedKernel_5 : ∀ left v, v ∈ stage 5 →
    ((∀ k, sidedStep left k v ∈ stage 7) ↔ v ∈ stage 6) := by
  apply gradedKernel_of_certificate 5 b5 b7 pivots7
    stage_5_eq stage_7_eq pivots7_correct
    (d := 5) ?_ minorMasks5 minorPivots5 minor5_correct
  rw [finrank_stage_5, finrank_stage_6]

def minorMasks6 (left : Bool) : Fin 3 → ℕ :=
  if left then ![7, 4, 2] else ![7, 4, 2]
def minorPivots6 : Fin 3 → Fin 3 × Fin 32 := ![(0, 0), (1, 0), (2, 0)]

theorem minor6_correct : ∀ left i j,
    joint left b8 pivots8 (combination b6 (minorMasks6 left i))
      (minorPivots6 j) = if i = j then 1 else 0 := by decide +kernel

theorem gradedKernel_6 : ∀ left v, v ∈ stage 6 →
    ((∀ k, sidedStep left k v ∈ stage 8) ↔ v ∈ stage 7) := by
  apply gradedKernel_of_certificate 6 b6 b8 pivots8
    stage_6_eq stage_8_eq pivots8_correct
    (d := 3) ?_ minorMasks6 minorPivots6 minor6_correct
  rw [finrank_stage_6, finrank_stage_7]

theorem gradedKernel_below_seven (n : ℕ) (hn : n < 7) (left : Bool)
    (v : V) (hv : v ∈ stage n) :
    (∀ k, sidedStep left k v ∈ stage (n + 2)) ↔ v ∈ stage (n + 1) := by
  interval_cases n
  · exact gradedKernel_0 left v hv
  · exact gradedKernel_1 left v hv
  · exact gradedKernel_2 left v hv
  · exact gradedKernel_3 left v hv
  · exact gradedKernel_4 left v hv
  · exact gradedKernel_5 left v hv
  · exact gradedKernel_6 left v hv

end UnitDistance.Dyadic.Graded
