module

public import UnitDistance.DyadicFiltration

@[expose] public section
set_option backward.privateInPublic true


/-! Exact row certificates generated by scripts/generate-dyadic-certificates.py.
The dimensions refer to the concrete coefficient-action recurrence in DyadicFiltration.
All finite identities use kernel-reduced `decide`, never native_decide. -/

set_option maxRecDepth 100000
set_option maxHeartbeats 8000000

open scoped BigOperators
namespace UnitDistance.Dyadic.Filtration

def b0 : Fin 32 → V := fun i => Pi.single i 1

theorem stage_zero_eq : stage 0 = spanRows b0 := by
  apply le_antisymm
  · intro v _
    have hv : v = ∑ i : Fin 32, v i • b0 i := by
      ext j
      simp [b0, Pi.single_apply]
    rw [hv]
    exact sum_mem_spanRows b0 _
  · exact le_top

def masks1 : Fin 31 → ℕ := ![2147483649, 2147483650, 2147483652, 2147483656, 2147483664, 2147483680, 2147483712, 2147483776, 2147483904, 2147484160, 2147484672, 2147485696, 2147487744, 2147491840, 2147500032, 2147516416, 2147549184, 2147614720, 2147745792, 2148007936, 2148532224, 2149580800, 2151677952, 2155872256, 2164260864, 2181038080, 2214592512, 2281701376, 2415919104, 2684354560, 3221225472]
def b1 : Fin 31 → V := rows masks1
def pivots1 : Fin 31 → Fin 32 := ![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
def lowerMasks1 : Fin 31 → ℕ := ![35184372629764, 35184439739686, 35184372629760, 35184439739654, 35184372629504, 35184439741702, 35184372613120, 35184439872774, 35184372629766, 35184439739702, 35184439738630, 35184372629888, 35184372637696, 35184439807238, 35184444067078, 35184372088832, 35184372629765, 35184439739694, 35184372629824, 35184439740166, 35184372633600, 35184439774470, 35184372875264, 35184441969926, 35184389406982, 35184573957430, 35185513480454, 35192962564480, 35253092114432, 35734195621126, 39582490578182]

theorem pivots1_correct : ∀ i j, b1 i (pivots1 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper1_correct : ∀ i k, step k (b0 i) =
    ∑ j, step k (b0 i) (pivots1 j) • b1 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower1_correct : ∀ j, b1 j =
    ∑ ik : Fin 32 × Fin 3,
      (if (lowerMasks1 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b0 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_1_eq : stage 1 = spanRows b1 := by
  rw [show stage 1 = next (stage 0) from rfl, stage_zero_eq]
  exact next_spanRows _ _ _ _
    upper1_correct lower1_correct

theorem finrank_stage_1 : Module.finrank F (stage 1) = 31 := by
  rw [stage_1_eq]
  exact finrank_spanRows b1 pivots1 pivots1_correct

def masks2 : Fin 28 → ℕ := ![545292289, 545292290, 2155905028, 2155905032, 545292304, 545292320, 2155905088, 2155905152, 2684387584, 2684387840, 33792, 34816, 2684391424, 2684395520, 49152, 2692808704, 2692874240, 8650752, 8912896, 2693791744, 2694840320, 12582912, 553648128, 570425344, 2214592512, 2281701376, 805306368, 3221225472]
def b2 : Fin 28 → V := rows masks2
def pivots2 : Fin 28 → Fin 32 := ![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 30]
def lowerMasks2 : Fin 28 → ℕ := ![549758386436, 549825496358, 69340166, 2230272, 549758386176, 549825498374, 69356806, 2097152, 549822991360, 549755881520, 67387654, 278912, 549822999814, 549755813888, 71716102, 549758386437, 549825496366, 69340230, 2230784, 549758390272, 549825531142, 69618950, 549839768576, 549823270150, 1141129478, 8590213504, 618542476550, 4398118227206]

theorem pivots2_correct : ∀ i j, b2 i (pivots2 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper2_correct : ∀ i k, step k (b1 i) =
    ∑ j, step k (b1 i) (pivots2 j) • b2 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower2_correct : ∀ j, b2 j =
    ∑ ik : Fin 31 × Fin 3,
      (if (lowerMasks2 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b1 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_2_eq : stage 2 = spanRows b2 := by
  rw [show stage 2 = next (stage 1) from rfl, stage_1_eq]
  exact next_spanRows _ _ _ _
    upper2_correct lower2_correct

theorem finrank_stage_2 : Module.finrank F (stage 2) = 28 := by
  rw [stage_2_eq]
  exact finrank_spanRows b2 pivots2 pivots2_correct

def masks3 : Fin 23 → ℕ := ![3902840961, 681615490, 1207959684, 2281701512, 1621139600, 2694881440, 3221225664, 1207968000, 2281710080, 1207993344, 2281736192, 3221237760, 3221274624, 1210122240, 2283929600, 1216610304, 2290614272, 3224371200, 3233808384, 1761607680, 2852126720, 3422552064, 4026531840]
def b3 : Fin 23 → V := rows masks3
def pivots3 : Fin 23 → Fin 32 := ![0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14, 16, 17, 18, 19, 20, 22, 24, 25, 26, 28]
def lowerMasks3 : Fin 23 → ℕ := ![8590295196, 8590281120, 8590196864, 8590248344, 16408, 32768, 98304, 8590196894, 8590248368, 8589987224, 8589934592, 122904, 4456448, 8590295197, 8590281128, 8590196928, 8590248856, 20504, 360448, 8606974110, 8590311808, 9663729048, 68719599640]

theorem pivots3_correct : ∀ i j, b3 i (pivots3 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper3_correct : ∀ i k, step k (b2 i) =
    ∑ j, step k (b2 i) (pivots3 j) • b3 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower3_correct : ∀ j, b3 j =
    ∑ ik : Fin 28 × Fin 3,
      (if (lowerMasks3 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b2 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_3_eq : stage 3 = spanRows b3 := by
  rw [show stage 3 = next (stage 2) from rfl, stage_2_eq]
  exact next_spanRows _ _ _ _
    upper3_correct lower3_correct

theorem finrank_stage_3 : Module.finrank F (stage 3) = 23 := by
  rw [stage_3_eq]
  exact finrank_spanRows b3 pivots3 pivots3_correct

def masks4 : Fin 16 → ℕ := ![306726945, 579373090, 1212696708, 2290649224, 817938480, 3233857728, 1509976320, 2852170240, 52224, 4026593280, 1516830720, 2863267840, 13369344, 4042260480, 855638016, 3422552064]
def b4 : Fin 16 → V := rows masks4
def pivots4 : Fin 16 → Fin 32 := ![0, 1, 2, 3, 4, 6, 8, 9, 10, 12, 16, 17, 18, 20, 24, 26]
def lowerMasks4 : Fin 16 → ℕ := ![8590009124, 2560, 66168, 512, 8590008320, 65536, 8590008606, 2088, 66616, 8589934592, 8590009125, 2568, 66104, 8590012416, 8589945208, 134284344]

theorem pivots4_correct : ∀ i j, b4 i (pivots4 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper4_correct : ∀ i k, step k (b3 i) =
    ∑ j, step k (b3 i) (pivots4 j) • b4 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower4_correct : ∀ j, b4 j =
    ∑ ik : Fin 23 × Fin 3,
      (if (lowerMasks4 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b3 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_4_eq : stage 4 = spanRows b4 := by
  rw [show stage 4 = next (stage 3) from rfl, stage_3_eq]
  exact next_spanRows _ _ _ _
    upper4_correct lower4_correct

theorem finrank_stage_4 : Module.finrank F (stage 4) = 16 := by
  rw [stage_4_eq]
  exact finrank_spanRows b4 pivots4 pivots4_correct

def masks5 : Fin 9 → ℕ := ![2522503785, 2863311530, 3422552268, 4042322160, 3422565120, 3422604288, 3425894400, 3435921408, 4278190080]
def b5 : Fin 9 → V := rows masks5
def pivots5 : Fin 9 → Fin 32 := ![0, 1, 2, 4, 8, 10, 16, 18, 24]
def lowerMasks5 : Fin 9 → ℕ := ![7, 8, 24, 4096, 29, 1088, 6, 88, 4363]

theorem pivots5_correct : ∀ i j, b5 i (pivots5 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper5_correct : ∀ i k, step k (b4 i) =
    ∑ j, step k (b4 i) (pivots5 j) • b5 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower5_correct : ∀ j, b5 j =
    ∑ ik : Fin 16 × Fin 3,
      (if (lowerMasks5 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b4 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_5_eq : stage 5 = spanRows b5 := by
  rw [show stage 5 = next (stage 4) from rfl, stage_4_eq]
  exact next_spanRows _ _ _ _
    upper5_correct lower5_correct

theorem finrank_stage_5 : Module.finrank F (stage 5) = 9 := by
  rw [stage_5_eq]
  exact finrank_spanRows b5 pivots5 pivots5_correct

def masks6 : Fin 4 → ℕ := ![869059635, 3435973836, 4278255360, 4294901760]
def b6 : Fin 4 → V := rows masks6
def pivots6 : Fin 4 → Fin 32 := ![0, 2, 8, 16]
def lowerMasks6 : Fin 4 → ℕ := ![272, 16, 258, 273]

theorem pivots6_correct : ∀ i j, b6 i (pivots6 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper6_correct : ∀ i k, step k (b5 i) =
    ∑ j, step k (b5 i) (pivots6 j) • b6 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower6_correct : ∀ j, b6 j =
    ∑ ik : Fin 9 × Fin 3,
      (if (lowerMasks6 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b5 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_6_eq : stage 6 = spanRows b6 := by
  rw [show stage 6 = next (stage 5) from rfl, stage_5_eq]
  exact next_spanRows _ _ _ _
    upper6_correct lower6_correct

theorem finrank_stage_6 : Module.finrank F (stage 6) = 4 := by
  rw [stage_6_eq]
  exact finrank_spanRows b6 pivots6 pivots6_correct

def masks7 : Fin 1 → ℕ := ![4294967295]
def b7 : Fin 1 → V := rows masks7
def pivots7 : Fin 1 → Fin 32 := ![0]
def lowerMasks7 : Fin 1 → ℕ := ![1]

theorem pivots7_correct : ∀ i j, b7 i (pivots7 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper7_correct : ∀ i k, step k (b6 i) =
    ∑ j, step k (b6 i) (pivots7 j) • b7 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower7_correct : ∀ j, b7 j =
    ∑ ik : Fin 4 × Fin 3,
      (if (lowerMasks7 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b6 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_7_eq : stage 7 = spanRows b7 := by
  rw [show stage 7 = next (stage 6) from rfl, stage_6_eq]
  exact next_spanRows _ _ _ _
    upper7_correct lower7_correct

theorem finrank_stage_7 : Module.finrank F (stage 7) = 1 := by
  rw [stage_7_eq]
  exact finrank_spanRows b7 pivots7 pivots7_correct

def masks8 : Fin 0 → ℕ := ![]
def b8 : Fin 0 → V := rows masks8
def pivots8 : Fin 0 → Fin 32 := ![]
def lowerMasks8 : Fin 0 → ℕ := ![]

theorem pivots8_correct : ∀ i j, b8 i (pivots8 j) =
    if i = j then 1 else 0 := by decide +kernel

theorem upper8_correct : ∀ i k, step k (b7 i) =
    ∑ j, step k (b7 i) (pivots8 j) • b8 j := by
  intro i k
  fin_cases i <;> fin_cases k <;> decide +kernel

theorem lower8_correct : ∀ j, b8 j =
    ∑ ik : Fin 1 × Fin 3,
      (if (lowerMasks8 j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)
        • step ik.2 (b7 ik.1) := by
  intro j
  fin_cases j <;> decide +kernel

theorem stage_8_eq : stage 8 = spanRows b8 := by
  rw [show stage 8 = next (stage 7) from rfl, stage_7_eq]
  exact next_spanRows _ _ _ _
    upper8_correct lower8_correct

theorem finrank_stage_8 : Module.finrank F (stage 8) = 0 := by
  rw [stage_8_eq]
  exact finrank_spanRows b8 pivots8 pivots8_correct

theorem stage_eight_eq_bot : stage 8 = ⊥ := by
  rw [stage_8_eq]
  simp [spanRows]

end UnitDistance.Dyadic.Filtration
