module

public import UnitDistance.KummerInvariantRadicand
public import Mathlib.RingTheory.Trace.Basic
public import Mathlib.RingTheory.Conductor
public import Mathlib.FieldTheory.KummerPolynomial
public import Mathlib.NumberTheory.KummerDedekind

@[expose] public section
set_option backward.privateInPublic true


/-! The integral order generated by a square root of -1 has conductor containing 2. -/
noncomputable section
namespace UnitDistance.GaussianQuadraticOrder
open QuadraticAlgebra KummerInvariant

 theorem trace_eq {A : Type*} [CommRing A] (d : A) (z : QuadraticAlgebra A d 0) :
    Algebra.trace A (QuadraticAlgebra A d 0) z = 2*z.re := by
  rw [Algebra.trace_eq_matrix_trace (QuadraticAlgebra.basis d 0)]
  simp [Matrix.trace, Algebra.leftMulMatrix_apply, LinearMap.toMatrix_apply, QuadraticAlgebra.basis]
  ring

variable {R F : Type*} [CommRing R] [Field F] [Algebra R F]

 theorem omega_sq : (omega : Extension (-1 : F))^2 = -1 := by
  ext <;> simp [pow_two]

 theorem omega_integral : IsIntegral R (omega : Extension (-1 : F)) := by
  apply IsIntegral.of_pow (n := 2) (by decide)
  rw [omega_sq]
  exact isIntegral_one.neg

variable [Fact (Nonsquare (-1 : F))]

 theorem double_coordinates_integral {z : Extension (-1 : F)} (hz : IsIntegral R z) :
    IsIntegral R (2*z.re) ∧ IsIntegral R (2*z.im) := by
  constructor
  · simpa only [trace_eq] using Algebra.isIntegral_trace (L := F) hz
  · have hh := Algebra.isIntegral_trace (L := F) ((omega_integral (R := R) (F := F)).neg.mul hz)
    have he : Algebra.trace F (Extension (-1 : F)) (-omega*z) = 2*z.im := by
      rw [trace_eq]
      simp
    rwa [he] at hh

variable [IsDomain R] [IsIntegrallyClosed R] [IsFractionRing R F]

 theorem double_coordinates {z : Extension (-1 : F)} (hz : IsIntegral R z) :
    ∃ a b : R, algebraMap R F a = 2*z.re ∧ algebraMap R F b = 2*z.im := by
  obtain ⟨hr,hi⟩ := double_coordinates_integral hz
  obtain ⟨a,ha⟩ := IsIntegrallyClosed.isIntegral_iff.mp hr
  obtain ⟨b,hb⟩ := IsIntegrallyClosed.isIntegral_iff.mp hi
  exact ⟨a,b,ha,hb⟩

section NumberField
open NumberField
variable (F : Type*) [Field F] [NumberField F] [Fact (Nonsquare (-1 : F))]
abbrev GaussianField := Extension (-1 : F)

def integralRoot : 𝓞 (GaussianField F) :=
  ⟨omega, omega_integral (R := ℤ)⟩

@[simp] theorem integralRoot_coe : (integralRoot F : GaussianField F) = omega := rfl

theorem two_mul_eq (x : 𝓞 (GaussianField F)) :
    ∃ a b : 𝓞 F, (2 : 𝓞 (GaussianField F))*x =
      algebraMap (𝓞 F) (𝓞 (GaussianField F)) a +
      algebraMap (𝓞 F) (𝓞 (GaussianField F)) b * integralRoot F := by
  have hx' : IsIntegral (𝓞 F) x := Algebra.IsIntegral.isIntegral x
  have hx : IsIntegral (𝓞 F) (x : GaussianField F) :=
    IsIntegral.map_of_comp_eq (RingHom.id (𝓞 F))
      (algebraMap (𝓞 (GaussianField F)) (GaussianField F))
      (by simpa only [RingHom.comp_id] using
        IsScalarTower.algebraMap_eq (𝓞 F) (𝓞 (GaussianField F)) (GaussianField F)) hx'
  obtain ⟨a,b,ha,hb⟩ := double_coordinates hx
  refine ⟨a,b,?_⟩
  apply RingOfIntegers.coe_injective
  change (2 : GaussianField F)*(x : GaussianField F) =
    algebraMap F (GaussianField F) (a : F) +
    algebraMap F (GaussianField F) (b : F) * omega
  change (a : F) = 2*(x : GaussianField F).re at ha
  change (b : F) = 2*(x : GaussianField F).im at hb
  rw [ha,hb]
  ext <;> simp

theorem two_mul_mem_adjoin (x : 𝓞 (GaussianField F)) :
    (2 : 𝓞 (GaussianField F))*x ∈ Algebra.adjoin (𝓞 F) {integralRoot F} := by
  obtain ⟨a,b,he⟩ := two_mul_eq F x
  rw [he]
  exact Subalgebra.add_mem _ (Subalgebra.algebraMap_mem _ a)
    (Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ b)
      (Algebra.subset_adjoin (Set.mem_singleton _)))

theorem two_mem_conductor :
    (2 : 𝓞 (GaussianField F)) ∈ conductor (𝓞 F) (integralRoot F) :=
  (mem_conductor_iff).mpr (two_mul_mem_adjoin F)

open Polynomial in
 theorem integralRoot_minpoly :
    minpoly (𝓞 F) (integralRoot F) = X^2-C (-1 : 𝓞 F) := by
  have hm : (X^2-C (-1 : 𝓞 F)).Monic := monic_X_pow_sub_C _ (by decide)
  have hiF : Irreducible (X^2-C (-1 : F)) :=
    (X_pow_sub_C_irreducible_iff_of_prime Nat.prime_two).mpr
      (Fact.out : Nonsquare (-1 : F))
  have hi : Irreducible (X^2-C (-1 : 𝓞 F)) :=
    (hm.irreducible_iff_irreducible_map_fraction_map (K := F)).mpr (by simpa using hiF)
  have hs : (integralRoot F)^2 = -1 := by
    apply RingOfIntegers.coe_injective
    exact omega_sq
  have hx : IsIntegral (𝓞 F) (integralRoot F) := Algebra.IsIntegral.isIntegral _
  have hd : minpoly (𝓞 F) (integralRoot F) ∣ X^2-C (-1 : 𝓞 F) :=
    minpoly.isIntegrallyClosed_dvd hx (by simp [hs])
  have ha := (hi.dvd_iff.mp hd).resolve_left (minpoly.not_isUnit (𝓞 F) (integralRoot F))
  exact (eq_of_monic_of_associated hm (minpoly.monic hx) ha).symm

 theorem conductor_coprime (P : Ideal (𝓞 F)) [hP : P.IsMaximal]
    (h2 : (2 : 𝓞 F) ∉ P) :
    (conductor (𝓞 F) (integralRoot F)).comap
      (algebraMap (𝓞 F) (𝓞 (GaussianField F))) ⊔ P = ⊤ := by
  let C := (conductor (𝓞 F) (integralRoot F)).comap
    (algebraMap (𝓞 F) (𝓞 (GaussianField F)))
  have hc : (2 : 𝓞 F) ∈ C := by
    change algebraMap (𝓞 F) (𝓞 (GaussianField F)) 2 ∈ conductor (𝓞 F) (integralRoot F)
    rw [map_ofNat]
    exact two_mem_conductor F
  by_contra hn
  have he : P = C ⊔ P := hP.eq_of_le hn le_sup_right
  exact h2 (he.symm ▸ (show (2 : 𝓞 F) ∈ C ⊔ P from (show C ≤ C ⊔ P from le_sup_left) hc))

open Polynomial in
/-- Away from2, reduction of the full ring of integers is the actual
quadratic polynomial quotient over the base residue field. -/
def oddPrimeQuotientEquiv (P : Ideal (𝓞 F)) [P.IsMaximal]
    (h2 : (2 : 𝓞 F) ∉ P) :
    𝓞 (GaussianField F) ⧸ P.map (algebraMap (𝓞 F) (𝓞 (GaussianField F))) ≃+*
      (𝓞 F ⧸ P)[X] ⧸ Ideal.span {X^2-C (-1 : 𝓞 F ⧸ P)} :=
  (KummerDedekind.quotMapEquivQuotQuotMap (conductor_coprime F P h2)
    (Algebra.IsIntegral.isIntegral (integralRoot F))).trans
    (Ideal.quotEquivOfEq (by rw [integralRoot_minpoly]; simp))

end NumberField
end UnitDistance.GaussianQuadraticOrder
