module

public import UnitDistance.IndependentQuadraticTower

@[expose] public section
set_option backward.privateInPublic true


/-!
# Generation by the actual square roots in a quadratic tower

The generating property is proved on actual quadratic coordinates. It will
permit automorphisms of the constructed fields to be compared on the actual
displayed radicals.
-/

noncomputable section
open scoped BigOperators
namespace UnitDistance.Multiquadratic
open QuadraticAlgebra KummerInvariant
variable {ι E L : Type*} [DecidableEq ι] [Field E] [CharZero E]
  [Field L] [CharZero L] [Algebra E L]

/-- All actual square roots of the selected base radicands. -/
def radicalSet (a : ι → E) (s : Finset ι) : Set L :=
  {x | ∃ i ∈ s, x^2 = algebraMap E L (a i)}

/-- Generation by actual selected roots is preserved when the next
actual square root is adjoined. -/
theorem adjoin_radicalSet_extension (a : ι → E) (s : Finset ι) (i : ι)
    [Fact (Nonsquare (algebraMap E L (a i)))]
    (hgen : Algebra.adjoin E (radicalSet (L := L) a s) = ⊤) :
    Algebra.adjoin E
      (radicalSet (L := Extension (algebraMap E L (a i))) a (insert i s)) = ⊤ := by
  let K := Extension (algebraMap E L (a i))
  let A : Subalgebra E K := Algebra.adjoin E (radicalSet a (insert i s))
  have hbase : ∀ x : L, algebraMap L K x ∈ A := by
    have hle : Algebra.adjoin E (radicalSet (L := L) a s) ≤
        A.comap (IsScalarTower.toAlgHom E L K) := by
      apply Algebra.adjoin_le_iff.mpr
      rintro x ⟨j,hj,hx⟩
      change algebraMap L K x ∈ A
      apply Algebra.subset_adjoin
      refine ⟨j,Finset.mem_insert_of_mem hj,?_⟩
      rw [← map_pow,hx,← IsScalarTower.algebraMap_apply E L K]
    rw [hgen] at hle
    intro x
    exact hle (show x ∈ (⊤ : Subalgebra E L) from trivial)
  have hroot : (omega : K) ∈ A := by
    apply Algebra.subset_adjoin
    refine ⟨i,Finset.mem_insert_self _ _,?_⟩
    rw [IsScalarTower.algebraMap_apply E L K]
    apply QuadraticAlgebra.ext <;> simp [K,pow_two]
  apply top_unique
  intro z _
  have hz : z = algebraMap L K z.re + algebraMap L K z.im * omega := by
    apply QuadraticAlgebra.ext <;> simp [K]
  rw [hz]
  exact A.add_mem (hbase z.re) (A.mul_mem (hbase z.im) hroot)

end UnitDistance.Multiquadratic

namespace UnitDistance.Multiquadratic
universe u
variable {ι : Type*} [DecidableEq ι] {E : Type u} [Field E] [CharZero E]
  (k : Type*) [Field k] [Algebra k E]

/-- A constructed actual Galois field generated by precisely the selected
quadratic radicals. -/
structure GeneratedGaloisTower (a : ι → E) (s : Finset ι)
    extends ActualGaloisTower k a s where
  generated : Algebra.adjoin E (radicalSet (L := Carrier) a s) = ⊤

/-- Independent invariant squareclasses construct an actual Galois field
of the expected degree which is generated by their actual square roots. -/
theorem exists_generatedGaloisTower [Module.Finite k E] [IsGalois k E]
    (a : ι → E) (ha : ∀ i, a i ≠ 0)
    (hind : ∀ t : Finset ι, t.Nonempty → ¬IsSquare (∏ j ∈ t, a j))
    (hinvariant : ∀ i (σ : Gal(E/k)), ∃ u : E, a i*u^2 = σ (a i))
    (s : Finset ι) : Nonempty (GeneratedGaloisTower k a s) := by
  induction s using Finset.induction_on with
  | empty =>
    exact ⟨{
      Carrier := E
      galois := IsGalois.self E
      squareKernel := squareKernel_self a
      degree := by simp
      generated := by
        apply top_unique
        intro x _
        exact (Algebra.adjoin E (radicalSet (L := E) a ∅)).algebraMap_mem x }⟩
  | @insert i s hi ih =>
    obtain ⟨T⟩ := ih
    let β : T.Carrier := algebraMap E T.Carrier (a i)
    letI : Fact (KummerInvariant.Nonsquare β) :=
      ⟨nonsquare_next_of_squareKernel a s i hi ha hind T.squareKernel⟩
    let L := KummerInvariant.Extension β
    letI : Module.Finite k T.Carrier := Module.Finite.trans E T.Carrier
    letI : Module.Finite E L := Module.Finite.trans T.Carrier L
    letI : IsGalois E L := KummerInvariant.isGalois_of_invariant β (by
      intro σ
      exact ⟨1,by simp [β]⟩)
    letI : IsGalois k L := KummerInvariant.isGalois_of_invariant β (by
      intro σ
      obtain ⟨u,hu⟩ := hinvariant i (σ.restrictNormal E)
      refine ⟨algebraMap E T.Carrier u,?_⟩
      change algebraMap E T.Carrier (a i) * (algebraMap E T.Carrier u)^2 =
        σ (algebraMap E T.Carrier (a i))
      rw [← map_pow,← map_mul,hu,AlgEquiv.restrictNormal_commutes])
    exact ⟨{
      Carrier := L
      squareKernel := squareKernel_extension a s i hi (ha i) T.squareKernel
      degree := by
        rw [KummerInvariant.absolute_finrank,T.degree]
        simp only [Finset.card_insert_of_notMem hi,pow_succ]
        omega
      generated := adjoin_radicalSet_extension a s i T.generated }⟩

end UnitDistance.Multiquadratic
