module

public import UnitDistance.GeneratedQuadraticTower
public import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure

@[expose] public section
set_option backward.privateInPublic true


/-! Actual embeddings of a field generated by square roots into another actual field. -/
noncomputable section
namespace UnitDistance.Multiquadratic
universe u
variable {ι : Type*} [DecidableEq ι] {E : Type u} [Field E] [CharZero E]
  {k : Type*} [Field k] [Algebra k E] {a : ι → E} {s : Finset ι}

/-- An actual target containing every selected radical admits an actual
embedding of the generated quadratic field. -/
theorem GeneratedGaloisTower.nonempty_embedding (T : GeneratedGaloisTower k a s)
    (M : Type*) [Field M] [Algebra E M]
    (hroots : ∀ i ∈ s, ∃ y : M, y^2=algebraMap E M (a i)) :
    Nonempty (T.Carrier →ₐ[E] M) := by
  let C := AlgebraicClosure M
  let φ : T.Carrier →ₐ[E] C := IsAlgClosed.lift
  let ψ : M →ₐ[E] C := IsScalarTower.toAlgHom E M C
  have hgen : Algebra.adjoin E (radicalSet (L := T.Carrier) a s) ≤ ψ.range.comap φ := by
    apply Algebra.adjoin_le_iff.mpr
    rintro x ⟨i,hi,hx⟩
    obtain ⟨y,hy⟩ := hroots i hi
    have hs : (φ x)^2 = (ψ y)^2 := by
      rw [← map_pow,← map_pow,hx,hy,AlgHom.commutes,AlgHom.commutes]
    change φ x ∈ ψ.range
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hs with h | h
    · exact ⟨y,h.symm⟩
    · refine ⟨-y,?_⟩
      change ψ (-y) = φ x
      rw [map_neg]
      exact h.symm
  rw [T.generated] at hgen
  have hrange : ∀ x, φ x ∈ ψ.range := fun x =>
    hgen (show x ∈ (⊤ : Subalgebra E T.Carrier) from trivial)
  exact ⟨(AlgEquiv.ofInjective ψ ψ.injective).symm.toAlgHom.comp (φ.codRestrict ψ.range hrange)⟩

end UnitDistance.Multiquadratic
