module

public import UnitDistance.GroupAugmentationFoxExact
public import Mathlib.Algebra.Module.Submodule.RestrictScalars
public import Mathlib.Algebra.Group.Subgroup.Basic

@[expose] public section
set_option backward.privateInPublic true


/-!
# The actual Fox relation sequence for a group presentation

A genuine normal-generation hypothesis for the kernel of free-word
evaluation implies that evaluated defining rows span the actual Fox
kernel over the target group algebra. This is an abstract group-presentation
theorem; no arithmetic or pro-finite presentation realization is assumed.
-/

noncomputable section
open scoped BigOperators
namespace UnitDistance.GroupAugmentation
variable (R G : Type*) [CommRing R] [Group G]
variable {ι : Type*} [Fintype ι]
variable (generators : ι → G)

/-- The same actual augmentation map is linear over the full group algebra
on the left, as required for relation-row generation. -/
def foxMapAlgebra : (ι → A R G) →ₗ[A R G] A R G where
  toFun a := ∑ i, a i * (delta R (generators i)-1)
  map_add' a b := by simp [add_mul,Finset.sum_add_distrib]
  map_smul' a b := by simp [smul_eq_mul,mul_assoc,Finset.mul_sum]

theorem foxMapAlgebra_apply (a : ι → A R G) :
    foxMapAlgebra R G generators a = foxMap R G generators a := rfl

/-- Conjugating an actual kernel word multiplies its evaluated row by the
actual group element of the conjugator. -/
theorem foxDerivative_conjugate (u w : FreeGroup ι)
    (hw : FreeGroup.lift generators w = 1) :
    foxDerivative R G generators (u*w*u⁻¹) =
      delta R (FreeGroup.lift generators u) • foxDerivative R G generators w := by
  funext i
  simp only [foxDerivative_mul,foxDerivative_inv,map_mul,hw,mul_one,
    Pi.smul_apply,smul_eq_mul,mul_neg,← mul_assoc,delta_mul,map_inv,mul_inv_cancel,
    delta_one,one_mul]
  abel

variable (M : Submodule (A R G) (ι → A R G))

/-- Kernel words whose actual evaluated derivative vanishes modulo the
specified actual relation-row module. -/
def foxWordsModulo : Subgroup (FreeGroup ι) where
  carrier := {w | FreeGroup.lift generators w = 1 ∧ foxDerivative R G generators w ∈ M}
  one_mem' := by simp
  mul_mem' {u v} hu hv := by
    refine ⟨by simp [hu.1,hv.1], ?_⟩
    have he : foxDerivative R G generators (u*v) =
        foxDerivative R G generators u + foxDerivative R G generators v := by
      funext i
      simp [foxDerivative_mul,hu.1]
    rw [he]
    exact M.add_mem hu.2 hv.2
  inv_mem' {u} hu := by
    refine ⟨by simp [hu.1], ?_⟩
    have he : foxDerivative R G generators u⁻¹ = -foxDerivative R G generators u := by
      funext i
      simp [foxDerivative_inv,hu.1]
    rw [he]
    exact M.neg_mem hu.2

instance foxWordsModulo_normal : (foxWordsModulo R G generators M).Normal where
  conj_mem w hw u := by
    refine ⟨by simp [hw.1], ?_⟩
    rw [foxDerivative_conjugate R G generators u w hw.1]
    exact M.smul_mem _ hw.2

variable (relations : Set (FreeGroup ι))

/-- The actual left group-algebra module generated by evaluated defining
Fox rows. No assigned relation costs enter this definition. -/
def foxRelationModule : Submodule (A R G) (ι → A R G) :=
  Submodule.span (A R G) (foxDerivative R G generators '' relations)

/-- For an actual group presentation, evaluated defining rows generate the
entire actual augmentation Fox kernel. Normal generation is kept explicit
so this theorem cannot stand in for an unproved global presentation. -/
theorem foxKernel_eq_relationModule
    (hgen : Subgroup.closure (Set.range generators) = ⊤)
    (hpresentation : (FreeGroup.lift generators).ker = Subgroup.normalClosure relations) :
    (foxMap R G generators).ker = (foxRelationModule R G generators relations).restrictScalars R := by
  have hrel (r : FreeGroup ι) (hr : r ∈ relations) : FreeGroup.lift generators r = 1 := by
    apply MonoidHom.mem_ker.mp
    rw [hpresentation]
    exact Subgroup.subset_normalClosure hr
  apply le_antisymm
  · rw [foxKernel_eq_span_derivatives R G generators hgen]
    apply Submodule.span_le.mpr
    rintro v ⟨w,hw,rfl⟩
    have hc : Subgroup.normalClosure relations ≤
        foxWordsModulo R G generators (foxRelationModule R G generators relations) := by
      apply Subgroup.normalClosure_le_normal
      intro r hr
      exact ⟨hrel r hr,Submodule.subset_span ⟨r,hr,rfl⟩⟩
    exact (hc (hpresentation ▸ (MonoidHom.mem_ker.mpr hw))).2
  · have hm : foxRelationModule R G generators relations ≤ (foxMapAlgebra R G generators).ker := by
      apply Submodule.span_le.mpr
      rintro v ⟨r,hr,rfl⟩
      exact foxDerivative_mem_ker R G generators r (hrel r hr)
    exact hm

end UnitDistance.GroupAugmentation
