module

public import UnitDistance.GroupAugmentationCompletedWords

@[expose] public section
set_option backward.privateInPublic true


/-!
# Actual Fox exactness for completed pro-2 presentation tests

Relators are actual completed words. The finite affine test, together with
simultaneous finite approximation, proves generation of the actual Fox
kernel without assuming that completed relators are finite words.
-/

noncomputable section
namespace UnitDistance.GroupAugmentation
universe u
variable (G : Type u) [Group G] [Finite G]
variable {ι : Type u} [Fintype ι]
local notation "F" => ZMod 2
variable (generators : ι → G) (relations : Set (CompletedWords ι))

/-- Completed relations vanish under actual evaluation, and generate the
presentation in every finite 2-group test. The relation set is a set of
actual completion elements, not a set of abstract free words. -/
structure CompletedProTwoPresentation : Prop where
  relators_vanish : ∀ r ∈ relations, completedWordEvaluation G generators r = 1
  finite_test : ∀ (N : Subgroup (FreeGroup ι)) [N.Normal] [Finite (FreeGroup ι ⧸ N)],
    IsPGroup 2 (FreeGroup ι ⧸ N) →
    (∀ r ∈ relations, completedFiniteMap (FreeGroup ι ⧸ N) (QuotientGroup.mk' N) r = 1) →
    (FreeGroup.lift generators).ker ≤ N

/-- The left module generated by the actual completed Fox derivatives. -/
def completedFoxRelationModule : Submodule (A F G) (ι → A F G) :=
  Submodule.span (A F G) (completedFoxDerivative G generators '' relations)

variable (hG : IsPGroup 2 G)

include hG in
/-- The actual Fox kernel is generated by actual completed relation rows
under the explicit finite-2 presentation test. The test quotient is proved
finite and a 2-group, and matching finite evaluations is proved by density. -/
theorem foxKernel_eq_completedRelationModule
    (hgen : Subgroup.closure (Set.range generators) = ⊤)
    (hpresentation : CompletedProTwoPresentation G generators relations) :
    (foxMap F G generators).ker =
      (completedFoxRelationModule G generators relations).restrictScalars F := by
  let M := completedFoxRelationModule G generators relations
  let N := foxWordsModulo F G generators M
  obtain ⟨hfinite,hTwo⟩ := foxWordsModulo_isFiniteTwoQuotient G generators hG M
  letI : Finite (FreeGroup ι ⧸ N) := hfinite
  have hN : ∀ r ∈ relations,
      completedFiniteMap (FreeGroup ι ⧸ N) (QuotientGroup.mk' N) r = 1 := by
    intro r hr
    obtain ⟨w,hwL,hwN⟩ := exists_word_matching_pair
      (FoxAffine F G (ι := ι)) (FreeGroup ι ⧸ N)
      (foxLift F G generators) (QuotientGroup.mk' N) r
    have he := congrArg (fun a : FoxAffine F G (ι := ι) => a.right) hwL
    change (foxLift F G generators w).right = completedWordEvaluation G generators r at he
    rw [foxLift_right,hpresentation.relators_vanish r hr] at he
    have hd := congrArg (fun a : FoxAffine F G (ι := ι) => a.left.toAdd) hwL
    change foxDerivative F G generators w = completedFoxDerivative G generators r at hd
    have hw : w ∈ N := by
      refine ⟨he,?_⟩
      rw [hd]
      exact Submodule.subset_span ⟨r,hr,rfl⟩
    rw [← hwN]
    exact (QuotientGroup.eq_one_iff w).mpr hw
  have hker := hpresentation.finite_test N hTwo hN
  apply le_antisymm
  · rw [foxKernel_eq_span_derivatives F G generators hgen]
    apply Submodule.span_le.mpr
    rintro v ⟨w,hw,rfl⟩
    exact (hker (MonoidHom.mem_ker.mpr hw)).2
  · have hm : M ≤ (foxMapAlgebra F G generators).ker := by
      apply Submodule.span_le.mpr
      rintro v ⟨r,hr,rfl⟩
      change foxMap F G generators (completedFoxDerivative G generators r) = 0
      rw [completedFoxDerivative_fundamental,hpresentation.relators_vanish r hr]
      simp
    exact hm

end UnitDistance.GroupAugmentation
