module

public import UnitDistance.LocalQuadraticSplit
public import Mathlib.RingTheory.Valuation.Integral

@[expose] public section
set_option backward.privateInPublic true


/-! # The actual integral closure in split quadratic coordinates

Integrality over a valuation ring corresponds to integrality in each split
factor. This identifies the full integral closure, without asserting that
the coefficient order generated by `i` is already integrally closed.
-/

noncomputable section

namespace UnitDistance.Local.QuadraticSplit

variable {K Γ : Type*} [Field K] [LinearOrderedCommGroupWithZero Γ]
variable (v : Valuation K Γ)

/-- The full integral closure, expressed using its defining integrality
predicate, is exactly the product of the two actual valuation rings. -/
theorem isIntegral_iff_coordinates_le_one (ι : K) (hι : ι ^ 2 = -1)
    (htwo : (2 : K) ≠ 0) (z : QuadraticAlgebra K (-1) 0) :
    IsIntegral v.integer z ↔
      v (coordinates ι z).1 ≤ 1 ∧ v (coordinates ι z).2 ≤ 1 := by
  let e := (splitEquiv ι hι htwo).restrictScalars v.integer
  change IsIntegral v.integer z ↔ v (e z).1 ≤ 1 ∧ v (e z).2 ≤ 1
  rw [← isIntegral_algEquiv e, IsIntegral.pair_iff,
    (Valuation.integer.integers v).isIntegral_iff_v_le_one,
    (Valuation.integer.integers v).isIntegral_iff_v_le_one]

/-- The split image of the full integral closure is the product unit ball;
surjectivity here uses the explicit half-sum/half-difference inverse. -/
theorem integralClosure_image (ι : K) (hι : ι ^ 2 = -1) (htwo : (2 : K) ≠ 0) :
    coordinates ι '' (integralClosure v.integer (QuadraticAlgebra K (-1) 0) :
      Set (QuadraticAlgebra K (-1) 0)) =
      (v.integer : Set K) ×ˢ (v.integer : Set K) := by
  ext x
  constructor
  · rintro ⟨z, hz, rfl⟩
    exact (isIntegral_iff_coordinates_le_one v ι hι htwo z).mp hz
  · intro hx
    obtain ⟨z, rfl⟩ := (coordinates_bijective ι hι htwo).surjective x
    exact ⟨z, (isIntegral_iff_coordinates_le_one v ι hι htwo z).mpr hx, rfl⟩

end UnitDistance.Local.QuadraticSplit
