module

public import UnitDistance.ClassGroupCoprime

@[expose] public section
set_option backward.privateInPublic true


/-! Odd ideal norms and avoidance of the actual primes above 2. -/
noncomputable section
namespace UnitDistance.OddNormDyadic
open ClassGroupCoprime NumberField IsDedekindDomain UniqueFactorizationMonoid
open scoped nonZeroDivisors BigOperators Classical

 theorem two_isUnit_of_odd_natCard (A : Type*) [CommRing A] [Finite A]
    (h : Odd (Nat.card A)) : IsUnit (2 : A) := by
  obtain ⟨b,hb⟩ := (h.coprime_two_right.nsmul_right_bijective (G := A)).surjective 1
  exact isUnit_iff_exists_inv.mpr ⟨b, by simpa [two_nsmul, two_mul] using hb⟩

 theorem coprime_span_of_isUnit_quotient_mk {A : Type*} [CommRing A]
    (I : Ideal A) (a : A) (h : IsUnit (Ideal.Quotient.mk I a)) :
    IsCoprime I (Ideal.span {a}) := by
  obtain ⟨b,hb⟩ := isUnit_iff_exists_inv.mp h
  obtain ⟨c,rfl⟩ := Ideal.Quotient.mk_surjective b
  have he : 1-a*c ∈ I := by
    apply Ideal.Quotient.eq_zero_iff_mem.mp
    rw [map_sub,map_mul,map_one,hb,sub_self]
  apply Ideal.isCoprime_iff_sup_eq.mpr
  apply (Ideal.eq_top_iff_one _).mpr
  exact Submodule.mem_sup.mpr ⟨1-a*c,he,a*c,
    Ideal.mem_span_singleton.mpr ⟨c,rfl⟩,by ring⟩

 theorem odd_absNorm_iff_coprime_two (F : Type*) [Field F] [NumberField F]
    (I : (Ideal (𝓞 F))⁰) :
    Odd (Ideal.absNorm (I : Ideal (𝓞 F))) ↔ IsCoprime (I : Ideal (𝓞 F)) (Ideal.span {(2:𝓞 F)}) := by
  letI : Finite ((𝓞 F) ⧸ (I : Ideal (𝓞 F))) :=
    (Ideal.absNorm_ne_zero_iff _).mp (Ideal.absNorm_ne_zero_of_nonZeroDivisors I)
  change Odd (Nat.card ((𝓞 F) ⧸ (I : Ideal (𝓞 F)))) ↔ _
  constructor
  · intro h
    apply coprime_span_of_isUnit_quotient_mk
    simpa only [map_ofNat] using two_isUnit_of_odd_natCard _ h
  · intro h
    apply odd_natCard_of_two_isUnit ((𝓞 F) ⧸ (I : Ideal (𝓞 F)))
    simpa only [map_ofNat] using isUnit_quotient_mk_of_coprime_span _ _ h

theorem powerset_indicator (A : Type*) [CommRing A] {ι : Type*}
    (p : ι → Prop) (S : Finset ι) :
    (if ∀ i ∈ S, ¬p i then (1:A) else 0) =
      ∑ T ∈ S.powerset, (-1:A)^T.card * (if ∀ i ∈ T, p i then 1 else 0) := by
  calc
    _ = ∏ i ∈ S, (if ¬p i then (1:A) else 0) := (Finset.prod_boole (s := S) (p := fun i => ¬p i)).symm
    _ = ∏ i ∈ S, ((1:A)-(if p i then 1 else 0)) := by
      apply Finset.prod_congr rfl
      intro i _
      by_cases h : p i <;> simp [h]
    _ = _ := by
      rw [Finset.prod_sub]
      simp only [Finset.prod_const_one,mul_one,Finset.prod_boole]

section Dedekind
variable {R : Type*} [CommRing R] [IsDedekindDomain R]

theorem coprime_iff_avoids_prime_factors (I D : Ideal R) (hD : D ≠ ⊥) :
    IsCoprime I D ↔ ∀ P ∈ normalizedFactors D, ¬I ≤ P := by
  constructor
  · intro h P hP hIP
    have hp := (Ideal.mem_normalizedFactors_iff hD).mp hP
    have he : (⊤ : Ideal R) ≤ P := by
      rw [← Ideal.isCoprime_iff_sup_eq.mp h]
      exact sup_le hIP hp.2
    exact hp.1.ne_top (top_le_iff.mp he)
  · intro h
    apply Ideal.isCoprime_iff_sup_eq.mpr
    by_contra hn
    obtain ⟨P,hP,hIP⟩ := Ideal.exists_le_maximal (I ⊔ D) hn
    have hmem : P ∈ normalizedFactors D :=
      (Ideal.mem_normalizedFactors_iff hD).mpr ⟨hP.isPrime, le_sup_right.trans hIP⟩
    exact h P hmem (le_sup_left.trans hIP)

end Dedekind

section NumberField
variable (F : Type*) [Field F] [NumberField F]

 theorem twoIdeal_ne_zero : Ideal.span {(2:𝓞 F)} ≠ ⊥ := by
  rw [ne_eq, Ideal.span_singleton_eq_bot]
  norm_num

 theorem twoIdeal_ne_top : Ideal.span {(2:𝓞 F)} ≠ ⊤ := by
  intro h
  have he := congrArg Ideal.absNorm h
  change Ideal.absNorm (Ideal.span {((2:ℕ):𝓞 F)}) = Ideal.absNorm (⊤ : Ideal (𝓞 F)) at he
  rw [Ideal.absNorm_span_natCast, Ideal.absNorm_top] at he
  have hd : 0 < Module.finrank ℤ (𝓞 F) :=
    (Module.finrank_pos_iff_of_free ℤ (𝓞 F)).mpr inferInstance
  have hl := Nat.le_self_pow hd.ne' 2
  omega

 theorem odd_norm_iff_coprime_two (a : 𝓞 F) :
    Odd (Algebra.norm ℤ a) ↔ IsCoprime (Ideal.span {a}) (Ideal.span {(2:𝓞 F)}) := by
  by_cases ha : a = 0
  · subst a
    simp only [Algebra.norm_zero, Int.not_odd_zero, Ideal.span_singleton_zero, false_iff]
    intro h
    have he := Ideal.isCoprime_iff_sup_eq.mp h
    exact twoIdeal_ne_top F (by simpa using he)
  · have hi : Ideal.span {a} ∈ (Ideal (𝓞 F))⁰ :=
      mem_nonZeroDivisors_iff_ne_zero.mpr (by simpa using ha)
    have h := odd_absNorm_iff_coprime_two F ⟨Ideal.span {a},hi⟩
    rw [Ideal.absNorm_span_singleton] at h
    simpa using h

 theorem odd_norm_iff_avoids_dyadic (a : 𝓞 F) :
    Odd (Algebra.norm ℤ a) ↔
      ∀ P ∈ normalizedFactors (Ideal.span {(2:𝓞 F)}), a ∉ P := by
  rw [odd_norm_iff_coprime_two, coprime_iff_avoids_prime_factors _ _ (twoIdeal_ne_zero F)]
  simp only [Ideal.span_singleton_le_iff_mem]

/-- Actual prime ideals dividing the ideal generated by 2. -/
abbrev DyadicPrime := ↥(normalizedFactors (Ideal.span {(2:𝓞 F)})).toFinset

theorem dyadicPrime_prime (P : DyadicPrime F) : Prime (P : Ideal (𝓞 F)) :=
  prime_of_normalized_factor _ (Multiset.mem_toFinset.mp P.2)

theorem dyadicPrime_contains_two (P : DyadicPrime F) : (2:𝓞 F) ∈ (P : Ideal (𝓞 F)) := by
  have h := (Ideal.mem_normalizedFactors_iff (twoIdeal_ne_zero F)).mp
    (Multiset.mem_toFinset.mp P.2)
  exact h.2 (Ideal.mem_span_singleton_self _)

theorem odd_norm_iff_avoids_dyadicPrime (a : 𝓞 F) :
    Odd (Algebra.norm ℤ a) ↔ ∀ P : DyadicPrime F, a ∉ (P : Ideal (𝓞 F)) := by
  rw [odd_norm_iff_avoids_dyadic]
  constructor
  · exact fun h P => h P (Multiset.mem_toFinset.mp P.2)
  · exact fun h P hP => h ⟨P,Multiset.mem_toFinset.mpr hP⟩

theorem dyadic_prod_mem_iff (S : Finset (DyadicPrime F)) (a : 𝓞 F) :
    a ∈ ∏ P ∈ S, (P : Ideal (𝓞 F)) ↔ ∀ P ∈ S, a ∈ (P : Ideal (𝓞 F)) := by
  have he := IsDedekindDomain.inf_pow_eq_prod_of_prime S
    (fun P : DyadicPrime F => (P : Ideal (𝓞 F))) (fun _ => 1)
    (fun P _ => dyadicPrime_prime F P)
    (fun P _ Q _ h => Subtype.coe_injective.ne h)
  simp only [pow_one] at he
  rw [← he, Finset.inf_eq_iInf]
  simp only [Ideal.mem_iInf]

theorem coprime_dyadicPrime (J : (Ideal (𝓞 F))⁰)
    (hJ : Odd (Ideal.absNorm (J : Ideal (𝓞 F)))) (P : DyadicPrime F) :
    IsCoprime (J : Ideal (𝓞 F)) (P : Ideal (𝓞 F)) := by
  have hc := Ideal.isCoprime_iff_sup_eq.mp ((odd_absNorm_iff_coprime_two F J).mp hJ)
  apply Ideal.isCoprime_iff_sup_eq.mpr
  apply top_unique
  rw [← hc]
  exact sup_le_sup_left ((Ideal.span_singleton_le_iff_mem _).mpr (dyadicPrime_contains_two F P)) _

/-- The actual integral ideal used for one inclusion-exclusion term. -/
def dyadicSubideal (J : (Ideal (𝓞 F))⁰) (S : Finset (DyadicPrime F)) :
    (Ideal (𝓞 F))⁰ :=
  ⟨(J : Ideal (𝓞 F)) * ∏ P ∈ S, (P : Ideal (𝓞 F)),
    mem_nonZeroDivisors_iff_ne_zero.mpr (mul_ne_zero (nonZeroDivisors.coe_ne_zero J)
      (Finset.prod_ne_zero_iff.mpr (fun P _ => (dyadicPrime_prime F P).ne_zero)))⟩

theorem mem_dyadicSubideal_iff (J : (Ideal (𝓞 F))⁰)
    (hJ : Odd (Ideal.absNorm (J : Ideal (𝓞 F)))) (S : Finset (DyadicPrime F)) (a : 𝓞 F) :
    a ∈ (dyadicSubideal F J S : Ideal (𝓞 F)) ↔
      a ∈ (J : Ideal (𝓞 F)) ∧ ∀ P ∈ S, a ∈ (P : Ideal (𝓞 F)) := by
  have hc : IsCoprime (J : Ideal (𝓞 F)) (∏ P ∈ S, (P : Ideal (𝓞 F))) :=
    IsCoprime.prod_right (fun P _ => coprime_dyadicPrime F J hJ P)
  change a ∈ (J : Ideal (𝓞 F)) * _ ↔ _
  rw [Ideal.mul_eq_inf_of_isCoprime hc, Ideal.mem_inf, dyadic_prod_mem_iff]

theorem indicator_dyadicSubideal (A : Type*) [CommRing A]
    (J : (Ideal (𝓞 F))⁰) (hJ : Odd (Ideal.absNorm (J : Ideal (𝓞 F))))
    (a : 𝓞 F) (w : A) :
    (if a ∈ (J : Ideal (𝓞 F)) ∧ Odd (Algebra.norm ℤ a) then w else 0) =
      ∑ S ∈ (Finset.univ : Finset (DyadicPrime F)).powerset,
        (-1:A)^S.card * (if a ∈ (dyadicSubideal F J S : Ideal (𝓞 F)) then w else 0) := by
  by_cases ha : a ∈ (J : Ideal (𝓞 F))
  · have h := powerset_indicator A (fun P : DyadicPrime F => a ∈ (P : Ideal (𝓞 F))) Finset.univ
    simp only [Finset.mem_univ,forall_true_left] at h
    simp only [← odd_norm_iff_avoids_dyadicPrime F a] at h
    have hm := congrArg (fun r : A => r*w) h
    simpa only [mem_dyadicSubideal_iff F J hJ,ha,true_and,Finset.sum_mul,
      ite_mul,one_mul,zero_mul,mul_assoc] using hm
  · simp only [mem_dyadicSubideal_iff F J hJ,ha,false_and,↓reduceIte,mul_zero,
      Finset.sum_const_zero]

end NumberField
end UnitDistance.OddNormDyadic
