module

public import UnitDistance.OddTameRadicalAction
public import UnitDistance.GaloisCyclicResidueInertia

@[expose] public section
set_option backward.privateInPublic true


/-! The actual residue quotient is generated by a chosen Frobenius lift. -/
noncomputable section
set_option backward.isDefEq.respectTransparency false
universe u v w x
namespace UnitDistance.OddTame
open RamificationTheory.HilbertRamification.Higher
open ValuationTheory.DiscreteValuationField.ResidueField
open ValuationTheory.DiscreteValuationField

variable {K : Type u} {L : Type w} [Field K] [Field L] [Algebra K L]
  (base : CompleteDVF.{u,v} K) (target : CompleteDVF.{w,x} L)
  [FiniteDimensional K L] [base.valuation.HasExtension target.valuation] [IsGalois K L]

abbrev completeResidueAction :=
  RamificationTheory.HilbertRamification.CompleteDVF.residueAction
    (base:=base) (target:=target)

theorem inertia_eq_ker_completeResidueAction :
    lowerRamificationGroup (base:=base.toDVF) (target:=target.toDVF)
      (completeUnique base target) ((0 : ℕ) : ℝ) =
      (completeResidueAction base target).ker := by
  ext σ
  rw [mem_lowerRamificationGroup_nat_iff, MonoidHom.mem_ker]
  constructor
  · intro h
    apply AlgEquiv.ext
    intro z
    obtain ⟨a,rfl⟩ := IsLocalRing.residue_surjective z
    change completeResidueAction base target σ (target.residueMap a)=target.residueMap a
    rw [residueAction_apply_residue]
    apply sub_eq_zero.mp
    rw [← map_sub, IsLocalRing.residue_eq_zero_iff]
    simpa using h a
  · intro h a
    have ha := congrArg (fun f : Gal(target.residueField/base.residueField) ↦
      f (target.residueMap a)) h
    change completeResidueAction base target σ (target.residueMap a)=target.residueMap a at ha
    rw [residueAction_apply_residue] at ha
    simpa only [Nat.reduceAdd, pow_one, ← IsLocalRing.residue_eq_zero_iff,
      map_sub, sub_eq_zero] using ha

theorem exists_generating_frobenius [Finite base.residueField] [Finite target.residueField] :
    ∃ φ : Gal(L/K),
      (∀ a : target.valuationSubringˣ,
        residueUnit (dvfValuationSubringUnitAut (completeUnique base target) φ a)=
          (residueUnit a)^(Nat.card base.residueField)) ∧
      ∀ σ : Gal(L/K), ∃ n : ℕ,
        completeResidueAction base target σ=(completeResidueAction base target φ)^n := by
  letI := Fintype.ofFinite base.residueField
  let F := FiniteField.frobeniusAlgEquivOfAlgebraic base.residueField target.residueField
  obtain ⟨φ,hφ⟩ := RamificationTheory.HilbertRamification.CompleteDVF.residueAction_surjective_of_isGalois
    (base:=base) (target:=target) F
  refine ⟨φ,?_,?_⟩
  · intro a
    apply Units.ext
    change target.residueMap (valuationSubringAutOfUniqueExtension (completeUnique base target) φ a)=
      (target.residueMap a)^(Nat.card base.residueField)
    rw [← residueAction_apply_residue,hφ]
    simp [F,Nat.card_eq_fintype_card]
  · intro σ
    obtain ⟨n,hn⟩ := (FiniteField.bijective_frobeniusAlgEquivOfAlgebraic_pow
      (K:=base.residueField) (L:=target.residueField)).2 (completeResidueAction base target σ)
    refine ⟨n,?_⟩
    rw [hφ]
    exact hn.symm

end UnitDistance.OddTame
