module

public import UnitDistance.KummerInvariantRadicand
public import Mathlib.FieldTheory.KummerPolynomial
public import Mathlib.NumberTheory.NumberField.Discriminant.Different

@[expose] public section
set_option backward.privateInPublic true


/-! Actual ramification control for quadratic extensions generated by integral
square roots. The different is constrained by the derivative of the actual
minimal polynomial, so no ramification or discriminant identity is an input. -/
noncomputable section
open NumberField Polynomial
namespace UnitDistance.QuadraticRamification
open UnitDistance.KummerInvariant
variable (F K : Type*) [Field F] [NumberField F] [Field K] [NumberField K] [Algebra F K]

/-- The actual minimal polynomial of an integral square root of a nonsquare. -/
theorem minpoly_integral_sqrt (a : 𝓞 F) (ha : Nonsquare (a:F))
    (x : 𝓞 K) (hx : x^2 = algebraMap (𝓞 F) (𝓞 K) a) :
    minpoly (𝓞 F) x = X^2-C a := by
  have hm : (X^2-C a).Monic := monic_X_pow_sub_C _ (by decide)
  have hiF : Irreducible (X^2-C (a:F)) :=
    (X_pow_sub_C_irreducible_iff_of_prime Nat.prime_two).mpr ha
  have hi : Irreducible (X^2-C a) :=
    (hm.irreducible_iff_irreducible_map_fraction_map (K := F)).mpr (by simpa using hiF)
  have hint : IsIntegral (𝓞 F) x := Algebra.IsIntegral.isIntegral _
  have hd : minpoly (𝓞 F) x ∣ X^2-C a := minpoly.isIntegrallyClosed_dvd hint (by simp [hx])
  have hassoc := (hi.dvd_iff.mp hd).resolve_left (minpoly.not_isUnit (𝓞 F) x)
  exact (eq_of_monic_of_associated hm (minpoly.monic hint) hassoc).symm

/-- Twice the integral square root belongs to the actual relative different. -/
theorem two_mul_sqrt_mem_different (a : 𝓞 F) (ha : Nonsquare (a:F))
    (x : 𝓞 K) (hx : x^2 = algebraMap (𝓞 F) (𝓞 K) a)
    (hgen : Algebra.adjoin F {(x:K)} = ⊤) :
    2*x ∈ differentIdeal (𝓞 F) (𝓞 K) := by
  have h := aeval_derivative_mem_differentIdeal (𝓞 F) F K x hgen
  rw [minpoly_integral_sqrt F K a ha x hx] at h
  norm_num at h ⊢
  simpa only [map_ofNat] using h

attribute [local instance] FractionRing.liftAlgebra FractionRing.isScalarTower_liftAlgebra

/-- A prime not containing twice the radicand is unramified in the actual
quadratic extension. -/
theorem isUnramifiedAt_of_not_mem (a : 𝓞 F) (ha : Nonsquare (a:F))
    (x : 𝓞 K) (hx : x^2 = algebraMap (𝓞 F) (𝓞 K) a)
    (hgen : Algebra.adjoin F {(x:K)} = ⊤)
    (P : Ideal (𝓞 K)) [P.IsPrime]
    (h2 : (2:𝓞 K) ∉ P) (haP : algebraMap (𝓞 F) (𝓞 K) a ∉ P) :
    Algebra.IsUnramifiedAt (𝓞 F) P := by
  apply not_dvd_differentIdeal_iff.mp
  intro hd
  have hm := (Ideal.dvd_iff_le.mp hd) (two_mul_sqrt_mem_different F K a ha x hx hgen)
  have hxP : x ∈ P := (Ideal.IsPrime.mem_or_mem inferInstance hm).resolve_left h2
  apply haP
  rw [← hx, pow_two]
  exact P.mul_mem_left x hxP

/-- A one-element exclusion form convenient for support calculations. -/
theorem isUnramifiedAt_of_not_mem_two_mul (a : 𝓞 F) (ha : Nonsquare (a:F))
    (x : 𝓞 K) (hx : x^2 = algebraMap (𝓞 F) (𝓞 K) a)
    (hgen : Algebra.adjoin F {(x:K)} = ⊤)
    (P : Ideal (𝓞 K)) [P.IsPrime]
    (hP : algebraMap (𝓞 F) (𝓞 K) (2*a) ∉ P) :
    Algebra.IsUnramifiedAt (𝓞 F) P := by
  apply isUnramifiedAt_of_not_mem F K a ha x hx hgen P
  · intro h2
    apply hP
    simpa only [map_mul, map_ofNat] using P.mul_mem_right (algebraMap (𝓞 F) (𝓞 K) a) h2
  · intro haP
    apply hP
    simpa only [map_mul, map_ofNat] using P.mul_mem_left (2:𝓞 K) haP

/-- A catalog norm identity excludes ramification without computing an absolute
field norm. The conjugate factor only needs to be an actual integral element. -/
theorem isUnramifiedAt_of_integral_product (a b : 𝓞 F) (n : ℤ)
    (hab : a*b = n) (ha : Nonsquare (a:F))
    (x : 𝓞 K) (hx : x^2 = algebraMap (𝓞 F) (𝓞 K) a)
    (hgen : Algebra.adjoin F {(x:K)} = ⊤)
    (P : Ideal (𝓞 K)) [P.IsPrime]
    (h2 : (2:𝓞 K) ∉ P) (hn : (n:𝓞 K) ∉ P) :
    Algebra.IsUnramifiedAt (𝓞 F) P := by
  apply isUnramifiedAt_of_not_mem F K a ha x hx hgen P h2
  intro haP
  apply hn
  have he : algebraMap (𝓞 F) (𝓞 K) a * algebraMap (𝓞 F) (𝓞 K) b = n := by
    rw [← map_mul, hab, map_intCast]
  rw [← he]
  exact P.mul_mem_right _ haP

/-- Rational-prime support version of the integral product criterion. -/
theorem isUnramifiedAt_of_prime_not_dvd_integral_product (a b : 𝓞 F) (n : ℤ)
    (hab : a*b = n) (ha : Nonsquare (a:F))
    (x : 𝓞 K) (hx : x^2 = algebraMap (𝓞 F) (𝓞 K) a)
    (hgen : Algebra.adjoin F {(x:K)} = ⊤)
    (p : ℤ) (P : Ideal (𝓞 K)) [P.IsPrime]
    [P.LiesOver (Ideal.span {p})]
    (h2 : ¬ p ∣ 2) (hn : ¬ p ∣ n) :
    Algebra.IsUnramifiedAt (𝓞 F) P := by
  apply isUnramifiedAt_of_integral_product F K a b n hab ha x hx hgen P
  · intro h
    apply h2
    apply Ideal.mem_span_singleton.mp
    apply (Ideal.mem_of_liesOver P (Ideal.span {p}) (2:ℤ)).mpr
    simpa only [map_ofNat] using h
  · intro h
    apply hn
    apply Ideal.mem_span_singleton.mp
    apply (Ideal.mem_of_liesOver P (Ideal.span {p}) n).mpr
    rw [algebraMap_int_eq]
    change (n : 𝓞 K) ∈ P
    exact h

section ActualQuadraticCarrier
open QuadraticAlgebra
variable {F K}
variable (F) (a : 𝓞 F) [Fact (Nonsquare (a:F))]

/-- The integral generator in the actual quadratic carrier. -/
def integralSqrt : 𝓞 (Extension (a:F)) :=
  ⟨omega, by
    apply IsIntegral.of_pow (n := 2) (by decide)
    have hs : (omega : Extension (a:F))^2 = algebraMap F (Extension (a:F)) (a:F) := by
      ext <;> simp [pow_two]
    rw [hs]
    exact map_isIntegral_int (algebraMap F (Extension (a:F))) a.property⟩

@[simp] theorem integralSqrt_sq :
    (integralSqrt F a)^2 = algebraMap (𝓞 F) (𝓞 (Extension (a:F))) a := by
  apply RingOfIntegers.coe_injective
  change (omega : Extension (a:F))^2 = algebraMap F (Extension (a:F)) (a:F)
  ext <;> simp [pow_two]

/-- The displayed root actually generates the quadratic field over its base. -/
theorem integralSqrt_adjoin : Algebra.adjoin F {(integralSqrt F a : Extension (a:F))} = ⊤ := by
  apply top_unique
  intro z _
  have he : z = algebraMap F (Extension (a:F)) z.re +
      algebraMap F (Extension (a:F)) z.im * (integralSqrt F a : Extension (a:F)) := by
    ext <;> simp [integralSqrt, QuadraticAlgebra.omega]
  rw [he]
  exact Subalgebra.add_mem _ (Subalgebra.algebraMap_mem _ _)
    (Subalgebra.mul_mem _ (Subalgebra.algebraMap_mem _ _)
      (Algebra.subset_adjoin (Set.mem_singleton _)))

/-- Ramification criterion for the independently defined quadratic carrier. -/
theorem extension_isUnramifiedAt (P : Ideal (𝓞 (Extension (a:F)))) [P.IsPrime]
    (hP : algebraMap (𝓞 F) (𝓞 (Extension (a:F))) (2*a) ∉ P) :
    Algebra.IsUnramifiedAt (𝓞 F) P :=
  isUnramifiedAt_of_not_mem_two_mul F (Extension (a:F)) a Fact.out
    (integralSqrt F a) (integralSqrt_sq F a) (integralSqrt_adjoin F a) P hP

end ActualQuadraticCarrier

end UnitDistance.QuadraticRamification
