module

public import UnitDistance.RelativeUnitsHerbrand
public import Mathlib.NumberTheory.NumberField.Units.Regulator

@[expose] public section
set_option backward.privateInPublic true


/-!
# The actual norm exact sequence of logarithmic unit lattices

The ambient lattices and logarithms are Mathlib's ordinary weighted Dirichlet
unit lattices. The relative group is the image of the actual norm-one units.
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false
open scoped NumberField Classical
open NumberField NumberField.Units NumberField.Units.dirichletUnitTheorem

namespace UnitDistance.RelativeUnits

variable (K : Type) [Field K] [NumberField K]

/-- The ordinary weighted logarithm with codomain restricted to its actual lattice. -/
def unitLog : Additive (𝓞 K)ˣ →+ unitLattice K :=
  (logEmbedding K).codRestrict (unitLattice K).toAddSubgroup
    (fun u ↦ ⟨u, Submodule.mem_top, rfl⟩)

@[simp] theorem coe_unitLog (u : Additive (𝓞 K)ˣ) :
    (unitLog K u : logSpace K) = logEmbedding K u := rfl

theorem unitLog_surjective : Function.Surjective (unitLog K) := by
  rintro ⟨x, u, _, rfl⟩
  exact ⟨u, rfl⟩

@[simp] theorem unitLog_eq_zero_iff (u : Additive (𝓞 K)ˣ) :
    unitLog K u = 0 ↔ u.toMul ∈ torsion K := by
  rw [← Subtype.val_inj]
  exact dirichletUnitTheorem.logEmbedding_eq_zero_iff

variable {F K : Type} [Field F] [Field K] [NumberField F] [NumberField K]
  [Algebra F K] [Algebra.IsQuadraticExtension F K]

omit [Algebra.IsQuadraticExtension F K] in
/-- Norm preserves logarithmic torsion, so it descends to the genuine unit lattice. -/
theorem unitLog_ker_le_normLog_ker :
    (unitLog K).ker ≤ ((unitLog F).comp (unitNorm (F := F) (K := K)).toAdditive).ker := by
  intro u hu
  rw [AddMonoidHom.mem_ker, unitLog_eq_zero_iff] at hu
  rw [AddMonoidHom.mem_ker, AddMonoidHom.comp_apply, unitLog_eq_zero_iff]
  exact (CommGroup.mem_torsion _).mpr
    ((unitNorm (F := F)).isOfFinOrder ((CommGroup.mem_torsion _).mp hu))

/-- The actual unit norm on the weighted logarithmic lattices. -/
def normLogLattice : unitLattice K →ₗ[ℤ] unitLattice F :=
  ((unitLog K).liftOfSurjective (unitLog_surjective K)
    ⟨(unitLog F).comp (unitNorm (F := F) (K := K)).toAdditive,
      unitLog_ker_le_normLog_ker⟩).toIntLinearMap

omit [Algebra.IsQuadraticExtension F K] in
@[simp] theorem normLogLattice_unitLog (u : Additive (𝓞 K)ˣ) :
    normLogLattice (F := F) (unitLog K u) =
      unitLog F ((unitNorm (F := F) (K := K)).toAdditive u) := by
  simp [normLogLattice, AddMonoidHom.liftOfSurjective]

/-- The logarithm of actual norm-one units, valued in the full unit lattice. -/
def relativeUnitLog : Additive (normOneUnits (F := F) (K := K)) →ₗ[ℤ] unitLattice K :=
  ((unitLog K).comp (normOneUnits (F := F) (K := K)).subtype.toAdditive).toIntLinearMap

/-- The actual relative logarithmic sublattice inside the full weighted unit lattice. -/
def relativeLogLattice : Submodule ℤ (unitLattice K) :=
  (relativeUnitLog (F := F) (K := K)).range

variable (ι : K ≃ₐ[F] K) (hι : ι ≠ 1)
  (ρ : F →+* ℝ) (σ : K →+* ℂ)
  (hbase : ∀ x : F, σ (algebraMap F K x) = (ρ x : ℂ))
  (hconj : ∀ x : K, σ (ι x) = star (σ x))

include ι hι ρ σ hbase hconj in
/-- Exactness on the actual logarithmic lattices. Logarithmic norm zero implies
norm one by positivity at the complexifying real place. -/
theorem normLogLattice_ker_eq :
    (normLogLattice (F := F) (K := K)).ker = relativeLogLattice (F := F) (K := K) := by
  ext x
  obtain ⟨u, rfl⟩ := unitLog_surjective K x
  constructor
  · intro hx
    rw [LinearMap.mem_ker, normLogLattice_unitLog, unitLog_eq_zero_iff] at hx
    have hu : u.toMul ∈ normOneUnits (F := F) :=
      norm_torsion_eq_one ι hι ρ σ hbase hconj u.toMul hx
    exact ⟨Additive.ofMul ⟨u.toMul, hu⟩, rfl⟩
  · rintro ⟨v, hv⟩
    rw [LinearMap.mem_ker, ← hv]
    change normLogLattice (F := F) (unitLog K (Additive.ofMul v.toMul.val)) = 0
    rw [normLogLattice_unitLog]
    change unitLog F (Additive.ofMul (unitNorm (F := F) v.toMul.val)) = 0
    rw [show unitNorm (F := F) v.toMul.val = 1 from v.toMul.prop]
    exact map_zero _

omit [Algebra.IsQuadraticExtension F K] in
/-- The full logarithmic norm image is generated by the actual norms. -/
theorem normLogLattice_range_eq :
    (normLogLattice (F := F) (K := K)).range.toAddSubgroup =
      (normUnitImage (F := F) (K := K)).toAddSubgroup.map (unitLog F) := by
  ext x
  constructor
  · rintro ⟨y, rfl⟩
    obtain ⟨u, rfl⟩ := unitLog_surjective K y
    exact ⟨(unitNorm (F := F) (K := K)).toAdditive u, ⟨u.toMul, rfl⟩,
      (normLogLattice_unitLog u).symm⟩
  · rintro ⟨v, ⟨u, rfl⟩, rfl⟩
    exact ⟨unitLog K (Additive.ofMul u), normLogLattice_unitLog _⟩

omit [Algebra.IsQuadraticExtension F K] in
/-- The index of the actual lattice norm image is the independently defined
logarithmic norm index. -/
theorem normLogLattice_index_eq :
    (normLogLattice (F := F) (K := K)).range.toAddSubgroup.index =
      logarithmicNormIndex (F := F) (K := K) := by
  rw [normLogLattice_range_eq]
  have hi := AddSubgroup.relIndex_map_map_of_injective
    ((normUnitImage (F := F) (K := K)).toAddSubgroup.map (unitLog F))
    ⊤ (f := (unitLattice F).toAddSubgroup.subtype) Subtype.val_injective
  rw [AddSubgroup.relIndex_top_right, AddSubgroup.map_map] at hi
  have hc : (unitLattice F).toAddSubgroup.subtype.comp (unitLog F) = logEmbedding F := rfl
  rw [hc] at hi
  have ht : (⊤ : AddSubgroup (unitLattice F)).map
      (unitLattice F).toAddSubgroup.subtype = (logEmbedding F).range := by
    rw [← AddMonoidHom.range_eq_map, AddSubgroup.range_subtype]
    ext x
    simp [unitLattice]
  rw [ht] at hi
  exact hi.symm

/-- An integral section of the actual logarithmic norm onto its image.
Existence follows from freeness of a subgroup of the ordinary unit lattice. -/
def normLogLatticeSection :
    (normLogLattice (F := F) (K := K)).range →ₗ[ℤ] unitLattice K :=
  Classical.choose (Module.projective_lifting_property
    (normLogLattice (F := F) (K := K)).rangeRestrict LinearMap.id
    (normLogLattice (F := F) (K := K)).surjective_rangeRestrict)

omit [Algebra.IsQuadraticExtension F K] in
/-- The constructed section is a right inverse, not an assumed splitting. -/
theorem normLogLattice_section :
    (normLogLattice (F := F) (K := K)).rangeRestrict.comp
      (normLogLatticeSection (F := F) (K := K)) = LinearMap.id :=
  Classical.choose_spec (Module.projective_lifting_property
    (normLogLattice (F := F) (K := K)).rangeRestrict LinearMap.id
    (normLogLattice (F := F) (K := K)).surjective_rangeRestrict)

include ι hι ρ σ hbase hconj in
/-- The exact integral norm sequence splits into its actual relative logarithmic
lattice and actual image. This does not impose an involution eigenspace split. -/
def relativeLogLatticeProdImageEquiv :
    ((relativeLogLattice (F := F) (K := K)) ×
      (normLogLattice (F := F) (K := K)).range) ≃ₗ[ℤ] unitLattice K :=
  lequivProdOfRightSplitExact
    (relativeLogLattice (F := F) (K := K)).injective_subtype
    (by rw [Submodule.range_subtype, LinearMap.ker_rangeRestrict,
      normLogLattice_ker_eq ι hι ρ σ hbase hconj])
    (normLogLattice_section (F := F) (K := K))

/-- The actual norm-image logarithmic lattice in the ordinary base log space. -/
def normImageLogLattice : Submodule ℤ (logSpace F) :=
  (normLogLattice (F := F) (K := K)).range.map (unitLattice F).subtype

omit [Algebra.IsQuadraticExtension F K] in
theorem normImageLogLattice_le :
    normImageLogLattice (F := F) (K := K) ≤ unitLattice F := by
  exact Submodule.map_le_iff_le_comap.mpr (by simp)

omit [Algebra.IsQuadraticExtension F K] in
/-- The ambient-coordinate lattice is exactly the weighted log of actual norms. -/
theorem normImageLogLattice_toAddSubgroup :
    (normImageLogLattice (F := F) (K := K)).toAddSubgroup =
      (normUnitImage (F := F) (K := K)).toAddSubgroup.map (logEmbedding F) := by
  rw [normImageLogLattice, Submodule.map_toAddSubgroup, normLogLattice_range_eq,
    AddSubgroup.map_map]
  rfl

instance normImageLogLattice_discrete :
    DiscreteTopology (normImageLogLattice (F := F) (K := K)) := by
  rw [← SetLike.isDiscrete_iff_discreteTopology]
  exact (inferInstance : DiscreteTopology (unitLattice F)).isDiscrete.mono
    (show (normImageLogLattice (F := F) (K := K) : Set (logSpace F)) ⊆ unitLattice F from
      normImageLogLattice_le)

/-- Every doubled base logarithmic unit is the logarithm of an actual norm. -/
theorem double_unitLattice_mem_normImage (x : unitLattice F) :
    (2 : ℝ) • (x : logSpace F) ∈ normImageLogLattice (F := F) (K := K) := by
  obtain ⟨u, rfl⟩ := unitLog_surjective F x
  change (2 : ℝ) • logEmbedding F u ∈ _
  have hu : u.toMul ^ 2 ∈ normUnitImage (F := F) (K := K) := square_mem_normUnitImage u.toMul
  have hm : logEmbedding F (2 • u) ∈
      (normImageLogLattice (F := F) (K := K)).toAddSubgroup := by
    rw [normImageLogLattice_toAddSubgroup]
    exact ⟨2 • u, hu, rfl⟩
  simpa only [map_nsmul, two_nsmul, two_smul, map_add] using! hm

/-- The logarithmic norm image is a full lattice, proved using actual base-unit
squares and Dirichlet's theorem. -/
instance normImageLogLattice_isZLattice :
    IsZLattice ℝ (normImageLogLattice (F := F) (K := K)) where
  span_top := by
    apply top_unique
    rw [← IsZLattice.span_top (K := ℝ) (L := unitLattice F)]
    apply Submodule.span_le.mpr
    intro x hx
    have hm := double_unitLattice_mem_normImage (F := F) (K := K) ⟨x, hx⟩
    have hs := (Submodule.span ℝ (normImageLogLattice (F := F) (K := K) : Set (logSpace F))).smul_mem
      (1 / 2 : ℝ) (Submodule.subset_span hm)
    simpa only [smul_smul, one_div, inv_mul_cancel₀ (by norm_num : (2 : ℝ) ≠ 0), one_smul] using! hs

/-- The norm-image regulator ratio is exactly its true logarithmic index. -/
theorem normImageLogLattice_covolume_div_regulator :
    ZLattice.covolume (normImageLogLattice (F := F) (K := K)) / regulator F =
      (logarithmicNormIndex (F := F) (K := K) : ℝ) := by
  rw [regulator, ZLattice.covolume_div_covolume_eq_relIndex _ _ normImageLogLattice_le,
    normImageLogLattice_toAddSubgroup]
  have hl : (unitLattice F).toAddSubgroup = (logEmbedding F).range := by
    ext x
    simp [unitLattice]
  rw [hl]
  rfl

include ι hι ρ σ hbase hconj in
/-- The actual norm-image covolume is `(I_U/2) R_F`, with the torsion factor
proved at the complexifying real place. -/
theorem normImageLogLattice_covolume :
    ZLattice.covolume (normImageLogLattice (F := F) (K := K)) =
      ((normUnitImage (F := F) (K := K)).index : ℝ) / 2 * regulator F := by
  have h := normImageLogLattice_covolume_div_regulator (F := F) (K := K)
  have hi := unitNorm_index_eq_two_mul_logarithmicNormIndex ι hι ρ σ hbase hconj
  rw [hi, Nat.cast_mul, Nat.cast_ofNat]
  apply (div_eq_iff (regulator_pos F).ne').mp at h
  nlinarith

end UnitDistance.RelativeUnits
