module

public import UnitDistance.RelativeIdealCosetsFamily
public import UnitDistance.RelativeIdealCosetsGenerators

@[expose] public section
set_option backward.privateInPublic true


/-! # Actual principal norm-one ratios of balanced ideals in one relative class -/

noncomputable section
set_option backward.isDefEq.respectTransparency false
open scoped NumberField nonZeroDivisors Classical
open NumberField

namespace UnitDistance.RelativeIdealCosets

private theorem ratio_of_balanced_relations {G : Type*} [CommGroup G]
    (J L B C B' C' T : G) (hJ : J * B' = B * T) (hL : L * C' = C * T) :
    J / L = (B / B') / (C / C') := by
  have hj : J = (B / B') * T := by
    calc
      J = (J * B') * B'⁻¹ := by simp
      _ = (B * T) * B'⁻¹ := by rw [hJ]
      _ = (B / B') * T := by simp [div_eq_mul_inv, mul_comm, mul_left_comm, mul_assoc]
  have hl : L = (C / C') * T := by
    calc
      L = (L * C') * C'⁻¹ := by simp
      _ = (C * T) * C'⁻¹ := by rw [hL]
      _ = (C / C') * T := by simp [div_eq_mul_inv, mul_comm, mul_left_comm, mul_assoc]
  rw [hj, hl]
  simp

variable {F K : Type} [Field F] [Field K] [NumberField F] [NumberField K]
  [Algebra F K] [Algebra.IsQuadraticExtension F K]
  {S : Type*} [Fintype S]

/-- The fixed integral ideal containing all conjugate primes to their full
exponent. It cancels when two balanced ideals are divided. -/
def tailNonzeroIdeal {ι : K ≃ₐ[F] K} (D : PrimePairFamily ι S) (k : S → ℕ) :
    NonzeroIdeal K :=
  ⟨∏ s, (D.prime (s, true)).asIdeal ^ k s,
    mem_nonZeroDivisors_iff_ne_zero.mpr (Finset.prod_ne_zero_iff.mpr
      fun s _ ↦ pow_ne_zero _ (D.prime (s, true)).ne_bot)⟩

theorem balancedNonzero_mul_conjugate_oneSided {ι : K ≃ₐ[F] K} (hι : ι ≠ 1)
    (D : PrimePairFamily ι S) (k : S → ℕ) (j : ChoiceIndex k) :
    balancedNonzeroIdeal D k j * conjugateNonzeroIdeal ι hι (oneSidedNonzeroIdeal D k j) =
      oneSidedNonzeroIdeal D k j * tailNonzeroIdeal D k := by
  apply Subtype.ext
  exact balanced_mul_conjugate_oneSided D k j

/-- The fractional-ideal ratio of two balanced ideals is exactly the ratio
of their actual anti-invariant one-sided ideals. -/
theorem balancedIdeal_ratio_eq {ι : K ≃ₐ[F] K} (hι : ι ≠ 1)
    (D : PrimePairFamily ι S) (k : S → ℕ) (j l : ChoiceIndex k) :
    FractionalIdeal.mk0 K (balancedNonzeroIdeal D k j) /
        FractionalIdeal.mk0 K (balancedNonzeroIdeal D k l) =
      idealAntiRatio ι hι (oneSidedNonzeroIdeal D k j) /
        idealAntiRatio ι hι (oneSidedNonzeroIdeal D k l) := by
  have hj := congrArg (FractionalIdeal.mk0 K)
    (balancedNonzero_mul_conjugate_oneSided hι D k j)
  have hl := congrArg (FractionalIdeal.mk0 K)
    (balancedNonzero_mul_conjugate_oneSided hι D k l)
  simp only [map_mul] at hj hl
  exact ratio_of_balanced_relations _ _ _ _ _ _ _ hj hl

/-- In one actual relative class fiber, the ratio of balanced ideals is
generated by the literal field element `x/ι(x)`, whose field norm is one. -/
theorem same_choiceClass_exists_normOne_generator {ι : K ≃ₐ[F] K} (hι : ι ≠ 1)
    (D : PrimePairFamily ι S) (k : S → ℕ) (j l : ChoiceIndex k)
    (h : choiceClass D k j = choiceClass D k l) :
    ∃ x : Kˣ,
      FractionalIdeal.mk0 K (balancedNonzeroIdeal D k j) /
          FractionalIdeal.mk0 K (balancedNonzeroIdeal D k l) =
        toPrincipalIdeal (𝓞 K) K (fieldCoboundary ι x) ∧
      Algebra.norm F (fieldCoboundary ι x : K) = 1 := by
  obtain ⟨x, hx⟩ := same_relativeClass_exists_normOne_generator ι hι
    (oneSidedNonzeroIdeal D k j) (oneSidedNonzeroIdeal D k l) h
  exact ⟨x, (balancedIdeal_ratio_eq hι D k j l).trans hx, norm_fieldCoboundary ι hι x⟩

end UnitDistance.RelativeIdealCosets
