module

public import UnitDistance.RetainedDyadicDifferentGenerator
public import UnitDistance.ArithmeticCatalogOddSquareclasses
public import UnitDistance.ArithmeticRetainedDiscriminant
public import UnitDistance.RetainedDyadicDifferentReduction
public import UnitDistance.QuadraticRadicalPresentation
public import Mathlib.NumberTheory.Cyclotomic.PrimitiveRoots
public import Mathlib.RingTheory.Norm.Transitivity

@[expose] public section
set_option backward.privateInPublic true


/-!
# Norm of the dyadic derivative factor

This file computes the absolute norm of the cyclotomic scalar occurring in
the derivative of the integral generator for the ramified retained quadratic
direction.
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false
open scoped NumberField
namespace UnitDistance
namespace ArithmeticRetained

open ArithmeticChosenGenus NumberField Polynomial
open QuadraticRamification KummerInvariant
attribute [local instance] FractionRing.liftAlgebra
  FractionRing.isScalarTower_liftAlgebra

theorem dyadicZeta_primitive : IsPrimitiveRoot dyadicZeta 8 := by
  rw [IsPrimitiveRoot.iff_orderOf]
  have hnot : ¬ dyadicZeta ^ 2 ^ 2 = 1 := by
    norm_num [dyadicZeta_fourth]
  have hfin : dyadicZeta ^ 2 ^ (2 + 1) = 1 := by
    norm_num only [Nat.reduceAdd, Nat.reducePow]
    rw [show dyadicZeta ^ 8 = (dyadicZeta ^ 4) ^ 2 by ring,
      dyadicZeta_fourth]
    norm_num
  exact orderOf_eq_prime_pow hnot hfin

/-- The copy of the eighth cyclotomic field generated by the chosen root
inside the actual genus field. -/
def DyadicCyclotomicField : IntermediateField ℚ GenusField :=
  IntermediateField.adjoin ℚ ({dyadicZeta} : Set GenusField)

abbrev DyadicCyclotomic := DyadicCyclotomicField

def cyclotomicZeta : DyadicCyclotomic :=
  ⟨dyadicZeta, IntermediateField.subset_adjoin ℚ _ (Set.mem_singleton _)⟩

theorem cyclotomicZeta_primitive : IsPrimitiveRoot cyclotomicZeta 8 := by
  rw [← IsPrimitiveRoot.coe_submonoidClass_iff]
  exact dyadicZeta_primitive

noncomputable instance dyadicCyclotomicExtension :
    IsCyclotomicExtension {8} ℚ DyadicCyclotomic :=
  dyadicZeta_primitive.intermediateField_adjoin_isCyclotomicExtension ℚ

noncomputable instance dyadicCyclotomicExtensionPower :
    IsCyclotomicExtension {2 ^ 3} ℚ DyadicCyclotomic := by
  norm_num
  infer_instance

theorem dyadicCyclotomic_degree :
    Module.finrank ℚ DyadicCyclotomic = 4 := by
  rw [IsCyclotomicExtension.finrank DyadicCyclotomic
    (n := 8) (Polynomial.cyclotomic.irreducible_rat (by norm_num))]
  decide

theorem cyclotomicZeta_sub_one_norm :
    Algebra.norm ℚ (cyclotomicZeta - 1) = 2 := by
  simpa only [Nat.reducePow] using
    cyclotomicZeta_primitive.norm_sub_one_two (k := 3) (by norm_num)
      (Polynomial.cyclotomic.irreducible_rat (by norm_num))

theorem cyclotomicZeta_norm :
    Algebra.norm ℚ cyclotomicZeta = 1 := by
  exact cyclotomicZeta_primitive.norm_eq_one (by norm_num)
    (Polynomial.cyclotomic.irreducible_rat (by norm_num))

theorem cyclotomicDerivative_norm :
    Algebra.norm ℚ (cyclotomicZeta ^ 2 - cyclotomicZeta) = 2 := by
  rw [show cyclotomicZeta ^ 2 - cyclotomicZeta =
      cyclotomicZeta * (cyclotomicZeta - 1) by ring,
    map_mul, cyclotomicZeta_norm, cyclotomicZeta_sub_one_norm, one_mul]

theorem dyadicCyclotomic_relative_degree :
    Module.finrank DyadicCyclotomic GenusField = 32 := by
  have h := Module.finrank_mul_finrank ℚ DyadicCyclotomic GenusField
  rw [dyadicCyclotomic_degree,
    ArithmeticChosenGenus.genusField_degree] at h
  omega

theorem dyadicDerivative_absolute_norm :
    Algebra.norm ℚ (dyadicZeta ^ 2 - dyadicZeta) = 2 ^ 32 := by
  rw [← Algebra.norm_norm (R := ℚ) (S := DyadicCyclotomic)]
  have hmap : dyadicZeta ^ 2 - dyadicZeta =
      algebraMap DyadicCyclotomic GenusField
        (cyclotomicZeta ^ 2 - cyclotomicZeta) := by
    rfl
  rw [hmap, Algebra.norm_algebraMap, dyadicCyclotomic_relative_degree,
    map_pow, cyclotomicDerivative_norm]

noncomputable instance ramifiedRadicandNonsquareFact :
    Fact (Nonsquare (retainedRadicand 11)) :=
  ⟨retainedRadicand_eleven_nonsquare⟩

/-- The displayed quadratic intermediate field is the actual quadratic
algebra attached to the eleventh retained squareclass. -/
def ramifiedQuadraticEquiv :
    Extension (retainedRadicand 11) ≃ₐ[GenusField]
      RamifiedField :=
  QuadraticRadical.equiv (retainedRadicand 11) ramifiedRoot
    ramifiedRoot_sq ramifiedField_degree

@[simp] theorem ramifiedQuadraticEquiv_root :
    ramifiedQuadraticEquiv QuadraticAlgebra.omega = ramifiedRoot :=
  QuadraticRadical.equiv_root (retainedRadicand 11) ramifiedRoot
    ramifiedRoot_sq ramifiedField_degree

/-- The ramified quadratic direction has no odd relative ramification. -/
theorem ramifiedField_unramifiedAtOddPrimes :
    UnramifiedAtOddPrimes GenusField RamifiedField := by
  have hq : HasOddLocalUnitSquareclass GenusField (retainedRadicand 11) := by
    exact ArithmeticCatalog.word_hasOddLocalUnitSquareclass
      (CatalogSquareclassData.retainedWords 11)
  exact (QuadraticRamification.extension_unramifiedAtOddPrimes
    GenusField (retainedRadicand 11) hq).of_algEquiv ramifiedQuadraticEquiv

/-- The integral cyclotomic scalar in the derivative. -/
def dyadicDerivativeInteger : RingOfIntegers GenusField :=
  ⟨dyadicZeta ^ 2 - dyadicZeta,
    (dyadicZeta_isIntegral.pow 2).sub dyadicZeta_isIntegral⟩

theorem dyadicDerivativeInteger_norm :
    Algebra.norm ℤ dyadicDerivativeInteger = (2 ^ 32 : ℤ) := by
  apply (Int.cast_injective : Function.Injective (fun z : ℤ => (z : ℚ)))
  rw [Algebra.coe_norm_int]
  exact_mod_cast dyadicDerivative_absolute_norm

theorem dyadicDerivativeInteger_absNorm :
    Ideal.absNorm (Ideal.span ({dyadicDerivativeInteger} :
      Set (RingOfIntegers GenusField))) = 2 ^ 32 := by
  rw [Ideal.absNorm_span_singleton, dyadicDerivativeInteger_norm]
  norm_num

/-- The integral catalog representative of the eleventh retained radicand. -/
def ramifiedRadicandInteger : RingOfIntegers GenusField :=
  ArithmeticCatalog.wordInteger (CatalogSquareclassData.retainedWords 11)

theorem ramifiedRadicandInteger_coe :
    (ramifiedRadicandInteger : GenusField) = retainedRadicand 11 := by
  rw [ramifiedRadicandInteger, ArithmeticCatalog.wordInteger_coe]
  rfl

theorem ramifiedRadicandInteger_eq_catalog :
    ramifiedRadicandInteger = ArithmeticCatalog.catalogInteger 16 := by
  have hword : CatalogSquareclassData.retainedWords 11 = 65536 := by decide
  have hfilter : Finset.univ.filter
      (fun i : Fin 17 => (65536 : ℕ).testBit i.val) = {16} := by
    ext i
    fin_cases i <;> decide
  rw [ramifiedRadicandInteger, hword, ArithmeticCatalog.wordInteger, hfilter]
  simp

theorem ramifiedRadicandInteger_product :
    ramifiedRadicandInteger * ArithmeticCatalog.catalogComplement 16 = 13 := by
  rw [ramifiedRadicandInteger_eq_catalog]
  have h := ArithmeticCatalog.catalogInteger_product (16 : Fin 17)
  have hrow : NormExtensionCatalog.catalog (16 : Fin 17) =
      ⟨-1, 13, -2, 3, 1⟩ := by decide
  rw [hrow] at h
  norm_num at h ⊢
  exact h

/-- The displayed radical, as an absolute algebraic integer. -/
def ramifiedRootInteger : RingOfIntegers RamifiedField :=
  ⟨ramifiedRoot, by
    apply IsIntegral.of_pow (n := 2) (by decide)
    rw [ramifiedRoot_sq, ← ramifiedRadicandInteger_coe]
    exact map_isIntegral_int (algebraMap GenusField RamifiedField)
      ramifiedRadicandInteger.property⟩

theorem ramifiedRootInteger_sq :
    ramifiedRootInteger ^ 2 =
      algebraMap (RingOfIntegers GenusField)
        (RingOfIntegers RamifiedField) ramifiedRadicandInteger := by
  apply RingOfIntegers.coe_injective
  change ramifiedRoot ^ 2 =
    algebraMap GenusField RamifiedField (ramifiedRadicandInteger : GenusField)
  rw [ramifiedRoot_sq, ramifiedRadicandInteger_coe]

theorem ramifiedRootInteger_complement_product :
    ramifiedRootInteger *
        (ramifiedRootInteger *
          algebraMap (RingOfIntegers GenusField)
            (RingOfIntegers RamifiedField)
              (ArithmeticCatalog.catalogComplement 16)) = 13 := by
  rw [← mul_assoc, ← pow_two, ramifiedRootInteger_sq, ← map_mul,
    ramifiedRadicandInteger_product]
  exact map_ofNat _ 13

theorem ramifiedField_absolute_degree :
    Module.finrank ℚ RamifiedField = 256 := by
  rw [← Module.finrank_mul_finrank ℚ GenusField RamifiedField,
    ArithmeticChosenGenus.genusField_degree, ramifiedField_degree]

theorem ramifiedRootInteger_absNorm_dvd_thirteen_pow :
    Ideal.absNorm (Ideal.span ({ramifiedRootInteger} :
      Set (RingOfIntegers RamifiedField))) ∣ 13 ^ 256 := by
  apply (Ideal.absNorm_dvd_absNorm_of_le (I := Ideal.span
    ({ramifiedRootInteger} : Set (RingOfIntegers RamifiedField)))
    (J := Ideal.span ({(13 : RingOfIntegers RamifiedField)} : Set _)) ?_).trans
  · change Ideal.absNorm (Ideal.span
      ({((13 : ℕ) : RingOfIntegers RamifiedField)} : Set _)) ∣ 13 ^ 256
    rw [Ideal.absNorm_span_natCast, RingOfIntegers.rank,
      ramifiedField_absolute_degree]
  · rw [Ideal.span_le]
    intro y hy
    simp only [Set.mem_singleton_iff] at hy
    subst y
    rw [← ramifiedRootInteger_complement_product]
    exact (Ideal.span ({ramifiedRootInteger} :
      Set (RingOfIntegers RamifiedField))).mul_mem_right _
        (Ideal.subset_span (Set.mem_singleton _))

theorem ramifiedRootInteger_absNorm_odd :
    Odd (Ideal.absNorm (Ideal.span ({ramifiedRootInteger} :
      Set (RingOfIntegers RamifiedField)))) :=
  Odd.of_dvd_nat (by exact (by norm_num : Odd 13).pow)
    ramifiedRootInteger_absNorm_dvd_thirteen_pow

/-- The integral derivative whose membership in the quadratic different was
proved in `RetainedDyadicDifferentGenerator`. -/
def ramifiedDerivativeInteger : RingOfIntegers RamifiedField :=
  2 * integralRamifiedCandidate -
    algebraMap (RingOfIntegers GenusField)
      (RingOfIntegers RamifiedField) traceInteger

theorem ramifiedDerivativeInteger_eq :
    ramifiedDerivativeInteger =
      algebraMap (RingOfIntegers GenusField)
        (RingOfIntegers RamifiedField) dyadicDerivativeInteger *
          ramifiedRootInteger := by
  apply RingOfIntegers.coe_injective
  change 2 * ramifiedIntegralCandidate -
      algebraMap GenusField RamifiedField
        (DyadicDifferentGenerator.traceCoefficient dyadicZeta) =
    algebraMap GenusField RamifiedField (dyadicZeta ^ 2 - dyadicZeta) *
      ramifiedRoot
  rw [ramifiedIntegralCandidate_derivative]
  simp only [map_sub, map_pow]
  rfl

theorem mappedDyadicDerivativeInteger_absNorm :
    Ideal.absNorm (Ideal.span
      ({(algebraMap (RingOfIntegers GenusField)
          (RingOfIntegers RamifiedField) dyadicDerivativeInteger)} : Set _)) =
        2 ^ 64 := by
  have hspan : Ideal.map
      (algebraMap (RingOfIntegers GenusField)
        (RingOfIntegers RamifiedField))
      (Ideal.span ({dyadicDerivativeInteger} :
        Set (RingOfIntegers GenusField))) =
      Ideal.span ({(algebraMap (RingOfIntegers GenusField)
        (RingOfIntegers RamifiedField) dyadicDerivativeInteger)} : Set _) := by
    rw [Ideal.map_span]
    congr 1
    ext x
    simp only [Set.image_singleton, Set.mem_singleton_iff]
  rw [← hspan, Ideal.absNorm_algebraMap,
    ← IsFractionRing.finrank_eq
      (RingOfIntegers GenusField) GenusField
      (RingOfIntegers RamifiedField) RamifiedField,
    ramifiedField_degree, dyadicDerivativeInteger_absNorm]
  norm_num [pow_mul]

theorem ramifiedDerivativeInteger_absNorm :
    Ideal.absNorm (Ideal.span ({ramifiedDerivativeInteger} :
      Set (RingOfIntegers RamifiedField))) =
      2 ^ 64 * Ideal.absNorm (Ideal.span ({ramifiedRootInteger} : Set _)) := by
  rw [ramifiedDerivativeInteger_eq,
    ← Ideal.span_singleton_mul_span_singleton, map_mul,
    mappedDyadicDerivativeInteger_absNorm]

theorem ramifiedRootInteger_absNorm_factorization_two :
    (Ideal.absNorm (Ideal.span ({ramifiedRootInteger} :
      Set (RingOfIntegers RamifiedField)))).factorization 2 = 0 := by
  apply Nat.factorization_eq_zero_of_not_dvd
  intro htwo
  exact (Nat.not_even_iff_odd.mpr ramifiedRootInteger_absNorm_odd)
    (even_iff_two_dvd.mpr htwo)

theorem ramifiedDerivativeInteger_absNorm_factorization_two :
    (Ideal.absNorm (Ideal.span ({ramifiedDerivativeInteger} :
      Set (RingOfIntegers RamifiedField)))).factorization 2 = 64 := by
  have hrootne : Ideal.absNorm (Ideal.span ({ramifiedRootInteger} :
      Set (RingOfIntegers RamifiedField))) ≠ 0 := by
    intro hzero
    have hodd := ramifiedRootInteger_absNorm_odd
    rw [hzero] at hodd
    norm_num at hodd
  have hrootfac : ((Algebra.norm ℤ ramifiedRootInteger).natAbs).factorization 2 = 0 := by
    simpa only [Ideal.absNorm_span_singleton] using
      ramifiedRootInteger_absNorm_factorization_two
  rw [ramifiedDerivativeInteger_absNorm,
    Nat.factorization_mul (pow_ne_zero _ (by decide))
      hrootne,
    Nat.Prime.factorization_pow Nat.prime_two]
  simp [hrootfac]

theorem ramifiedDerivativeInteger_mem_different :
    ramifiedDerivativeInteger ∈
      differentIdeal (RingOfIntegers GenusField)
        (RingOfIntegers RamifiedField) :=
  ramifiedDerivative_mem_different

/-- The actual quadratic different has rational two-adic exponent at most
sixty-four.  Odd support is removed using the proved catalog local-unit
criterion; the bound at two comes from the integral derivative above. -/
theorem ramifiedDifferent_factorization_two_le :
    (Ideal.absNorm (differentIdeal (RingOfIntegers GenusField)
      (RingOfIntegers RamifiedField))).factorization 2 ≤ 64 := by
  let D := differentIdeal (RingOfIntegers GenusField)
    (RingOfIntegers RamifiedField)
  let J := Ideal.span ({ramifiedDerivativeInteger} :
    Set (RingOfIntegers RamifiedField))
  have hJD : J ≤ D := by
    dsimp [J]
    rw [Ideal.span_singleton_le_iff_mem]
    exact ramifiedDerivativeInteger_mem_different
  have hdvd : Ideal.absNorm D ∣ Ideal.absNorm J :=
    Ideal.absNorm_dvd_absNorm_of_le hJD
  have hDne : Ideal.absNorm D ≠ 0 := by
    rw [ne_eq, Ideal.absNorm_eq_zero_iff]
    exact differentIdeal_ne_bot
  have hJne : Ideal.absNorm J ≠ 0 := by
    intro hzero
    have hfac := ramifiedDerivativeInteger_absNorm_factorization_two
    change (Ideal.absNorm J).factorization 2 = 64 at hfac
    rw [hzero] at hfac
    norm_num at hfac
  have hfac := (Nat.factorization_le_iff_dvd hDne hJne).mpr hdvd
  exact (hfac 2).trans_eq (by
    change (Ideal.absNorm J).factorization 2 = 64
    exact ramifiedDerivativeInteger_absNorm_factorization_two)

def ramifiedRelativeDifferentTwoExponent : ℕ :=
  (Ideal.absNorm (differentIdeal (RingOfIntegers GenusField)
    (RingOfIntegers RamifiedField))).factorization 2

theorem ramifiedRelativeDifferentTwoExponent_le :
    ramifiedRelativeDifferentTwoExponent ≤ 64 :=
  ramifiedDifferent_factorization_two_le

theorem ramifiedDifferent_absNorm_le :
    Ideal.absNorm (differentIdeal (RingOfIntegers GenusField)
      (RingOfIntegers RamifiedField)) ≤ 2 ^ 64 := by
  obtain ⟨k, hk⟩ :=
    ramifiedField_unramifiedAtOddPrimes.absNorm_differentIdeal_eq_two_pow
      GenusField RamifiedField
  have hk64 : k ≤ 64 := by
    have h := ramifiedDifferent_factorization_two_le
    rw [hk] at h
    simpa [Nat.Prime.factorization_pow Nat.prime_two] using h
  rw [hk]
  exact Nat.pow_le_pow_right (by norm_num) hk64

theorem ramifiedComplement_degree :
    Module.finrank RamifiedField RetainedField = 2048 := by
  have h := Module.finrank_mul_finrank GenusField RamifiedField RetainedField
  rw [ramifiedField_degree, retainedField_relative_degree] at h
  omega

/-- Once the complementary extension is globally unramified, transitivity of
the actual different scales the quadratic norm by its actual degree 2048. -/
theorem retainedDifferent_absNorm_eq_pow_of_finiteUnramifiedComplement
    (hu : NumberFieldAnalysis.FiniteUnramified RamifiedField RetainedField) :
    Ideal.absNorm (differentIdeal (RingOfIntegers GenusField)
      (RingOfIntegers RetainedField)) =
      (Ideal.absNorm (differentIdeal (RingOfIntegers GenusField)
        (RingOfIntegers RamifiedField))) ^ 2048 := by
  rw [differentIdeal_eq_differentIdeal_mul_differentIdeal
      (RingOfIntegers GenusField) (RingOfIntegers RamifiedField)
        (RingOfIntegers RetainedField),
    NumberFieldAnalysis.differentIdeal_eq_top_of_finiteUnramified
      RamifiedField RetainedField hu,
    ← Ideal.one_eq_top, one_mul, Ideal.absNorm_algebraMap,
    ← IsFractionRing.finrank_eq
      (RingOfIntegers RamifiedField) RamifiedField
      (RingOfIntegers RetainedField) RetainedField,
    ramifiedComplement_degree]

theorem retainedDifferent_absNorm_le_of_finiteUnramifiedComplement
    (hu : NumberFieldAnalysis.FiniteUnramified RamifiedField RetainedField) :
    Ideal.absNorm (differentIdeal (RingOfIntegers GenusField)
      (RingOfIntegers RetainedField)) ≤ 2 ^ 131072 := by
  rw [retainedDifferent_absNorm_eq_pow_of_finiteUnramifiedComplement hu]
  calc
    _ ≤ (2 ^ 64) ^ 2048 := Nat.pow_le_pow_left ramifiedDifferent_absNorm_le _
    _ = 2 ^ 131072 := by
      change (2 ^ 64) ^ 2048 = 2 ^ 131072
      rw [← pow_mul]

theorem retainedRelativeDifferentTwoExponent_le_of_finiteUnramifiedComplement
    (hu : NumberFieldAnalysis.FiniteUnramified RamifiedField RetainedField) :
    retainedRelativeDifferentTwoExponent ≤ 131072 :=
  (retainedField_absNorm_differentIdeal_le_two_pow_iff 131072).1
    (retainedDifferent_absNorm_le_of_finiteUnramifiedComplement hu)

end ArithmeticRetained
end UnitDistance
