module

public import UnitDistance.GroupAugmentationRetainedQuadratic

@[expose] public section
set_option backward.privateInPublic true


/-! The actual order-32 subgroup persists for arbitrary lifts of the three
specified genus vectors. Central changes of lifts are realized by a genuine
automorphism of the retained group; all augmentation layers remain strict. -/
noncomputable section
namespace UnitDistance.ClassTwo.GroupModel
variable {R V W : Type*} [CommRing R] [AddCommGroup V] [Module R V]
  [AddCommGroup W] [Module R W] (β : V →ₗ[R] V →ₗ[R] W)

/-- Adding a linear function of the base coordinates is an actual group automorphism. -/
def centralShear (L : V →ₗ[R] W) : GroupModel β ≃* GroupModel β where
  toFun g := ⟨g.base,g.central+L g.base⟩
  invFun g := ⟨g.base,g.central-L g.base⟩
  left_inv g := by ext <;> simp
  right_inv g := by ext <;> simp
  map_mul' g h := by
    apply GroupModel.ext
    · rfl
    · change g.central+h.central+β g.base h.base+L (g.base+h.base)=
        (g.central+L g.base)+(h.central+L h.base)+β g.base h.base
      rw [map_add]
      abel

end UnitDistance.ClassTwo.GroupModel
namespace UnitDistance.RetainedQuadratic
open GroupAugmentation ClassTwo

/-- The genus coordinates 1,2,3 are dual to the local masks 2,53,89. -/
def dyadicAdjustment (a b c : W) : V →ₗ[F] W where
  toFun v := v 1 • a+v 2 • b+v 3 • c
  map_add' v w := by simp only [Pi.add_apply,add_smul]; abel
  map_smul' r v := by simp only [Pi.smul_apply,smul_eq_mul,smul_smul,RingHom.id_apply,smul_add]

@[simp] theorem dyadicAdjustment_x (a b c : W) : dyadicAdjustment a b c (binaryVector 7 2)=a := by
  simp only [dyadicAdjustment,LinearMap.coe_mk,AddHom.coe_mk]
  norm_num [binaryVector,Nat.testBit,Nat.shiftRight_eq_div_pow]
@[simp] theorem dyadicAdjustment_y (a b c : W) : dyadicAdjustment a b c (binaryVector 7 53)=b := by
  simp only [dyadicAdjustment,LinearMap.coe_mk,AddHom.coe_mk]
  norm_num [binaryVector,Nat.testBit,Nat.shiftRight_eq_div_pow]
@[simp] theorem dyadicAdjustment_z (a b c : W) : dyadicAdjustment a b c (binaryVector 7 89)=c := by
  simp only [dyadicAdjustment,LinearMap.coe_mk,AddHom.coe_mk]
  norm_num [binaryVector,Nat.testBit,Nat.shiftRight_eq_div_pow]

theorem dyadicMap_x : dyadicMap Dyadic.D.x=x := by
  apply GroupModel.ext <;> funext i <;> fin_cases i <;> decide +kernel
theorem dyadicMap_y : dyadicMap Dyadic.D.y=y := by
  apply GroupModel.ext <;> funext i <;> fin_cases i <;> decide +kernel
theorem dyadicMap_z : dyadicMap Dyadic.D.z=z := by
  apply GroupModel.ext <;> funext i <;> fin_cases i <;> decide +kernel

/-- The canonical D32 embedding adjusted to any three specified lifts. -/
def dyadicMapOfLifts (a b c : Q) : Dyadic.D →* Q :=
  (GroupModel.centralShear cocycle (dyadicAdjustment a.central b.central c.central)).toMonoidHom.comp dyadicMap

theorem dyadicMapOfLifts_injective (a b c : Q) : Function.Injective (dyadicMapOfLifts a b c) :=
  (GroupModel.centralShear cocycle _).injective.comp dyadicMap_injective

@[simp] theorem dyadicMapOfLifts_x (a b c : Q) (ha : a.base=binaryVector 7 2) :
    dyadicMapOfLifts a b c Dyadic.D.x=a := by
  change GroupModel.centralShear cocycle _ (dyadicMap Dyadic.D.x)=a
  rw [dyadicMap_x]
  apply GroupModel.ext
  · exact ha.symm
  · change 0+dyadicAdjustment a.central b.central c.central (binaryVector 7 2)=a.central
    simp
@[simp] theorem dyadicMapOfLifts_y (a b c : Q) (hb : b.base=binaryVector 7 53) :
    dyadicMapOfLifts a b c Dyadic.D.y=b := by
  change GroupModel.centralShear cocycle _ (dyadicMap Dyadic.D.y)=b
  rw [dyadicMap_y]
  apply GroupModel.ext
  · exact hb.symm
  · change 0+dyadicAdjustment a.central b.central c.central (binaryVector 7 53)=b.central
    simp
@[simp] theorem dyadicMapOfLifts_z (a b c : Q) (hc : c.base=binaryVector 7 89) :
    dyadicMapOfLifts a b c Dyadic.D.z=c := by
  change GroupModel.centralShear cocycle _ (dyadicMap Dyadic.D.z)=c
  rw [dyadicMap_z]
  apply GroupModel.ext
  · exact hc.symm
  · change 0+dyadicAdjustment a.central b.central c.central (binaryVector 7 89)=c.central
    simp

/-- The subgroup generated by any such lifts is the image of the actual order-32 group. -/
theorem dyadicMapOfLifts_range (a b c : Q)
    (ha : a.base=binaryVector 7 2) (hb : b.base=binaryVector 7 53) (hc : c.base=binaryVector 7 89) :
    (dyadicMapOfLifts a b c).range=Subgroup.closure ({a,b,c} : Set Q) := by
  have ht : (dyadicMapOfLifts a b c).range=(⊤ : Subgroup Dyadic.D).map (dyadicMapOfLifts a b c) := by
    ext g
    simp only [MonoidHom.mem_range,Subgroup.mem_map,Subgroup.mem_top,true_and]
  rw [ht]
  rw [← Dyadic.D.generators,MonoidHom.map_closure]
  simp [Set.image_insert_eq,Set.image_singleton,dyadicMapOfLifts_x a b c ha,
    dyadicMapOfLifts_y a b c hb,dyadicMapOfLifts_z a b c hc]

/-- Central changes of generators preserve every actual augmentation-layer injection. -/
theorem dyadicMapOfLifts_comap_dimensionSubgroup (a b c : Q) (n : ℕ) :
    (dimensionSubgroup F Q n).comap (dyadicMapOfLifts a b c)=Dyadic.AlgebraD.dimensionSubgroup n := by
  let e := GroupModel.centralShear cocycle (dyadicAdjustment a.central b.central c.central)
  have he : (dimensionSubgroup F Q n).comap e.toMonoidHom=dimensionSubgroup F Q n := by
    ext g
    change e g∈dimensionSubgroup F Q n ↔ g∈dimensionSubgroup F Q n
    constructor
    · intro h
      have hh := map_dimensionSubgroup_le F Q e.symm.toMonoidHom n ⟨e g,h,rfl⟩
      simpa using hh
    · intro h
      exact map_dimensionSubgroup_le F Q e.toMonoidHom n ⟨g,h,rfl⟩
  change (dimensionSubgroup F Q n).comap (e.toMonoidHom.comp dyadicMap)=_
  rw [← Subgroup.comap_comap,he]
  exact dyadicMap_comap_dimensionSubgroup n

end UnitDistance.RetainedQuadratic
