module

public import UnitDistance.RationalLocalAbsoluteEmbedding
public import UnitDistance.AbsoluteProPUnramified
public import UnitDistance.MaximalProTwoSigma
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Local.LocalUnramifiedH2Vanishing
public import UnitDistance.Upstream.Yamaguchi.SawinTotallyRealTowers.UnramifiedProPRelationRank.Global.ProfiniteIntegerFree

@[expose] public section
set_option backward.privateInPublic true


/-! Actual Frobenius lifts and decomposition generators outside the six-prime
ramification support. The proof uses the actual local residue-degree quotient. -/
noncomputable section
set_option backward.isDefEq.respectTransparency false
set_option maxHeartbeats 800000
namespace UnitDistance.SigmaUnramified
open ArithmeticProP PrimeCompletion LocalClassFieldTheory ClassFormation
open ClassFieldTower.Martinet.Shafarevich
open ClassFieldTower.Cohomology.ProfiniteInteger
attribute [local instance] PrimeCompletion.primeFact PrimeCompletion.baseRationalAlgebra
abbrev SigmaGroup := Gal(maximalSigmaProTwo/ℚ)

def decompositionMap (p : Nat.Primes) : AbsoluteDecomposition p →ₜ* SigmaGroup :=
  (absoluteToMaximalProPOutside 2 sigmaPrimeSupport).comp
    ⟨(AbsoluteDecomposition p).subtype,continuous_subtype_val⟩

def localMap (p : Nat.Primes) : Gal(SeparableClosure (Base p)/Base p) →ₜ* SigmaGroup :=
  (decompositionMap p).comp
    ⟨(decompositionEquiv p).symm.toMulEquiv.toMonoidHom,(decompositionEquiv p).symm.continuous⟩

theorem inertia_killed (p : Nat.Primes) (hp : place p∉sigmaPrimeSupport)
    (σ : AbsoluteInertia p) : decompositionMap p σ.val=1 :=
  absoluteToMaximalProPOutside_inertia 2 sigmaPrimeSupport (place p) hp σ

theorem residueDegree_ker_le (p : Nat.Primes) (hp : place p∉sigmaPrimeSupport) :
    (localResidueDegree (Base p)).toMonoidHom.ker≤(localMap p).toMonoidHom.ker := by
  intro σ hσ
  have hi : (decompositionEquiv p).symm σ∈AbsoluteInertia p := by
    apply (decomposition_mem_inertia_iff p _).mp
    simpa using hσ
  exact inertia_killed p hp ⟨_,hi⟩

/-- The actual outside-support decomposition map factors continuously through
its arithmetic residue degree. -/
def residueFactor (p : Nat.Primes) (hp : place p∉sigmaPrimeSupport) : ZHatMul →ₜ* SigmaGroup :=
  (ProCGroups.QuotientGroup.liftₜ (localResidueDegree (Base p)).toMonoidHom.ker
    (localMap p) (residueDegree_ker_le p hp)).comp
      ⟨(localUnramifiedQuotientContinuousMulEquiv (Base p)).symm.toMulEquiv.toMonoidHom,
        (localUnramifiedQuotientContinuousMulEquiv (Base p)).symm.continuous⟩

theorem residueFactor_degree (p : Nat.Primes) (hp : place p∉sigmaPrimeSupport)
    (σ : Gal(SeparableClosure (Base p)/Base p)) :
    residueFactor p hp (localResidueDegree (Base p) σ)=localMap p σ := by
  have h : localResidueDegree (Base p) σ=
      localUnramifiedQuotientContinuousMulEquiv (Base p)
        (QuotientGroup.mk' (localResidueDegree (Base p)).toMonoidHom.ker σ) := rfl
  rw [h]
  change ProCGroups.QuotientGroup.liftₜ (localResidueDegree (Base p)).toMonoidHom.ker
    (localMap p) (residueDegree_ker_le p hp)
    ((localUnramifiedQuotientContinuousMulEquiv (Base p)).symm
      (localUnramifiedQuotientContinuousMulEquiv (Base p) _))=_
  rw [ContinuousMulEquiv.symm_apply_apply]
  rfl

/-- An actual local absolute automorphism of arithmetic residue degree one. -/
def localFrobenius (p : Nat.Primes) : Gal(SeparableClosure (Base p)/Base p) :=
  Function.surjInv (localResidueDegree_surjective (Base p)) generator

theorem localFrobenius_degree (p : Nat.Primes) :
    localResidueDegree (Base p) (localFrobenius p)=generator :=
  Function.surjInv_eq (localResidueDegree_surjective (Base p)) generator

def absoluteFrobenius (p : Nat.Primes) : AbsoluteDecomposition p :=
  (decompositionEquiv p).symm (localFrobenius p)

def frobenius (p : Nat.Primes) : SigmaGroup := decompositionMap p (absoluteFrobenius p)

theorem residueFactor_generator (p : Nat.Primes) (hp : place p∉sigmaPrimeSupport) :
    residueFactor p hp generator=frobenius p := by
  rw [←localFrobenius_degree p,residueFactor_degree]
  rfl

/-- Every continuous discrete image of the profinite integers is generated
by the image of arithmetic degree one. -/
theorem profiniteInteger_image_zpowers
    {H : Type*} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    (f : ZHatMul →ₜ* H) (z : ZHatMul) : f z∈Subgroup.zpowers (f generator) := by
  refine denseRange_integersMap.induction_on z ?_ ?_
  · exact (isClosed_discrete (Subgroup.zpowers (f generator) : Set H)).preimage f.continuous
  · intro n
    change f (integersMap (Multiplicative.ofAdd n.toAdd))∈_
    rw [integersMap_apply,map_zpow]
    exact Subgroup.zpow_mem _ (Subgroup.mem_zpowers _) _

/-- In every finite quotient, the image of the full chosen decomposition
subgroup is generated by this one actual Frobenius. The theorem in fact
holds for every continuous discrete quotient. -/
theorem decomposition_image_zpowers (p : Nat.Primes) (hp : place p∉sigmaPrimeSupport)
    {H : Type*} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    (q : SigmaGroup →ₜ* H) (d : AbsoluteDecomposition p) :
    q (decompositionMap p d)∈Subgroup.zpowers (q (frobenius p)) := by
  have h := profiniteInteger_image_zpowers (q.comp (residueFactor p hp))
    (localResidueDegree (Base p) (decompositionEquiv p d))
  change q (residueFactor p hp (localResidueDegree (Base p) (decompositionEquiv p d)))∈
    Subgroup.zpowers (q (residueFactor p hp generator)) at h
  rw [residueFactor_degree,residueFactor_generator] at h
  change q (decompositionMap p ((decompositionEquiv p).symm (decompositionEquiv p d)))∈_ at h
  simpa only [ContinuousMulEquiv.symm_apply_apply] using h

/-- Equality of the full decomposition image with the cyclic subgroup, not
only membership of its individual elements. -/
theorem decomposition_range_eq_zpowers (p : Nat.Primes) (hp : place p∉sigmaPrimeSupport)
    {H : Type*} [Group H] [TopologicalSpace H] [DiscreteTopology H]
    (q : SigmaGroup →ₜ* H) :
    (q.comp (decompositionMap p)).toMonoidHom.range=Subgroup.zpowers (q (frobenius p)) := by
  apply le_antisymm
  · rintro _ ⟨d,rfl⟩
    exact decomposition_image_zpowers p hp q d
  · apply Subgroup.zpowers_le.mpr
    exact ⟨absoluteFrobenius p,rfl⟩

end UnitDistance.SigmaUnramified
