module

public import UnitDistance.TruncatedMagnusConjugacy

@[expose] public section
set_option backward.privateInPublic true


/-! The cubic detector supplies an actual conjugacy-index bound, even in
the subgroup generated by the seven displayed generators. No surjectivity
onto the much larger ambient tensor quotient is assumed. -/
noncomputable section
namespace UnitDistance.TruncatedMagnus

/-- An injectively parametrized family of actual conjugates bounds the actual centralizer index. -/
theorem card_le_centralizer_index_of_conjugates_injective
    {G P : Type*} [_root_.Group G] [Finite G] [Finite P] (c : G) (g : P → G)
    (hinj : Function.Injective (fun p => g p*c*(g p)⁻¹)) :
    Nat.card P ≤ (Subgroup.centralizer ({c} : Set G)).index := by
  let f : P → G ⧸ Subgroup.centralizer ({c} : Set G) := fun p => QuotientGroup.mk (g p)
  apply Nat.card_le_card_of_injective f
  intro p q hpq
  apply hinj
  have hmem : (g p)⁻¹*g q∈Subgroup.centralizer ({c} : Set G) := QuotientGroup.eq.mp hpq
  have hc := Subgroup.mem_centralizer_singleton_iff.mp hmem
  have h := congrArg (fun x : G => g p*x*(g q)⁻¹) hc
  simpa [mul_assoc] using h.symm

namespace Certificate
open ClassTwo.Collection

theorem card_parameters : Nat.card (U × U)=4096 := by
  rw [Nat.card_prod]
  simp only [U,Nat.card_fun,Nat.card_fin,Nat.card_zmod]
  norm_num

/-- At least 4096 conjugates survive in the actual finite cut quotient. -/
theorem conjugacy_index_lower (tails : Fin 16 → V₃ F) :
    4096 ≤ (Subgroup.centralizer ({quotientMap tails (generator 0)} : Set (Cut tails))).index := by
  rw [← card_parameters]
  apply card_le_centralizer_index_of_conjugates_injective _
    (fun p : U × U => quotientMap tails (conjugator p.1 p.2))
  simpa only [conjugate,map_mul,map_inv] using conjugate_injective tails

theorem word_mem_subgroup {G I : Type*} [_root_.Group G] (H : Subgroup G)
    (g : I → G) (l : List I) (v : I → F) (hg : ∀ i∈l,g i∈H) : word g l v∈H := by
  unfold word
  apply H.list_prod_mem
  intro x hx
  obtain ⟨i,hi,rfl⟩ := List.mem_map.mp hx
  rcases binary_cases (v i) with ht | ht
  · simp [ht]
  · simpa only [ht,bit_one] using hg i hi

theorem conjugator_mem_subgroup (tails : Fin 16 → V₃ F) (H : Subgroup (Cut tails))
    (hgen : ∀ i,quotientMap tails (generator i)∈H) (u v : U) :
    quotientMap tails (conjugator u v)∈H := by
  let H' := H.comap (quotientMap tails)
  change conjugator u v∈H'
  apply H'.mul_mem
  · exact word_mem_subgroup H' _ _ _ (fun i _ => hgen i.succ)
  · apply word_mem_subgroup H'
    intro i hi
    exact H'.mul_mem (H'.mul_mem (H'.mul_mem (hgen _) (hgen _))
      (H'.inv_mem (hgen _))) (H'.inv_mem (hgen _))

/-- The same 4096 bound holds inside every actual subgroup containing the seven generators. -/
theorem conjugacy_index_lower_subgroup (tails : Fin 16 → V₃ F) (H : Subgroup (Cut tails))
    (hgen : ∀ i,quotientMap tails (generator i)∈H) :
    4096 ≤ (Subgroup.centralizer
      ({(⟨quotientMap tails (generator 0),hgen 0⟩ : H)} : Set H)).index := by
  rw [← card_parameters]
  let c : H := ⟨quotientMap tails (generator 0),hgen 0⟩
  let g : U × U → H := fun p =>
    ⟨quotientMap tails (conjugator p.1 p.2),conjugator_mem_subgroup tails H hgen p.1 p.2⟩
  apply card_le_centralizer_index_of_conjugates_injective c g
  intro p q hpq
  apply conjugate_injective tails
  have h := congrArg (fun x : H => (x : Cut tails)) hpq
  simpa only [g,c,Subgroup.coe_mul,Subgroup.coe_inv,conjugate,map_mul,map_inv] using h

end Certificate
end UnitDistance.TruncatedMagnus
