-- Generated by scripts/sqrt241/generate_group_data.py — do not edit by hand.
module

public import Mathlib.Data.Nat.Bitwise
public import Mathlib.Data.Fin.VecNotation

@[expose] public section
set_option backward.privateInPublic true


/-!
# Generated finite data for the tower over `ℚ(√241)`

Generated by `scripts/sqrt241/generate_group_data.py`; do not edit by hand.
All numbers are untrusted bit masks: every property used downstream is
checked in the other `GroupData` modules by `decide +kernel`.

Coordinates: bit `i` of a vector mask is the Kummer coordinate `αᵢ` of
`[-1, ε, π₂, π₂', π₃, π₃', π₅, π₅']`; the universal quadratic layer has the
squares at bits `0..7` and the pairs `(j<i)` at `8 + ` lexicographic index;
Magnus tensor entry `(i,j)` is bit `8i+j` and `(i,j,k)` is bit `64i+8j+k`.
-/

namespace UnitDistance.Sqrt241.GroupData

/-- Complex conjugations `c₁ = 10111010`, `c₂ = 11000101`. -/
def conjMask : Fin 2 → ℕ := ![93,163]
/-- Tame inertia at `𝔮₁, 𝔮₂, 𝔯₁, 𝔯₂`. -/
def tameInertiaMask : Fin 4 → ℕ := ![16,32,64,128]
/-- Tame Frobenius lifts (fixing the Kummer class of the prime) at `𝔮₁, 𝔮₂, 𝔯₁, 𝔯₂`. -/
def tameFrobeniusMask : Fin 4 → ℕ := ![229,215,166,90]
/-- Norms of the tame primes. -/
def tameNorm : Fin 4 → ℕ := ![3,3,5,5]
/-- Dyadic local generators `a, b, c` (classes of `-1, 5, 2`) at `𝔭₁, 𝔭₂`. -/
def dyadicAMask : Fin 2 → ℕ := ![79,129]
def dyadicBMask : Fin 2 → ℕ := ![4,8]
def dyadicCMask : Fin 2 → ℕ := ![110,158]
/-- The dyadic generators `x = b`, `y = a`, `z = a c`. -/
def dyadicXMask : Fin 2 → ℕ := ![4,8]
def dyadicYMask : Fin 2 → ℕ := ![79,129]
def dyadicZMask : Fin 2 → ℕ := ![33,31]
/-- Frobenius at `29₁`, `29₂` and the square of the Frobenius at the inert `7`. -/
def capMask : Fin 3 → ℕ := ![228,216,14]

/-- Lower-triangular universal cocycle on `F₂⁸ × F₂³⁶`. -/
def universalCocycleMasks : Fin 8 → Fin 8 → ℕ :=
  ![![1,0,0,0,0,0,0,0],
    ![256,2,0,0,0,0,0,0],
    ![512,32768,4,0,0,0,0,0],
    ![1024,65536,2097152,8,0,0,0,0],
    ![2048,131072,4194304,67108864,16,0,0,0],
    ![4096,262144,8388608,134217728,1073741824,32,0,0],
    ![8192,524288,16777216,268435456,2147483648,8589934592,64,0],
    ![16384,1048576,33554432,536870912,4294967296,17179869184,34359738368,128]]

/-- The 21 quadratic cut initials in the universal layer (order of `quadraticWords`: c1^2, c2^2, tame(q0), tame(q1), tame(q2), tame(q3), y2^2, x1^2, [x1,y1], [x1,z1], x2^2, [x2,y2], [x2,z2], tau(q0)^2, tau(q1)^2, tau(q2)^2, tau(q3)^2, phi(q0)^2, phi(q1)^2, phi(q2)^2, phi(q3)^2). -/
def cutInitialMasks : Fin 21 → ℕ :=
  ![2506108509,17181200803,7520389136,26852200480,42966974464,39192625152,16513,4,18907648,8389120,8,536871936,69272576,16,32,64,128,60188291813,40858479575,17223155878,2483748954]
/-- The seven presentation relator initials (`c₁², c₂²`, four tame, genuine at `𝔭₂`). -/
def relatorInitialMasks : Fin 7 → ℕ := ![2506108509,17181200803,7520389136,26852200480,42966974464,39192625152,606158977]
/-- Dual functionals on the universal layer for the seven relator initials. -/
def relatorCoordinateMasks : Fin 7 → ℕ := ![4,2,20,34,524288,1048578,7]

/-- Images of the 36 universal basis vectors in the 15 retained coordinates. -/
def quadraticColumns : Fin 36 → ℕ :=
  ![1,2,0,0,0,0,0,0,4,8,16,32,64,128,1,256,512,204,1024,2048,3530,4096,2943,8,4360,332,4624,8192,2711,16,16384,4681,22806,19908,2444,21708]
/-- Coefficients (21-bit masks) of the relation part of each universal basis vector. -/
def relationCoefficientColumns : Fin 36 → ℕ :=
  ![0,0,128,1024,8192,16384,32768,65536,0,0,0,0,0,0,65600,0,0,884828,0,0,753744,0,1933789,512,256,590530,4096,0,40703,2048,0,1944227,2938,754202,770066,754442]
/-- The section `F₂¹⁵ → F₂³⁶`: the universal basis vector of each free coordinate. -/
def freeColumnMasks : Fin 15 → ℕ :=
  ![1,2,256,512,1024,2048,4096,8192,32768,65536,262144,524288,2097152,134217728,1073741824]
/-- Lower-triangular cocycle of the retained model on `F₂⁸ × F₂¹⁵`. -/
def retainedCocycleMasks : Fin 8 → Fin 8 → ℕ :=
  ![![1,0,0,0,0,0,0,0],
    ![4,2,0,0,0,0,0,0],
    ![8,256,0,0,0,0,0,0],
    ![16,512,4096,0,0,0,0,0],
    ![32,204,2943,4624,0,0,0,0],
    ![64,1024,8,8192,16384,0,0,0],
    ![128,2048,4360,2711,4681,19908,0,0],
    ![1,3530,332,16,22806,2444,21708,0]]

/-- Normal-form images of the 32 elements of `Dyadic.D` (indexed by `D.index`) in the retained model. -/
def dyadicBaseMasks : Fin 2 → Fin 32 → ℕ :=
  ![![0,0,33,33,0,0,33,33,79,79,110,110,79,79,110,110,4,4,37,37,4,4,37,37,75,75,106,106,75,75,106,106],
    ![0,0,31,31,0,0,31,31,129,129,158,158,129,129,158,158,8,8,23,23,8,8,23,23,137,137,150,150,137,137,150,150]]
def dyadicCentralMasks : Fin 2 → Fin 32 → ℕ :=
  ![![0,26896,0,26896,65,26961,65,26961,0,26896,19801,9289,65,26961,19736,9224,0,26896,8,26904,65,26961,73,26969,264,26648,19545,9545,329,26713,19480,9480],
    ![0,21949,0,21949,2716,24353,2716,24353,0,21949,21888,61,2716,24353,24348,2721,0,21949,4624,18349,2716,24353,6284,19761,16,21933,18304,4669,2700,24369,19740,6305]]
/-- Linear functionals on `F₂⁸` dual to `(x_P, y_P, z_P)`. -/
def dyadicCharacterMasks : Fin 2 → Fin 3 → ℕ :=
  ![![6,2,32],
    ![10,128,2]]

/-- The 21 quadratic cut initials as Magnus tensors. -/
def quadraticRowMasks : Fin 21 → ℕ :=
  ![26177573832425565,11745567048577622947,1157443748688298000,2315121925281554464,4658481233309745152,6521212812335808512,9295429630892703873,262144,1125899978867716,4398048673796,134217728,576460754467684360,34746140680,68719476736,35184372088832,18014398509481984,9223372036854775808,16565898592530006245,15552900761579411415,11961743129237169664,25333135960988160]
/-- Supports of a left inverse of the 21 rows. -/
def leftSupports : Fin 21 → List (Fin 8 × Fin 8) :=
  ![[(0,0),(7,0)],
    [(1,1),(1,2),(2,3),(4,3)],
    [(1,4),(4,0),(6,3)],
    [(1,1),(1,5),(4,1)],
    [(4,1),(6,1)],
    [(3,6),(6,4),(7,4)],
    [(1,1),(1,4),(7,0),(7,2)],
    [(1,3),(2,2),(2,7),(3,4)],
    [(2,3),(3,1),(3,6)],
    [(1,1),(4,1),(5,0),(5,2)],
    [(3,3),(3,6)],
    [(0,3),(3,1),(3,6)],
    [(3,6),(4,3)],
    [(4,4),(6,4)],
    [(5,5),(5,7)],
    [(0,6),(2,4),(6,4),(6,6)],
    [(0,0),(2,7),(6,0),(7,7)],
    [(1,5),(7,5)],
    [(1,5),(5,0),(7,2)],
    [(0,5),(5,7)],
    [(2,4),(6,4)]]
/-- Generators used for the second-layer conjugators. -/
def baseIndex : Fin 7 → Fin 8 := ![1,2,3,4,5,6,7]
/-- Supports of the second-layer detector (kills the rows, dual to `[e_i, c₁]`). -/
def secondSupports : Fin 7 → List (Fin 8 × Fin 8) :=
  ![[(1,1),(3,5),(5,6),(6,1),(7,5)],
    [(0,4),(4,2)],
    [(0,6),(1,1),(1,4),(1,5),(3,5),(3,6),(5,6),(6,1)],
    [(0,1),(4,1),(4,5),(4,6),(5,0),(6,0)],
    [(5,3)],
    [(0,4),(0,5),(1,0),(4,6),(5,6),(6,1)],
    [(3,5),(5,1),(5,6),(6,7),(7,1)]]
/-- Generator pairs used for the third-layer conjugators. -/
def selectedPairs : Fin 8 → Fin 8 × Fin 8 := ![(0,1),(0,2),(0,3),(0,4),(0,5),(0,7),(2,3),(4,5)]
/-- Supports of the third-layer detector (kills `[e_j, row]` and the dyadic cubics). -/
def thirdSupports : Fin 8 → List (Fin 8 × Fin 8 × Fin 8) :=
  ![[(0,1,1),(0,5,7),(0,6,1),(0,6,7),(1,1,7),(1,4,3),(3,0,1),(3,4,5),(3,6,1),(3,7,1),(5,3,0),(5,3,7),(5,4,0),(5,4,7),(5,6,3),(7,2,1),(7,2,3),(7,4,0),(7,4,3)],
    [(0,0,2),(0,0,6),(0,1,2),(0,1,6),(0,4,2),(0,4,6),(0,5,2),(0,5,6),(2,0,7),(2,4,7),(2,5,7),(6,0,7),(7,1,2),(7,1,6),(7,4,6),(7,5,6)],
    [(0,1,7),(0,4,7),(0,5,1),(1,1,4),(1,1,5),(1,6,4),(3,0,5),(3,1,7),(3,2,7),(3,4,5),(3,7,4),(4,0,3),(4,0,6),(4,1,3),(4,1,7),(4,2,1),(4,2,6),(4,5,0),(4,6,3),(7,1,5),(7,2,1),(7,3,5),(7,5,4)],
    [(1,0,6),(1,1,2),(1,1,5),(1,2,4),(1,3,5),(1,6,2),(1,7,2),(1,7,5),(2,1,5),(2,3,5),(4,0,1),(4,1,1),(4,1,6),(5,3,6),(5,7,2),(6,0,4),(6,1,1),(6,1,5),(6,2,4),(6,7,2),(6,7,5)],
    [(0,3,5),(1,1,6),(1,3,5),(1,6,3),(1,7,4),(1,7,5),(1,7,6),(3,0,4),(4,0,6),(4,1,3),(4,2,1),(4,3,6),(4,7,3),(5,0,4),(5,1,1),(5,3,6),(5,6,4),(6,0,3),(6,2,4),(6,7,3),(7,3,5)],
    [(0,0,4),(0,4,2),(1,0,6),(1,3,2),(2,3,4),(2,3,6),(2,6,4),(3,0,4),(3,0,6),(3,1,6),(3,4,1),(3,7,4),(4,0,1),(4,0,6),(4,1,1),(4,2,7),(4,3,6),(4,7,6),(6,1,1),(6,2,1),(6,4,1),(6,7,3),(7,0,4)],
    [(1,2,3),(1,2,6),(1,7,4),(1,7,6),(3,4,1),(3,4,5),(3,4,6),(3,6,5),(3,7,5),(4,7,6),(5,0,3),(5,1,4),(5,1,6),(6,0,5),(6,2,3),(6,4,1),(6,5,4),(6,7,5)],
    [(1,5,6),(1,7,4),(4,5,1),(4,7,6),(6,5,4),(6,7,1)]]

end UnitDistance.Sqrt241.GroupData
