module

public import UnitDistance.Sqrt241.GroupData.Words
public import UnitDistance.RetainedCyclicLocalModels
public import UnitDistance.GroupAugmentationStrictness

@[expose] public section
set_option backward.privateInPublic true


/-!
# Strict embeddings of the nondyadic local groups into class-two models

Generic statements for any bilinear class-two group `GroupModel β` over
`F₂`: a homomorphism from a finite group that is injective and whose kernel on
elementary coordinates lies in the second dimension subgroup is strict in
every augmentation degree (the third dimension subgroup of the model is
trivial). This gives all layer injections for

* `C₂` generated by an element with nonzero elementary vector (real places);
* `C₄` generated by an element of order four with nonzero elementary vector
  (the three caps);
* `C₂ × C₂ = OddLocal.D 0` generated by two commuting involutions with
  independent elementary vectors (the four tame places).

The `B`-specific facts (nonzero vectors, nonzero squares of the caps,
independent tame pairs) are finite certificates below. Layer injectivity
passes from a composite to its first factor (`layers_of_comp`), which is how
the local maps into a cut quotient inherit it from `Q_B`.
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false
namespace UnitDistance.Sqrt241.LocalModels
open ClassTwo GroupData GroupAugmentation OddLocal RetainedCyclic

section Pullback
variable {H P K : Type*} [Group H] [Group P] [Group K]

/-- Layer injectivity of a composite passes to its first factor. -/
theorem layer_injective_of_comp (f : H →* P) (π : P →* K) (n : ℕ)
    (h : Function.Injective (layerMap F H (π.comp f) n)) :
    Function.Injective (layerMap F H f n) := by
  apply (layerMap_injective_iff F H f n).mpr
  intro g hg hfg
  exact (layerMap_injective_iff F H (π.comp f) n).mp h g hg
    (map_dimensionSubgroup_le F P π (n+1) ⟨f g,hfg,rfl⟩)

theorem layers_of_comp (f : H →* P) (π : P →* K) (ψ : H →* K) (hψ : π.comp f = ψ)
    (h : ∀ n, Function.Injective (layerMap F H ψ n)) (n : ℕ) :
    Function.Injective (layerMap F H f n) :=
  layer_injective_of_comp f π n (by rw [hψ]; exact h n)

end Pullback

section Generic
variable {V' W' : Type*} [AddCommGroup V'] [Module F V'] [AddCommGroup W'] [Module F W']
  (β : V' →ₗ[F] V' →ₗ[F] W')

theorem base_pow (g : GroupModel β) (k : ℕ) : (g^k).base = k • g.base := by
  induction k with
  | zero => rw [pow_zero,zero_nsmul]; rfl
  | succ k ih => rw [pow_succ,GroupModel.mul_base,ih,succ_nsmul]

theorem two_nsmul_eq_zero (v : V') : (2 : ℕ) • v = 0 := by
  rw [two_nsmul]
  exact GroupModel.add_self_of_charTwo (R := F) v

/-- Injective maps whose elementary kernel lies in `D₂` are strict. -/
theorem strict_of_base {H : Type*} [Group H] (ψ : H →* GroupModel β)
    (hinj : Function.Injective ψ)
    (hbase : ∀ h, (ψ h).base = 0 → h ∈ dimensionSubgroup F H 2) (n : ℕ) :
    (dimensionSubgroup F (GroupModel β) n).comap ψ = dimensionSubgroup F H n := by
  have hthird : dimensionSubgroup F H 3 = ⊥ := by
    apply le_bot_iff.mp
    intro g hg
    have hm := map_dimensionSubgroup_le F H ψ 3 ⟨g,hg,rfl⟩
    rw [GroupModel.dimensionSubgroup_three,Subgroup.mem_bot] at hm
    exact hinj (hm.trans (map_one ψ).symm)
  apply comap_dimensionSubgroup_eq_of_first_two_layers F H ψ hthird
  · apply (layerMap_injective_iff F H ψ 1).mpr
    intro g _ hg
    exact hbase g (GroupModel.base_eq_zero_of_mem_dimension_two β (ψ g) hg)
  · apply (layerMap_injective_iff F H ψ 2).mpr
    intro g _ hg
    rw [GroupModel.dimensionSubgroup_three,Subgroup.mem_bot] at hg
    have he : g = 1 := hinj (hg.trans (map_one ψ).symm)
    rw [he]
    exact Subgroup.one_mem _

theorem layers_of_base {H : Type*} [Group H] (ψ : H →* GroupModel β)
    (hinj : Function.Injective ψ)
    (hbase : ∀ h, (ψ h).base = 0 → h ∈ dimensionSubgroup F H 2) (n : ℕ) :
    Function.Injective (layerMap F H ψ n) :=
  layer_injections_of_comap_dimensionSubgroup_eq F H (GroupModel β) ψ
    (strict_of_base β ψ hinj hbase) n

theorem cyclicMap_base (n : ℕ) [NeZero n] (g : GroupModel β) (hg : g^n = 1) (x : Cyclic n) :
    (cyclicMap n g hg x).base = x.toAdd.val • g.base := by
  rw [cyclicMap_pow_val,base_pow]

/-- `C₂` with a nonzero elementary vector: all layers inject. -/
theorem cyclicTwo_layers (g : GroupModel β) (hg : g^2 = 1) (hb : g.base ≠ 0) (n : ℕ) :
    Function.Injective (layerMap F (Cyclic 2) (cyclicMap 2 g hg) n) := by
  have hzero (x : Cyclic 2) (hx : (cyclicMap 2 g hg x).base = 0) : x = 1 := by
    have hv := ZMod.val_lt x.toAdd
    rw [cyclicMap_base] at hx
    have hn : x.toAdd.val = 0 ∨ x.toAdd.val = 1 := by omega
    rcases hn with hn | hn
    · rw [cyclic_pow_val 2 x,hn,pow_zero]
    · rw [hn,one_nsmul] at hx
      exact absurd hx hb
  apply layers_of_base β
  · rw [← MonoidHom.ker_eq_bot_iff]
    apply le_bot_iff.mp
    intro x hx
    exact hzero x (congrArg GroupModel.base hx)
  · intro x hx
    rw [hzero x hx]
    exact Subgroup.one_mem _

/-- An element of order four with nonzero elementary vector. -/
theorem orderOf_eq_four (g : GroupModel β) (hsq : g^2 ≠ 1) : orderOf g = 4 := by
  have h4 : g^(2^(1+1)) = 1 := by
    change g^(2*2) = 1
    rw [pow_mul,GroupModel.square_coordinates,GroupModel.square_coordinates]
    apply GroupModel.ext <;> simp
  exact orderOf_eq_prime_pow (p := 2) (n := 1) (by simpa using hsq) h4

theorem pow_four_eq_one (g : GroupModel β) : g^4 = 1 := by
  change g^(2*2) = 1
  rw [pow_mul,GroupModel.square_coordinates,GroupModel.square_coordinates]
  apply GroupModel.ext <;> simp

/-- `C₄` generated by an element whose square is nontrivial and whose
elementary vector is nonzero: all layers inject. -/
theorem cyclicFour_layers (g : GroupModel β) (hsq : g^2 ≠ 1) (hb : g.base ≠ 0) (n : ℕ) :
    Function.Injective (layerMap F (Cyclic 4) (cyclicMap 4 g (pow_four_eq_one β g)) n) := by
  apply layers_of_base β
  · exact cyclicMap_injective 4 g _ (orderOf_eq_four β g hsq)
  · intro x hx
    have hv := ZMod.val_lt x.toAdd
    rw [cyclicMap_base] at hx
    have hn : x.toAdd.val = 0 ∨ x.toAdd.val = 1 ∨ x.toAdd.val = 2 ∨ x.toAdd.val = 3 := by omega
    rcases hn with hn | hn | hn | hn
    · rw [cyclic_pow_val 4 x,hn,pow_zero]
      exact Subgroup.one_mem _
    · rw [hn,one_nsmul] at hx
      exact absurd hx hb
    · rw [cyclic_pow_val 4 x,hn]
      exact square_mem F (Cyclic 4) (n := 1) (g := cyclicGenerator 4) (by simp)
    · exfalso
      rw [hn,show (3 : ℕ) = 2+1 from rfl,add_nsmul,two_nsmul_eq_zero,zero_add,one_nsmul] at hx
      exact hb hx

theorem residueDegree_zero : residueDegree 0 = 2 := rfl

/-- The tame local map `C₂ × C₂ → GroupModel β`. -/
def tameMap (t f : GroupModel β) (ht : t^2 = 1) (hf : f^2 = 1) (hc : Commute t f) :
    OddLocal.D 0 →* GroupModel β :=
  OddLocal.map 0 t f ht (by rw [residueDegree_zero]; exact hf) hc

theorem tameMap_apply (t f : GroupModel β) (ht : t^2 = 1) (hf : f^2 = 1) (hc : Commute t f)
    (x : OddLocal.D 0) :
    tameMap β t f ht hf hc x = t^x.1.toAdd.val*f^x.2.toAdd.val := by
  unfold tameMap OddLocal.map
  rw [MonoidHom.noncommCoprod_apply,cyclicMap_pow_val,cyclicMap_pow_val]

/-- `C₂ × C₂` with independent elementary vectors: all layers inject. -/
theorem tame_layers (t f : GroupModel β) (ht : t^2 = 1) (hf : f^2 = 1) (hc : Commute t f)
    (hind : ∀ a b : F, a • t.base + b • f.base = 0 → a = 0 ∧ b = 0) (n : ℕ) :
    Function.Injective (layerMap F (OddLocal.D 0) (tameMap β t f ht hf hc) n) := by
  have hzero (x : OddLocal.D 0) (hx : (tameMap β t f ht hf hc x).base = 0) : x = 1 := by
    rw [tameMap_apply,GroupModel.mul_base,base_pow,base_pow] at hx
    have h1 := ZMod.val_lt x.1.toAdd
    have h2 : x.2.toAdd.val < 2 := ZMod.val_lt (n := 2) x.2.toAdd
    have hcast (k : ℕ) (hk : k < 2) (v : V') : k • v = (k : F) • v := by
      rw [Nat.cast_smul_eq_nsmul]
    rw [hcast _ h1,hcast _ h2] at hx
    obtain ⟨ha,hb⟩ := hind _ _ hx
    have ha' : x.1.toAdd.val = 0 := by
      have : ((x.1.toAdd.val : ℕ) : F) = 0 := ha
      rcases (show x.1.toAdd.val = 0 ∨ x.1.toAdd.val = 1 by omega) with h | h
      · exact h
      · rw [h] at this; exact absurd this (by decide)
    have hb' : x.2.toAdd.val = 0 := by
      have : ((x.2.toAdd.val : ℕ) : F) = 0 := hb
      rcases (show x.2.toAdd.val = 0 ∨ x.2.toAdd.val = 1 by omega) with h | h
      · exact h
      · rw [h] at this; exact absurd this (by decide)
    apply Prod.ext
    · rw [cyclic_pow_val 2 x.1,ha',pow_zero]; rfl
    · change x.2 = 1
      have hx2 : x.2 = cyclicGenerator 2^x.2.toAdd.val := cyclic_pow_val 2 x.2
      rw [hx2,hb',pow_zero]
  apply layers_of_base β
  · rw [← MonoidHom.ker_eq_bot_iff]
    apply le_bot_iff.mp
    intro x hx
    exact hzero x (congrArg GroupModel.base hx)
  · intro x hx
    rw [hzero x hx]
    exact Subgroup.one_mem _

end Generic

/-! ### Certificates for the local vectors of `B` -/

open Retained

theorem conjVector_ne_zero_certificate : ∀ i : Fin 2, conjVector i ≠ 0 := by decide +kernel

set_option maxRecDepth 100000 in
set_option maxHeartbeats 16000000 in
theorem cap_square_ne_zero_certificate : ∀ k : Fin 3,
    capVector k ≠ 0 ∧ squareForm (capVector k) ≠ 0 := by decide +kernel

theorem tame_independent_certificate : ∀ (q : Fin 4) (a b : F),
    a • tameInertiaVector q + b • tameFrobeniusVector q = 0 → a = 0 ∧ b = 0 := by
  decide +kernel

/-- Real places: any lift with the vector of `c_i` gives a strict `C₂`. -/
theorem real_layers (g : Q) (hg : g^2 = 1) (i : Fin 2) (hb : g.base = conjVector i) (n : ℕ) :
    Function.Injective (layerMap F (Cyclic 2) (cyclicMap 2 g hg) n) :=
  cyclicTwo_layers cocycle g hg (by rw [hb]; exact conjVector_ne_zero_certificate i) n

theorem cap_square_ne_one (g : Q) (k : Fin 3) (hb : g.base = capVector k) : g^2 ≠ 1 := by
  intro h
  have hc := congrArg GroupModel.central h
  rw [sq_coordinates,hb] at hc
  exact (cap_square_ne_zero_certificate k).2 hc

/-- Caps: any lift with the vector of the cap gives a strict `C₄`. -/
theorem cap_layers (g : Q) (k : Fin 3) (hb : g.base = capVector k) (n : ℕ) :
    Function.Injective (layerMap F (Cyclic 4) (cyclicMap 4 g (pow_four_eq_one cocycle g)) n) :=
  cyclicFour_layers cocycle g (cap_square_ne_one g k hb)
    (by rw [hb]; exact (cap_square_ne_zero_certificate k).1) n

/-- Tame places: lifts with the tame vectors give a strict `C₂ × C₂`. -/
theorem tame_layers_B (t f : Q) (ht : t^2 = 1) (hf : f^2 = 1) (hc : Commute t f) (q : Fin 4)
    (htb : t.base = tameInertiaVector q) (hfb : f.base = tameFrobeniusVector q) (n : ℕ) :
    Function.Injective (layerMap F (OddLocal.D 0) (tameMap cocycle t f ht hf hc) n) :=
  tame_layers cocycle t f ht hf hc (by rw [htb,hfb]; exact tame_independent_certificate q) n

end UnitDistance.Sqrt241.LocalModels
