{
res=List();
forprime(p=7,200000,
  g=znprimroot(p); n=p-1;
  \\ subgroup generated by -1,2,3,5: gcd of discrete logs with n
  d=n; foreach([-1,2,3,5],a, d=gcd(d, znlog(Mod(a,p),g)));
  m=d; \\ index of subgroup
  if(m>=3, rd=p^((m-1)/m); if(rd<200, listput(res,[rd,p,m]))));
res=vecsort(Vec(res),1);
for(i=1,min(#res,30),printf("p=%d index m=%d rd=%.1f\n",res[i][2],res[i][3],res[i][1]));
}
