-- Generated by scripts/sqrt241/generate_finite_certificates.py — do not edit by hand.
module

public import UnitDistance.Sqrt241.FiniteCertificates.Prime2
public import UnitDistance.Sqrt241.FiniteCertificates.Prime3
public import UnitDistance.Sqrt241.FiniteCertificates.Prime5
public import UnitDistance.Sqrt241.FiniteCertificates.Prime29
public import UnitDistance.Sqrt241.FiniteCertificates.Prime7

@[expose] public section
set_option backward.privateInPublic true


/-! # Assembly of the individually proved finite-place enclosures

Generated by scripts/sqrt241/generate_finite_certificates.py. The tables are
untrusted rational candidates; the theorems connect them to the witness and to
the proved inequalities of the prime modules.
-/
noncomputable section
namespace UnitDistance.Sqrt241.Witness.FiniteCertificates

def residueLogUpper : Fin 5 → ℝ :=
  ![(2772588722239781239 : ℝ) / 1000000000000000000, (274653072167027423 : ℝ) / 125000000000000000, (12875503299472803 : ℝ) / 4000000000000000, (1346918331994589611 : ℝ) / 100000000000000000, (7783640596221253221 : ℝ) / 500000000000000000]

def energyLogLower : Fin 5 → ℝ :=
  ![(2183917558544022023 : ℝ) / 1000000000000000000, (1242079676955912249 : ℝ) / 500000000000000000, (2008998724720483309 : ℝ) / 1000000000000000000, (346574125337709689 : ℝ) / 500000000000000000, (173286816678076689 : ℝ) / 250000000000000000]

def massLogUpper : Fin 5 → ℝ :=
  ![(2294668560825061 : ℝ) / 50000000000000000, (16203202941411783 : ℝ) / 200000000000000000, (27280477672486777 : ℝ) / 1000000000000000000, (68909032241 : ℝ) / 200000000000000000, (13184037233 : ℝ) / 500000000000000000]

theorem power_bounds (v : Fin 5) (i : Fin 6) :
    (shellWeights v i : ℝ) ^ p ≤ powerUpper v i := by
  fin_cases v <;> fin_cases i
  · exact power_bound_0_0
  · exact power_bound_0_1
  · exact power_bound_0_2
  · exact power_bound_0_3
  · exact power_bound_0_4
  · exact power_bound_0_5
  · exact power_bound_1_0
  · exact power_bound_1_1
  · exact power_bound_1_2
  · exact power_bound_1_3
  · exact power_bound_1_4
  · exact power_bound_1_5
  · exact power_bound_2_0
  · exact power_bound_2_1
  · exact power_bound_2_2
  · exact power_bound_2_3
  · exact power_bound_2_4
  · exact power_bound_2_5
  · exact power_bound_3_0
  · exact power_bound_3_1
  · exact power_bound_3_2
  · exact power_bound_3_3
  · exact power_bound_3_4
  · exact power_bound_3_5
  · exact power_bound_4_0
  · exact power_bound_4_1
  · exact power_bound_4_2
  · exact power_bound_4_3
  · exact power_bound_4_4
  · exact power_bound_4_5

theorem residue_log_upper (v : Fin 5) : Real.log (residueCard v) ≤ residueLogUpper v := by
  fin_cases v
  · have h := residue_log_0.2
    norm_num [residueLogUpper, residueCard, primes, residueDegree, Matrix.cons_val] at h ⊢
    exact h
  · have h := residue_log_1.2
    norm_num [residueLogUpper, residueCard, primes, residueDegree, Matrix.cons_val] at h ⊢
    exact h
  · have h := residue_log_2.2
    norm_num [residueLogUpper, residueCard, primes, residueDegree, Matrix.cons_val] at h ⊢
    exact h
  · have h := residue_log_3.2
    norm_num [residueLogUpper, residueCard, primes, residueDegree, Matrix.cons_val] at h ⊢
    exact h
  · have h := residue_log_4.2
    norm_num [residueLogUpper, residueCard, primes, residueDegree, Matrix.cons_val] at h ⊢
    exact h

theorem energy_log_lower (v : Fin 5) : energyLogLower v ≤ Real.log (energyLower v) := by
  fin_cases v
  · have h := energy_log_0.1
    norm_num [energyLogLower, energyLower, Matrix.cons_val] at h ⊢
    exact h
  · have h := energy_log_1.1
    norm_num [energyLogLower, energyLower, Matrix.cons_val] at h ⊢
    exact h
  · have h := energy_log_2.1
    norm_num [energyLogLower, energyLower, Matrix.cons_val] at h ⊢
    exact h
  · have h := energy_log_3.1
    norm_num [energyLogLower, energyLower, Matrix.cons_val] at h ⊢
    exact h
  · have h := energy_log_4.1
    norm_num [energyLogLower, energyLower, Matrix.cons_val] at h ⊢
    exact h

theorem mass_log_upper (v : Fin 5) : Real.log (massUpper v) ≤ massLogUpper v := by
  fin_cases v
  · have h := mass_log_0.2
    norm_num [massLogUpper, massUpper, Matrix.cons_val] at h ⊢
    exact h
  · have h := mass_log_1.2
    norm_num [massLogUpper, massUpper, Matrix.cons_val] at h ⊢
    exact h
  · have h := mass_log_2.2
    norm_num [massLogUpper, massUpper, Matrix.cons_val] at h ⊢
    exact h
  · have h := mass_log_3.2
    norm_num [massLogUpper, massUpper, Matrix.cons_val] at h ⊢
    exact h
  · have h := mass_log_4.2
    norm_num [massLogUpper, massUpper, Matrix.cons_val] at h ⊢
    exact h

end UnitDistance.Sqrt241.Witness.FiniteCertificates
