-- Generated by scripts/sqrt241/generate_finite_certificates.py — do not edit by hand.
module

public import UnitDistance.Sqrt241.FiniteCertificates.Data

@[expose] public section
set_option backward.privateInPublic true


/-!
# Compact rational receipts for finite logarithm enclosures

Copy of `UnitDistance.FiniteCertificates.LogEnclosureCompactRun20260920` in the
certificate namespace of this witness: the finite premises are stated over `ℚ`,
proved by kernel reduction, and cast once into `ℝ`.
-/

noncomputable section
set_option autoImplicit false

namespace UnitDistance.Sqrt241.Witness.FiniteCertificates

theorem log_enclosure_of_rat (q : ℚ) (n : ℕ) (lo hi : ℚ)
    (hq : 1 ≤ q)
    (hl : lo ≤ 2 * ∑ i ∈ Finset.range n,
      ((q - 1) / (q + 1)) ^ (2 * i + 1) / (2 * i + 1))
    (hu : 2 * ((∑ i ∈ Finset.range n,
      ((q - 1) / (q + 1)) ^ (2 * i + 1) / (2 * i + 1)) +
      ((q - 1) / (q + 1)) ^ (2 * n + 1) /
        (1 - ((q - 1) / (q + 1)) ^ 2)) ≤ hi) :
    (lo : ℝ) ≤ Real.log (q : ℝ) ∧ Real.log (q : ℝ) ≤ (hi : ℝ) := by
  apply UnitDistance.log_enclosure (q : ℝ) n
  · exact_mod_cast hq
  · exact_mod_cast hl
  · exact_mod_cast hu

end UnitDistance.Sqrt241.Witness.FiniteCertificates
