-- Generated by scripts/sqrt241/generate_finite_certificates.py — do not edit by hand.
module

public import UnitDistance.Sqrt241.FiniteCertificates.LogEnclosure

@[expose] public section
set_option backward.privateInPublic true
set_option linter.unnecessarySeqFocus false


namespace UnitDistance.Sqrt241.Witness.FiniteCertificates

theorem power_bound_1_0 :
    (shellWeights ⟨1, by decide⟩ ⟨0, by decide⟩ : ℝ)^p ≤ powerUpper ⟨1, by decide⟩ ⟨0, by decide⟩ := by
  norm_num [shellWeights, powerUpper, Matrix.cons_val]

theorem weight_log_1_1 :
    (-2458794723170165621 : ℝ) / 1000000000000000000 ≤ Real.log ((3557293422470 : ℝ) / 41587294680821) ∧
    Real.log ((3557293422470 : ℝ) / 41587294680821) ≤ (-2458794723170165619 : ℝ) / 1000000000000000000 := by
  have hb : (7844849976740390431 : ℝ) / 25000000000000000000 ≤ Real.log ((342151943257855917 : ℝ) / 250000000000000000) ∧
      Real.log ((342151943257855917 : ℝ) / 250000000000000000) ≤ (1255175996278462469 : ℝ) / 4000000000000000000 := by
    have h := log_enclosure_of_rat
      ((342151943257855917 : ℚ) / 250000000000000000) 25
      ((7844849976740390431 : ℚ) / 25000000000000000000)
      ((1255175996278462469 : ℚ) / 4000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (56916694759520 : ℝ) / 41587294680821) (l := (342151943257855917 : ℝ) / 250000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((3557293422470 : ℝ) / 41587294680821) ((56916694759520 : ℝ) / 41587294680821) (-4) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_1_1 :
    (-4714172886296531583 : ℝ) / 1000000000000000000 ≤ Real.log ((89672799605278981 : ℝ) / 10000000000000000000) ∧
    Real.log ((89672799605278981 : ℝ) / 10000000000000000000) ≤ (-4714172886296531581 : ℝ) / 1000000000000000000 := by
  have hb : (689286888115427919 : ℝ) / 5000000000000000000 ≤ Real.log ((286952958736892739 : ℝ) / 250000000000000000) ∧
      Real.log ((286952958736892739 : ℝ) / 250000000000000000) ≤ (13785737762308558381 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((286952958736892739 : ℚ) / 250000000000000000) 25
      ((689286888115427919 : ℚ) / 5000000000000000000)
      ((13785737762308558381 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (89672799605278981 : ℝ) / 78125000000000000) (l := (286952958736892739 : ℝ) / 250000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((89672799605278981 : ℝ) / 10000000000000000000) ((89672799605278981 : ℝ) / 78125000000000000) (-7) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_1_1 :
    (shellWeights ⟨1, by decide⟩ ⟨1, by decide⟩ : ℝ)^p ≤ powerUpper ⟨1, by decide⟩ ⟨1, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (3557293422470 : ℝ) / 41587294680821)
    (by norm_num : 0 < (89672799605278981 : ℝ) / 10000000000000000000) witness_basic.2.2.1.le
    weight_log_1_1.2 power_upper_log_1_1.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_1_2 :
    (-4977324333906551563 : ℝ) / 1000000000000000000 ≤ Real.log ((4473097537 : ℝ) / 648982313134) ∧
    Real.log ((4473097537 : ℝ) / 648982313134) ≤ (-4977324333906551561 : ℝ) / 1000000000000000000 := by
  have hb : (14196327764325272823 : ℝ) / 25000000000000000000 ≤ Real.log ((1764474849772308617 : ℝ) / 1000000000000000000) ∧
      Real.log ((1764474849772308617 : ℝ) / 1000000000000000000) ≤ (56785311057301091293 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1764474849772308617 : ℚ) / 1000000000000000000) 25
      ((14196327764325272823 : ℚ) / 25000000000000000000)
      ((56785311057301091293 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (572556484736 : ℝ) / 324491156567) (l := (1764474849772308617 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((4473097537 : ℝ) / 648982313134) ((572556484736 : ℝ) / 324491156567) (-8) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_1_2 :
    (-1908574733799165757 : ℝ) / 200000000000000000 ≤ Real.log ((4481904943838391 : ℝ) / 62500000000000000000) ∧
    Real.log ((4481904943838391 : ℝ) / 62500000000000000000) ≤ (-9542873668995828783 : ℝ) / 1000000000000000000 := by
  have hb : (4029671471085138679 : ℝ) / 25000000000000000000 ≤ Real.log ((117490448959757117 : ℝ) / 100000000000000000) ∧
      Real.log ((117490448959757117 : ℝ) / 100000000000000000) ≤ (16118685884340554717 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((117490448959757117 : ℚ) / 100000000000000000) 25
      ((4029671471085138679 : ℚ) / 25000000000000000000)
      ((16118685884340554717 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (4481904943838391 : ℝ) / 3814697265625000) (l := (117490448959757117 : ℝ) / 100000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((4481904943838391 : ℝ) / 62500000000000000000) ((4481904943838391 : ℝ) / 3814697265625000) (-14) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_1_2 :
    (shellWeights ⟨1, by decide⟩ ⟨2, by decide⟩ : ℝ)^p ≤ powerUpper ⟨1, by decide⟩ ⟨2, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (4473097537 : ℝ) / 648982313134)
    (by norm_num : 0 < (4481904943838391 : ℝ) / 62500000000000000000) witness_basic.2.2.1.le
    weight_log_1_2.2 power_upper_log_1_2.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_1_3 :
    (-3742024352849108401 : ℝ) / 500000000000000000 ≤ Real.log ((26849579809 : ℝ) / 47776963967923) ∧
    Real.log ((26849579809 : ℝ) / 47776963967923) ≤ (-9355060882122771 : ℝ) / 1250000000000000 := by
  have hb : (14057028046118160231 : ℝ) / 100000000000000000000 ≤ Real.log ((1150929964611195899 : ℝ) / 1000000000000000000) ∧
      Real.log ((1150929964611195899 : ℝ) / 1000000000000000000) ≤ (1757128505764770029 : ℝ) / 12500000000000000000 := by
    have h := log_enclosure_of_rat
      ((1150929964611195899 : ℚ) / 1000000000000000000) 25
      ((14057028046118160231 : ℚ) / 100000000000000000000)
      ((1757128505764770029 : ℚ) / 12500000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (54987939448832 : ℝ) / 47776963967923) (l := (1150929964611195899 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((26849579809 : ℝ) / 47776963967923) ((54987939448832 : ℝ) / 47776963967923) (-11) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_1_3 :
    (-2869788124698524523 : ℝ) / 200000000000000000 ≤ Real.log ((29329473733904577 : ℝ) / 50000000000000000000000) ∧
    Real.log ((29329473733904577 : ℝ) / 50000000000000000000000) ≤ (-14348940623492622613 : ℝ) / 1000000000000000000 := by
  have hb : (647344275831965261 : ℝ) / 3125000000000000000 ≤ Real.log ((1230167290000109029 : ℝ) / 1000000000000000000) ∧
      Real.log ((1230167290000109029 : ℝ) / 1000000000000000000) ≤ (20715016826622888353 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1230167290000109029 : ℚ) / 1000000000000000000) 25
      ((647344275831965261 : ℚ) / 3125000000000000000)
      ((20715016826622888353 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (29329473733904577 : ℝ) / 23841857910156250) (l := (1230167290000109029 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((29329473733904577 : ℝ) / 50000000000000000000000) ((29329473733904577 : ℝ) / 23841857910156250) (-21) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_1_3 :
    (shellWeights ⟨1, by decide⟩ ⟨3, by decide⟩ : ℝ)^p ≤ powerUpper ⟨1, by decide⟩ ⟨3, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (26849579809 : ℝ) / 47776963967923)
    (by norm_num : 0 < (29329473733904577 : ℝ) / 50000000000000000000000) witness_basic.2.2.1.le
    weight_log_1_3.2 power_upper_log_1_3.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_1_4 :
    (-9976711992671248129 : ℝ) / 1000000000000000000 ≤ Real.log ((2513662972 : ℝ) / 54092619562375) ∧
    Real.log ((2513662972 : ℝ) / 54092619562375) ≤ (-9976711992671248127 : ℝ) / 1000000000000000000 := by
  have hb : (8409914314558630253 : ℝ) / 20000000000000000000 ≤ Real.log ((761358101464438941 : ℝ) / 500000000000000000) ∧
      Real.log ((761358101464438941 : ℝ) / 500000000000000000) ≤ (21024785786396575633 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((761358101464438941 : ℚ) / 500000000000000000) 25
      ((8409914314558630253 : ℚ) / 20000000000000000000)
      ((21024785786396575633 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (82367708266496 : ℝ) / 54092619562375) (l := (761358101464438941 : ℝ) / 500000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((2513662972 : ℝ) / 54092619562375) ((82367708266496 : ℝ) / 54092619562375) (-15) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_1_4 :
    (-9564024342300911627 : ℝ) / 500000000000000000 ≤ Real.log ((49293993865384733 : ℝ) / 10000000000000000000000000) ∧
    Real.log ((49293993865384733 : ℝ) / 10000000000000000000000000) ≤ (-4782012171150455813 : ℝ) / 250000000000000000 := by
  have hb : (2800723710766454107 : ℝ) / 10000000000000000000 ≤ Real.log ((1323225572131575341 : ℝ) / 1000000000000000000) ∧
      Real.log ((1323225572131575341 : ℝ) / 1000000000000000000) ≤ (28007237107664541071 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1323225572131575341 : ℚ) / 1000000000000000000) 25
      ((2800723710766454107 : ℚ) / 10000000000000000000)
      ((28007237107664541071 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (394351950923077864 : ℝ) / 298023223876953125) (l := (1323225572131575341 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((49293993865384733 : ℝ) / 10000000000000000000000000) ((394351950923077864 : ℝ) / 298023223876953125) (-28) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_1_4 :
    (shellWeights ⟨1, by decide⟩ ⟨4, by decide⟩ : ℝ)^p ≤ powerUpper ⟨1, by decide⟩ ⟨4, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (2513662972 : ℝ) / 54092619562375)
    (by norm_num : 0 < (49293993865384733 : ℝ) / 10000000000000000000000000) witness_basic.2.2.1.le
    weight_log_1_4.2 power_upper_log_1_4.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_1_5 :
    (-6230969792178841651 : ℝ) / 500000000000000000 ≤ Real.log ((282581518 : ℝ) / 72995375851841) ∧
    Real.log ((282581518 : ℝ) / 72995375851841) ≤ (-12461939584357683299 : ℝ) / 1000000000000000000 := by
  have hb : (29419331442664537 : ℝ) / 2000000000000000000 ≤ Real.log ((1014818385276164303 : ℝ) / 1000000000000000000) ∧
      Real.log ((1014818385276164303 : ℝ) / 1000000000000000000) ≤ (1470966572133226851 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1014818385276164303 : ℚ) / 1000000000000000000) 25
      ((29419331442664537 : ℚ) / 2000000000000000000)
      ((1470966572133226851 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (74077049454592 : ℝ) / 72995375851841) (l := (1014818385276164303 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((282581518 : ℝ) / 72995375851841) ((74077049454592 : ℝ) / 72995375851841) (-18) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_1_5 :
    (-2389290051163807917 : ℝ) / 100000000000000000 ≤ Real.log ((42018945684096331 : ℝ) / 1000000000000000000000000000) ∧
    Real.log ((42018945684096331 : ℝ) / 1000000000000000000000000000) ≤ (-373326570494344987 : ℝ) / 15625000000000000 := by
  have hb : (36725080796000666013 : ℝ) / 100000000000000000000 ≤ Real.log ((1443759980204752711 : ℝ) / 1000000000000000000) ∧
      Real.log ((1443759980204752711 : ℝ) / 1000000000000000000) ≤ (18362540398000333007 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1443759980204752711 : ℚ) / 1000000000000000000) 25
      ((36725080796000666013 : ℚ) / 100000000000000000000)
      ((18362540398000333007 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (10756850095128660736 : ℝ) / 7450580596923828125) (l := (1443759980204752711 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((42018945684096331 : ℝ) / 1000000000000000000000000000) ((10756850095128660736 : ℝ) / 7450580596923828125) (-35) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_1_5 :
    (shellWeights ⟨1, by decide⟩ ⟨5, by decide⟩ : ℝ)^p ≤ powerUpper ⟨1, by decide⟩ ⟨5, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (282581518 : ℝ) / 72995375851841)
    (by norm_num : 0 < (42018945684096331 : ℝ) / 1000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_1_5.2 power_upper_log_1_5.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem residue_log_1 :
    (1098612288668109691 : ℝ) / 500000000000000000 ≤ Real.log ((9 : ℝ) / 1) ∧
    Real.log ((9 : ℝ) / 1) ≤ (274653072167027423 : ℝ) / 125000000000000000 := by
  have hb : (11778303565638345453 : ℝ) / 100000000000000000000 ≤ Real.log ((9 : ℝ) / 8) ∧
      Real.log ((9 : ℝ) / 8) ≤ (5889151782819172727 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((9 : ℚ) / 8) 25
      ((11778303565638345453 : ℚ) / 100000000000000000000)
      ((5889151782819172727 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (9 : ℝ) / 8) (l := (9 : ℝ) / 8)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((9 : ℝ) / 1) ((9 : ℝ) / 8) (3) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem energy_log_1 :
    (9880659081273891 : ℝ) / 4000000000000000 ≤ Real.log ((1182439500047337759 : ℝ) / 100000000000000000) ∧
    Real.log ((1182439500047337759 : ℝ) / 100000000000000000) ≤ (2470164770318472751 : ℝ) / 1000000000000000000 := by
  have hb : (19536161431931841089 : ℝ) / 50000000000000000000 ≤ Real.log ((739024687529586099 : ℝ) / 500000000000000000) ∧
      Real.log ((739024687529586099 : ℝ) / 500000000000000000) ≤ (39072322863863682179 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((739024687529586099 : ℚ) / 500000000000000000) 25
      ((19536161431931841089 : ℚ) / 50000000000000000000)
      ((39072322863863682179 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (1182439500047337759 : ℝ) / 800000000000000000) (l := (739024687529586099 : ℝ) / 500000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1182439500047337759 : ℝ) / 100000000000000000) ((1182439500047337759 : ℝ) / 800000000000000000) (3) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem mass_log_1 :
    (37234737430010493 : ℝ) / 500000000000000000 ≤ Real.log ((538656228953379887 : ℝ) / 500000000000000000) ∧
    Real.log ((538656228953379887 : ℝ) / 500000000000000000) ≤ (18617368715005247 : ℝ) / 250000000000000000 := by
  have hb : (7446947486002098663 : ℝ) / 100000000000000000000 ≤ Real.log ((538656228953379887 : ℝ) / 500000000000000000) ∧
      Real.log ((538656228953379887 : ℝ) / 500000000000000000) ≤ (930868435750262333 : ℝ) / 12500000000000000000 := by
    have h := log_enclosure_of_rat
      ((538656228953379887 : ℚ) / 500000000000000000) 25
      ((7446947486002098663 : ℚ) / 100000000000000000000)
      ((930868435750262333 : ℚ) / 12500000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (538656228953379887 : ℝ) / 500000000000000000) (l := (538656228953379887 : ℝ) / 500000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((538656228953379887 : ℝ) / 500000000000000000) ((538656228953379887 : ℝ) / 500000000000000000) (0) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

end UnitDistance.Sqrt241.Witness.FiniteCertificates
