-- Generated by scripts/sqrt241/generate_finite_certificates.py — do not edit by hand.
module

public import UnitDistance.Sqrt241.FiniteCertificates.LogEnclosure

@[expose] public section
set_option backward.privateInPublic true
set_option linter.unnecessarySeqFocus false


namespace UnitDistance.Sqrt241.Witness.FiniteCertificates

theorem power_bound_4_0 :
    (shellWeights ⟨4, by decide⟩ ⟨0, by decide⟩ : ℝ)^p ≤ powerUpper ⟨4, by decide⟩ ⟨0, by decide⟩ := by
  norm_num [shellWeights, powerUpper, Matrix.cons_val]

theorem weight_log_4_1 :
    (-3283707421367722651 : ℝ) / 200000000000000000 ≤ Real.log ((6670914 : ℝ) / 90087681134399) ∧
    Real.log ((6670914 : ℝ) / 90087681134399) ≤ (-16418537106838613253 : ℝ) / 1000000000000000000 := by
  have hb : (10849761330003708583 : ℝ) / 50000000000000000000 ≤ Real.log ((62116908597333631 : ℝ) / 50000000000000000) ∧
      Real.log ((62116908597333631 : ℝ) / 50000000000000000) ≤ (21699522660007417167 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((62116908597333631 : ℚ) / 50000000000000000) 25
      ((10849761330003708583 : ℚ) / 50000000000000000000)
      ((21699522660007417167 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (111919365095424 : ℝ) / 90087681134399) (l := (62116908597333631 : ℝ) / 50000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((6670914 : ℝ) / 90087681134399) ((111919365095424 : ℝ) / 90087681134399) (-24) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_4_1 :
    (-7869691370770532081 : ℝ) / 250000000000000000 ≤ Real.log ((21327789885943911 : ℝ) / 1000000000000000000000000000000) ∧
    Real.log ((21327789885943911 : ℝ) / 1000000000000000000000000000000) ≤ (-15739382741541064161 : ℝ) / 500000000000000000 := by
  have hb : (20300241133767795477 : ℝ) / 50000000000000000000 ≤ Real.log ((1500809790358956733 : ℝ) / 1000000000000000000) ∧
      Real.log ((1500809790358956733 : ℝ) / 1000000000000000000) ≤ (8120096453507118191 : ℝ) / 20000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1500809790358956733 : ℚ) / 1000000000000000000) 25
      ((20300241133767795477 : ℚ) / 50000000000000000000)
      ((8120096453507118191 : ℚ) / 20000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (1397738037965220151296 : ℝ) / 931322574615478515625) (l := (1500809790358956733 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((21327789885943911 : ℝ) / 1000000000000000000000000000000) ((1397738037965220151296 : ℝ) / 931322574615478515625) (-46) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_4_1 :
    (shellWeights ⟨4, by decide⟩ ⟨1, by decide⟩ : ℝ)^p ≤ powerUpper ⟨4, by decide⟩ ⟨1, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (6670914 : ℝ) / 90087681134399)
    (by norm_num : 0 < (21327789885943911 : ℝ) / 1000000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_4_1.2 power_upper_log_4_1.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_4_2 :
    (-32236191301916639577 : ℝ) / 1000000000000000000 ≤ Real.log ((1 : ℝ) / 100000000000000) ∧
    Real.log ((1 : ℝ) / 100000000000000) ≤ (-1289447652076665583 : ℝ) / 40000000000000000 := by
  have hb : (6834523688015799327 : ℝ) / 20000000000000000000 ≤ Real.log ((8589934592 : ℝ) / 6103515625) ∧
      Real.log ((8589934592 : ℝ) / 6103515625) ≤ (8543154610019749159 : ℝ) / 25000000000000000000 := by
    have h := log_enclosure_of_rat
      ((8589934592 : ℚ) / 6103515625) 25
      ((6834523688015799327 : ℚ) / 20000000000000000000)
      ((8543154610019749159 : ℚ) / 25000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (8589934592 : ℝ) / 6103515625) (l := (8589934592 : ℝ) / 6103515625)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1 : ℝ) / 100000000000000) ((8589934592 : ℝ) / 6103515625) (-47) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_4_2 :
    (-12361095260285323261 : ℝ) / 200000000000000000 ≤ Real.log ((14395365325876291 : ℝ) / 10000000000000000000000000000000000000000000) ∧
    Real.log ((14395365325876291 : ℝ) / 10000000000000000000000000000000000000000000) ≤ (-61805476301426616303 : ℝ) / 1000000000000000000 := by
  have hb : (28888497448423077159 : ℝ) / 50000000000000000000 ≤ Real.log ((178205991170426967 : ℝ) / 100000000000000000) ∧
      Real.log ((178205991170426967 : ℝ) / 100000000000000000) ≤ (57776994896846154319 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((178205991170426967 : ℚ) / 100000000000000000) 25
      ((28888497448423077159 : ℚ) / 50000000000000000000)
      ((57776994896846154319 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (2025967559921206964609978728448 : ℝ) / 1136868377216160297393798828125) (l := (178205991170426967 : ℝ) / 100000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((14395365325876291 : ℝ) / 10000000000000000000000000000000000000000000) ((2025967559921206964609978728448 : ℝ) / 1136868377216160297393798828125) (-90) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_4_2 :
    (shellWeights ⟨4, by decide⟩ ⟨2, by decide⟩ : ℝ)^p ≤ powerUpper ⟨4, by decide⟩ ⟨2, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (1 : ℝ) / 100000000000000)
    (by norm_num : 0 < (14395365325876291 : ℝ) / 10000000000000000000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_4_2.2 power_upper_log_4_2.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_4_3 :
    (-46051701859880913681 : ℝ) / 1000000000000000000 ≤ Real.log ((1 : ℝ) / 100000000000000000000) ∧
    Real.log ((1 : ℝ) / 100000000000000000000) ≤ (-46051701859880913679 : ℝ) / 1000000000000000000 := by
  have hb : (486449047044277563 : ℝ) / 1250000000000000000 ≤ Real.log ((1475739525896764129 : ℝ) / 1000000000000000000) ∧
      Real.log ((1475739525896764129 : ℝ) / 1000000000000000000) ≤ (38915923763542205041 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1475739525896764129 : ℚ) / 1000000000000000000) 25
      ((486449047044277563 : ℚ) / 1250000000000000000)
      ((38915923763542205041 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (140737488355328 : ℝ) / 95367431640625) (l := (1475739525896764129 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1 : ℝ) / 100000000000000000000) ((140737488355328 : ℝ) / 95367431640625) (-67) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_4_3 :
    (-22073384393366659403 : ℝ) / 250000000000000000 ≤ Real.log ((45144395717260621 : ℝ) / 10000000000000000000000000000000000000000000000000000000) ∧
    Real.log ((45144395717260621 : ℝ) / 10000000000000000000000000000000000000000000000000000000) ≤ (-88293537573466637609 : ℝ) / 1000000000000000000 := by
  have hb : (8586030764127239883 : ℝ) / 20000000000000000000 ≤ Real.log ((1536184182788492157 : ℝ) / 1000000000000000000) ∧
      Real.log ((1536184182788492157 : ℝ) / 1000000000000000000) ≤ (5366269227579524927 : ℝ) / 12500000000000000000 := by
    have h := log_enclosure_of_rat
      ((1536184182788492157 : ℚ) / 1000000000000000000) 25
      ((8586030764127239883 : ℚ) / 20000000000000000000)
      ((5366269227579524927 : ℚ) / 12500000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (426376762449191026259238443890541330432 : ℝ) / 277555756156289135105907917022705078125) (l := (1536184182788492157 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((45144395717260621 : ℝ) / 10000000000000000000000000000000000000000000000000000000) ((426376762449191026259238443890541330432 : ℝ) / 277555756156289135105907917022705078125) (-128) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_4_3 :
    (shellWeights ⟨4, by decide⟩ ⟨3, by decide⟩ : ℝ)^p ≤ powerUpper ⟨4, by decide⟩ ⟨3, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (1 : ℝ) / 100000000000000000000)
    (by norm_num : 0 < (45144395717260621 : ℝ) / 10000000000000000000000000000000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_4_3.2 power_upper_log_4_3.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_4_4 :
    (-29933606208922593893 : ℝ) / 500000000000000000 ≤ Real.log ((1 : ℝ) / 100000000000000000000000000) ∧
    Real.log ((1 : ℝ) / 100000000000000000000000000) ≤ (-59867212417845187783 : ℝ) / 1000000000000000000 := by
  have hb : (21829614543502706721 : ℝ) / 50000000000000000000 ≤ Real.log ((1547425049106725343 : ℝ) / 1000000000000000000) ∧
      Real.log ((1547425049106725343 : ℝ) / 1000000000000000000) ≤ (43659229087005413443 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1547425049106725343 : ℚ) / 1000000000000000000) 25
      ((21829614543502706721 : ℚ) / 50000000000000000000)
      ((43659229087005413443 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (2305843009213693952 : ℝ) / 1490116119384765625) (l := (1547425049106725343 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1 : ℝ) / 100000000000000000000000000) ((2305843009213693952 : ℝ) / 1490116119384765625) (-87) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_4_4 :
    (-57390799422753329433 : ℝ) / 500000000000000000 ≤ Real.log ((3539362181057671 : ℝ) / 250000000000000000000000000000000000000000000000000000000000000000) ∧
    Real.log ((3539362181057671 : ℝ) / 250000000000000000000000000000000000000000000000000000000000000000) ≤ (-57390799422753329431 : ℝ) / 500000000000000000 := by
  have hb : (28083312744426249863 : ℝ) / 100000000000000000000 ≤ Real.log ((1324232607417052629 : ℝ) / 1000000000000000000) ∧
      Real.log ((1324232607417052629 : ℝ) / 1000000000000000000) ≤ (3510414093053281233 : ℝ) / 12500000000000000000 := by
    have h := log_enclosure_of_rat
      ((1324232607417052629 : ℚ) / 1000000000000000000) 25
      ((28083312744426249863 : ℚ) / 100000000000000000000)
      ((3510414093053281233 : ℚ) / 12500000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (17946698372971407160061833356412026622452957184 : ℝ) / 13552527156068805425093160010874271392822265625) (l := (1324232607417052629 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((3539362181057671 : ℝ) / 250000000000000000000000000000000000000000000000000000000000000000) ((17946698372971407160061833356412026622452957184 : ℝ) / 13552527156068805425093160010874271392822265625) (-166) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_4_4 :
    (shellWeights ⟨4, by decide⟩ ⟨4, by decide⟩ : ℝ)^p ≤ powerUpper ⟨4, by decide⟩ ⟨4, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (1 : ℝ) / 100000000000000000000000000)
    (by norm_num : 0 < (3539362181057671 : ℝ) / 250000000000000000000000000000000000000000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_4_4.2 power_upper_log_4_4.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_4_5 :
    (-7368272297580946189 : ℝ) / 100000000000000000 ≤ Real.log ((1 : ℝ) / 100000000000000000000000000000000) ∧
    Real.log ((1 : ℝ) / 100000000000000000000000000000000) ≤ (-73682722975809461887 : ℝ) / 1000000000000000000 := by
  have hb : (968050688209372437 : ℝ) / 2000000000000000000 ≤ Real.log ((1622592768292133633 : ℝ) / 1000000000000000000) ∧
      Real.log ((1622592768292133633 : ℝ) / 1000000000000000000) ≤ (48402534410468621851 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1622592768292133633 : ℚ) / 1000000000000000000) 25
      ((968050688209372437 : ℚ) / 2000000000000000000)
      ((48402534410468621851 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (37778931862957161709568 : ℝ) / 23283064365386962890625) (l := (1622592768292133633 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1 : ℝ) / 100000000000000000000000000000000) ((37778931862957161709568 : ℝ) / 23283064365386962890625) (-107) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_4_5 :
    (-35317415029386670051 : ℝ) / 250000000000000000 ≤ Real.log ((2774892530882117 : ℝ) / 62500000000000000000000000000000000000000000000000000000000000000000000000000) ∧
    Real.log ((2774892530882117 : ℝ) / 62500000000000000000000000000000000000000000000000000000000000000000000000000) ≤ (-706348300587733401 : ℝ) / 5000000000000000 := by
  have hb : (2647294333643258367 : ℝ) / 20000000000000000000 ≤ Real.log ((4566098305643099 : ℝ) / 4000000000000000) ∧
      Real.log ((4566098305643099 : ℝ) / 4000000000000000) ≤ (3309117917054072959 : ℝ) / 25000000000000000000 := by
    have h := log_enclosure_of_rat
      ((4566098305643099 : ℚ) / 4000000000000000) 25
      ((2647294333643258367 : ℚ) / 20000000000000000000)
      ((3309117917054072959 : ℚ) / 25000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (3776987993439200414061574405316070852978415612259729408 : ℝ) / 3308722450212110699485634768279851414263248443603515625) (l := (4566098305643099 : ℝ) / 4000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((2774892530882117 : ℝ) / 62500000000000000000000000000000000000000000000000000000000000000000000000000) ((3776987993439200414061574405316070852978415612259729408 : ℝ) / 3308722450212110699485634768279851414263248443603515625) (-204) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_4_5 :
    (shellWeights ⟨4, by decide⟩ ⟨5, by decide⟩ : ℝ)^p ≤ powerUpper ⟨4, by decide⟩ ⟨5, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (1 : ℝ) / 100000000000000000000000000000000)
    (by norm_num : 0 < (2774892530882117 : ℝ) / 62500000000000000000000000000000000000000000000000000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_4_5.2 power_upper_log_4_5.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem residue_log_4 :
    (2970857653363446243 : ℝ) / 200000000000000000 ≤ Real.log ((2825761 : ℝ) / 1) ∧
    Real.log ((2825761 : ℝ) / 1) ≤ (14854288266817231217 : ℝ) / 1000000000000000000 := by
  have hb : (29819747505837971761 : ℝ) / 100000000000000000000 ≤ Real.log ((1347427845001220703 : ℝ) / 1000000000000000000) ∧
      Real.log ((1347427845001220703 : ℝ) / 1000000000000000000) ≤ (14909873752918985881 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1347427845001220703 : ℚ) / 1000000000000000000) 25
      ((29819747505837971761 : ℚ) / 100000000000000000000)
      ((14909873752918985881 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (2825761 : ℝ) / 2097152) (l := (1347427845001220703 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((2825761 : ℝ) / 1) ((2825761 : ℝ) / 2097152) (21) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem energy_log_4 :
    (693147375141442249 : ℝ) / 1000000000000000000 ≤ Real.log ((2000000389163031743 : ℝ) / 1000000000000000000) ∧
    Real.log ((2000000389163031743 : ℝ) / 1000000000000000000) ≤ (693147375141442251 : ℝ) / 1000000000000000000 := by
  have hb : (19458149694001 : ℝ) / 100000000000000000000 ≤ Real.log ((1000000194581515871 : ℝ) / 1000000000000000000) ∧
      Real.log ((1000000194581515871 : ℝ) / 1000000000000000000) ≤ (9729074847001 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1000000194581515871 : ℚ) / 1000000000000000000) 25
      ((19458149694001 : ℚ) / 100000000000000000000)
      ((9729074847001 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (2000000389163031743 : ℝ) / 2000000000000000000) (l := (1000000194581515871 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((2000000389163031743 : ℝ) / 1000000000000000000) ((2000000389163031743 : ℝ) / 2000000000000000000) (1) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem mass_log_4 :
    (30133612613 : ℝ) / 500000000000000000 ≤ Real.log ((1000000060267227043 : ℝ) / 1000000000000000000) ∧
    Real.log ((1000000060267227043 : ℝ) / 1000000000000000000) ≤ (15066806307 : ℝ) / 250000000000000000 := by
  have hb : (6026722522693 : ℝ) / 100000000000000000000 ≤ Real.log ((1000000060267227043 : ℝ) / 1000000000000000000) ∧
      Real.log ((1000000060267227043 : ℝ) / 1000000000000000000) ≤ (3013361261347 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1000000060267227043 : ℚ) / 1000000000000000000) 25
      ((6026722522693 : ℚ) / 100000000000000000000)
      ((3013361261347 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (1000000060267227043 : ℝ) / 1000000000000000000) (l := (1000000060267227043 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1000000060267227043 : ℝ) / 1000000000000000000) ((1000000060267227043 : ℝ) / 1000000000000000000) (0) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

end UnitDistance.Sqrt241.Witness.FiniteCertificates
