-- Generated by scripts/sqrt241/generate_finite_certificates.py — do not edit by hand.
module

public import UnitDistance.Sqrt241.FiniteCertificates.LogEnclosure

@[expose] public section
set_option backward.privateInPublic true
set_option linter.unnecessarySeqFocus false


namespace UnitDistance.Sqrt241.Witness.FiniteCertificates

theorem power_bound_2_0 :
    (shellWeights ⟨2, by decide⟩ ⟨0, by decide⟩ : ℝ)^p ≤ powerUpper ⟨2, by decide⟩ ⟨0, by decide⟩ := by
  norm_num [shellWeights, powerUpper, Matrix.cons_val]

theorem weight_log_2_1 :
    (-3539481583195652993 : ℝ) / 1000000000000000000 ≤ Real.log ((2640115727474 : ℝ) / 90949493463877) ∧
    Real.log ((2640115727474 : ℝ) / 90949493463877) ≤ (-27652199868716039 : ℝ) / 7812500000000000 := by
  have hb : (30970075008200943183 : ℝ) / 50000000000000000000 ≤ Real.log ((1857815806587706619 : ℝ) / 1000000000000000000) ∧
      Real.log ((1857815806587706619 : ℝ) / 1000000000000000000) ≤ (61940150016401886367 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1857815806587706619 : ℚ) / 1000000000000000000) 25
      ((30970075008200943183 : ℚ) / 50000000000000000000)
      ((61940150016401886367 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (168967406558336 : ℝ) / 90949493463877) (l := (1857815806587706619 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((2640115727474 : ℝ) / 90949493463877) ((168967406558336 : ℝ) / 90949493463877) (-6) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_2_1 :
    (-1697267470603050177 : ℝ) / 250000000000000000 ≤ Real.log ((2815039035460261 : ℝ) / 2500000000000000000) ∧
    Real.log ((2815039035460261 : ℝ) / 2500000000000000000) ≤ (-3394534941206100353 : ℝ) / 500000000000000000 := by
  have hb : (14240192318725238677 : ℝ) / 100000000000000000000 ≤ Real.log ((230607997784904581 : ℝ) / 200000000000000000) ∧
      Real.log ((230607997784904581 : ℝ) / 200000000000000000) ≤ (7120096159362619339 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((230607997784904581 : ℚ) / 200000000000000000) 25
      ((14240192318725238677 : ℚ) / 100000000000000000000)
      ((7120096159362619339 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (2815039035460261 : ℝ) / 2441406250000000) (l := (230607997784904581 : ℝ) / 200000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((2815039035460261 : ℝ) / 2500000000000000000) ((2815039035460261 : ℝ) / 2441406250000000) (-10) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_2_1 :
    (shellWeights ⟨2, by decide⟩ ⟨1, by decide⟩ : ℝ)^p ≤ powerUpper ⟨2, by decide⟩ ⟨1, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (2640115727474 : ℝ) / 90949493463877)
    (by norm_num : 0 < (2815039035460261 : ℝ) / 2500000000000000000) witness_basic.2.2.1.le
    weight_log_2_1.2 power_upper_log_2_1.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_2_2 :
    (-89854323872787867 : ℝ) / 12500000000000000 ≤ Real.log ((57338538679 : ℝ) / 75911152151678) ∧
    Real.log ((57338538679 : ℝ) / 75911152151678) ≤ (-3594172954911514679 : ℝ) / 500000000000000000 := by
  have hb : (43627307633636904403 : ℝ) / 100000000000000000000 ≤ Real.log ((1546931167372569637 : ℝ) / 1000000000000000000) ∧
      Real.log ((1546931167372569637 : ℝ) / 1000000000000000000) ≤ (10906826908409226101 : ℝ) / 25000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1546931167372569637 : ℚ) / 1000000000000000000) 25
      ((43627307633636904403 : ℚ) / 100000000000000000000)
      ((10906826908409226101 : ℚ) / 25000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (58714663607296 : ℝ) / 37955576075839) (l := (1546931167372569637 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((57338538679 : ℝ) / 75911152151678) ((58714663607296 : ℝ) / 37955576075839) (-11) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_2_2 :
    (-2757589300785643881 : ℝ) / 200000000000000000 ≤ Real.log ((2055894914363979 : ℝ) / 2000000000000000000000) ∧
    Real.log ((2055894914363979 : ℝ) / 2000000000000000000000) ≤ (-6893973251964109701 : ℝ) / 500000000000000000 := by
  have hb : (1874927681767169609 : ℝ) / 25000000000000000000 ≤ Real.log ((1077881032862061821 : ℝ) / 1000000000000000000) ∧
      Real.log ((1077881032862061821 : ℝ) / 1000000000000000000) ≤ (7499710727068678437 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1077881032862061821 : ℚ) / 1000000000000000000) 25
      ((1874927681767169609 : ℚ) / 25000000000000000000)
      ((7499710727068678437 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (2055894914363979 : ℝ) / 1907348632812500) (l := (1077881032862061821 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((2055894914363979 : ℝ) / 2000000000000000000000) ((2055894914363979 : ℝ) / 1907348632812500) (-20) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_2_2 :
    (shellWeights ⟨2, by decide⟩ ⟨2, by decide⟩ : ℝ)^p ≤ powerUpper ⟨2, by decide⟩ ⟨2, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (57338538679 : ℝ) / 75911152151678)
    (by norm_num : 0 < (2055894914363979 : ℝ) / 2000000000000000000000) witness_basic.2.2.1.le
    weight_log_2_2.2 power_upper_log_2_2.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_2_3 :
    (-2164424908040174237 : ℝ) / 200000000000000000 ≤ Real.log ((1993282330 : ℝ) / 99898228546427) ∧
    Real.log ((1993282330 : ℝ) / 99898228546427) ≤ (-10822124540200871183 : ℝ) / 1000000000000000000 := by
  have hb : (26823034875825376641 : ℝ) / 100000000000000000000 ≤ Real.log ((1307648320492187821 : ℝ) / 1000000000000000000) ∧
      Real.log ((1307648320492187821 : ℝ) / 1000000000000000000) ≤ (13411517437912688321 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((1307648320492187821 : ℚ) / 1000000000000000000) 25
      ((26823034875825376641 : ℚ) / 100000000000000000000)
      ((13411517437912688321 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (130631750778880 : ℝ) / 99898228546427) (l := (1307648320492187821 : ℝ) / 1000000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1993282330 : ℝ) / 99898228546427) ((130631750778880 : ℝ) / 99898228546427) (-16) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_2_3 :
    (-2075788729299092557 : ℝ) / 100000000000000000 ≤ Real.log ((48298550477173677 : ℝ) / 50000000000000000000000000) ∧
    Real.log ((48298550477173677 : ℝ) / 50000000000000000000000000) ≤ (-81085497238245803 : ℝ) / 3906250000000000 := by
  have hb : (3652812380743371271 : ℝ) / 100000000000000000000 ≤ Real.log ((518601736859165343 : ℝ) / 500000000000000000) ∧
      Real.log ((518601736859165343 : ℝ) / 500000000000000000) ≤ (456601547592921409 : ℝ) / 12500000000000000000 := by
    have h := log_enclosure_of_rat
      ((518601736859165343 : ℚ) / 500000000000000000) 25
      ((3652812380743371271 : ℚ) / 100000000000000000000)
      ((456601547592921409 : ℚ) / 12500000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (1545553615269557664 : ℝ) / 1490116119384765625) (l := (518601736859165343 : ℝ) / 500000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((48298550477173677 : ℝ) / 50000000000000000000000000) ((1545553615269557664 : ℝ) / 1490116119384765625) (-30) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_2_3 :
    (shellWeights ⟨2, by decide⟩ ⟨3, by decide⟩ : ℝ)^p ≤ powerUpper ⟨2, by decide⟩ ⟨3, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (1993282330 : ℝ) / 99898228546427)
    (by norm_num : 0 < (48298550477173677 : ℝ) / 50000000000000000000000000) witness_basic.2.2.1.le
    weight_log_2_3.2 power_upper_log_2_3.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_2_4 :
    (-902114798725974549 : ℝ) / 62500000000000000 ≤ Real.log ((32287067 : ℝ) / 59918959199341) ∧
    Real.log ((32287067 : ℝ) / 59918959199341) ≤ (-7216918389807796391 : ℝ) / 500000000000000000 := by
  have hb : (3056350303581467851 : ℝ) / 25000000000000000000 ≤ Real.log ((7062756934320287 : ℝ) / 6250000000000000) ∧
      Real.log ((7062756934320287 : ℝ) / 6250000000000000) ≤ (2445080242865174281 : ℝ) / 20000000000000000000 := by
    have h := log_enclosure_of_rat
      ((7062756934320287 : ℚ) / 6250000000000000) 25
      ((3056350303581467851 : ℚ) / 25000000000000000000)
      ((2445080242865174281 : ℚ) / 20000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (67710887133184 : ℝ) / 59918959199341) (l := (7062756934320287 : ℝ) / 6250000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((32287067 : ℝ) / 59918959199341) ((67710887133184 : ℝ) / 59918959199341) (-21) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_2_4 :
    (-13842751299142169987 : ℝ) / 500000000000000000 ≤ Real.log ((94697604446093053 : ℝ) / 100000000000000000000000000000) ∧
    Real.log ((94697604446093053 : ℝ) / 100000000000000000000000000000) ≤ (-6921375649571084993 : ℝ) / 250000000000000000 := by
  have hb : (2019231205673620163 : ℝ) / 50000000000000000000 ≤ Real.log ((41648446884404619 : ℝ) / 40000000000000000) ∧
      Real.log ((41648446884404619 : ℝ) / 40000000000000000) ≤ (4038462411347240327 : ℝ) / 100000000000000000000 := by
    have h := log_enclosure_of_rat
      ((41648446884404619 : ℚ) / 40000000000000000) 25
      ((2019231205673620163 : ℚ) / 50000000000000000000)
      ((4038462411347240327 : ℚ) / 100000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (193940693905598572544 : ℝ) / 186264514923095703125) (l := (41648446884404619 : ℝ) / 40000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((94697604446093053 : ℝ) / 100000000000000000000000000000) ((193940693905598572544 : ℝ) / 186264514923095703125) (-40) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_2_4 :
    (shellWeights ⟨2, by decide⟩ ⟨4, by decide⟩ : ℝ)^p ≤ powerUpper ⟨2, by decide⟩ ⟨4, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (32287067 : ℝ) / 59918959199341)
    (by norm_num : 0 < (94697604446093053 : ℝ) / 100000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_2_4.2 power_upper_log_2_4.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem weight_log_2_5 :
    (-18027388731323860293 : ℝ) / 1000000000000000000 ≤ Real.log ((1005993 : ℝ) / 67887592557980) ∧
    Real.log ((1005993 : ℝ) / 67887592557980) ≤ (-4506847182830965073 : ℝ) / 250000000000000000 := by
  have hb : (13751702875893261227 : ℝ) / 20000000000000000000 ≤ Real.log ((994453402722943691 : ℝ) / 500000000000000000) ∧
      Real.log ((994453402722943691 : ℝ) / 500000000000000000) ≤ (8594814297433288267 : ℝ) / 12500000000000000000 := by
    have h := log_enclosure_of_rat
      ((994453402722943691 : ℚ) / 500000000000000000) 25
      ((13751702875893261227 : ℚ) / 20000000000000000000)
      ((8594814297433288267 : ℚ) / 12500000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (33755523710976 : ℝ) / 16971898139495) (l := (994453402722943691 : ℝ) / 500000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((1005993 : ℝ) / 67887592557980) ((33755523710976 : ℝ) / 16971898139495) (-27) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_upper_log_2_5 :
    (-34578284705713643721 : ℝ) / 1000000000000000000 ≤ Real.log ((96126196509861781 : ℝ) / 100000000000000000000000000000000) ∧
    Real.log ((96126196509861781 : ℝ) / 100000000000000000000000000000000) ≤ (-17289142352856821859 : ℝ) / 500000000000000000 := by
  have hb : (7907432228362175071 : ℝ) / 100000000000000000000 ≤ Real.log ((43291390278235659 : ℝ) / 40000000000000000) ∧
      Real.log ((43291390278235659 : ℝ) / 40000000000000000) ≤ (247107257136317971 : ℝ) / 3125000000000000000 := by
    have h := log_enclosure_of_rat
      ((43291390278235659 : ℚ) / 40000000000000000) 25
      ((7907432228362175071 : ℚ) / 100000000000000000000)
      ((247107257136317971 : ℚ) / 3125000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (25198905657881206718464 : ℝ) / 23283064365386962890625) (l := (43291390278235659 : ℝ) / 40000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((96126196509861781 : ℝ) / 100000000000000000000000000000000) ((25198905657881206718464 : ℝ) / 23283064365386962890625) (-50) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem power_bound_2_5 :
    (shellWeights ⟨2, by decide⟩ ⟨5, by decide⟩ : ℝ)^p ≤ powerUpper ⟨2, by decide⟩ ⟨5, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < (1005993 : ℝ) / 67887592557980)
    (by norm_num : 0 < (96126196509861781 : ℝ) / 100000000000000000000000000000000) witness_basic.2.2.1.le
    weight_log_2_5.2 power_upper_log_2_5.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

theorem residue_log_2 :
    (3218875824868200749 : ℝ) / 1000000000000000000 ≤ Real.log ((25 : ℝ) / 1) ∧
    Real.log ((25 : ℝ) / 1) ≤ (12875503299472803 : ℝ) / 4000000000000000 := by
  have hb : (44628710262841951153 : ℝ) / 100000000000000000000 ≤ Real.log ((25 : ℝ) / 16) ∧
      Real.log ((25 : ℝ) / 16) ≤ (22314355131420975577 : ℝ) / 50000000000000000000 := by
    have h := log_enclosure_of_rat
      ((25 : ℚ) / 16) 25
      ((44628710262841951153 : ℚ) / 100000000000000000000)
      ((22314355131420975577 : ℚ) / 50000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (25 : ℝ) / 16) (l := (25 : ℝ) / 16)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((25 : ℝ) / 1) ((25 : ℝ) / 16) (4) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem energy_log_2 :
    (2008998724720483309 : ℝ) / 1000000000000000000 ≤ Real.log ((7455848252090355121 : ℝ) / 1000000000000000000) ∧
    Real.log ((7455848252090355121 : ℝ) / 1000000000000000000) ≤ (200899872472048331 : ℝ) / 100000000000000000 := by
  have hb : (12454087272011853807 : ℝ) / 20000000000000000000 ≤ Real.log ((93198103151129439 : ℝ) / 50000000000000000) ∧
      Real.log ((93198103151129439 : ℝ) / 50000000000000000) ≤ (15567609090014817259 : ℝ) / 25000000000000000000 := by
    have h := log_enclosure_of_rat
      ((93198103151129439 : ℚ) / 50000000000000000) 25
      ((12454087272011853807 : ℚ) / 20000000000000000000)
      ((15567609090014817259 : ℚ) / 25000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (7455848252090355121 : ℝ) / 4000000000000000000) (l := (93198103151129439 : ℝ) / 50000000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((7455848252090355121 : ℝ) / 1000000000000000000) ((7455848252090355121 : ℝ) / 4000000000000000000) (2) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

theorem mass_log_2 :
    (1091219106899471 : ℝ) / 40000000000000000 ≤ Real.log ((64228499806732403 : ℝ) / 62500000000000000) ∧
    Real.log ((64228499806732403 : ℝ) / 62500000000000000) ≤ (27280477672486777 : ℝ) / 1000000000000000000 := by
  have hb : (1364023883624338757 : ℝ) / 50000000000000000000 ≤ Real.log ((64228499806732403 : ℝ) / 62500000000000000) ∧
      Real.log ((64228499806732403 : ℝ) / 62500000000000000) ≤ (545609553449735503 : ℝ) / 20000000000000000000 := by
    have h := log_enclosure_of_rat
      ((64228499806732403 : ℚ) / 62500000000000000) 25
      ((1364023883624338757 : ℚ) / 50000000000000000000)
      ((545609553449735503 : ℚ) / 20000000000000000000)
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := (64228499806732403 : ℝ) / 62500000000000000) (l := (64228499806732403 : ℝ) / 62500000000000000)
    (ε := (1 : ℝ) / 1000000000000000000) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ((64228499806732403 : ℝ) / 62500000000000000) ((64228499806732403 : ℝ) / 62500000000000000) (0) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

end UnitDistance.Sqrt241.Witness.FiniteCertificates
