#!/usr/bin/env python3
"""Produce untrusted rational candidates and Lean proofs for finite-place bounds.

Only kernel-checked Lean inequalities certify the output. Decimal is used to
choose power upper bounds, never as a trusted evaluation rule. The generated
proofs also identify every candidate with the independently defined Witness.
"""
import argparse
from decimal import Decimal, localcontext, ROUND_CEILING
from fractions import Fraction as F
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--only", type=int, help="Generate only the selected rational-prime module")
args = parser.parse_args()
data = json.loads((ROOT / "certificates/finite-witness.json").read_text())
OUT = ROOT / "UnitDistance/FiniteCertificates"
OUT.mkdir(exist_ok=True)
delta = F(data["delta"])
power = 2 / (1 + delta)
SCALE = 10**18
LOGSCALE = 10**20
LOGTWO = (F(69314718055994530941, LOGSCALE), F(69314718055994530942, LOGSCALE))

def floor(q): return q.numerator // q.denominator
def ceil(q): return -floor(-q)
def literal(q, field="ℝ"):
    q = F(q)
    return f"({q.numerator} : {field}) / {q.denominator}"
def real(q): return literal(q)
def rational(q): return literal(q, "ℚ")
def vec(xs): return "![" + ", ".join(xs) + "]"
def dec(q): return Decimal(q.numerator) / Decimal(q.denominator)

def log_certificate(q, name):
    """Exact scaling, proved short rational log series, and monotonicity."""
    q = F(q)
    if q == 1:
        return f"theorem {name} : (0 : ℝ) ≤ Real.log 1 ∧ Real.log 1 ≤ 0 := by simp\n\n", (F(0), F(0))
    k = q.numerator.bit_length() - q.denominator.bit_length()
    while q < F(2)**k: k -= 1
    while F(2)**(k+1) <= q: k += 1
    r = q / F(2)**k
    low = F(floor(r*SCALE), SCALE)
    eps = F(1, SCALE)
    x = (low-1)/(low+1)
    n = 25
    s = sum((x**(2*i+1)/F(2*i+1) for i in range(n)), F(0))
    rem = x**(2*n+1)/(1-x*x)
    sl = F(floor(2*s*LOGSCALE), LOGSCALE)
    su = F(ceil(2*(s+rem)*LOGSCALE), LOGSCALE)
    lb = k*LOGTWO[0 if k >= 0 else 1] + sl
    ub = k*LOGTWO[1 if k >= 0 else 0] + su + eps/low
    bounds = (F(floor(lb*SCALE), SCALE), F(ceil(ub*SCALE), SCALE))
    text = f'''theorem {name} :
    {real(bounds[0])} ≤ Real.log ({real(q)}) ∧
    Real.log ({real(q)}) ≤ {real(bounds[1])} := by
  have hb : {real(sl)} ≤ Real.log ({real(low)}) ∧
      Real.log ({real(low)}) ≤ {real(su)} := by
    have h := log_enclosure_of_rat
      ({rational(low)}) {n}
      ({rational(sl)})
      ({rational(su)})
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    norm_num at h ⊢ <;> exact h
  have hr := log_bounds_of_lower (x := {real(r)}) (l := {real(low)})
    (ε := {real(eps)}) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ({real(q)}) ({real(r)}) ({k}) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

'''
    return text, bounds

rows = []
with localcontext() as ctx:
    ctx.prec = 100
    for v, prime in enumerate(data["primes"]):
        q = prime**data["residue_degree"][v]
        k = data["period"][v]
        weights = list(map(F, data["weights"][v]))
        upper = [F(1)]
        for w in weights[1:]:
            estimate = (dec(w).ln()*dec(power)).exp() * (Decimal(1)+Decimal("1e-13"))
            quantum = Decimal(1).scaleb(estimate.adjusted()-16)
            upper.append(F(estimate.quantize(quantum, rounding=ROUND_CEILING)))
        masses = [F(1)] + [F(q**i-q**(i-1)) for i in range(1,6)]
        second = sum((masses[i]*weights[i]**2 for i in range(6)), F(0))
        transition = sum((weights[i]*weights[j]*(masses[min(i,j)] if i != j
            else (i*masses[i]-q**(i-1) if i else 0))
            for i in range(6) for j in range(6)), F(0))
        energy = (k+1)*second**2 + 2*second*transition
        lower_energy = F(floor(energy*SCALE), SCALE)
        upper_mass = F(ceil(sum((masses[i]*upper[i] for i in range(6)), F(0))*SCALE), SCALE)
        rows.append(dict(prime=prime, q=q, k=k, weights=weights, upper=upper,
                         energy=lower_energy, mass=upper_mass))

header = '''import UnitDistance.RationalPowerBounds
import UnitDistance.Witness

/-! Generated by scripts/generate-finite-certificates.py. Candidate values
are untrusted until these explicit rational inequalities compile in Lean. -/

noncomputable section
namespace UnitDistance.Witness.FiniteCertificates

'''
data_text = header
for field, typ in [("upper", "Fin 11 → Fin 6 → ℝ"), ("energy", "Fin 11 → ℝ"), ("mass", "Fin 11 → ℝ")]:
    name = {"upper":"powerUpper", "energy":"energyLower", "mass":"massUpper"}[field]
    terms = [vec([real(x) for x in row[field]]) if field == "upper" else real(row[field]) for row in rows]
    data_text += f"def {name} : {typ} :=\n  {vec(terms)}\n\n"
data_text += "end UnitDistance.Witness.FiniteCertificates\n"
(OUT / "Data.lean").write_text(data_text)

summary = []
for v, row in enumerate(rows):
    if args.only is not None and row["prime"] != args.only: continue
    text = "import UnitDistance.FiniteCertificates.LogEnclosureCompactRun20260920\n\nnamespace UnitDistance.Witness.FiniteCertificates\n\n"
    for i, (w,u) in enumerate(zip(row["weights"], row["upper"])):
        if i:
            tw, bw = log_certificate(w, f"weight_log_{v}_{i}")
            tu, bu = log_certificate(u, f"power_upper_log_{v}_{i}")
            assert power*bw[1] <= bu[0], (v, i, "insufficient power enclosure")
            text += tw + tu
            text += f'''theorem power_bound_{v}_{i} :
    (shellWeights ⟨{v}, by decide⟩ ⟨{i}, by decide⟩ : ℝ)^p ≤ powerUpper ⟨{v}, by decide⟩ ⟨{i}, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < {real(w)})
    (by norm_num : 0 < {real(u)}) witness_basic.2.2.1.le
    weight_log_{v}_{i}.2 power_upper_log_{v}_{i}.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

'''
        else:
            text += f'''theorem power_bound_{v}_0 :
    (shellWeights ⟨{v}, by decide⟩ ⟨0, by decide⟩ : ℝ)^p ≤ powerUpper ⟨{v}, by decide⟩ ⟨0, by decide⟩ := by
  norm_num [shellWeights, powerUpper, Matrix.cons_val]

'''
    info = {}
    for name, value in [("residue_log", row["q"]), ("energy_log", row["energy"]), ("mass_log", row["mass"])]:
        cert, bound = log_certificate(value, f"{name}_{v}")
        text += cert
        info[name] = bound
    lower = -delta*row["k"]*info["residue_log"][1] + info["energy_log"][0] - 2*(1+delta)*info["mass_log"][1]
    summary.append(dict(index=v, prime=row["prime"], lower=str(lower),
                        residue_upper=str(info["residue_log"][1]),
                        energy_lower=str(info["energy_log"][0]), mass_upper=str(info["mass_log"][1])))
    text += "end UnitDistance.Witness.FiniteCertificates\n"
    (OUT / f"Prime{row['prime']}.lean").write_text(text)
(ROOT / ".cache").mkdir(exist_ok=True)
(ROOT / ".cache/finite-certificate-summary.json").write_text(json.dumps(summary, indent=2)+"\n")
print(f"Generated {len(summary)} prime proof modules; all candidate bounds still require Lean verification.")
