#!/usr/bin/env python3
"""Generate transparent GF(2) row certificates; Lean checks their soundness.

The search uses ordinary integer bitsets. Its output includes both inclusions
of successive spans and pivot identities. Python's execution is not part of
the mathematical trust base: each emitted identity is proved by Lean `decide`.
"""

from pathlib import Path


def multiply(i, j):
    a, b, c, d = i // 16, (i // 8) % 2, (i // 2) % 4, i % 2
    A, B, C, D = j // 16, (j // 8) % 2, (j // 2) % 4, j % 2
    return 16 * (a ^ A) + 8 * (b ^ B) + 2 * ((c + C) % 4) + (d ^ D ^ ((c % 2) * B))


def right_difference(row, generator):
    result = row
    for i in range(32):
        if row >> i & 1:
            result ^= 1 << multiply(i, generator)
    return result


def rref(vectors):
    echelon = {}
    for i, row in enumerate(vectors):
        combination = 1 << i
        while row:
            pivot = (row & -row).bit_length() - 1
            if pivot in echelon:
                other, cert = echelon[pivot]
                row ^= other
                combination ^= cert
            else:
                echelon[pivot] = (row, combination)
                break
    pivots = sorted(echelon)
    for pivot in reversed(pivots):
        row, combination = echelon[pivot]
        for previous in pivots:
            if previous < pivot and (echelon[previous][0] >> pivot & 1):
                oldrow, oldcert = echelon[previous]
                echelon[previous] = (oldrow ^ row, oldcert ^ combination)
    return ([echelon[p][0] for p in pivots], pivots,
            [echelon[p][1] for p in pivots])


def vector(values):
    return "![" + ", ".join(map(str, values)) + "]"


def main():
    output = [
        "module\n",
        "public import UnitDistance.DyadicFiltration\n",
        "@[expose] public section",
        "set_option backward.privateInPublic true\n\n",
        "/-! Exact row certificates generated by scripts/generate-dyadic-certificates.py.",
        "The dimensions refer to the concrete coefficient-action recurrence in DyadicFiltration.",
        "All finite identities use kernel-reduced `decide`, never native_decide. -/\n",
        "set_option maxRecDepth 100000",
        "set_option maxHeartbeats 8000000\n",
        "open scoped BigOperators",
        "namespace UnitDistance.Dyadic.Filtration\n",
        "def b0 : Fin 32 → V := fun i => Pi.single i 1\n",
        "theorem stage_zero_eq : stage 0 = spanRows b0 := by",
        "  apply le_antisymm",
        "  · intro v _",
        "    have hv : v = ∑ i : Fin 32, v i • b0 i := by",
        "      ext j",
        "      simp [b0, Pi.single_apply]",
        "    rw [hv]",
        "    exact sum_mem_spanRows b0 _",
        "  · exact le_top\n",
    ]
    previous = [1 << i for i in range(32)]
    dimensions = [32]
    for stage in range(1, 9):
        inputs = [right_difference(row, generator)
                  for row in previous for generator in [16, 8, 2]]
        reduced, pivots, lower = rref(inputs)
        r, s = len(previous), len(reduced)
        dimensions.append(s)
        output += [
            f"def masks{stage} : Fin {s} → ℕ := {vector(reduced)}",
            f"def b{stage} : Fin {s} → V := rows masks{stage}",
            f"def pivots{stage} : Fin {s} → Fin 32 := {vector(pivots)}",
            f"def lowerMasks{stage} : Fin {s} → ℕ := {vector(lower)}\n",
            f"theorem pivots{stage}_correct : ∀ i j, b{stage} i (pivots{stage} j) =",
            "    if i = j then 1 else 0 := by decide +kernel\n",
            f"theorem upper{stage}_correct : ∀ i k, step k (b{stage-1} i) =",
            f"    ∑ j, step k (b{stage-1} i) (pivots{stage} j) • b{stage} j := by",
            "  intro i k",
            "  fin_cases i <;> fin_cases k <;> decide +kernel\n",
            f"theorem lower{stage}_correct : ∀ j, b{stage} j =",
            f"    ∑ ik : Fin {r} × Fin 3,",
            f"      (if (lowerMasks{stage} j).testBit (3 * ik.1.val + ik.2.val) then (1 : F) else 0)",
            f"        • step ik.2 (b{stage-1} ik.1) := by",
            "  intro j",
            "  fin_cases j <;> decide +kernel\n",
            f"theorem stage_{stage}_eq : stage {stage} = spanRows b{stage} := by",
            f"  rw [show stage {stage} = next (stage {stage-1}) from rfl, stage_{'zero' if stage == 1 else stage-1}_eq]",
            "  exact next_spanRows _ _ _ _",
            f"    upper{stage}_correct lower{stage}_correct\n",
            f"theorem finrank_stage_{stage} : Module.finrank F (stage {stage}) = {s} := by",
            f"  rw [stage_{stage}_eq]",
            f"  exact finrank_spanRows b{stage} pivots{stage} pivots{stage}_correct\n",
        ]
        previous = reduced
    assert dimensions == [32, 31, 28, 23, 16, 9, 4, 1, 0], dimensions
    output += [
        "theorem stage_eight_eq_bot : stage 8 = ⊥ := by",
        "  rw [stage_8_eq]",
        "  simp [spanRows]\n",
        "end UnitDistance.Dyadic.Filtration\n",
    ]
    project = Path(__file__).resolve().parents[1]
    destination = project / "UnitDistance" / "DyadicCertificates.lean"
    destination.write_text("\n".join(output))
    print("Generated", destination)
    print("Dimensions:", dimensions)


if __name__ == "__main__":
    main()
