#!/usr/bin/env python3
"""Generate `UnitDistance/Sqrt241/Geometry/*` copies of witness-dependent modules.

Input: the taint analysis written by `Analyze.lean` (same directory; the
committed output is `geometry_analysis.json`), and the compiled `.ilean` files
of the ℚ development under `.lake/build` (reference positions of every
constant). Normally run through `regenerate_geometry.sh`, which also applies
`postprocess_values.py` and `postprocess_root.py`.

For every ℚ module that contains a needed witness-dependent declaration the
script writes a copy that keeps only the needed declarations (and the private
helpers and local instances they use), moves the namespace `UnitDistance.X` to
`UnitDistance.Sqrt241.X`, imports the ℚ original for all generic declarations,
and rewrites every reference so that it resolves exactly: references to copied
declarations go to the copies, all others to the ℚ declarations.

Usage: copy_geometry.py ANALYSIS_JSON OUTDIR [--only Mod1,Mod2]
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD = os.path.join(ROOT, '.lake', 'build', 'lib', 'lean')

UD = 'UnitDistance'
GENERATED_HEADER = '-- Generated by scripts/sqrt241/regenerate_geometry.sh — do not edit by hand.'
NEWROOT = 'UnitDistance.Sqrt241'
GEOM = 'UnitDistance.Sqrt241.Geometry'

# ℚ modules with an existing Sqrt241 port (names map by namespace move).
PORTED = {
    'UnitDistance.Witness': 'UnitDistance.Sqrt241.Witness',
    'UnitDistance.Target': 'UnitDistance.Sqrt241.Target',
    'UnitDistance.FiniteFunctionalArithmetic': 'UnitDistance.Sqrt241.FiniteFunctionalArithmetic',
    'UnitDistance.FiniteCertificates.Data': 'UnitDistance.Sqrt241.FiniteCertificates.Data',
}
# Target-module names that are witness-dependent (the rest is generic).
TARGET_MAPPED = {'increment', 'exponent', 'exponent_eq', 'increment_pos',
                 'increment_lt_one', 'Target'}
# Modules written by hand.
MANUAL = {
    'UnitDistance.SharperPairFixedBaseBridgeRun20260920',
    'UnitDistance.SharperPairFixedBaseCoreRun20260920',
    'UnitDistance.SharperPairArithmeticRateCoreRun20260920',
    'UnitDistance.GaloisFixedArithmetic',
}


def mod_path(m):
    return os.path.join(ROOT, *m.split('.')) + '.lean'


def ilean_path(m):
    return os.path.join(BUILD, *m.split('.')) + '.ilean'


_ilean_cache = {}


def load_ilean(m):
    if m not in _ilean_cache:
        p = ilean_path(m)
        _ilean_cache[m] = json.load(open(p)) if os.path.exists(p) else None
    return _ilean_cache[m]


def u16_to_idx(line, col):
    i = 0
    c = 0
    while c < col and i < len(line):
        c += 2 if ord(line[i]) > 0xFFFF else 1
        i += 1
    return i


def strip_private(n):
    """`_private.Mod.0.Real.Name` -> ('Real.Name', True)."""
    if n.startswith('_private.'):
        parts = n.split('.')
        # find the numeric component
        for k, part in enumerate(parts):
            if part.isdigit() and k > 0:
                return '.'.join(parts[k + 1:]), True
    return n, False


def all_ud_modules():
    mods = []
    base = os.path.join(BUILD, 'UnitDistance')
    for dp, _, fns in os.walk(base):
        for fn in fns:
            if fn.endswith('.ilean'):
                rel = os.path.relpath(os.path.join(dp, fn), BUILD)[:-len('.ilean')]
                mods.append(rel.replace(os.sep, '.'))
    return mods


class World:
    def __init__(self, analysis):
        self.collected = analysis['collected']
        self.wt = set(analysis['wtainted'])
        self.st = set(analysis['stainted'])
        # decl owners per module
        self.decl_module = {}
        self.module_decls = {}
        self.all_names = set()
        self.namespaces = set()
        for m in all_ud_modules():
            if m.startswith(GEOM):
                continue
            d = load_ilean(m)
            if d is None:
                continue
            decls = d.get('decls', {})
            self.module_decls[m] = decls
            for n in decls:
                self.decl_module[n] = m
                self.add_name(n)
        # references also give auto-generated names
        self.ref_module = {}

    def add_name(self, n):
        rn, _ = strip_private(n)
        self.all_names.add(rn)
        parts = rn.split('.')
        for k in range(1, len(parts)):
            self.namespaces.add('.'.join(parts[:k]))

    def owner(self, n):
        """Declaration (as listed in .ilean decls) owning constant n."""
        if n in self.decl_module:
            return n
        parts = n.split('.')
        for k in range(len(parts) - 1, 0, -1):
            cand = '.'.join(parts[:k])
            if cand in self.decl_module:
                return cand
        return None

    def tainted(self, n):
        return n in self.wt or n in self.st


def mapped_name(n, world, kept):
    """New full name for a ℚ constant `n` (None if it stays)."""
    rn, priv = strip_private(n)
    own = world.owner(n)
    m = world.decl_module.get(own) if own else None
    if m in PORTED:
        if m == 'UnitDistance.Target':
            last = rn.split('.')[1] if rn.count('.') >= 1 else rn
            if last not in TARGET_MAPPED:
                return None
        return NEWROOT + rn[len(UD):]
    if own is not None and own in kept:
        return NEWROOT + rn[len(UD):]
    return None


def new_module_name(m):
    if m in PORTED:
        return PORTED[m]
    return GEOM + m[len(UD):]


IDENT_RE = re.compile(r"^(@?)((?:_root_\.)?[^\s\d()\[\]{}⟨⟩,;:`\"@#$%^&*+=|\\/<>~!?.-][^\s()\[\]{}⟨⟩,;:`\"@#$%^&*+=|\\/<>~-]*)$")


def resolve_step1(ns, t, names):
    """First step of Lean's name resolution: longest namespace prefix first."""
    parts = ns.split('.') if ns else []
    for k in range(len(parts), 0, -1):
        cand = '.'.join(parts[:k]) + '.' + t
        if cand in names:
            return cand
    return None


def transform_ns(ns):
    if ns == UD or ns.startswith(UD + '.'):
        return NEWROOT + ns[len(UD):]
    return ns


def compute_kept(world, only_modules=None):
    kept = set()
    missing = []
    for c in world.collected:
        n, kind, mod = c['name'], c['kind'], c['module']
        if 'C' in kind or 'B' in kind:
            continue
        if not ('W' in kind or 'S' in kind):
            continue
        if mod in PORTED or mod in MANUAL or not mod.startswith(UD + '.'):
            continue
        own = world.owner(n)
        if own is None:
            rn, _ = strip_private(n)
            own = world.owner(rn)
        if own is None:
            missing.append(n)
            continue
        om = world.decl_module.get(own)
        if om in PORTED or om in MANUAL:
            continue
        kept.add(own)
    # local instances of modules with kept decls; source closure
    changed = True
    while changed:
        changed = False
        mods = {world.decl_module[k] for k in kept}
        for m in mods:
            d = load_ilean(m)
            src = open(mod_path(m)).read().split('\n')
            for dn, rng in d['decls'].items():
                if dn in kept:
                    continue
                text = '\n'.join(src[rng[0]:rng[2] + 1])
                if re.search(r'^\s*local instance', text, re.M):
                    kept.add(dn)
                    changed = True
                # private declarations carrying attributes (e.g. `@[simp]`) are
                # used implicitly by tactics and are invisible to importers
                elif strip_private(dn)[1] and re.search(r'^\s*@\[[^\]]*\]\s*private', text, re.M):
                    kept.add(dn)
                    changed = True
            for key, v in d['references'].items():
                kk = json.loads(key)
                if 'c' not in kk:
                    continue
                target = kk['c']['n']
                for u in v.get('usages', []):
                    if len(u) < 5 or u[4] not in kept:
                        continue
                    own = world.owner(target)
                    if own is None:
                        continue
                    om = world.decl_module.get(own)
                    if om is None or om in PORTED or om in MANUAL:
                        continue
                    rn, priv = strip_private(own)
                    need = False
                    if priv and om == m:
                        need = True
                    elif world.tainted(own) or world.tainted(target):
                        need = True
                    if need and own not in kept:
                        kept.add(own)
                        changed = True
    return kept, missing


OPEN_RE = re.compile(r'^(\s*)open\s+(scoped\s+)?(.*?)(\s+in)?\s*$')
NS_RE = re.compile(r'^(\s*)namespace\s+(\S+)\s*$')
END_RE = re.compile(r'^(\s*)end(?:\s+(\S+))?\s*$')
SECTION_RE = re.compile(r'^(\s*)(?:@\[[^\]]*\]\s*)?(?:public\s+)?(?:noncomputable\s+)?section(?:\s+(\S+))?\s*$')
IN_PREFIX_RE = re.compile(r'^\s*(include|omit|set_option|open|variable)\b.*\bin\s*$')


def generate(world, m, kept, outdir, warnings):
    d = load_ilean(m)
    src_text = open(mod_path(m)).read()
    src = src_text.split('\n')
    decls = d['decls']
    kept_here = {n for n in decls if n in kept}
    # line classification
    owner_of_line = {}
    for n, rng in decls.items():
        for ln in range(rng[0], rng[2] + 1):
            owner_of_line[ln] = n
    drop = set()
    for n, rng in decls.items():
        if n not in kept_here:
            for ln in range(rng[0], rng[2] + 1):
                drop.add(ln)
            # attached `... in` prefixes
            ln = rng[0] - 1
            while ln >= 0 and ln not in owner_of_line and IN_PREFIX_RE.match(src[ln]):
                drop.add(ln)
                ln -= 1
    # all names visible for resolution simulation
    names = world.all_names | world.new_names
    # --- namespace tracking over glue lines ---
    stack = []  # entries: ('ns', name, rewritten) or ('sec', name)
    ns_at_line = {}

    def cur_ns():
        return '.'.join(e[1] for e in stack if e[0] == 'ns')

    new_lines = list(src)
    in_header = True
    for ln, line in enumerate(src):
        ns_at_line[ln] = cur_ns()
        if ln in owner_of_line:
            continue
        mns = NS_RE.match(line)
        if mns:
            name = mns.group(2)
            full = (cur_ns() + '.' + name) if cur_ns() else name
            if not cur_ns():
                if name == UD or name.startswith(UD + '.'):
                    new_lines[ln] = mns.group(1) + 'namespace ' + transform_ns(name)
                else:
                    warnings.append(f'{m}:{ln+1}: root namespace {name} not under UnitDistance')
            stack.append(('ns', name, not cur_ns()))
            continue
        msec = SECTION_RE.match(line)
        if msec and not line.strip().startswith('end'):
            stack.append(('sec', msec.group(2) or ''))
            continue
        mend = END_RE.match(line)
        if mend and line.strip().startswith('end'):
            name = mend.group(2)
            if name is None:
                # closes an unnamed section
                if stack and stack[-1][0] == 'sec':
                    stack.pop()
                else:
                    warnings.append(f'{m}:{ln+1}: unmatched end')
            else:
                if stack and stack[-1][0] == 'sec' and stack[-1][1] == name:
                    stack.pop()
                else:
                    k = len(name.split('.'))
                    # pop k namespace components (a namespace command may push several)
                    top = stack[-1] if stack else None
                    if top and top[0] == 'ns' and top[1] == name:
                        stack.pop()
                        if top[2] and (name == UD or name.startswith(UD + '.')):
                            new_lines[ln] = mend.group(1) + 'end ' + transform_ns(name)
                    else:
                        warnings.append(f'{m}:{ln+1}: end {name} does not match {top}')
            continue
        mo = OPEN_RE.match(line)
        if mo and ln not in drop:
            toks = mo.group(3).split()
            ns = cur_ns()
            out = []
            ok = True
            for t in toks:
                if not re.match(r'^[A-Za-z_][\w.]*$', t):
                    ok = False
                    break
                parts = ns.split('.') if ns else []
                res = None
                for k in range(len(parts), 0, -1):
                    cand = '.'.join(parts[:k]) + '.' + t
                    if cand in world.namespaces:
                        res = cand
                        break
                if res is None:
                    res = t
                if res == UD or res.startswith(UD + '.'):
                    out.append(res)
                else:
                    out.append(t)
            if ok:
                new_lines[ln] = (mo.group(1) + 'open ' + (mo.group(2) or '') + ' '.join(out) +
                                 (mo.group(4) or ''))
            else:
                warnings.append(f'{m}:{ln+1}: unparsed open: {line.strip()}')
    # --- reference rewriting ---
    edits = {}  # line -> list of (start, end, newtext)
    for key, v in d['references'].items():
        kk = json.loads(key)
        if 'c' not in kk:
            continue
        target = kk['c']['n']
        for u in v.get('usages', []):
            l0, c0, l1, c1 = u[0], u[1], u[2], u[3]
            if l0 != l1 or l0 in drop:
                continue
            line = src[l0]
            a = u16_to_idx(line, c0)
            b = u16_to_idx(line, c1)
            text = line[a:b]
            mm = IDENT_RE.match(text)
            if not mm:
                continue
            if a > 0 and line[a - 1] == '.':
                if mapped_name(target, world, kept):
                    warnings.append(f'{m}:{l0+1}: dot-notation use of copied {target}')
                continue
            at, t = mm.group(1), mm.group(2)
            rt0, _ = strip_private(target)
            tt = t[len('_root_.'):] if t.startswith('_root_.') else t
            if not (rt0 == tt or rt0.endswith('.' + tt)):
                if mapped_name(target, world, kept):
                    warnings.append(f'{m}:{l0+1}: non-name reference {text!r} to copied {target}')
                continue
            ns_orig = ns_at_line.get(l0, '')
            ns_new = transform_ns(ns_orig)
            rtarget, priv = strip_private(target)
            newn = mapped_name(target, world, kept)
            if t.startswith('_root_.'):
                if newn:
                    edits.setdefault(l0, []).append((a, b, at + '_root_.' + newn))
                continue
            if newn:
                hit = resolve_step1(ns_new, t, names)
                if hit == newn:
                    continue
                if not hit and t == newn:
                    continue
                rel = newn[len(UD) + 1:]
                if resolve_step1(ns_new, rel, names) == newn:
                    edits.setdefault(l0, []).append((a, b, at + rel))
                else:
                    edits.setdefault(l0, []).append((a, b, at + newn))
            else:
                # generic target: keep if the new namespace chain still finds it
                if priv:
                    continue
                hit = resolve_step1(ns_new, t, names)
                if hit == rtarget:
                    continue
                orig_hit = resolve_step1(ns_orig, t, world.all_names)
                if hit is None and orig_hit != rtarget:
                    continue  # resolved by open/root in the original too
                if rtarget.startswith(UD + '.'):
                    rel = rtarget[len(UD) + 1:]
                    if resolve_step1(ns_new, rel, names) == rtarget:
                        edits.setdefault(l0, []).append((a, b, at + rel))
                        continue
                edits.setdefault(l0, []).append((a, b, at + '_root_.' + rtarget))
    for l0, es in edits.items():
        line = new_lines[l0] if new_lines[l0] == src[l0] else None
        if line is None:
            warnings.append(f'{m}:{l0+1}: reference edit on rewritten line skipped')
            continue
        es = sorted(set(es), key=lambda e: e[0], reverse=True)
        s = src[l0]
        last = None
        for a, b, rep in es:
            if last is not None and b > last:
                warnings.append(f'{m}:{l0+1}: overlapping edits')
                continue
            s = s[:a] + rep + s[b:]
            last = a
        new_lines[l0] = s
    # --- imports ---
    out = []
    body_start = None
    imports = []
    for ln, line in enumerate(src):
        mi = re.match(r'^(public\s+)?(meta\s+)?import\s+(\S+)\s*$', line)
        if mi:
            imports.append((ln, mi.group(3)))
    copy_mods = world.copy_modules
    new_imports = []
    seen = set()

    def add_imp(x):
        if x not in seen:
            seen.add(x)
            new_imports.append(x)
    add_imp(m)
    for _, im in imports:
        if im in copy_mods:
            add_imp(new_module_name(im))
        elif im in PORTED:
            add_imp(PORTED[im])
        else:
            add_imp(im)
    # modules of referenced copied constants
    for key, v in d['references'].items():
        kk = json.loads(key)
        if 'c' not in kk:
            continue
        target = kk['c']['n']
        if not any(u[0] not in drop for u in v.get('usages', [])):
            continue
        newn = mapped_name(target, world, kept)
        if newn:
            own = world.owner(target)
            om = world.decl_module.get(own)
            if om and om != m:
                if om in PORTED:
                    add_imp(PORTED[om])
                elif om in copy_mods:
                    add_imp(new_module_name(om))
    # --- assemble ---
    first_import = imports[0][0] if imports else 1
    last_import = imports[-1][0] if imports else 1
    res = [GENERATED_HEADER]
    for ln in range(0, first_import):
        res.append(src[ln])
    for im in new_imports:
        res.append('public import ' + im)
    header_done = False
    for ln in range(last_import + 1, len(src)):
        if ln in drop:
            continue
        line = new_lines[ln]
        res.append(line)
        if not header_done and line.startswith('set_option backward.privateInPublic'):
            res.append('')
            res.append('/-! Copy of `' + m + '` for the witness `UnitDistance.Sqrt241.Witness`:')
            res.append('only its witness-dependent declarations, moved to `UnitDistance.Sqrt241`;')
            res.append('generic declarations are used from the original. -/')
            res.append('set_option autoImplicit false')
            header_done = True
    text = '\n'.join(res)
    # value substitutions
    text = text.replace('Fin 11', 'Fin 5')
    # collapse runs of blank lines
    text = re.sub(r'\n{4,}', '\n\n\n', text)
    path = os.path.join(outdir, *new_module_name(m).split('.')) + '.lean'
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(text)
    return path, sorted(kept_here)


def main():
    analysis = json.load(open(sys.argv[1]))
    outdir = sys.argv[2]
    only = None
    if len(sys.argv) > 3 and sys.argv[3] == '--only':
        only = set(sys.argv[4].split(','))
    world = World(analysis)
    kept, missing = compute_kept(world)
    world.copy_modules = {world.decl_module[k] for k in kept}
    world.new_names = set()
    for k in kept:
        rn, _ = strip_private(k)
        world.new_names.add(NEWROOT + rn[len(UD):])
    # Sqrt241 ports: collect their names
    for pm in PORTED.values():
        dd = load_ilean(pm)
        if dd:
            for n in dd['decls']:
                rn, _ = strip_private(n)
                world.new_names.add(rn)
    # names for resolution in copies include the new ones
    warnings = []
    report = {}
    for m in sorted(world.copy_modules):
        if only and m not in only:
            continue
        path, ks = generate(world, m, kept, outdir, warnings)
        report[m] = ks
    json.dump({'kept': sorted(kept), 'missing': missing, 'modules': report,
               'warnings': warnings}, open(os.path.join(outdir, 'copy_report.json'), 'w'),
              indent=1)
    print('modules', len(report), 'kept', len(kept), 'missing', len(missing),
          'warnings', len(warnings))
    for w in warnings:
        print('WARN', w)


if __name__ == '__main__':
    main()
