#!/usr/bin/env python3
"""Generate UnitDistance/Sqrt241/Wide/CensusData.lean.

For every census prime p of Analytic.wideCensusOne / wideCensusTwo and every root a of
X^2 - X - 60 mod p, the label v (Legendre symbols of the radicands alpha_k = m + n*omega at
omega -> a) is computed; the place is good when bil_i(phi1_i v, phi1_i v) = 0 for the four D4
forms of Wide/D4Model.lean. The Lean side re-checks every hypothesis by `decide`.
"""
import sys

COORDS = [(-1, 0), (-75585293, 9148450), (-2854, -393), (3247, -393), (33, -4), (29, 4),
          (347, -42), (305, 42)]
ROWA = [[0, 1, 0, 1, 1, 1, 1, 1], [0, 1, 0, 0, 1, 1, 0, 0], [0, 1, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 1, 0, 1, 0]]
ROWB = [[1, 0, 0, 1, 1, 0, 0, 0], [1, 0, 0, 1, 0, 0, 0, 1], [1, 0, 0, 0, 1, 0, 0, 0],
        [1, 1, 0, 0, 0, 1, 0, 0]]
ONE = [47, 59, 61, 67, 83, 97, 113, 181, 223, 229, 257, 277, 281, 331, 337, 347, 401, 457,
       487, 509, 523, 541, 563, 607, 617, 673, 683, 691, 719, 733, 739, 773, 787, 821, 823,
       857, 877, 881, 883, 887, 937, 967]
TWO = [151, 191, 233, 421, 569, 743, 839, 991]


def good_places(p):
    out = []
    for a in range(p):
        if (a * a - a - 60) % p:
            continue
        t = [(m + n * a) % p for m, n in COORDS]
        assert all(t), (p, a)
        v = [0 if pow(x, (p - 1) // 2, p) == 1 else 1 for x in t]
        ok = True
        for i in range(4):
            x0 = sum(ROWA[i][k] * v[k] for k in range(8)) % 2
            x1 = sum(ROWB[i][k] * v[k] for k in range(8)) % 2
            if (x0 * x1 + (x1 if i == 0 else 0)) % 2:
                ok = False
        if ok:
            out.append((a, v))
    return out


def vec(v):
    return "![" + ", ".join(map(str, v)) + "]"


def place_args(a, v):
    return (f"{a} (by decide) {vec(v)}\n      (by decide +kernel) (by decide +kernel)")


def main(path):
    L = []
    L.append("""module

public import UnitDistance.Sqrt241.Wide.Census

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false

/-!
# The census places of `WideLocalTypes`

Generated by `scripts/sqrt241/generate_wide_census.py` — do not edit by hand.

For each prime of `Analytic.wideCensusOne` (`wideCensusTwo`), the root(s) `a` of
`X² - X - 60` mod `p` whose place has `fW = 2`, with the Legendre label `v` of the radicands;
all hypotheses of `censusOne_of_place` / `censusTwo_of_places` are checked by `decide`.
-/

noncomputable section

namespace UnitDistance.Sqrt241.Wide

open NumberField UnitDistance.Sqrt241.Analytic CanonicalWide

set_option maxRecDepth 100000
""")
    L.append("/-- **Census, one place.** -/")
    L.append("theorem wide_censusOne (p : Nat.Primes) (hp : p.val ∈ wideCensusOne) :")
    L.append("    ContribLowerBound CanonicalWide.Carrier p [(1 / 4, 2)] := by")
    L.append("  obtain ⟨n, hn⟩ := p")
    L.append("  simp only [wideCensusOne, Finset.mem_insert, Finset.mem_singleton] at hp")
    L.append("  rcases hp with " + " | ".join(["rfl"] * len(ONE)))
    for p in ONE:
        g = good_places(p)
        assert len(g) == 1, p
        a, v = g[0]
        L.append(f"  · exact censusOne_of_place ⟨{p}, by norm_num⟩ (by decide) (by decide) {a} (by decide) {vec(v)}")
        L.append("      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)")
        L.append("      (by decide +kernel)")
    L.append("")
    L.append("/-- **Census, both places.** -/")
    L.append("theorem wide_censusTwo (p : Nat.Primes) (hp : p.val ∈ wideCensusTwo) :")
    L.append("    ContribLowerBound CanonicalWide.Carrier p [(1 / 2, 2)] := by")
    L.append("  obtain ⟨n, hn⟩ := p")
    L.append("  simp only [wideCensusTwo, Finset.mem_insert, Finset.mem_singleton] at hp")
    L.append("  rcases hp with " + " | ".join(["rfl"] * len(TWO)))
    for p in TWO:
        g = good_places(p)
        assert len(g) == 2, p
        (a, v), (b, w) = g
        L.append(f"  · exact censusTwo_of_places ⟨{p}, by norm_num⟩ (by decide) (by decide) (by decide +kernel)")
        L.append(f"      (by decide) {a} (by decide) {vec(v)} (by decide +kernel) (by decide +kernel)")
        L.append(f"      (by decide +kernel) {b} (by decide) {vec(w)} (by decide +kernel) (by decide +kernel)")
        L.append("      (by decide +kernel) (by decide)")
    L.append("")
    L.append("end UnitDistance.Sqrt241.Wide")
    open(path, "w").write("\n".join(L) + "\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "UnitDistance/Sqrt241/Wide/CensusData.lean")
