#!/usr/bin/env python3
"""Regenerate the repetitive blocks of the base-field modules (B = Q(sqrt 241)).

  python3 scripts/sqrt241/generate_base_tables.py primes [--write | --check]
  python3 scripts/sqrt241/generate_base_tables.py local  [--write | --check]
  python3 scripts/sqrt241/generate_base_tables.py         # re-check the square classes

`primes` produces the per-prime section of UnitDistance/Sqrt241/Base/Primes.lean
(after "The split primes and the ramified prime"); `local` produces the
embedding/square-class section of UnitDistance/Sqrt241/Base/Local.lean (after
"The eight embeddings ...").  In the modules each block is enclosed by the lines
"-- BEGIN Generated by scripts/sqrt241/generate_base_tables.py <what> — do not
edit by hand." and "-- END Generated by ...".  Without an option the marked
block is printed; `--write` replaces the marked block of the module, `--check`
exits with status 1 if it differs.  The data: omega = (1 + sqrt 241)/2 is a root of
X^2 - X - 60; a split prime (pi) of norm p corresponds to the root r mod p with
pi = m + n*omega = 0 mod (p, omega - r).  The square-class tables are
reproduced by `check_squareclasses()` below from the explicit radicands, and
agree with the Hilbert-symbol lines of
papers/0.04273/certificates/kummer241.gp.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TARGETS = {"primes": "UnitDistance/Sqrt241/Base/Primes.lean",
           "local": "UnitDistance/Sqrt241/Base/Local.lean"}

ALPHA = [(-1, 0), (-75585293, 9148450), (-2854, -393), (3247, -393),
         (33, -4), (29, 4), (347, -42), (305, 42)]   # (m, n): m + n*omega

SPLIT = [  # suffix, element, p, root of X^2-X-60 mod p, description
    ("2", "pi2", 2, 0, "(-6101 - 393√241)/2"),
    ("2'", "pi2'", 2, 1, "(6101 - 393√241)/2"),
    ("3", "pi3", 3, 0, "31 - 2√241"),
    ("3'", "pi3'", 3, 1, "31 + 2√241"),
    ("5", "pi5", 5, 1, "326 - 21√241"),
    ("5'", "pi5'", 5, 0, "326 + 21√241"),
    ("29", "pi29", 29, 2, "-14127 + 910√241"),
    ("29'", "pi29'", 29, 28, "-14127 - 910√241"),
    ("241", "sqrt241Int", 241, 121, "√241"),
]

EMB = [  # suffix, p, lift a of the root (mod 8 for p = 2), table, uniformizer (i, N, c')
    ("2", 2, 4, [7, 3, 6, 3, 1, 5, 3, 1], (2, -2, -3)),
    ("2'", 2, 13, [7, 5, 5, 10, 5, 1, 1, 3], (3, -2, -5)),
    ("3", 3, 0, [-1, 1, -1, 1, 3, -1, -1, -1], (4, -3, -1)),
    ("3'", 3, 1, [-1, -1, -1, 1, -1, 3, -1, -1], (5, -3, -1)),
    ("5", 5, 1, [1, 2, 2, 1, 1, 2, 10, 2], (6, -5, -2)),
    ("5'", 5, 0, [1, 2, 1, 2, 2, 1, 2, 10], (7, -5, -2)),
    ("29", 29, 2, [1, 1, 2, 1, 1, 2, 2, 2], None),
    ("29'", 29, 28, [1, 1, 1, 2, 2, 1, 2, 2], None),
]
NORMNAME = {2: "norm_pi2", 3: "norm_pi2'", 4: "norm_pi3", 5: "norm_pi3'",
            6: "norm_pi5", 7: "norm_pi5'"}
PNAME = {"2": "P2", "2'": "P2'", "3": "P3", "3'": "P3'", "5": "P5", "5'": "P5'",
         "29": "P29", "29'": "P29'"}


def primes_block():
    out = []
    for (N, pi, p, r, desc) in SPLIT:
        f = 1
        out.append(f"""
/-- The residue map at `({desc})`: `ω ↦ {r}` modulo `{p}`. -/
def res{N} : 𝓞 B →+* ZMod {p} := evalHom ({r} : ZMod {p}) (by decide)

/-- The prime ideal `({desc})` of norm `{p}`. -/
def P{N} : Ideal (𝓞 B) := span {{{pi}}}

theorem res{N}_{pi} : res{N} {pi} = 0 := by
  rw [res{N}, {pi}, evalHom_mk]; decide

theorem natAbs_norm_{pi} : (Algebra.norm ℤ {pi}).natAbs = {p} := by
  rw [norm_{pi}]; rfl

theorem prime_{pi} : Prime {pi} := prime_of_norm (by norm_num) natAbs_norm_{pi}

theorem {pi}_ne_zero : {pi} ≠ 0 := ne_zero_of_norm (by norm_num) natAbs_norm_{pi}

theorem P{N}_eq_ker : P{N} = RingHom.ker res{N} :=
  span_eq_ker_of_norm natAbs_norm_{pi} res{N} res{N}_{pi}

theorem mem_P{N} {{x : 𝓞 B}} : x ∈ P{N} ↔ res{N} x = 0 := by
  rw [P{N}_eq_ker, RingHom.mem_ker]

instance isMaximal_P{N} : P{N}.IsMaximal := isMaximal_span_of_norm (by norm_num) natAbs_norm_{pi}

instance isPrime_P{N} : P{N}.IsPrime := isMaximal_P{N}.isPrime

theorem P{N}_ne_bot : P{N} ≠ ⊥ := by
  rw [P{N}, Ne, span_singleton_eq_bot]; exact {pi}_ne_zero

theorem absNorm_P{N} : absNorm P{N} = {p} := absNorm_span_eq natAbs_norm_{pi}

theorem natCast_mem_P{N} : (({p} : ℕ) : 𝓞 B) ∈ P{N} := by
  rw [mem_P{N}, map_natCast]; decide

instance liesOver_P{N} : P{N}.LiesOver (span {{(({p} : ℕ) : ℤ)}}) :=
  liesOver_of_natCast_mem (by norm_num) natCast_mem_P{N}

theorem inertiaDeg_P{N} : P{N}.inertiaDeg ℤ = {f} :=
  inertiaDeg_eq_of_absNorm {p} (by norm_num) (by rw [absNorm_P{N}]; norm_num)

/-- The residue field at `({desc})` is `ZMod {p}`. -/
def residueEquiv{N} : 𝓞 B ⧸ P{N} ≃+* ZMod {p} :=
  (quotEquivOfEq P{N}_eq_ker).trans
    (RingHom.quotientKerEquivOfSurjective (evalHom_surjective _ _))
""")
    return "".join(out)


def local_block():
    out = []
    for (N, p, a, table, unif) in EMB:
        ares = a % p
        if p == 2:
            out.append(f"""/-- The root of `X² - X - 60` in `ℤ_2` with `r ≡ {a % 8} (mod 8)`. -/
def root{N} : ℤ_[2] := (exists_omegaRoot_two {a} (by decide)).choose

theorem root{N}_mul_self : root{N} * root{N} = root{N} + 60 :=
  (exists_omegaRoot_two {a} (by decide)).choose_spec.1

theorem toZMod_root{N} : PadicInt.toZMod root{N} = {ares} := by
  rw [root{N}, (exists_omegaRoot_two {a} (by decide)).choose_spec.2.1]; decide

theorem residue8_root{N} : UnitDistance.PadicTwo.residue8 root{N} = {a % 8} := by
  rw [root{N}, (exists_omegaRoot_two {a} (by decide)).choose_spec.2.2]; decide
""")
        else:
            out.append(f"""/-- The root of `X² - X - 60` in `ℤ_{p}` with `r ≡ {a} (mod {p})`. -/
def root{N} : ℤ_[{p}] := (exists_omegaRoot (p := {p}) {a} (by decide) (by decide)).choose

theorem root{N}_mul_self : root{N} * root{N} = root{N} + 60 :=
  (exists_omegaRoot (p := {p}) {a} (by decide) (by decide)).choose_spec.1

theorem toZMod_root{N} : PadicInt.toZMod root{N} = {ares} := by
  rw [root{N}, (exists_omegaRoot (p := {p}) {a} (by decide) (by decide)).choose_spec.2]; decide
""")
        out.append(f"""
/-- The embedding `B → ℚ_{p}` at `{PNAME[N]}` (`ω ↦ root{N}`). -/
def iota{N} : B →ₐ[ℚ] ℚ_[{p}] := iota root{N} root{N}_mul_self

/-- The embedding `𝓞 B → ℤ_{p}` at `{PNAME[N]}`. -/
def iotaInt{N} : 𝓞 B →+* ℤ_[{p}] := iotaInt root{N} root{N}_mul_self

theorem iota{N}_coe (x : 𝓞 B) : iota{N} (x : B) = (iotaInt{N} x : ℚ_[{p}]) :=
  iota_coe _ _ x

/-- `{PNAME[N]}` is the prime of `iota{N}`: `x ∈ {PNAME[N]} ↔ ‖iota{N} x‖ < 1`. -/
theorem mem_{PNAME[N]}_iff_norm_iota (x : 𝓞 B) : x ∈ {PNAME[N]} ↔ ‖iotaInt{N} x‖ < 1 := by
  rw [padicInt_norm_lt_one_iff, iotaInt{N}, toZMod_iotaInt, mem_{PNAME[N]}, res{N},
    evalHom_congr toZMod_root{N}]

/-- Square-class representatives of `iota{N} (alpha i)` in `ℚ_{p}^×/ℚ_{p}^{{×2}}`. -/
def squareclass{N} : Fin 8 → ℤ := ![{", ".join(str(t) for t in table)}]

theorem iota{N}_alpha (i : Fin 8) : ∃ z : ℚ_[{p}], z ≠ 0 ∧
    iota{N} ((alpha i : 𝓞 B) : B) = (squareclass{N} i : ℚ_[{p}]) * z ^ 2 := by
  fin_cases i""")
        for i in range(8):
            c = table[i]
            if unif is not None and unif[0] == i:
                (_, n, cp) = unif
                if p == 2:
                    out.append(f"""
  · exact iota_alpha_of_uniformizer_two _ _ _ residue8_root{N} {i} ({n}) ({cp}) {c} {NORMNAME[i]}
      (by decide) (by norm_num) (by decide)""")
                else:
                    out.append(f"""
  · exact iota_alpha_of_uniformizer_odd _ _ _ toZMod_root{N} {i} ({n}) ({cp}) {c} {NORMNAME[i]}
      (by norm_num) (by norm_num) (by decide)""")
            elif p == 2:
                out.append(f"""
  · exact iota_alpha_of_unit_two _ _ _ residue8_root{N} {i} ({c}) (by decide) (by decide)""")
            else:
                out.append(f"""
  · exact iota_alpha_of_unit_odd _ _ _ toZMod_root{N} {i} ({c}) (by decide)""")
        out.append("\n")
    return "".join(out)


def check_squareclasses():
    """Recompute the tables from the radicands (numerically, in Z/p^K)."""
    def legendre(x, p):
        x %= p
        return 0 if x == 0 else (1 if pow(x, (p - 1) // 2, p) == 1 else -1)
    for (N, p, a, table, unif) in EMB:
        K = 14 if p == 2 else 8
        M = p ** K
        r = a
        for k in range(2, K + 1):  # Hensel lift of a (a simple root mod p)
            for t in range(p):
                x = r + t * p ** (k - 1) if k > 1 else r
                if (x * x - x - 60) % p ** k == 0:
                    r = x
                    break
        assert (r * r - r - 60) % M == 0
        for i, (m, n) in enumerate(ALPHA):
            x = (m + n * r) % M
            v = 0
            while x % p == 0:
                x //= p
                v += 1
            c = table[i]
            cv = 0
            cu = c
            while cu % p == 0:
                cu //= p
                cv += 1
            assert v % 2 == cv % 2, (N, i)
            if p == 2:
                assert x % 8 == cu % 8, (N, i)
            else:
                assert legendre(x, p) == legendre(cu, p), (N, i)
    print("square-class tables verified", file=sys.stderr)


def begin_marker(what):
    return (f"-- BEGIN Generated by scripts/sqrt241/generate_base_tables.py {what}"
            " — do not edit by hand.")


def end_marker(what):
    return f"-- END Generated by scripts/sqrt241/generate_base_tables.py {what}."


def marked_block(what):
    block = primes_block() if what == "primes" else local_block()
    return begin_marker(what) + "\n" + block.strip("\n") + "\n" + end_marker(what) + "\n"


def replace_marked(text, what, new):
    """Replace the lines from the BEGIN marker to the END marker (inclusive)."""
    b = text.index(begin_marker(what))
    e = text.index(end_marker(what), b)
    e = text.index("\n", e) + 1
    return text[:b] + new + text[e:]


if __name__ == "__main__":
    what = sys.argv[1] if len(sys.argv) > 1 else "check"
    mode = sys.argv[2] if len(sys.argv) > 2 else None
    if what in TARGETS:
        new = marked_block(what)
        if mode is None:
            print(new, end="")
        else:
            path = ROOT / TARGETS[what]
            old = path.read_text()
            text = replace_marked(old, what, new)
            if mode == "--write":
                path.write_text(text)
                print(("updated " if text != old else "unchanged ") + str(path))
            elif mode == "--check":
                if text != old:
                    print(f"{path}: generated block differs", file=sys.stderr)
                    sys.exit(1)
                print(f"{path}: generated block up to date")
            else:
                sys.exit(f"unknown option {mode}")
    else:
        check_squareclasses()
