import sys
FORMS = [(0, 24, [1,3,4,5,6,7], [0,3,4], "837220446735*s/2 - 12997156474395/2", "24385*s/2 - 378557/2"),
         (1, 20, [1,4,5], [0,3,7], "-13722675*s + 213033204", "-3*s/2 + 47/2"),
         (2, 17, [1,5,6], [0,4], "-144198668*s + 2238565313", "2*s - 31"),
         (3, 7, [4,6], [0,1,5], "-1303*s + 20228", "221161*s - 3433342")]
NAMES = ["10", "01", "11"]
def omegaRhs(e): return e.replace("s", "rootOmega")
CV = "Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one"
out = []
for i, o, A, Bk, a, b in FORMS:
    prodA = " * ".join(f"genusRootOmega {k}" for k in A)
    prodB = " * ".join(f"genusRootOmega {k}" for k in Bk)
    sumA = " + ".join(f"genusChar g {k}" for k in A)
    sumB = " + ".join(f"genusChar g {k}" for k in Bk)
    ids = []
    for k in NAMES:
        for l in NAMES:
            ids.append(f"u{o}_cocycle_{k}_{l} rootOmega (xOm {i}) (yOm {i}) rootOmega_sq hxO_{i} hyO_{i}")
    cocycle_tac = " | ".join(["ring1"] + [f"linear_combination {t}" for t in ids])
    sq_tac = " | ".join(["ring1"] + [f"linear_combination beta{o}_sigma_{k} rootOmega (xOm {i}) (yOm {i}) rootOmega_sq hxO_{i} hyO_{i}" for k in NAMES])
    out.append(f'''
/-! ### Form {o} (index {i}) -/

theorem xOm_eq_{i} : xOm {i} = {prodA} := Subtype.ext (by simp [xOm, rootA])

theorem yOm_eq_{i} : yOm {i} = {prodB} := Subtype.ext (by simp [yOm, rootB])

theorem xOm_ne_zero_{i} : xOm {i} ≠ 0 := by
  rw [xOm_eq_{i}]
  simp [genusRootOmega_ne_zero]

theorem yOm_ne_zero_{i} : yOm {i} ≠ 0 := by
  rw [yOm_eq_{i}]
  simp [genusRootOmega_ne_zero]

theorem hxO_{i} : xOm {i} ^ 2 = {omegaRhs(a)} := by
  apply (Omega.val : Omega →ₐ[ℚ] Closure).toRingHom.injective
  simp only [map_pow, map_sub, map_add, map_mul, map_div₀, map_ofNat, map_neg]
  exact rootA_sq_{i}

theorem hyO_{i} : yOm {i} ^ 2 = {omegaRhs(b)} := by
  apply (Omega.val : Omega →ₐ[ℚ] Closure).toRingHom.injective
  simp only [map_pow, map_sub, map_add, map_mul, map_div₀, map_ofNat, map_neg]
  exact rootB_sq_{i}

theorem aBit_eq_{i} (g : GB) : aBit {i} g = {sumA} := by
  simp [aBit, rowA, Fin.sum_univ_eight, genusLabel_apply]

theorem bBit_eq_{i} (g : GB) : bBit {i} g = {sumB} := by
  simp [bBit, rowB, Fin.sum_univ_eight, genusLabel_apply]

theorem act_xOm_{i} (g : GB) : (g : Ghat) (xOm {i}) = binarySign (aBit {i} g) * xOm {i} := by
  rw [xOm_eq_{i}, aBit_eq_{i}]
  simp only [map_mul, genusChar_action, binarySign_add]
  ring

theorem act_yOm_{i} (g : GB) : (g : Ghat) (yOm {i}) = binarySign (bBit {i} g) * yOm {i} := by
  rw [yOm_eq_{i}, bBit_eq_{i}]
  simp only [map_mul, genusChar_action, binarySign_add]
  ring

theorem betaOm_eq_{i} : betaOm {i} = betaFun {i} rootOmega (xOm {i}) (yOm {i}) := by
  apply Subtype.ext
  have h := beta{o}_map Omega.val.toRingHom rootOmega (xOm {i}) (yOm {i})
  simp only [betaFun, {CV}]
  rw [show ((beta{o} rootOmega (xOm {i}) (yOm {i}) : Omega) : Closure) =
    beta{o} (rootOmega : Closure) (xOm {i} : Closure) (yOm {i} : Closure) from h]
  exact wideRadicand_{i}

theorem sq_{i} (a b : F) : betaFun {i} rootOmega (binarySign a * xOm {i}) (binarySign b * yOm {i}) =
    uOm {i} a b ^ 2 * betaFun {i} rootOmega (xOm {i}) (yOm {i}) := by
  rcases ClassTwo.Collection.binary_cases a with rfl | rfl <;> rcases ClassTwo.Collection.binary_cases b with rfl | rfl <;>
    simp only [uOm, uFun, betaFun, {CV}, binarySign_zero, bs_one, one_mul, neg_one_mul,
      eq_self_iff_true, F_one_ne_zero, ite_true, ite_false, ↓reduceIte] <;>
    first | {sq_tac}

theorem cocycle_{i} (a b c d : F) : uOmS {i} a b c d * uOm {i} a b =
    binarySign (bilFormula {i} ![a, b] ![c, d]) * uOm {i} (a + c) (b + d) := by
  rcases ClassTwo.Collection.binary_cases a with rfl | rfl <;> rcases ClassTwo.Collection.binary_cases b with rfl | rfl <;>
    rcases ClassTwo.Collection.binary_cases c with rfl | rfl <;> rcases ClassTwo.Collection.binary_cases d with rfl | rfl <;>
    simp only [uOmS, uOm, uFun, bilFormula, {CV}, binarySign_zero, bs_one, one_mul,
      neg_one_mul, mul_one, mul_zero, zero_mul, add_zero, zero_add, F_one_add_one,
      eq_self_iff_true, F_one_ne_zero, ite_true, ite_false, ↓reduceIte, Fin.reduceEq] <;>
    first | {cocycle_tac}
''')
FAMS = {0: 24, 1: 20, 2: 17, 3: 7}
def vec(fn): return "![" + ", ".join(fn(o) for o in (24, 20, 17, 7)) + "]"
hdr = f'''module

public import UnitDistance.Sqrt241.Wide.Omega
public import UnitDistance.Sqrt241.Wide.D4Model
public import UnitDistance.Sqrt241.Retained.Field

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false
set_option linter.unusedSimpArgs false

/-!
# The D4 characters of `G_B` and `E_W ≤ M`

Generated by `scripts/sqrt241/generate_wide_character.py` — do not edit by hand.

For each form `i`, an element `g ∈ G_B` multiplies `√a_i`, `√b_i` by the signs of
`φ₁(label g) = (aBit, bBit)` and sends `√β_i` to `± u_{{φ₁(label g)}} √β_i`
(`act_wOm`; `u_0 = 1`). By the cocycle identities of `Wide/Identities.lean`,
`chi i : G_B →* D4 i`, `g ↦ (φ₁(label g), sign)`, is a continuous homomorphism. On the free
generators it agrees with `lambdaHom i (ell i) ∘ retainedFree` (`Wide/D4Model.lean`), so the two
agree on the free source (`chi_freeMap`). Hence every element of `retainedKer` (in particular of
`core`) fixes `√β_i`, and `E_W ≤ M` for every retained input (`field_le_M`).
-/

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.Wide

open Tower Base CanonicalGenus CanonicalWide IntermediateField ClassTwo GroupData Multiquadratic

theorem F_one_ne_zero : (1 : F) ≠ 0 := by decide
theorem F_one_add_one : (1 : F) + 1 = 0 := by decide
theorem F_add_self (a : F) : a + a = 0 := by
  have h : ∀ x : F, x + x = 0 := by decide
  exact h a

theorem bs_one : binarySign (E := Omega) 1 = -1 := by simp [binarySign, binarySignInteger]

theorem rootA_mem_genusB : ∀ i : Fin 4, rootA i ∈ genusB
  | 0 => rootA_mem_genusB_0 | 1 => rootA_mem_genusB_1 | 2 => rootA_mem_genusB_2
  | 3 => rootA_mem_genusB_3

theorem rootB_mem_genusB : ∀ i : Fin 4, rootB i ∈ genusB
  | 0 => rootB_mem_genusB_0 | 1 => rootB_mem_genusB_1 | 2 => rootB_mem_genusB_2
  | 3 => rootB_mem_genusB_3

theorem rootA_mem_Omega (i : Fin 4) : rootA i ∈ Omega := admissible_genusB.le_Omega (rootA_mem_genusB i)
theorem rootB_mem_Omega (i : Fin 4) : rootB i ∈ Omega := admissible_genusB.le_Omega (rootB_mem_genusB i)

/-- `√a_i`, `√b_i`, `√β_i` and `β_i` in `Ω`. -/
def xOm (i : Fin 4) : Omega := ⟨rootA i, rootA_mem_Omega i⟩
def yOm (i : Fin 4) : Omega := ⟨rootB i, rootB_mem_Omega i⟩
def wOm (i : Fin 4) : Omega := ⟨wideRoot i, wideRoot_mem_Omega i⟩

theorem wideRadicand_mem_Omega (i : Fin 4) : wideRadicand i ∈ Omega := by
  rw [← wideRoot_sq]
  exact pow_mem (wideRoot_mem_Omega i) 2

def betaOm (i : Fin 4) : Omega := ⟨wideRadicand i, wideRadicand_mem_Omega i⟩

theorem wOm_sq (i : Fin 4) : wOm i ^ 2 = betaOm i := Subtype.ext (wideRoot_sq i)

/-- The radicand polynomials at `Ω`. -/
def betaFun (i : Fin 4) (s x y : Omega) : Omega :=
  (![beta24 s x y, beta20 s x y, beta17 s x y, beta7 s x y] : Fin 4 → Omega) i

/-- The polynomials `u_k` (`k = 10, 01, 11`) at `Ω`. -/
def uFun (i : Fin 4) (k : Fin 3) (s x y : Omega) : Omega :=
  (![![u24_10 s x y, u24_01 s x y, u24_11 s x y], ![u20_10 s x y, u20_01 s x y, u20_11 s x y],
    ![u17_10 s x y, u17_01 s x y, u17_11 s x y], ![u7_10 s x y, u7_01 s x y, u7_11 s x y]] :
    Fin 4 → Fin 3 → Omega) i k

/-- `u_(a,b)` at `(√241, √a_i, √b_i)`, with `u_(0,0) = 1`. -/
def uOm (i : Fin 4) (a b : F) : Omega :=
  if a = 0 then (if b = 0 then 1 else uFun i 1 rootOmega (xOm i) (yOm i))
  else (if b = 0 then uFun i 0 rootOmega (xOm i) (yOm i) else uFun i 2 rootOmega (xOm i) (yOm i))

/-- `u_(c,d)` with the signs `(a, b)` applied to `√a_i`, `√b_i`. -/
def uOmS (i : Fin 4) (a b c d : F) : Omega :=
  if c = 0 then (if d = 0 then 1 else uFun i 1 rootOmega (binarySign a * xOm i) (binarySign b * yOm i))
  else (if d = 0 then uFun i 0 rootOmega (binarySign a * xOm i) (binarySign b * yOm i)
    else uFun i 2 rootOmega (binarySign a * xOm i) (binarySign b * yOm i))

theorem betaFun_map (i : Fin 4) (f : Omega →+* Omega) (s x y : Omega) :
    f (betaFun i s x y) = betaFun i (f s) (f x) (f y) := by
  fin_cases i <;> simp only [betaFun, {CV}]
  · exact beta24_map f s x y
  · exact beta20_map f s x y
  · exact beta17_map f s x y
  · exact beta7_map f s x y

theorem uFun_map (i : Fin 4) (k : Fin 3) (f : Omega →+* Omega) (s x y : Omega) :
    f (uFun i k s x y) = uFun i k (f s) (f x) (f y) := by
  fin_cases i <;> fin_cases k <;> simp only [uFun, {CV}]
  all_goals first
    | exact u24_10_map f s x y | exact u24_01_map f s x y | exact u24_11_map f s x y
    | exact u20_10_map f s x y | exact u20_01_map f s x y | exact u20_11_map f s x y
    | exact u17_10_map f s x y | exact u17_01_map f s x y | exact u17_11_map f s x y
    | exact u7_10_map f s x y | exact u7_01_map f s x y | exact u7_11_map f s x y

/-- The Klein-four coordinates of `g`: `(r₁ · label g, r₂ · label g)`. -/
def aBit (i : Fin 4) (g : GB) : F := ∑ k, rowA i k * (genusLabel g).toAdd k
def bBit (i : Fin 4) (g : GB) : F := ∑ k, rowB i k * (genusLabel g).toAdd k

theorem aBit_mul (i : Fin 4) (g h : GB) : aBit i (g * h) = aBit i g + aBit i h := by
  simp only [aBit, map_mul, toAdd_mul, Pi.add_apply, mul_add, Finset.sum_add_distrib]

theorem bBit_mul (i : Fin 4) (g h : GB) : bBit i (g * h) = bBit i g + bBit i h := by
  simp only [bBit, map_mul, toAdd_mul, Pi.add_apply, mul_add, Finset.sum_add_distrib]

theorem act_root (g : GB) : (g : Ghat) rootOmega = rootOmega := (mem_GB_iff _).1 g.2
'''
mid = '''
theorem act_xOm : ∀ (i : Fin 4) (g : GB), (g : Ghat) (xOm i) = binarySign (aBit i g) * xOm i
  | 0 => act_xOm_0 | 1 => act_xOm_1 | 2 => act_xOm_2 | 3 => act_xOm_3

theorem act_yOm : ∀ (i : Fin 4) (g : GB), (g : Ghat) (yOm i) = binarySign (bBit i g) * yOm i
  | 0 => act_yOm_0 | 1 => act_yOm_1 | 2 => act_yOm_2 | 3 => act_yOm_3

theorem betaOm_eq : ∀ i : Fin 4, betaOm i = betaFun i rootOmega (xOm i) (yOm i)
  | 0 => betaOm_eq_0 | 1 => betaOm_eq_1 | 2 => betaOm_eq_2 | 3 => betaOm_eq_3

theorem sq_u : ∀ (i : Fin 4) (a b : F),
    betaFun i rootOmega (binarySign a * xOm i) (binarySign b * yOm i) =
      uOm i a b ^ 2 * betaFun i rootOmega (xOm i) (yOm i)
  | 0 => sq_0 | 1 => sq_1 | 2 => sq_2 | 3 => sq_3

theorem cocycle : ∀ (i : Fin 4) (a b c d : F), uOmS i a b c d * uOm i a b =
    binarySign (bilFormula i ![a, b] ![c, d]) * uOm i (a + c) (b + d)
  | 0 => cocycle_0 | 1 => cocycle_1 | 2 => cocycle_2 | 3 => cocycle_3

theorem act_uOm (i : Fin 4) (g : GB) (c d : F) :
    (g : Ghat) (uOm i c d) = uOmS i (aBit i g) (bBit i g) c d := by
  have hf : ∀ k : Fin 3, (g : Ghat) (uFun i k rootOmega (xOm i) (yOm i)) =
      uFun i k rootOmega (binarySign (aBit i g) * xOm i) (binarySign (bBit i g) * yOm i) := by
    intro k
    have h := uFun_map i k (g : Ghat).toRingEquiv.toRingHom rootOmega (xOm i) (yOm i)
    change (g : Ghat) _ = uFun i k ((g : Ghat) rootOmega) ((g : Ghat) (xOm i)) ((g : Ghat) (yOm i)) at h
    rw [h, act_root, act_xOm, act_yOm]
  unfold uOm uOmS
  split_ifs <;> simp only [map_one, hf]

theorem uOm_ne_zero (i : Fin 4) (a b : F) : uOm i a b ≠ 0 := by
  intro h
  have hc := cocycle i a b a b
  rw [h, mul_zero, F_add_self, F_add_self] at hc
  have h00 : uOm i 0 0 = 1 := by simp [uOm]
  rw [h00, mul_one] at hc
  exact binarySign_ne_zero _ hc.symm

theorem xOm_ne_zero : ∀ i : Fin 4, xOm i ≠ 0
  | 0 => xOm_ne_zero_0 | 1 => xOm_ne_zero_1 | 2 => xOm_ne_zero_2 | 3 => xOm_ne_zero_3

theorem yOm_ne_zero : ∀ i : Fin 4, yOm i ≠ 0
  | 0 => yOm_ne_zero_0 | 1 => yOm_ne_zero_1 | 2 => yOm_ne_zero_2 | 3 => yOm_ne_zero_3

theorem wideRadicand_ne_zero : ∀ i : Fin 4, wideRadicand i ≠ 0
  | 0 => fun h => by
    have := betaO_mul_cofO_0
    rw [← oHom_injective.eq_iff, map_mul, oHom_betaO_0, h, zero_mul, map_intCast] at this
    norm_num at this
  | 1 => fun h => by
    have := betaO_mul_cofO_1
    rw [← oHom_injective.eq_iff, map_mul, oHom_betaO_1, h, zero_mul, map_intCast] at this
    norm_num at this
  | 2 => fun h => by
    have := betaO_mul_cofO_2
    rw [← oHom_injective.eq_iff, map_mul, oHom_betaO_2, h, zero_mul, map_intCast] at this
    norm_num at this
  | 3 => fun h => by
    have := betaO_mul_cofO_3
    rw [← oHom_injective.eq_iff, map_mul, oHom_betaO_3, h, zero_mul, map_intCast] at this
    norm_num at this

theorem betaOm_ne_zero (i : Fin 4) : betaOm i ≠ 0 := fun h =>
  wideRadicand_ne_zero i (congrArg Subtype.val h)

theorem wOm_ne_zero (i : Fin 4) : wOm i ≠ 0 := by
  intro h
  apply betaOm_ne_zero i
  rw [← wOm_sq, h]
  ring

open Classical in
/-- The sign of `g` on `√β_i`. -/
def sgn (i : Fin 4) (g : GB) : F :=
  if (g : Ghat) (wOm i) = uOm i (aBit i g) (bBit i g) * wOm i then 0 else 1

theorem act_wOm (i : Fin 4) (g : GB) :
    (g : Ghat) (wOm i) = binarySign (sgn i g) * (uOm i (aBit i g) (bBit i g) * wOm i) := by
  have hsq : ((g : Ghat) (wOm i)) ^ 2 = (uOm i (aBit i g) (bBit i g) * wOm i) ^ 2 := by
    have h := betaFun_map i (g : Ghat).toRingEquiv.toRingHom rootOmega (xOm i) (yOm i)
    change (g : Ghat) _ = betaFun i ((g : Ghat) rootOmega) ((g : Ghat) (xOm i)) ((g : Ghat) (yOm i)) at h
    rw [← map_pow, wOm_sq, betaOm_eq, h, act_root, act_xOm, act_yOm, sq_u, mul_pow, wOm_sq, betaOm_eq]
  classical
  unfold sgn
  split_ifs with h
  · rw [h, binarySign_zero, one_mul]
  · rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h' | h'
    · exact absurd h' h
    · rw [h', bs_one]
      ring

/-- **The D4 character** `G_B →* D4 i`. -/
def chiHom (i : Fin 4) : GB →* D4 i where
  toFun g := ⟨![aBit i g, bBit i g], sgn i g⟩
  map_one' := by
    apply GroupModel.ext
    · funext c
      fin_cases c <;> simp [aBit, bBit]
    · change sgn i 1 = 0
      have ha : aBit i 1 = 0 := by simp [aBit]
      have hb : bBit i 1 = 0 := by simp [bBit]
      simp [sgn, ha, hb, uOm]
  map_mul' g h := by
    apply GroupModel.ext
    · funext c
      fin_cases c <;> simp [aBit_mul, bBit_mul]
    · change sgn i (g * h) = sgn i g + sgn i h + bilD4 i ![aBit i g, bBit i g] ![aBit i h, bBit i h]
      rw [bilD4_apply]
      apply binarySign_injective (E := Omega)
      apply mul_right_cancel₀ (mul_ne_zero (uOm_ne_zero i (aBit i (g * h)) (bBit i (g * h)))
        (wOm_ne_zero i))
      rw [← act_wOm, Subgroup.coe_mul, AlgEquiv.mul_apply, act_wOm i h, map_mul, map_mul,
        act_uOm, act_wOm i g, aBit_mul, bBit_mul, binarySign_add, binarySign_add]
      have hb : ∀ e : F, (g : Ghat) (binarySign e) = binarySign e := by
        intro e
        simp [binarySign]
      rw [hb]
      have hc := cocycle i (aBit i g) (bBit i g) (aBit i h) (bBit i h)
      linear_combination (binarySign (sgn i h) * binarySign (sgn i g) * wOm i) * hc

theorem chiHom_apply (i : Fin 4) (g : GB) : chiHom i g = ⟨![aBit i g, bBit i g], sgn i g⟩ := rfl

/-- The finite field generated by `√a_i, √b_i, √β_i`; its fixing group lies in `ker chi`. -/
def chiField (i : Fin 4) : IntermediateField ℚ Omega :=
  IntermediateField.adjoin ℚ {xOm i, yOm i, wOm i}

instance chiField_finiteDimensional (i : Fin 4) : FiniteDimensional ℚ (chiField i) := by
  apply IntermediateField.finiteDimensional_adjoin
  intro x _
  exact (Algebra.IsAlgebraic.isAlgebraic (R := ℚ) x).isIntegral

theorem chi_eq_one_of_fix (i : Fin 4) (g : GB) (hx : (g : Ghat) (xOm i) = xOm i)
    (hy : (g : Ghat) (yOm i) = yOm i) (hw : (g : Ghat) (wOm i) = wOm i) : chiHom i g = 1 := by
  have ha : aBit i g = 0 := by
    apply binarySign_injective (E := Omega)
    apply mul_right_cancel₀ (xOm_ne_zero i)
    rw [← act_xOm, hx, binarySign_zero, one_mul]
  have hb : bBit i g = 0 := by
    apply binarySign_injective (E := Omega)
    apply mul_right_cancel₀ (yOm_ne_zero i)
    rw [← act_yOm, hy, binarySign_zero, one_mul]
  have hs : sgn i g = 0 := by
    simp [sgn, ha, hb, uOm, hw]
  apply GroupModel.ext
  · funext c
    fin_cases c <;> simp [chiHom_apply, ha, hb]
  · simp [chiHom_apply, hs]

theorem chiHom_continuous (i : Fin 4) : Continuous (chiHom i) := by
  apply continuous_of_le_ker (chiHom i) ((chiField i).fixingSubgroup.subgroupOf GB)
    (((chiField i).fixingSubgroup_isOpen).preimage continuous_subtype_val)
  intro g hg
  have hfix := (IntermediateField.mem_fixingSubgroup_iff _ _).1 (Subgroup.mem_subgroupOf.1 hg)
  rw [MonoidHom.mem_ker]
  apply chi_eq_one_of_fix
  · exact hfix _ (IntermediateField.subset_adjoin ℚ _ (by simp))
  · exact hfix _ (IntermediateField.subset_adjoin ℚ _ (by simp))
  · exact hfix _ (IntermediateField.subset_adjoin ℚ _ (by simp))

/-- The linear twist `ℓ(v) = ∑ v_k sgn(gen k)`. -/
def ell (i : Fin 4) : (Fin 8 → F) →ₗ[F] F where
  toFun v := ∑ k, v k * sgn i (gen k)
  map_add' v w := by simp [add_mul, Finset.sum_add_distrib]
  map_smul' r v := by simp [Finset.mul_sum, mul_assoc]

theorem ell_single (i : Fin 4) (a : Fin 8) : ell i (Pi.single a 1) = sgn i (gen a) := by
  rw [show ell i (Pi.single a 1) = ∑ k, (Pi.single a (1 : F) : Fin 8 → F) k * sgn i (gen k) from rfl]
  simp [Pi.single_apply]

theorem aBit_gen (i : Fin 4) (a : Fin 8) : aBit i (gen a) = phi1 i (Pi.single a 1) 0 := by
  simp only [aBit, gen_label, toAdd_ofAdd, phi1_apply_zero]

theorem bBit_gen (i : Fin 4) (a : Fin 8) : bBit i (gen a) = phi1 i (Pi.single a 1) 1 := by
  simp only [bBit, gen_label, toAdd_ofAdd, phi1_apply_one]

/-- **`chi` agrees with `Λ ∘ retainedFree` on the free source.** -/
theorem chi_freeMap (i : Fin 4) (s : Cut.Source) :
    chiHom i (freeMap s) = lambdaHom i (ell i) (Cut.retainedFree s) := by
  have h := (FiniteFreeProTwo.isFree 8).hom_ext (d4_hasPGroupOpenNormalBasis i)
    (f := (chiHom i).comp freeMap.toMonoidHom)
    (g := (lambdaHom i (ell i)).comp Cut.retainedFree.toMonoidHom)
    ((chiHom_continuous i).comp freeMap.continuous_toFun)
    ((continuous_of_discreteTopology (f := lambdaHom i (ell i))).comp
      Cut.retainedFree.continuous_toFun)
    (by
      intro a
      change chiHom i (freeMap (FiniteFreeProTwo.generator 8 a)) =
        lambdaHom i (ell i) (Cut.retainedFree (FiniteFreeProTwo.generator 8 a))
      rw [freeMap_generator, Cut.retainedFree_generator, lambdaHom_generator, chiHom_apply]
      apply GroupModel.ext
      · funext c
        fin_cases c
        · exact aBit_gen i a
        · exact bBit_gen i a
      · exact (ell_single i a).symm)
  exact congrArg (fun f : Cut.Source →* D4 i => f s) h

/-- **Every element of `core` fixes `√β_i`.** -/
theorem wOm_mem_M (I : Sqrt241.Retained.Input) (i : Fin 4) : wOm i ∈ I.M := by
  rw [I.mem_M_iff]
  intro σ hσ
  obtain ⟨hB, h1⟩ := (I.mem_retainedKer_iff σ).mp (I.core_le_retainedKer hσ)
  obtain ⟨s, hs⟩ := freeMap_surjective (⟨σ, hB⟩ : GB)
  have hfree : Cut.retainedFree s = 1 := by rw [← I.retainedMap_freeMap, hs, h1]
  have hchi : chiHom i ⟨σ, hB⟩ = 1 := by rw [← hs, chi_freeMap, hfree, map_one]
  have ha : aBit i ⟨σ, hB⟩ = 0 := congrFun (congrArg GroupModel.base hchi) 0
  have hb : bBit i ⟨σ, hB⟩ = 0 := congrFun (congrArg GroupModel.base hchi) 1
  have hs0 : sgn i ⟨σ, hB⟩ = 0 := congrArg GroupModel.central hchi
  have h := act_wOm i ⟨σ, hB⟩
  rw [ha, hb, hs0] at h
  simpa [uOm] using h

/-- **`E_W ≤ M`** (inside the closure). -/
theorem field_le_M (I : Sqrt241.Retained.Input) : CanonicalWide.field ≤ IntermediateField.lift I.M := by
  rw [CanonicalWide.field, IntermediateField.adjoin_le_iff]
  rintro x (rfl | (⟨k, rfl⟩ | ⟨i, rfl⟩))
  · exact (IntermediateField.mem_lift (⟨baseRoot, baseRoot_mem_Omega⟩ : Omega)).mpr
      (I.mem_M_of_mem_field baseRoot_mem)
  · exact (IntermediateField.mem_lift (⟨genusRoot k, genusRoot_mem_Omega k⟩ : Omega)).mpr
      (I.mem_M_of_mem_field (genusRoot_mem k))
  · exact (IntermediateField.mem_lift (wOm i)).mpr (wOm_mem_M I i)

/-- The algebra map `E_W → M`. -/
def wideToM (I : Sqrt241.Retained.Input) : CanonicalWide.Carrier →ₐ[ℚ] I.M where
  toFun x := ⟨⟨(x : Closure), IntermediateField.lift_le I.M (field_le_M I x.2)⟩, by
    obtain ⟨y, hy, hyx⟩ := field_le_M I x.2
    have : y = ⟨(x : Closure), IntermediateField.lift_le I.M (field_le_M I x.2)⟩ := Subtype.ext hyx
    rw [← this]
    exact hy⟩
  map_one' := rfl
  map_mul' _ _ := rfl
  map_zero' := rfl
  map_add' _ _ := rfl
  commutes' _ := rfl

@[simp] theorem coe_wideToM (I : Sqrt241.Retained.Input) (x : CanonicalWide.Carrier) :
    (((wideToM I x : I.M) : Omega) : Closure) = (x : Closure) := rfl

end UnitDistance.Sqrt241.Wide
'''
src = hdr + "".join(out) + mid
open(sys.argv[1], "w").write(src)
