#!/usr/bin/env python3
"""Generate UnitDistance/Sqrt241/Analytic/Numerics.lean (stream B).

Directed rational enclosures, at sigma = 1 + 1/300, of the Euler factors
a(q) = -log(1 - q^-sigma) and debit weights w(q) = log q/(q^2-1) that enter
the E -> M corrections of the analytic bridge:

  E side (lower bounds):  a(2^2), a(29^2), a(7^4), a(p^2) (census), w(2^2), w(29^2), w(7^4)
  M side (upper bounds):  a(2^4), a(29^4), a(7^8), a(p^4) (census), w(2^4), w(29^4), w(7^8)

The script only proposes rational candidates; every inequality is re-proved in
Lean by `norm_num` from the generic lemmas of `Analytic.NumericsBasic`.  It
also checks, in exact rational arithmetic, that the final combination exceeds
357/10000 = 852/10000 - 495/10000, and prints the slack.

    python3 scripts/sqrt241/generate_analytic_numerics.py
"""
from fractions import Fraction as F
from pathlib import Path
import math

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "UnitDistance/Sqrt241/Analytic/Numerics.lean"

LOG2 = (F(69314718055994530941, 10**20), F(69314718055994530942, 10**20))
CENSUS = [41, 47, 53, 59, 61, 67, 79, 83, 97]
LOGPRIMES = [7, 29] + CENSUS
EPS = F(1, 300)
TARGET = F(357, 10000)


def floor_to(q, d):
    return F((q.numerator * d) // q.denominator, d)


def ceil_to(q, d):
    return F(-((-q.numerator * d) // q.denominator), d)


def lit(q):
    q = F(q)
    if q.denominator == 1:
        return f"({q.numerator} : ℝ)"
    return f"({q.numerator} : ℝ) / {q.denominator}"


def log_ratio(r, n):
    x = (r - 1) / (r + 1)
    s = sum(x ** (2 * i + 1) / (2 * i + 1) for i in range(n))
    return 2 * s, 2 * (s + x ** (2 * n + 1) / (1 - x * x))


LOGDEN = 10**24
logs = {2: LOG2}
logproofs = {}
for p in LOGPRIMES:
    m = round(math.log2(p))
    if p >= 2**m:
        r, form = F(p, 2**m), "mul"
    else:
        r, form = F(2**m, p), "div"
    n = 1
    while True:
        lo, hi = log_ratio(r, n)
        if hi - lo < F(1, 10**22):
            break
        n += 1
    lor, hir = floor_to(lo, LOGDEN), ceil_to(hi, LOGDEN)
    if form == "mul":
        lp, hp = m * LOG2[0] + lor, m * LOG2[1] + hir
    else:
        lp, hp = m * LOG2[0] - hir, m * LOG2[1] - lor
    assert lp < F(math.log(p)) < hp or abs(float(lp) - math.log(p)) < 1e-12
    logs[p] = (lp, hp)
    logproofs[p] = (m, r, form, n, lor, hir)


def exp_lower(t):
    return 1 - t + t**2 / 2 - t**3 / 6 - 5 * t**4 / 96


def exp_upper(t):
    return 1 - t + t**2 / 2 - t**3 / 6 + 5 * t**4 / 96


YDEN = 10**30
VDEN = 10**25


def series(Y, N):
    return sum(Y ** (i + 1) / (i + 1) for i in range(N))


def a_lower(p, k):
    hi = logs[p][1]
    t = k * hi / 300
    assert 0 <= t <= 1
    Y = floor_to(exp_lower(t) / p**k, YDEN)
    N = 1
    while Y ** (N + 1) / (1 - Y) > F(1, 10**24):
        N += 1
    L = floor_to(series(Y, N), VDEN)
    return dict(p=p, k=k, hi=hi, Y=Y, N=N, L=L)


def a_upper(p, k):
    lo = logs[p][0]
    t = k * lo / 300
    assert 0 <= t <= 1
    Y = ceil_to(exp_upper(t) / p**k, YDEN)
    N = 1
    while Y ** (N + 1) / (1 - Y) > F(1, 10**24):
        N += 1
    U = ceil_to(series(Y, N) + Y ** (N + 1) / (1 - Y), VDEN)
    return dict(p=p, k=k, lo=lo, Y=Y, N=N, U=U)


def w_lower(p, k):
    return floor_to(k * logs[p][0] / (F(p) ** (2 * k) - 1), VDEN)


def w_upper(p, k):
    return ceil_to(k * logs[p][1] / (F(p) ** (2 * k) - 1), VDEN)


# E side: (p, k, divisor); M side: (p, k, divisor)
EA = [(2, 2, 8), (29, 2, 2), (7, 4, 4)] + [(p, 2, 2) for p in CENSUS]
MA = [(2, 4, 32), (29, 4, 4), (7, 8, 8)] + [(p, 4, 4) for p in CENSUS]
EW = [(2, 2, 8), (29, 2, 2), (7, 4, 4)]
MW = [(2, 4, 32), (29, 4, 4), (7, 8, 8)]

ea = {(p, k): a_lower(p, k) for p, k, _ in EA}
ma = {(p, k): a_upper(p, k) for p, k, _ in MA}
ew = {(p, k): w_lower(p, k) for p, k, _ in EW}
mw = {(p, k): w_upper(p, k) for p, k, _ in MW}

total = (sum(ea[(p, k)]["L"] / d for p, k, d in EA) - sum(ma[(p, k)]["U"] / d for p, k, d in MA)
         + EPS * (sum(ew[(p, k)] / d for p, k, d in EW) - sum(mw[(p, k)] / d for p, k, d in MW)))
zeta_only = sum(ea[(p, k)]["L"] / d for p, k, d in EA) - sum(ma[(p, k)]["U"] / d for p, k, d in MA)
print("certified correction lower bound:", float(total))
print("  of which log-zeta part:", float(zeta_only), " debit part x eps:", float(total - zeta_only))
print("slack over 357/10000:", float(total - TARGET))
assert total > TARGET

lines = []
w = lines.append
w("-- Generated by scripts/sqrt241/generate_analytic_numerics.py — do not edit by hand.")
w("module\n\npublic import UnitDistance.Sqrt241.Analytic.NumericsBasic\n\n@[expose] public section")
w("set_option backward.privateInPublic true\n\n")
w("/-!\n# Generated enclosures of the E → M corrections at `σ = 1 + 1/300`\n")
w("Generated by `scripts/sqrt241/generate_analytic_numerics.py`; do not edit.")
w("Every rational endpoint is re-proved by `norm_num` from the generic lemmas")
w("of `Analytic.NumericsBasic`.  The final theorem `corrections_ge` is the")
w("numerical input of the analytic bridge: the local corrections at")
w("2, 29, 7 and at the nine census primes exceed `357/10000`.")
w(f"Certified value of the combination: {float(total):.12f}; slack {float(total - TARGET):.3e}.\n-/\n")
# Every declaration below elaborates within the default `maxHeartbeats` and `maxRecDepth`.
w("noncomputable section\n")
w("namespace UnitDistance.Sqrt241.Analytic.Numerics\n")
w("open UnitDistance.NumberFieldAnalysis UnitDistance.Sqrt241.Analytic\n")

# log bounds
for p in LOGPRIMES:
    m, r, form, n, lor, hir = logproofs[p]
    lp, hp = logs[p]
    fn = "log_bounds_mul_two_pow" if form == "mul" else "log_bounds_div_two_pow"
    rel = f"(2 : ℝ) ^ {m} * {lit(r)}" if form == "mul" else f"(2 : ℝ) ^ {m} / ({lit(r)})"
    w(f"theorem log{p}_bounds :\n    {lit(lp)} ≤ Real.log ({p} : ℝ) ∧ Real.log ({p} : ℝ) ≤ {lit(hp)} := by")
    w(f"  have hr := UnitDistance.log_enclosure ({lit(r)}) {n} (by norm_num) ({lit(lor)}) ({lit(hir)})")
    w("    (by norm_num [Finset.sum_range_succ]) (by norm_num [Finset.sum_range_succ])")
    w(f"  have h := {fn} {p} {m} ({lit(r)}) (by norm_num) (by norm_num) log_two_bounds hr")
    w("  norm_num only [Nat.cast_ofNat] at h")
    w("  constructor <;> linarith [h.1, h.2]\n")


def logref(p, side):
    return f"log_nat{p}_bounds." + ("2" if side == "hi" else "1")


for p in [2] + LOGPRIMES:
    lp, hp = logs[p]
    src = "log_two_bounds" if p == 2 else f"log{p}_bounds"
    w(f"theorem log_nat{p}_bounds :\n    {lit(lp)} ≤ Real.log (({p} : ℕ) : ℝ) ∧ Real.log (({p} : ℕ) : ℝ) ≤ {lit(hp)} := by")
    w(f"  have h := {src}")
    w("  norm_num only [Nat.cast_ofNat] at h ⊢")
    w("  exact h\n")


for (p, k), d in ea.items():
    w(f"theorem a_lower_{p}_{k} : {lit(d['L'])} ≤ primeEulerLog ({p} ^ {k}) sigma :=")
    w(f"  primeEulerLog_pow_lower (p := {p}) (k := {k}) (hi := {lit(d['hi'])}) (Y := {lit(d['Y'])})")
    w(f"    (hp := by norm_num) (hk := by norm_num) (N := {d['N']}) (hlog := {logref(p, 'hi')})")
    w(f"    (h0 := by norm_num) (h1 := by norm_num) (hY0 := by norm_num)")
    w(f"    (hY := by norm_num [expNegLower]) (hL := by norm_num [Finset.sum_range_succ])\n")

for (p, k), d in ma.items():
    w(f"theorem a_upper_{p}_{k} : primeEulerLog ({p} ^ {k}) sigma ≤ {lit(d['U'])} :=")
    w(f"  primeEulerLog_pow_upper (p := {p}) (k := {k}) (lo := {lit(d['lo'])}) (Y := {lit(d['Y'])})")
    w(f"    (hp := by norm_num) (N := {d['N']}) (hlog := {logref(p, 'lo')})")
    w(f"    (h0 := by norm_num) (h1 := by norm_num) (hY1 := by norm_num)")
    w(f"    (hY := by norm_num [expNegUpper]) (hU := by norm_num [Finset.sum_range_succ])\n")

for (p, k), L in ew.items():
    lo = logs[p][0]
    w(f"theorem w_lower_{p}_{k} : {lit(L)} ≤ primeDebitWeight ((({p} ^ {k} : ℕ) : ℝ)) :=")
    w(f"  primeDebitWeight_pow_lower (p := {p}) (k := {k}) (lo := {lit(lo)}) (hp := by norm_num)")
    w(f"    (hk := by norm_num) (hlog := {logref(p, 'lo')}) (hL := by norm_num)\n")

for (p, k), U in mw.items():
    hi = logs[p][1]
    w(f"theorem w_upper_{p}_{k} : primeDebitWeight ((({p} ^ {k} : ℕ) : ℝ)) ≤ {lit(U)} :=")
    w(f"  primeDebitWeight_pow_upper (p := {p}) (k := {k}) (hi := {lit(hi)}) (hp := by norm_num)")
    w(f"    (hk := by norm_num) (hlog := {logref(p, 'hi')}) (hU := by norm_num)\n")

# final combination
terms = []
for p, k, d in EA:
    pass
zeta_terms = []
for (pe, ke, de), (pm, km, dm) in zip(EA, MA):
    assert pe == pm
    zeta_terms.append(f"(primeEulerLog ({pe} ^ {ke}) sigma / {de} - primeEulerLog ({pm} ^ {km}) sigma / {dm})")
debit_terms = []
for (pe, ke, de), (pm, km, dm) in zip(EW, MW):
    debit_terms.append(f"(primeDebitWeight ((({pe} ^ {ke} : ℕ) : ℝ)) / {de} - "
                       f"primeDebitWeight ((({pm} ^ {km} : ℕ) : ℝ)) / {dm})")
w("/-- The certified local corrections exceed `852/10000 - 495/10000`. -/")
w("theorem corrections_ge :\n    (357 : ℝ) / 10000 ≤")
w("      " + " +\n      ".join(zeta_terms) + " +")
w("      (1 / 300 : ℝ) * (" + " +\n        ".join(debit_terms) + ") := by")
hyps = ([f"a_lower_{p}_{k}" for p, k, _ in EA] + [f"a_upper_{p}_{k}" for p, k, _ in MA]
        + [f"w_lower_{p}_{k}" for p, k, _ in EW] + [f"w_upper_{p}_{k}" for p, k, _ in MW])
w("  linarith [" + ", ".join(hyps) + "]\n")
w("end UnitDistance.Sqrt241.Analytic.Numerics")
OUT.write_text("\n".join(lines) + "\n")
print("wrote", OUT)
