#!/usr/bin/env python3
"""Stream E (root discriminant): generate UnitDistance/Sqrt241/Discriminant/DyadicModel.lean.

Runs scripts/sqrt241/dyadic_certificate.gp (PARI/GP), which computes and checks
the dyadic certificate for the field F = Q(sqrt241, sqrt2, sqrt pi2', sqrt beta1):

* y  : a generator of the unique prime of F above p1 = (pi2) (e = 8, f = 1,
       different exponent 18), with norm 2;
* f  : the characteristic polynomial of y (monic, integer coefficients);
* f = X^8 G + 2 Kp with Kp(0) = 1, and f' = X^18 Z + f W with Z(0) odd;
* u  : the unit y^8 / pi2 and its characteristic polynomial h.

Usage (from lean-formalization/):
    python3 scripts/sqrt241/generate_dyadic_certificate.py
"""

import ast
import pathlib
import subprocess
from fractions import Fraction

ROOT = pathlib.Path(__file__).resolve().parents[2]
GP_SCRIPT = ROOT / "scripts" / "sqrt241" / "dyadic_certificate.gp"
OUT = ROOT / "UnitDistance" / "Sqrt241" / "Discriminant" / "DyadicModel.lean"


def run_gp():
    out = subprocess.run(["gp", "-q", str(GP_SCRIPT)], stdin=subprocess.DEVNULL,
                         capture_output=True, text=True, check=True).stdout
    data = {}
    for line in out.splitlines():
        if ":=" in line:
            key, value = line.split(":=", 1)
            data[key.strip()] = value.strip()
    return data


def wrap_list(items, indent="    "):
    lines = []
    cur = indent + "["
    for i, x in enumerate(items):
        piece = str(x) + (", " if i < len(items) - 1 else "]")
        if len(cur) + len(piece.rstrip()) > 100:
            lines.append(cur.rstrip())
            cur = indent + " " + piece
        else:
            cur += piece
    lines.append(cur)
    return "\n".join(lines)


def top_split(text):
    """Split ⟨A, B⟩ into (A, B) at the top-level comma."""
    assert text.startswith("⟨") and text.endswith("⟩")
    inner = text[1:-1]
    depth = 0
    for i, ch in enumerate(inner):
        if ch == "⟨":
            depth += 1
        elif ch == "⟩":
            depth -= 1
        elif ch == "," and depth == 0:
            return inner[:i].strip(), inner[i + 1:].strip()
    raise ValueError("no top-level comma")


def split_element(text):
    """Lay out an M4 literal ⟨⟨a, b⟩, ⟨c, d⟩⟩ (a, b, c, d in M2) on four lines."""
    lo, hi = top_split(text)
    a, b = top_split(lo)
    c, d = top_split(hi)
    return f"  ⟨⟨{a},\n    {b}⟩,\n   ⟨{c},\n    {d}⟩⟩"


def model_coords(text):
    """Read the rational coordinates of a nested quadratic-algebra literal."""
    if text.startswith("⟨"):
        lo, hi = top_split(text)
        return model_coords(lo) + model_coords(hi)
    return (Fraction(text.strip("()")),)


# Squares of r, t, g, s in the respective preceding algebras, in the same
# coordinate order as the GP certificate and the Lean model. These are only
# used to propose intermediate coordinates; Lean checks every multiplication.
MODEL_SQUARES = {
    2: (Fraction(241),),
    4: (Fraction(2), Fraction(0)),
    8: (Fraction(6101, 2), Fraction(-393, 2), Fraction(0), Fraction(0)),
    16: tuple(map(Fraction, (-25, 2, 0, 0, -139, -9, 0, 0))),
}


def model_mul(x, y):
    """Multiply rational coordinate vectors in the nested quadratic model."""
    assert len(x) == len(y)
    if len(x) == 1:
        return (x[0] * y[0],)
    n = len(x) // 2
    ac = model_mul(x[:n], y[:n])
    bdsq = model_mul(model_mul(x[n:], y[n:]), MODEL_SQUARES[len(x)])
    ad = model_mul(x[:n], y[n:])
    bc = model_mul(x[n:], y[:n])
    return tuple(a + b for a, b in zip(ac, bdsq)) + tuple(a + b for a, b in zip(ad, bc))


def model_literal(coords):
    """Format exact rational coordinates as a nested Lean constructor."""
    if len(coords) == 1:
        q = coords[0]
        return str(q.numerator) if q.denominator == 1 else f"({q.numerator}/{q.denominator})"
    n = len(coords) // 2
    return f"⟨{model_literal(coords[:n])}, {model_literal(coords[n:])}⟩"


TEMPLATE = """-- Generated by scripts/sqrt241/generate_dyadic_certificate.py — do not edit by hand.
module

public import UnitDistance.Sqrt241.Discriminant.Horner
public import Mathlib.Algebra.QuadraticAlgebra.Basic
public import Mathlib.Tactic.NormNum

@[expose] public section
set_option backward.privateInPublic true


/-!
# The dyadic certificate: an explicit model of `ℚ(√241, √2, √π₂', √β₁)`

`M4 = ℚ[r, t, g, s]` with `r² = 241`, `t² = 2`, `g² = π₂'(r) = (6101 - 393 r)/2` and
`s² = β₁ = (-25 + 2r) + (-139 - 9r) g`, as nested `QuadraticAlgebra`s over `ℚ`
(coordinates with respect to `r^a t^b g^c s^d`, index `a + 2b + 4c + 8d`).

In the number field `F = ℚ(r, t, g, s)` (degree 16) the prime above
`𝔭₁ = (π₂)`, `π₂ = (-6101 - 393 r)/2`, is unique, with `e = 8`, `f = 1` and
different exponent `18` (PARI). It is principal, generated by `y = yM`
(norm `2`). The data below are kernel-checked:

* `f_yM`: `f(y) = 0` for the monic integer polynomial `f = fL` (the characteristic
  polynomial of `y`);
* `u_yM`: `π₂ · u = y⁸` for the explicit unit `u = uM`, and `h_uM`: `h(u) = 0` for the
  monic integer polynomial `h = hL` (so `u` is integral and every prime containing `π₂`
  contains `y`);
* `f_split`: `f = X⁸ G + 2 Kp` with `Kp(0) = 1` (so `2 ∈ (y)⁸ ⋅ unit` at the prime `(y)`);
* `f_deriv`: `f' = X¹⁸ Z + f W` with `Z(0)` odd (so `v(f'(y)) = 18` at `(y)`).

Generated by `scripts/sqrt241/generate_dyadic_certificate.py` from
`scripts/sqrt241/dyadic_certificate.gp`.
-/

noncomputable section

namespace UnitDistance.Sqrt241.Discriminant.Dyadic

open UnitDistance.Sqrt241.Discriminant

/-- `ℚ(√241)`, generator `r`. -/
abbrev M1 := QuadraticAlgebra ℚ 241 0
/-- `ℚ(r, √2)`, generator `t`. -/
abbrev M2 := QuadraticAlgebra M1 2 0
/-- `π₂' = (6101 - 393 r)/2` in `M2`. -/
def pi2pM : M2 := ⟨⟨6101 / 2, -393 / 2⟩, 0⟩
/-- `ℚ(r, t, √π₂')`, generator `g`. -/
abbrev M3 := QuadraticAlgebra M2 pi2pM 0
/-- `β₁ = (-25 + 2r) + (-139 - 9r) g` in `M3`. -/
def beta1M : M3 := ⟨⟨⟨-25, 2⟩, 0⟩, ⟨⟨-139, -9⟩, 0⟩⟩
/-- `ℚ(r, t, g, √β₁)`, generator `s`. -/
abbrev M4 := QuadraticAlgebra M3 beta1M 0

/-- `π₂ = (-6101 - 393 r)/2` in the model. -/
def pi2M : M4 := ⟨⟨⟨⟨-6101 / 2, -393 / 2⟩, 0⟩, 0⟩, 0⟩

/-- The generator `y` of the prime above `𝔭₁`. -/
def yM : M4 :=
{yM}

/-- The unit `u = y⁸ / π₂`. -/
def uM : M4 :=
{uM}

/-- Characteristic polynomial of `y` (constant term first). -/
def fL : List ℤ :=
{fL}

/-- `fL` without its leading coefficient `1`. -/
def fL₀ : List ℤ := fL.dropLast

/-- Characteristic polynomial of `u` (constant term first). -/
def hL : List ℤ :=
{hL}

/-- `hL` without its leading coefficient `1`. -/
def hL₀ : List ℤ := hL.dropLast

/-- `f = X⁸ G + 2 Kp`. -/
def GhiL : List ℤ :=
{GL}

/-- `Kp = 1 + X Kp₁`. -/
def Kp₁L : List ℤ :=
{Kp1L}

/-- `f' = X¹⁸ Z + f W`. -/
def ZL : List ℤ :=
{ZL}

/-- The cofactor `W` in `f' = X¹⁸ Z + f W`. -/
def WL : List ℤ :=
{WL}

/-- `Z = Z₀ + X Z₁`. -/
def Z₀ : ℤ := {Z0}

/-- `Z = Z₀ + X Z₁`. -/
def Z₁L : List ℤ := ZL.tail

theorem fL_eq : fL = fL₀ ++ [1] := by decide

theorem hL_eq : hL = hL₀ ++ [1] := by decide

theorem ZL_eq : ZL = Z₀ :: Z₁L := by decide

theorem Z₀_odd : Odd Z₀ := by decide

set_option maxRecDepth 100000 in
/-- Kernel check: `f(y) = 0` in the model. -/
theorem f_yM : horner fL yM = 0 := by decide +kernel

/-- Exact intermediate coordinates for the bounded multiplication checks below. -/
{power_coordinates}

{power_checks}

set_option maxRecDepth 100000 in
private theorem pi2M_mul_uM : pi2M * uM = y8M := by decide +kernel

set_option maxRecDepth 100000 in
/-- Kernel check: `π₂ u = y⁸` in the model. -/
theorem u_yM : pi2M * uM = yM * yM * yM * yM * yM * yM * yM * yM := by
  have h3 := (congrArg (fun z : M4 => z * yM) yM_step2).trans yM_step3
  have h4 := (congrArg (fun z : M4 => z * yM) h3).trans yM_step4
  have h5 := (congrArg (fun z : M4 => z * yM) h4).trans yM_step5
  have h6 := (congrArg (fun z : M4 => z * yM) h5).trans yM_step6
  have h7 := (congrArg (fun z : M4 => z * yM) h6).trans yM_step7
  have h8 := (congrArg (fun z : M4 => z * yM) h7).trans yM_step8
  exact pi2M_mul_uM.trans h8.symm

set_option maxRecDepth 100000 in
/-- Kernel check: `h(u) = 0` in the model. -/
theorem h_uM : horner hL uM = 0 := by decide +kernel

/-- `f = X⁸ G + 2 (1 + X Kp₁)`, in any commutative ring. -/
theorem f_split {{R : Type*}} [CommRing R] (z : R) :
    horner fL z = z ^ 8 * horner GhiL z + 2 * (1 + z * horner Kp₁L z) := by
  simp only [fL, GhiL, Kp₁L, horner_cons, horner_nil]
  push_cast
  ring

/-- `f' = X¹⁸ Z + f W`, in any commutative ring. -/
theorem f_deriv {{R : Type*}} [CommRing R] (z : R) :
    hornerD fL z = z ^ 18 * horner ZL z + horner fL z * horner WL z := by
  simp only [fL, ZL, WL, horner_cons, horner_nil, hornerD_cons, hornerD_nil]
  push_cast
  ring

end UnitDistance.Sqrt241.Discriminant.Dyadic
"""


def main():
    d = run_gp()
    y = model_coords(d["yM"])
    assert len(y) == 16
    powers = {1: y}
    for exponent in range(2, 9):
        powers[exponent] = model_mul(powers[exponent - 1], y)
    pi2 = (Fraction(-6101, 2), Fraction(-393, 2)) + (Fraction(0),) * 14
    assert model_mul(pi2, model_coords(d["uM"])) == powers[8]
    power_coordinates = "\n\n".join(
        f"private def y{e}M : M4 :=\n" + split_element(model_literal(powers[e]))
        for e in range(2, 9))
    power_checks = "\n\n".join(
        "set_option maxRecDepth 100000 in\n"
        f"private theorem yM_step{e} : {'yM' if e == 2 else f'y{e - 1}M'} * yM = y{e}M "
        ":= by decide +kernel" for e in range(2, 9))
    kp = ast.literal_eval(d["KpL"])
    z = ast.literal_eval(d["ZL"])
    f = ast.literal_eval(d["fL"])
    h = ast.literal_eval(d["hL"])
    assert kp[0] == 1 and z[0] % 2 == 1 and f[-1] == 1 and h[-1] == 1 and f[0] == 2
    text = TEMPLATE.format(
        yM=split_element(d["yM"]),
        uM=split_element(d["uM"]),
        power_coordinates=power_coordinates,
        power_checks=power_checks,
        fL=wrap_list(f),
        hL=wrap_list(h),
        GL=wrap_list(ast.literal_eval(d["GL"])),
        Kp1L=wrap_list(kp[1:]),
        ZL=wrap_list(z),
        WL=wrap_list(ast.literal_eval(d["WL"])),
        Z0=z[0],
    )
    OUT.write_text(text)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
