#!/usr/bin/env python3
"""Parametrized finite-place certificate generator (port of generate-finite-certificates.py).

Produces untrusted rational candidates and Lean proofs for the finite-place
shell bounds of a witness JSON. Only kernel-checked Lean inequalities certify
the output. Decimal arithmetic chooses the candidate power bounds; it is never
a trusted evaluation. Unlike the original script this one takes the witness,
output directory and namespace as arguments, emits module-system headers, and
also writes the dispatcher module All.lean.

Default arguments generate the certificates of the tower over Q(sqrt 241):
    python3 scripts/sqrt241/generate_finite_certificates.py
"""
import argparse
from decimal import Decimal, localcontext, ROUND_CEILING
from fractions import Fraction as F
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("--witness", default="certificates/finite-witness-241.json")
parser.add_argument("--out", default="UnitDistance/Sqrt241/FiniteCertificates")
parser.add_argument("--witness-module", default="UnitDistance.Sqrt241.Witness")
parser.add_argument("--namespace", default="UnitDistance.Sqrt241.Witness",
                    help="namespace of the witness definitions; certificates go to <namespace>.FiniteCertificates")
parser.add_argument("--only", type=int, help="generate only the selected rational-prime module")
args = parser.parse_args()

data = json.loads((ROOT / args.witness).read_text())
OUT = ROOT / args.out
OUT.mkdir(parents=True, exist_ok=True)
MODPREFIX = args.out.replace("/", ".")
NS = args.namespace + ".FiniteCertificates"
N = len(data["primes"])
delta = F(data["delta"])
power = 2 / (1 + delta)
SCALE = 10**18
LOGSCALE = 10**20
LOGTWO = (F(69314718055994530941, LOGSCALE), F(69314718055994530942, LOGSCALE))
GENERATED = "-- Generated by scripts/sqrt241/generate_finite_certificates.py — do not edit by hand.\n"
HEAD = (GENERATED + "module\n\n{imports}\n@[expose] public section\n"
        "set_option backward.privateInPublic true\n{options}\n\n")
# The prime modules use `tac <;> tac'` uniformly; where the first tactic leaves a single
# goal the style linter would suggest `(tac; tac')`, which is not worth special-casing.
PRIME_OPTIONS = "set_option linter.unnecessarySeqFocus false\n"


def header(*mods, options=""):
    return HEAD.format(imports="".join(f"public import {m}\n" for m in mods), options=options)


def floor(q): return q.numerator // q.denominator
def ceil(q): return -floor(-q)


def literal(q, field="ℝ"):
    q = F(q)
    return f"({q.numerator} : {field}) / {q.denominator}"


def real(q): return literal(q)
def rational(q): return literal(q, "ℚ")
def vec(xs): return "![" + ", ".join(xs) + "]"
def dec(q): return Decimal(q.numerator) / Decimal(q.denominator)


def log_certificate(q, name):
    """Exact scaling, proved short rational log series, and monotonicity."""
    q = F(q)
    if q == 1:
        return f"theorem {name} : (0 : ℝ) ≤ Real.log 1 ∧ Real.log 1 ≤ 0 := by simp\n\n", (F(0), F(0))
    k = q.numerator.bit_length() - q.denominator.bit_length()
    while q < F(2)**k: k -= 1
    while F(2)**(k+1) <= q: k += 1
    r = q / F(2)**k
    low = F(floor(r*SCALE), SCALE)
    eps = F(1, SCALE)
    x = (low-1)/(low+1)
    n = 25
    s = sum((x**(2*i+1)/F(2*i+1) for i in range(n)), F(0))
    rem = x**(2*n+1)/(1-x*x)
    sl = F(floor(2*s*LOGSCALE), LOGSCALE)
    su = F(ceil(2*(s+rem)*LOGSCALE), LOGSCALE)
    lb = k*LOGTWO[0 if k >= 0 else 1] + sl
    ub = k*LOGTWO[1 if k >= 0 else 0] + su + eps/low
    bounds = (F(floor(lb*SCALE), SCALE), F(ceil(ub*SCALE), SCALE))
    # For an exact power of two (`low = 1`) the inner enclosure is `log 1 ∈ [0, 0]`, which
    # `norm_num` closes on its own.
    close = "norm_num at h ⊢" if low == 1 else "norm_num at h ⊢ <;> exact h"
    text = f'''theorem {name} :
    {real(bounds[0])} ≤ Real.log ({real(q)}) ∧
    Real.log ({real(q)}) ≤ {real(bounds[1])} := by
  have hb : {real(sl)} ≤ Real.log ({real(low)}) ∧
      Real.log ({real(low)}) ≤ {real(su)} := by
    have h := log_enclosure_of_rat
      ({rational(low)}) {n}
      ({rational(sl)})
      ({rational(su)})
      (by decide +kernel) (by decide +kernel) (by decide +kernel)
    {close}
  have hr := log_bounds_of_lower (x := {real(r)}) (l := {real(low)})
    (ε := {real(eps)}) (by norm_num) (by norm_num) (by norm_num) hb
  have hs := log_scale_two ({real(q)}) ({real(r)}) ({k}) (by norm_num) (by norm_num)
  have h2 := log_two_precise
  simp only [div_one] at h2
  rw [hs]
  norm_num at hr ⊢
  constructor <;> linarith [h2.1, h2.2]

'''
    return text, bounds


rows = []
with localcontext() as ctx:
    ctx.prec = 100
    for v, prime in enumerate(data["primes"]):
        q = prime**data["residue_degree"][v]
        k = data["period"][v]
        weights = list(map(F, data["weights"][v]))
        assert len(weights) == 6 and all(w > 0 for w in weights), "six positive shell weights required"
        upper = [F(1)]
        for w in weights[1:]:
            estimate = (dec(w).ln()*dec(power)).exp() * (Decimal(1)+Decimal("1e-13"))
            quantum = Decimal(1).scaleb(estimate.adjusted()-16)
            upper.append(F(estimate.quantize(quantum, rounding=ROUND_CEILING)))
        masses = [F(1)] + [F(q**i-q**(i-1)) for i in range(1, 6)]
        second = sum((masses[i]*weights[i]**2 for i in range(6)), F(0))
        transition = sum((weights[i]*weights[j]*(masses[min(i, j)] if i != j
            else (i*masses[i]-q**(i-1) if i else 0))
            for i in range(6) for j in range(6)), F(0))
        energy = (k+1)*second**2 + 2*second*transition
        lower_energy = F(floor(energy*SCALE), SCALE)
        upper_mass = F(ceil(sum((masses[i]*upper[i] for i in range(6)), F(0))*SCALE), SCALE)
        rows.append(dict(prime=prime, q=q, k=k, weights=weights, upper=upper,
                         energy=lower_energy, mass=upper_mass))

data_text = header("UnitDistance.RationalPowerBounds", args.witness_module) + f'''/-! Generated by scripts/sqrt241/generate_finite_certificates.py from
`{args.witness}`. Candidate values are untrusted until the explicit rational
inequalities of the prime modules compile in Lean. -/

noncomputable section
namespace {NS}

'''
for field, typ in [("upper", f"Fin {N} → Fin 6 → ℝ"), ("energy", f"Fin {N} → ℝ"), ("mass", f"Fin {N} → ℝ")]:
    name = {"upper": "powerUpper", "energy": "energyLower", "mass": "massUpper"}[field]
    terms = [vec([real(x) for x in row[field]]) if field == "upper" else real(row[field]) for row in rows]
    data_text += f"def {name} : {typ} :=\n  {vec(terms)}\n\n"
data_text += f"end {NS}\n"
if args.only is None:
    (OUT / "Data.lean").write_text(data_text)
    (OUT / "LogEnclosure.lean").write_text(header(f"{MODPREFIX}.Data") + f'''/-!
# Compact rational receipts for finite logarithm enclosures

Copy of `UnitDistance.FiniteCertificates.LogEnclosureCompactRun20260920` in the
certificate namespace of this witness: the finite premises are stated over `ℚ`,
proved by kernel reduction, and cast once into `ℝ`.
-/

noncomputable section
set_option autoImplicit false

namespace {NS}

theorem log_enclosure_of_rat (q : ℚ) (n : ℕ) (lo hi : ℚ)
    (hq : 1 ≤ q)
    (hl : lo ≤ 2 * ∑ i ∈ Finset.range n,
      ((q - 1) / (q + 1)) ^ (2 * i + 1) / (2 * i + 1))
    (hu : 2 * ((∑ i ∈ Finset.range n,
      ((q - 1) / (q + 1)) ^ (2 * i + 1) / (2 * i + 1)) +
      ((q - 1) / (q + 1)) ^ (2 * n + 1) /
        (1 - ((q - 1) / (q + 1)) ^ 2)) ≤ hi) :
    (lo : ℝ) ≤ Real.log (q : ℝ) ∧ Real.log (q : ℝ) ≤ (hi : ℝ) := by
  apply UnitDistance.log_enclosure (q : ℝ) n
  · exact_mod_cast hq
  · exact_mod_cast hl
  · exact_mod_cast hu

end {NS}
''')

summary = []
for v, row in enumerate(rows):
    text = header(f"{MODPREFIX}.LogEnclosure", options=PRIME_OPTIONS) + f"namespace {NS}\n\n"
    for i, (w, u) in enumerate(zip(row["weights"], row["upper"])):
        if i:
            tw, bw = log_certificate(w, f"weight_log_{v}_{i}")
            tu, bu = log_certificate(u, f"power_upper_log_{v}_{i}")
            assert power*bw[1] <= bu[0], (v, i, "insufficient power enclosure")
            text += tw + tu
            text += f'''theorem power_bound_{v}_{i} :
    (shellWeights ⟨{v}, by decide⟩ ⟨{i}, by decide⟩ : ℝ)^p ≤ powerUpper ⟨{v}, by decide⟩ ⟨{i}, by decide⟩ := by
  have h := rpow_le_of_log_bounds (p := p) (by norm_num : 0 < {real(w)})
    (by norm_num : 0 < {real(u)}) witness_basic.2.2.1.le
    weight_log_{v}_{i}.2 power_upper_log_{v}_{i}.1 (by norm_num [p, increment])
  norm_num [shellWeights, powerUpper, Matrix.cons_val] at h ⊢
  exact h

'''
        else:
            text += f'''theorem power_bound_{v}_0 :
    (shellWeights ⟨{v}, by decide⟩ ⟨0, by decide⟩ : ℝ)^p ≤ powerUpper ⟨{v}, by decide⟩ ⟨0, by decide⟩ := by
  norm_num [shellWeights, powerUpper, Matrix.cons_val]

'''
    info = {}
    for name, value in [("residue_log", row["q"]), ("energy_log", row["energy"]), ("mass_log", row["mass"])]:
        cert, bound = log_certificate(value, f"{name}_{v}")
        text += cert
        info[name] = bound
    lower = -delta*row["k"]*info["residue_log"][1] + info["energy_log"][0] - 2*(1+delta)*info["mass_log"][1]
    row.update(info)
    summary.append(dict(index=v, prime=row["prime"], lower=str(lower), lower_float=float(lower),
                        residue_upper=str(info["residue_log"][1]),
                        energy_lower=str(info["energy_log"][0]), mass_upper=str(info["mass_log"][1])))
    text += f"end {NS}\n"
    if args.only is None or args.only == row["prime"]:
        (OUT / f"Prime{row['prime']}.lean").write_text(text)

if args.only is None:
    mods = [f"{MODPREFIX}.Prime{row['prime']}" for row in rows]
    all_text = header(*mods) + f'''/-! # Assembly of the individually proved finite-place enclosures

Generated by scripts/sqrt241/generate_finite_certificates.py. The tables are
untrusted rational candidates; the theorems connect them to the witness and to
the proved inequalities of the prime modules.
-/
noncomputable section
namespace {NS}

def residueLogUpper : Fin {N} → ℝ :=
  {vec([real(row["residue_log"][1]) for row in rows])}

def energyLogLower : Fin {N} → ℝ :=
  {vec([real(row["energy_log"][0]) for row in rows])}

def massLogUpper : Fin {N} → ℝ :=
  {vec([real(row["mass_log"][1]) for row in rows])}

theorem power_bounds (v : Fin {N}) (i : Fin 6) :
    (shellWeights v i : ℝ) ^ p ≤ powerUpper v i := by
  fin_cases v <;> fin_cases i
'''
    for v in range(N):
        for i in range(6):
            all_text += f"  · exact power_bound_{v}_{i}\n"
    for thm, lhs_rhs, sel, unf in [
        ("residue_log_upper", "Real.log (residueCard v) ≤ residueLogUpper v", "residue_log_{v}.2",
         "residueLogUpper, residueCard, primes, residueDegree, Matrix.cons_val"),
        ("energy_log_lower", "energyLogLower v ≤ Real.log (energyLower v)", "energy_log_{v}.1",
         "energyLogLower, energyLower, Matrix.cons_val"),
        ("mass_log_upper", "Real.log (massUpper v) ≤ massLogUpper v", "mass_log_{v}.2",
         "massLogUpper, massUpper, Matrix.cons_val")]:
        all_text += f"\ntheorem {thm} (v : Fin {N}) : {lhs_rhs} := by\n  fin_cases v\n"
        for v in range(N):
            all_text += f"  · have h := {sel.format(v=v)}\n    norm_num [{unf}] at h ⊢\n    exact h\n"
    all_text += f"\nend {NS}\n"
    (OUT / "All.lean").write_text(all_text)

(ROOT / ".cache").mkdir(exist_ok=True)
(ROOT / ".cache/finite-certificate-summary-241.json").write_text(json.dumps(summary, indent=2)+"\n")
tot = sum(F(s["lower"]) / (data["ramification"][s["index"]]*data["residue_degree"][s["index"]]) for s in summary)
print(f"Generated {len(summary)} prime modules; candidate finite-profit lower bound {float(tot):.12f} = {tot}")
