module

public import UnitDistance.Sqrt241.Wide.Census

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false

/-!
# The census places of `WideLocalTypes`

Generated by `scripts/sqrt241/generate_wide_census.py` — do not edit by hand.

For each prime of `Analytic.wideCensusOne` (`wideCensusTwo`), the root(s) `a` of
`X² - X - 60` mod `p` whose place has `fW = 2`, with the Legendre label `v` of the radicands;
all hypotheses of `censusOne_of_place` / `censusTwo_of_places` are checked by `decide`.
-/

noncomputable section

namespace UnitDistance.Sqrt241.Wide

open NumberField UnitDistance.Sqrt241.Analytic CanonicalWide

set_option maxRecDepth 100000

/-- **Census, one place.** -/
theorem wide_censusOne (p : Nat.Primes) (hp : p.val ∈ wideCensusOne) :
    ContribLowerBound CanonicalWide.Carrier p [(1 / 4, 2)] := by
  obtain ⟨n, hn⟩ := p
  simp only [wideCensusOne, Finset.mem_insert, Finset.mem_singleton] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact censusOne_of_place ⟨47, by norm_num⟩ (by decide) (by decide) 29 (by decide) ![1, 0, 0, 0, 1, 0, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨59, by norm_num⟩ (by decide) (by decide) 34 (by decide) ![1, 0, 0, 1, 0, 1, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨61, by norm_num⟩ (by decide) (by decide) 48 (by decide) ![0, 1, 1, 0, 1, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨67, by norm_num⟩ (by decide) (by decide) 22 (by decide) ![1, 0, 0, 1, 1, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨83, by norm_num⟩ (by decide) (by decide) 51 (by decide) ![1, 1, 0, 1, 0, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨97, by norm_num⟩ (by decide) (by decide) 55 (by decide) ![0, 0, 0, 0, 1, 1, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨113, by norm_num⟩ (by decide) (by decide) 79 (by decide) ![0, 1, 0, 0, 0, 1, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨181, by norm_num⟩ (by decide) (by decide) 77 (by decide) ![0, 1, 1, 0, 0, 0, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨223, by norm_num⟩ (by decide) (by decide) 23 (by decide) ![1, 0, 1, 1, 0, 0, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨229, by norm_num⟩ (by decide) (by decide) 186 (by decide) ![0, 0, 0, 1, 1, 1, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨257, by norm_num⟩ (by decide) (by decide) 97 (by decide) ![0, 0, 1, 1, 0, 1, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨277, by norm_num⟩ (by decide) (by decide) 42 (by decide) ![0, 0, 0, 1, 1, 1, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨281, by norm_num⟩ (by decide) (by decide) 214 (by decide) ![0, 1, 1, 1, 0, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨331, by norm_num⟩ (by decide) (by decide) 64 (by decide) ![1, 0, 1, 0, 1, 1, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨337, by norm_num⟩ (by decide) (by decide) 285 (by decide) ![0, 1, 1, 1, 0, 0, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨347, by norm_num⟩ (by decide) (by decide) 203 (by decide) ![1, 1, 0, 1, 1, 0, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨401, by norm_num⟩ (by decide) (by decide) 220 (by decide) ![0, 1, 0, 0, 0, 1, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨457, by norm_num⟩ (by decide) (by decide) 129 (by decide) ![0, 0, 1, 1, 1, 1, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨487, by norm_num⟩ (by decide) (by decide) 210 (by decide) ![1, 1, 0, 0, 0, 0, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨509, by norm_num⟩ (by decide) (by decide) 353 (by decide) ![0, 1, 0, 1, 0, 1, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨523, by norm_num⟩ (by decide) (by decide) 126 (by decide) ![1, 0, 0, 1, 0, 0, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨541, by norm_num⟩ (by decide) (by decide) 484 (by decide) ![0, 1, 1, 0, 1, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨563, by norm_num⟩ (by decide) (by decide) 117 (by decide) ![1, 1, 0, 1, 1, 0, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨607, by norm_num⟩ (by decide) (by decide) 387 (by decide) ![1, 0, 0, 0, 1, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨617, by norm_num⟩ (by decide) (by decide) 374 (by decide) ![0, 0, 1, 1, 0, 1, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨673, by norm_num⟩ (by decide) (by decide) 38 (by decide) ![0, 1, 1, 1, 1, 1, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨683, by norm_num⟩ (by decide) (by decide) 254 (by decide) ![1, 0, 1, 0, 1, 0, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨691, by norm_num⟩ (by decide) (by decide) 442 (by decide) ![1, 0, 1, 0, 1, 1, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨719, by norm_num⟩ (by decide) (by decide) 255 (by decide) ![1, 1, 1, 1, 0, 1, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨733, by norm_num⟩ (by decide) (by decide) 420 (by decide) ![0, 1, 0, 1, 0, 0, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨739, by norm_num⟩ (by decide) (by decide) 189 (by decide) ![1, 0, 1, 0, 0, 0, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨773, by norm_num⟩ (by decide) (by decide) 558 (by decide) ![0, 1, 1, 0, 1, 0, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨787, by norm_num⟩ (by decide) (by decide) 619 (by decide) ![1, 1, 1, 0, 0, 0, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨821, by norm_num⟩ (by decide) (by decide) 437 (by decide) ![0, 1, 0, 1, 0, 1, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨823, by norm_num⟩ (by decide) (by decide) 445 (by decide) ![1, 0, 1, 1, 0, 0, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨857, by norm_num⟩ (by decide) (by decide) 556 (by decide) ![0, 1, 0, 0, 0, 1, 1, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨877, by norm_num⟩ (by decide) (by decide) 325 (by decide) ![0, 1, 0, 1, 1, 1, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨881, by norm_num⟩ (by decide) (by decide) 383 (by decide) ![0, 1, 1, 1, 0, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨883, by norm_num⟩ (by decide) (by decide) 665 (by decide) ![1, 1, 1, 0, 0, 0, 1, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨887, by norm_num⟩ (by decide) (by decide) 95 (by decide) ![1, 1, 1, 1, 1, 0, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨937, by norm_num⟩ (by decide) (by decide) 291 (by decide) ![0, 1, 1, 1, 0, 0, 0, 1]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)
  · exact censusOne_of_place ⟨967, by norm_num⟩ (by decide) (by decide) 797 (by decide) ![1, 0, 1, 1, 1, 1, 0, 0]
      (by decide +kernel) (by decide +kernel) (by decide +kernel) (by decide)
      (by decide +kernel)

/-- **Census, both places.** -/
theorem wide_censusTwo (p : Nat.Primes) (hp : p.val ∈ wideCensusTwo) :
    ContribLowerBound CanonicalWide.Carrier p [(1 / 2, 2)] := by
  obtain ⟨n, hn⟩ := p
  simp only [wideCensusTwo, Finset.mem_insert, Finset.mem_singleton] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact censusTwo_of_places ⟨151, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 56 (by decide) ![1, 1, 1, 1, 1, 1, 1, 0] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 96 (by decide) ![1, 0, 0, 0, 1, 1, 0, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)
  · exact censusTwo_of_places ⟨191, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 49 (by decide) ![1, 1, 0, 0, 1, 0, 0, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 143 (by decide) ![1, 0, 1, 1, 0, 1, 1, 0] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)
  · exact censusTwo_of_places ⟨233, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 32 (by decide) ![0, 1, 0, 0, 1, 0, 1, 0] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 202 (by decide) ![0, 1, 0, 0, 0, 1, 0, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)
  · exact censusTwo_of_places ⟨421, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 72 (by decide) ![0, 0, 0, 1, 0, 0, 1, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 350 (by decide) ![0, 0, 1, 0, 0, 0, 1, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)
  · exact censusTwo_of_places ⟨569, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 102 (by decide) ![0, 1, 1, 1, 1, 0, 1, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 468 (by decide) ![0, 1, 1, 1, 0, 1, 1, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)
  · exact censusTwo_of_places ⟨743, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 150 (by decide) ![1, 0, 0, 0, 0, 1, 1, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 594 (by decide) ![1, 1, 1, 1, 1, 0, 1, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)
  · exact censusTwo_of_places ⟨839, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 225 (by decide) ![1, 1, 0, 0, 1, 0, 0, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 615 (by decide) ![1, 0, 1, 1, 0, 1, 1, 0] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)
  · exact censusTwo_of_places ⟨991, by norm_num⟩ (by decide) (by decide) (by decide +kernel)
      (by decide) 78 (by decide) ![1, 1, 1, 1, 1, 1, 1, 0] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) 914 (by decide) ![1, 0, 0, 0, 1, 1, 0, 1] (by decide +kernel) (by decide +kernel)
      (by decide +kernel) (by decide)

end UnitDistance.Sqrt241.Wide
