module

public import UnitDistance.Sqrt241.Wide.Basic
public import UnitDistance.Sqrt241.Wide.Kummer

@[expose] public section
set_option backward.privateInPublic true

set_option autoImplicit false
set_option linter.unusedSimpArgs false

/-!
# The four D4 radicands of `E_W` have square roots in `Ω`

Generated by `scripts/sqrt241/generate_wide_omega.py` — do not edit by hand.

For each form, `β_i = wideRadicand i` is an algebraic integer of the genus field `genusB`
(`betaO_i`), an `S`-unit (`β_i · cofO_i = m_i` with `m_i = ±2^a 3^b`), and every
`B`-automorphism `σ` of the closure satisfies `σ(β_i) = u² β_i` with `u ∈ genusB`
(`Wide/Identities.lean`). By `squareRoot_mem_OmegaBcl`, `√β_i ∈ Ω`; hence `E_W ≤ Ω`.
-/

open scoped NumberField
open NumberField

noncomputable section
set_option backward.isDefEq.respectTransparency false

namespace UnitDistance.Sqrt241.Wide

open Tower Base CanonicalGenus CanonicalWide IntermediateField

theorem sigma_baseRoot_B (σ : Closure ≃ₐ[B] Closure) : σ baseRoot = baseRoot := by
  have h := σ.commutes sqrt241
  rwa [IntermediateField.algebraMap_apply, coe_sqrt241] at h

/-- A prime ideal of `ℤ` containing `2^a 3^b` contains `30`. -/
theorem thirty_mem_of_two_three (P : Ideal ℤ) [hP : P.IsPrime] (a b : ℕ)
    (h : (2 : ℤ) ^ a * 3 ^ b ∈ P) : (30 : ℤ) ∈ P := by
  rcases hP.mem_or_mem h with h2 | h3
  · have := hP.mem_of_pow_mem a h2
    have h30 : (30 : ℤ) = 15 * 2 := by norm_num
    rw [h30]
    exact P.mul_mem_left 15 this
  · have := hP.mem_of_pow_mem b h3
    have h30 : (30 : ℤ) = 10 * 3 := by norm_num
    rw [h30]
    exact P.mul_mem_left 10 this

/-! ### Integral generators of the genus field -/

/-- `√α_k` as an algebraic integer of `genusB`. -/
def gO (k : Fin 8) : 𝓞 genusB :=
  ⟨⟨genusRoot k, genusRoot_mem_genusB k⟩, by
    apply IsIntegral.of_pow (n := 2) (by norm_num)
    have h : (⟨genusRoot k, genusRoot_mem_genusB k⟩ : genusB) ^ 2 =
        algebraMap B genusB ((alpha k : 𝓞 B) : B) := by
      apply Subtype.ext
      change genusRoot k ^ 2 = _
      rw [genusRoot_sq_alpha]
      rfl
    rw [h]
    exact ((alpha k).2).map (IsScalarTower.toAlgHom ℤ B genusB)⟩

/-- `√241` as an algebraic integer of `genusB`. -/
def sO : 𝓞 genusB := algebraMap (𝓞 B) (𝓞 genusB) sqrt241Int

/-- The coercion `𝓞 genusB → Closure` as a ring homomorphism. -/
def oHom : 𝓞 genusB →+* Closure :=
  (IntermediateField.val genusB).toRingHom.comp (algebraMap (𝓞 genusB) genusB)

theorem oHom_apply (x : 𝓞 genusB) : oHom x = ((x : genusB) : Closure) := rfl

theorem oHom_injective : Function.Injective oHom :=
  Subtype.val_injective.comp RingOfIntegers.coe_injective

@[simp] theorem oHom_gO (k : Fin 8) : oHom (gO k) = genusRoot k := rfl

theorem oHom_algebraMap (b : 𝓞 B) :
    oHom (algebraMap (𝓞 B) (𝓞 genusB) b) = (((b : 𝓞 B) : B) : Closure) := rfl

@[simp] theorem oHom_sO : oHom sO = baseRoot := by
  rw [sO, oHom_algebraMap, coe_sqrt241Int, coe_sqrt241]

theorem oHom_algebraMap_mk (m n : ℤ) :
    oHom (algebraMap (𝓞 B) (𝓞 genusB) (mk m n)) = (m : Closure) + (n : Closure) * ((1 + baseRoot) / 2) := by
  unfold Base.mk
  rw [map_add, map_mul, map_intCast, map_intCast, map_add, map_mul, map_intCast, map_intCast,
    oHom_algebraMap, coe_omega]
  have h2 : (((2 : B)) : Closure) = 2 := rfl
  simp [coe_sqrt241, h2]

/-- `√a_i` as an algebraic integer of `genusB`. -/
def rootAO : Fin 4 → 𝓞 genusB :=
  ![gO 1 * gO 3 * gO 4 * gO 5 * gO 6 * gO 7,
    gO 1 * gO 4 * gO 5,
    gO 1 * gO 5 * gO 6,
    gO 4 * gO 6]

/-- `√b_i` as an algebraic integer of `genusB`. -/
def rootBO : Fin 4 → 𝓞 genusB :=
  ![gO 0 * gO 3 * gO 4,
    gO 0 * gO 3 * gO 7,
    gO 0 * gO 4,
    gO 0 * gO 1 * gO 5]

theorem oHom_rootAO (i : Fin 4) : oHom (rootAO i) = rootA i := by
  fin_cases i <;> simp [rootAO, rootA, map_mul]

theorem oHom_rootBO (i : Fin 4) : oHom (rootBO i) = rootB i := by
  fin_cases i <;> simp [rootBO, rootB, map_mul]

/-! ### Form 24 (index 0) -/

theorem rootA_mem_genusB_0 : rootA 0 ∈ genusB := by
  simp only [rootA, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem rootB_mem_genusB_0 : rootB 0 ∈ genusB := by
  simp only [rootB, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem sigma_rootA_0 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootA 0) = rootA 0 ∨ σ (rootA 0) = -rootA 0 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootA_sq_0]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

theorem sigma_rootB_0 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootB 0) = rootB 0 ∨ σ (rootB 0) = -rootB 0 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootB_sq_0]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

/-- `β_24` as an algebraic integer of the genus field. -/
def betaO_0 : 𝓞 genusB := beta24 sO (rootAO 0) (rootBO 0)

theorem oHom_betaO_0 : oHom betaO_0 = wideRadicand 0 := by
  rw [betaO_0, beta24_map, oHom_sO, oHom_rootAO, oHom_rootBO, wideRadicand_0]

/-- The cofactor of the norm of `β_24`. -/
def cofO_0 : 𝓞 genusB :=
  normConj24 sO (rootAO 0) (rootBO 0) *
    algebraMap (𝓞 B) (𝓞 genusB) (mk normBarMk24.1 normBarMk24.2)

theorem betaO_mul_cofO_0 : betaO_0 * cofO_0 = ((660451885056 : ℤ) : 𝓞 genusB) := by
  apply oHom_injective
  rw [map_mul, oHom_betaO_0, cofO_0, map_mul, normConj24_map, oHom_sO, oHom_rootAO, oHom_rootBO,
    oHom_algebraMap_mk, map_intCast, wideRadicand_0]
  have h := beta24_mul_normCofactor baseRoot (rootA 0) (rootB 0) baseRoot_sq rootA_sq_0 rootB_sq_0
  rw [normCofactor24, ← normBar24_eq] at h
  simp only [normBarMk24] at h ⊢
  exact_mod_cast h

theorem hm30_0 : ∀ P : Ideal ℤ, P.IsPrime → (660451885056 : ℤ) ∈ P → (30 : ℤ) ∈ P := by
  intro P hP hM
  apply thirty_mem_of_two_three P 25 9
  have he : (660451885056 : ℤ) = (2 ^ 25 * 3 ^ 9) := by norm_num
  rw [he] at hM
  exact hM

theorem hconj_0 (σ : Closure ≃ₐ[B] Closure) :
    ∃ u ∈ genusB, σ ((betaO_0 : genusB) : Closure) = u ^ 2 * ((betaO_0 : genusB) : Closure) := by
  have hb : ((betaO_0 : genusB) : Closure) = beta24 baseRoot (rootA 0) (rootB 0) := by
    rw [← wideRadicand_0, ← oHom_betaO_0]
    rfl
  rw [hb, show σ (beta24 baseRoot (rootA 0) (rootB 0)) =
      beta24 (σ baseRoot) (σ (rootA 0)) (σ (rootB 0)) from beta24_map σ.toRingHom _ _ _,
    sigma_baseRoot_B σ]
  have hs := baseRoot_mem_genusB
  have ha := rootA_mem_genusB_0
  have hb' := rootB_mem_genusB_0
  rcases sigma_rootA_0 σ with hx | hx <;> rcases sigma_rootB_0 σ with hy | hy <;> rw [hx, hy]
  · exact ⟨1, one_mem _, by ring⟩
  · refine ⟨u24_01 baseRoot (rootA 0) (rootB 0), ?_,
      beta24_sigma_01 _ _ _ baseRoot_sq rootA_sq_0 rootB_sq_0⟩
    have hmem : genusB.val (u24_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u24_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u24_01 baseRoot (rootA 0) (rootB 0) from u24_01_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u24_10 baseRoot (rootA 0) (rootB 0), ?_,
      beta24_sigma_10 _ _ _ baseRoot_sq rootA_sq_0 rootB_sq_0⟩
    have hmem : genusB.val (u24_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u24_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u24_10 baseRoot (rootA 0) (rootB 0) from u24_10_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u24_11 baseRoot (rootA 0) (rootB 0), ?_,
      beta24_sigma_11 _ _ _ baseRoot_sq rootA_sq_0 rootB_sq_0⟩
    have hmem : genusB.val (u24_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u24_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u24_11 baseRoot (rootA 0) (rootB 0) from u24_11_map genusB.val.toRingHom _ _ _] at hmem

/-- **`√β_24 ∈ Ω`.** -/
theorem wideRoot_mem_OmegaBcl_0 : wideRoot 0 ∈ OmegaBcl := by
  have h := squareRoot_mem_OmegaBcl genusB admissible_genusB betaO_0 cofO_0 (660451885056)
    betaO_mul_cofO_0 hm30_0 hconj_0
  have hb : ((betaO_0 : genusB) : Closure) = wideRadicand 0 := oHom_betaO_0
  rwa [hb] at h

/-! ### Form 20 (index 1) -/

theorem rootA_mem_genusB_1 : rootA 1 ∈ genusB := by
  simp only [rootA, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem rootB_mem_genusB_1 : rootB 1 ∈ genusB := by
  simp only [rootB, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem sigma_rootA_1 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootA 1) = rootA 1 ∨ σ (rootA 1) = -rootA 1 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootA_sq_1]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

theorem sigma_rootB_1 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootB 1) = rootB 1 ∨ σ (rootB 1) = -rootB 1 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootB_sq_1]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

/-- `β_20` as an algebraic integer of the genus field. -/
def betaO_1 : 𝓞 genusB := beta20 sO (rootAO 1) (rootBO 1)

theorem oHom_betaO_1 : oHom betaO_1 = wideRadicand 1 := by
  rw [betaO_1, beta20_map, oHom_sO, oHom_rootAO, oHom_rootBO, wideRadicand_1]

/-- The cofactor of the norm of `β_20`. -/
def cofO_1 : 𝓞 genusB :=
  normConj20 sO (rootAO 1) (rootBO 1) *
    algebraMap (𝓞 B) (𝓞 genusB) (mk normBarMk20.1 normBarMk20.2)

theorem betaO_mul_cofO_1 : betaO_1 * cofO_1 = ((68719476736 : ℤ) : 𝓞 genusB) := by
  apply oHom_injective
  rw [map_mul, oHom_betaO_1, cofO_1, map_mul, normConj20_map, oHom_sO, oHom_rootAO, oHom_rootBO,
    oHom_algebraMap_mk, map_intCast, wideRadicand_1]
  have h := beta20_mul_normCofactor baseRoot (rootA 1) (rootB 1) baseRoot_sq rootA_sq_1 rootB_sq_1
  rw [normCofactor20, ← normBar20_eq] at h
  simp only [normBarMk20] at h ⊢
  exact_mod_cast h

theorem hm30_1 : ∀ P : Ideal ℤ, P.IsPrime → (68719476736 : ℤ) ∈ P → (30 : ℤ) ∈ P := by
  intro P hP hM
  apply thirty_mem_of_two_three P 36 0
  have he : (68719476736 : ℤ) = (2 ^ 36 * 3 ^ 0) := by norm_num
  rw [he] at hM
  exact hM

theorem hconj_1 (σ : Closure ≃ₐ[B] Closure) :
    ∃ u ∈ genusB, σ ((betaO_1 : genusB) : Closure) = u ^ 2 * ((betaO_1 : genusB) : Closure) := by
  have hb : ((betaO_1 : genusB) : Closure) = beta20 baseRoot (rootA 1) (rootB 1) := by
    rw [← wideRadicand_1, ← oHom_betaO_1]
    rfl
  rw [hb, show σ (beta20 baseRoot (rootA 1) (rootB 1)) =
      beta20 (σ baseRoot) (σ (rootA 1)) (σ (rootB 1)) from beta20_map σ.toRingHom _ _ _,
    sigma_baseRoot_B σ]
  have hs := baseRoot_mem_genusB
  have ha := rootA_mem_genusB_1
  have hb' := rootB_mem_genusB_1
  rcases sigma_rootA_1 σ with hx | hx <;> rcases sigma_rootB_1 σ with hy | hy <;> rw [hx, hy]
  · exact ⟨1, one_mem _, by ring⟩
  · refine ⟨u20_01 baseRoot (rootA 1) (rootB 1), ?_,
      beta20_sigma_01 _ _ _ baseRoot_sq rootA_sq_1 rootB_sq_1⟩
    have hmem : genusB.val (u20_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u20_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u20_01 baseRoot (rootA 1) (rootB 1) from u20_01_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u20_10 baseRoot (rootA 1) (rootB 1), ?_,
      beta20_sigma_10 _ _ _ baseRoot_sq rootA_sq_1 rootB_sq_1⟩
    have hmem : genusB.val (u20_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u20_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u20_10 baseRoot (rootA 1) (rootB 1) from u20_10_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u20_11 baseRoot (rootA 1) (rootB 1), ?_,
      beta20_sigma_11 _ _ _ baseRoot_sq rootA_sq_1 rootB_sq_1⟩
    have hmem : genusB.val (u20_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u20_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u20_11 baseRoot (rootA 1) (rootB 1) from u20_11_map genusB.val.toRingHom _ _ _] at hmem

/-- **`√β_20 ∈ Ω`.** -/
theorem wideRoot_mem_OmegaBcl_1 : wideRoot 1 ∈ OmegaBcl := by
  have h := squareRoot_mem_OmegaBcl genusB admissible_genusB betaO_1 cofO_1 (68719476736)
    betaO_mul_cofO_1 hm30_1 hconj_1
  have hb : ((betaO_1 : genusB) : Closure) = wideRadicand 1 := oHom_betaO_1
  rwa [hb] at h

/-! ### Form 17 (index 2) -/

theorem rootA_mem_genusB_2 : rootA 2 ∈ genusB := by
  simp only [rootA, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem rootB_mem_genusB_2 : rootB 2 ∈ genusB := by
  simp only [rootB, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem sigma_rootA_2 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootA 2) = rootA 2 ∨ σ (rootA 2) = -rootA 2 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootA_sq_2]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

theorem sigma_rootB_2 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootB 2) = rootB 2 ∨ σ (rootB 2) = -rootB 2 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootB_sq_2]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

/-- `β_17` as an algebraic integer of the genus field. -/
def betaO_2 : 𝓞 genusB := beta17 sO (rootAO 2) (rootBO 2)

theorem oHom_betaO_2 : oHom betaO_2 = wideRadicand 2 := by
  rw [betaO_2, beta17_map, oHom_sO, oHom_rootAO, oHom_rootBO, wideRadicand_2]

/-- The cofactor of the norm of `β_17`. -/
def cofO_2 : 𝓞 genusB :=
  normConj17 sO (rootAO 2) (rootBO 2) *
    algebraMap (𝓞 B) (𝓞 genusB) (mk normBarMk17.1 normBarMk17.2)

theorem betaO_mul_cofO_2 : betaO_2 * cofO_2 = ((-768 : ℤ) : 𝓞 genusB) := by
  apply oHom_injective
  rw [map_mul, oHom_betaO_2, cofO_2, map_mul, normConj17_map, oHom_sO, oHom_rootAO, oHom_rootBO,
    oHom_algebraMap_mk, map_intCast, wideRadicand_2]
  have h := beta17_mul_normCofactor baseRoot (rootA 2) (rootB 2) baseRoot_sq rootA_sq_2 rootB_sq_2
  rw [normCofactor17, ← normBar17_eq] at h
  simp only [normBarMk17] at h ⊢
  exact_mod_cast h

theorem hm30_2 : ∀ P : Ideal ℤ, P.IsPrime → (-768 : ℤ) ∈ P → (30 : ℤ) ∈ P := by
  intro P hP hM
  apply thirty_mem_of_two_three P 8 1
  have he : (-768 : ℤ) = -(2 ^ 8 * 3 ^ 1) := by norm_num
  rw [he] at hM
  simpa using neg_mem hM

theorem hconj_2 (σ : Closure ≃ₐ[B] Closure) :
    ∃ u ∈ genusB, σ ((betaO_2 : genusB) : Closure) = u ^ 2 * ((betaO_2 : genusB) : Closure) := by
  have hb : ((betaO_2 : genusB) : Closure) = beta17 baseRoot (rootA 2) (rootB 2) := by
    rw [← wideRadicand_2, ← oHom_betaO_2]
    rfl
  rw [hb, show σ (beta17 baseRoot (rootA 2) (rootB 2)) =
      beta17 (σ baseRoot) (σ (rootA 2)) (σ (rootB 2)) from beta17_map σ.toRingHom _ _ _,
    sigma_baseRoot_B σ]
  have hs := baseRoot_mem_genusB
  have ha := rootA_mem_genusB_2
  have hb' := rootB_mem_genusB_2
  rcases sigma_rootA_2 σ with hx | hx <;> rcases sigma_rootB_2 σ with hy | hy <;> rw [hx, hy]
  · exact ⟨1, one_mem _, by ring⟩
  · refine ⟨u17_01 baseRoot (rootA 2) (rootB 2), ?_,
      beta17_sigma_01 _ _ _ baseRoot_sq rootA_sq_2 rootB_sq_2⟩
    have hmem : genusB.val (u17_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u17_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u17_01 baseRoot (rootA 2) (rootB 2) from u17_01_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u17_10 baseRoot (rootA 2) (rootB 2), ?_,
      beta17_sigma_10 _ _ _ baseRoot_sq rootA_sq_2 rootB_sq_2⟩
    have hmem : genusB.val (u17_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u17_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u17_10 baseRoot (rootA 2) (rootB 2) from u17_10_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u17_11 baseRoot (rootA 2) (rootB 2), ?_,
      beta17_sigma_11 _ _ _ baseRoot_sq rootA_sq_2 rootB_sq_2⟩
    have hmem : genusB.val (u17_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u17_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u17_11 baseRoot (rootA 2) (rootB 2) from u17_11_map genusB.val.toRingHom _ _ _] at hmem

/-- **`√β_17 ∈ Ω`.** -/
theorem wideRoot_mem_OmegaBcl_2 : wideRoot 2 ∈ OmegaBcl := by
  have h := squareRoot_mem_OmegaBcl genusB admissible_genusB betaO_2 cofO_2 (-768)
    betaO_mul_cofO_2 hm30_2 hconj_2
  have hb : ((betaO_2 : genusB) : Closure) = wideRadicand 2 := oHom_betaO_2
  rwa [hb] at h

/-! ### Form 7 (index 3) -/

theorem rootA_mem_genusB_3 : rootA 3 ∈ genusB := by
  simp only [rootA, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem rootB_mem_genusB_3 : rootB 3 ∈ genusB := by
  simp only [rootB, Fin.isValue, Matrix.cons_val, Matrix.cons_val_zero, Matrix.cons_val_one]
  repeat' apply mul_mem
  all_goals exact genusRoot_mem_genusB _

theorem sigma_rootA_3 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootA 3) = rootA 3 ∨ σ (rootA 3) = -rootA 3 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootA_sq_3]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

theorem sigma_rootB_3 (σ : Closure ≃ₐ[B] Closure) :
    σ (rootB 3) = rootB 3 ∨ σ (rootB 3) = -rootB 3 := by
  apply sq_eq_sq_iff_eq_or_eq_neg.mp
  rw [← map_pow, rootB_sq_3]
  simp [map_sub, map_add, map_mul, map_div₀, map_neg, map_ofNat, sigma_baseRoot_B σ]

/-- `β_7` as an algebraic integer of the genus field. -/
def betaO_3 : 𝓞 genusB := beta7 sO (rootAO 3) (rootBO 3)

theorem oHom_betaO_3 : oHom betaO_3 = wideRadicand 3 := by
  rw [betaO_3, beta7_map, oHom_sO, oHom_rootAO, oHom_rootBO, wideRadicand_3]

/-- The cofactor of the norm of `β_7`. -/
def cofO_3 : 𝓞 genusB :=
  normConj7 sO (rootAO 3) (rootBO 3) *
    algebraMap (𝓞 B) (𝓞 genusB) (mk normBarMk7.1 normBarMk7.2)

theorem betaO_mul_cofO_3 : betaO_3 * cofO_3 = ((768 : ℤ) : 𝓞 genusB) := by
  apply oHom_injective
  rw [map_mul, oHom_betaO_3, cofO_3, map_mul, normConj7_map, oHom_sO, oHom_rootAO, oHom_rootBO,
    oHom_algebraMap_mk, map_intCast, wideRadicand_3]
  have h := beta7_mul_normCofactor baseRoot (rootA 3) (rootB 3) baseRoot_sq rootA_sq_3 rootB_sq_3
  rw [normCofactor7, ← normBar7_eq] at h
  simp only [normBarMk7] at h ⊢
  exact_mod_cast h

theorem hm30_3 : ∀ P : Ideal ℤ, P.IsPrime → (768 : ℤ) ∈ P → (30 : ℤ) ∈ P := by
  intro P hP hM
  apply thirty_mem_of_two_three P 8 1
  have he : (768 : ℤ) = (2 ^ 8 * 3 ^ 1) := by norm_num
  rw [he] at hM
  exact hM

theorem hconj_3 (σ : Closure ≃ₐ[B] Closure) :
    ∃ u ∈ genusB, σ ((betaO_3 : genusB) : Closure) = u ^ 2 * ((betaO_3 : genusB) : Closure) := by
  have hb : ((betaO_3 : genusB) : Closure) = beta7 baseRoot (rootA 3) (rootB 3) := by
    rw [← wideRadicand_3, ← oHom_betaO_3]
    rfl
  rw [hb, show σ (beta7 baseRoot (rootA 3) (rootB 3)) =
      beta7 (σ baseRoot) (σ (rootA 3)) (σ (rootB 3)) from beta7_map σ.toRingHom _ _ _,
    sigma_baseRoot_B σ]
  have hs := baseRoot_mem_genusB
  have ha := rootA_mem_genusB_3
  have hb' := rootB_mem_genusB_3
  rcases sigma_rootA_3 σ with hx | hx <;> rcases sigma_rootB_3 σ with hy | hy <;> rw [hx, hy]
  · exact ⟨1, one_mem _, by ring⟩
  · refine ⟨u7_01 baseRoot (rootA 3) (rootB 3), ?_,
      beta7_sigma_01 _ _ _ baseRoot_sq rootA_sq_3 rootB_sq_3⟩
    have hmem : genusB.val (u7_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u7_01 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u7_01 baseRoot (rootA 3) (rootB 3) from u7_01_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u7_10 baseRoot (rootA 3) (rootB 3), ?_,
      beta7_sigma_10 _ _ _ baseRoot_sq rootA_sq_3 rootB_sq_3⟩
    have hmem : genusB.val (u7_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u7_10 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u7_10 baseRoot (rootA 3) (rootB 3) from u7_10_map genusB.val.toRingHom _ _ _] at hmem
  · refine ⟨u7_11 baseRoot (rootA 3) (rootB 3), ?_,
      beta7_sigma_11 _ _ _ baseRoot_sq rootA_sq_3 rootB_sq_3⟩
    have hmem : genusB.val (u7_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) ∈ genusB := SetLike.coe_mem _
    rwa [show genusB.val (u7_11 ⟨_, hs⟩ ⟨_, ha⟩ ⟨_, hb'⟩) =
      u7_11 baseRoot (rootA 3) (rootB 3) from u7_11_map genusB.val.toRingHom _ _ _] at hmem

/-- **`√β_7 ∈ Ω`.** -/
theorem wideRoot_mem_OmegaBcl_3 : wideRoot 3 ∈ OmegaBcl := by
  have h := squareRoot_mem_OmegaBcl genusB admissible_genusB betaO_3 cofO_3 (768)
    betaO_mul_cofO_3 hm30_3 hconj_3
  have hb : ((betaO_3 : genusB) : Closure) = wideRadicand 3 := oHom_betaO_3
  rwa [hb] at h

/-- **`√β_i ∈ Ω`** for the four forms. -/
theorem wideRoot_mem_Omega (i : Fin 4) : wideRoot i ∈ Omega := by
  fin_cases i
  · exact wideRoot_mem_OmegaBcl_0
  · exact wideRoot_mem_OmegaBcl_1
  · exact wideRoot_mem_OmegaBcl_2
  · exact wideRoot_mem_OmegaBcl_3

/-- **`E_W ≤ Ω`.** -/
theorem field_le_Omega : CanonicalWide.field ≤ Omega := by
  rw [CanonicalWide.field, IntermediateField.adjoin_le_iff]
  rintro x (rfl | (⟨k, rfl⟩ | ⟨i, rfl⟩))
  · exact baseRoot_mem_Omega
  · exact genusRoot_mem_Omega k
  · exact wideRoot_mem_Omega i

end UnitDistance.Sqrt241.Wide
